### ISSUE TITLE
Error on opening flutter gallery example

### ISSUE THREAD

**Issue by epool** [flutter/flutter-intellij#1013]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2017.1.2` • Flutter plugin `13.1` • Dart plugin `171.4424`

Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 9f1d5ba50e (26 hours ago) • 2017-05-09 17:06:52 -0700
Engine • revision cbbf956fcb
Tools • Dart 1.23.0-dev.11.11

## Exception

Already disposed: Project (Disposed) flutter_gallery

```
java.lang.AssertionError: Already disposed: Project (Disposed) flutter_gallery
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:167)
	at com.intellij.openapi.module.ModuleManager.getInstance(ModuleManager.java:42)
	at com.intellij.openapi.module.ModuleUtil$1.compute(ModuleUtil.java:42)
	at com.intellij.openapi.module.ModuleUtil$1.compute(ModuleUtil.java:37)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
	at com.intellij.openapi.module.ModuleUtil.getModulesOfType(ModuleUtil.java:80)
	at com.intellij.openapi.module.ModuleUtil.hasModulesOfType(ModuleUtil.java:85)
	at io.flutter.utils.FlutterModuleUtils.hasFlutterModule(FlutterModuleUtils.java:53)
	at io.flutter.project.FlutterProjectOpenProcessor.doOpenProject(FlutterProjectOpenProcessor.java:75)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:112)
	at com.intellij.ide.actions.OpenFileAction.doOpenFile(OpenFileAction.java:93)
	at com.intellij.ide.actions.OpenFileAction.lambda$actionPerformed$0(OpenFileAction.java:68)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:169)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:114)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:91)
	at com.intellij.ide.actions.OpenFileAction.actionPerformed(OpenFileAction.java:60)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:309)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:929)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:116)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:767)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
Thanks for this report @epool!  I'm working on reproducing the issue and I'm curious, do you remember whether, when this happened:

  * did you already have another project open?
  * if so, did you select the option to open a new window or reuse the current one?

Thanks in advance!

**Comment by epool** [comment]
Yes I did, and I selected open a new window.

**Comment by pq** [comment]
Do you recall if you were trying to open `flutter_gallery` or was that the one that was already open and you were trying to open something else?

Does this happen consistently?

Thank you!

**Comment by epool** [comment]
I had opened the hello world example and I wanted to open the gallery example in a second window, but that just happened once and I got the trace for reporting this issue.

**Comment by pq** [comment]
OK, perfect.  Thanks for your help!
