### ISSUE TITLE
Unable to "Open Flutter View"

### ISSUE THREAD

**Issue by lorrainekan** [flutter/flutter-intellij#1028]
## What happened

After running my application using the Flutter tool bar, I clicked on "Open Flutter View".

## Version information

IntelliJ IDEA `2017.1.1` • Flutter plugin `13.1` • Dart plugin `171.4424`

No Flutter sdk configured.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.view.OpenFlutterViewAction.actionPerformed(OpenFlutterViewAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:188)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:154)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:325)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Flutter version
[✓] Flutter (on Linux, channel alpha)
    • Flutter at 
    • Framework revision c8c37fcc85 (3 months ago), 2017-02-27 16:10:57
    • Engine revision 0a7b177c33
    • Tools Dart version 1.23.0-dev.0.0

**Comment by devoncarew** [comment]
Thanks for the report! It's not immediately clear how that stack trace could occur.

I see this issue:

> No Flutter sdk configured.

I would make sure that there's a flutter sdk set for your project, in the Settings, Languages & Frameworks section.

also:

> • Framework revision c8c37fcc85 (3 months ago)

You should run `flutter upgrade` from the command line, in order to get the latest version of flutter. 3 months is old enough that it's unlikely that version of flutter will work with the IDE.

**Comment by pq** [comment]
@devoncarew : what's interesting is that the failure suggests that this is returning `null`:

    ToolWindowManager.getInstance(project).getToolWindow("Flutter");

Thoughts on how SDK configuration would affect that?

**Comment by devoncarew** [comment]
I don't think they're related.

**Comment by devoncarew** [comment]
Ah, I think this is related to our condition class (FlutterViewCondition).

**Comment by lorrainekan** [comment]
Thanks for the suggestions!

I am using the plugin internally, so I can't set the SDK path. Every time I try to set the SDK path, it erases the Dart SDK path.

**Comment by devoncarew** [comment]
@lorrainekan, it shouldn't remove the sdk path. Can you open an issues internally for this, and cc @jwren? This may be due to internal specific dart tooling.

**Comment by devoncarew** [comment]
(closing for the NPE portion of this issue)

**Comment by mit-mit** [comment]
@devoncarew did this make it into M14?

**Comment by devoncarew** [comment]
yup!
