### ISSUE TITLE
java.lang.IllegalAccessError in debugger classes

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#103]
I think I'm seeing a classloader issue, where we're loading a few debugger classes from the flutter classloader, and others from the dart classloader. This changes the effective access level of fields, and some fields and methods are no longer visible (things that appear like they're in the same package - `com.jetbrains.lang.dart.ide.runner.server.vmService` - are really effectively in two separate ones).

```java
2016-09-06 15:30:22,769 [ 160121]  ERROR - til.concurrency.QueueProcessor - tried to access method com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceBreakpointHandler.<init>(Lcom/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcess;)V from class com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess 
java.lang.IllegalAccessError: tried to access method com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceBreakpointHandler.<init>(Lcom/jetbrains/lang/dart/ide/runner/server/vmService/DartVmServiceDebugProcess;)V from class com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess.<init>(DartVmServiceDebugProcess.java:103)
	at com.jetbrains.lang.dart.ide.runner.DartRunner$1.start(DartRunner.java:164)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:219)
```

@stevemessick

**Comment by stevemessick** [comment]
I remember seeing the class path get reordered in a recent PR. Try changing
it so flutter is first?

**Comment by stevemessick** [comment]
I took another look. The classpath looks OK. I would expect classpath errors to be deterministic. I can't reproduce this, though. Got a repro?

**Comment by devoncarew** [comment]
I tested w/ the old and new classpath issue - no change.

I'm running the built plugin in a copy if IntelliJ CE; I suspect the classloaders must behave a little differently than in the runtime workbench. Running works - all of it's classes load from the Dart plugin classloader; but debugging doesn't as some load from the Flutter classloader and some from the Dart one.

**Comment by stevemessick** [comment]
I thought that our current target environment was IntelliJ Ultimate EAP. Have you tried running it there? I was going to try but for some reason I can't build the Flutter plugin.

**Comment by devoncarew** [comment]
Fixed by https://github.com/flutter/flutter-intellij/pull/111.
