### ISSUE TITLE
NPE in the built plugin

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#109]
Not sure how this is null:

```java

java.lang.NullPointerException
	at io.flutter.sdk.FlutterSettingsConfigurable.init(FlutterSettingsConfigurable.java:60)
	at io.flutter.sdk.FlutterSettingsConfigurable.<init>(FlutterSettingsConfigurable.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
```

@pq

**Comment by pq** [comment]
Interesting!

I think I see what's happening...  Odd that it doesn't happen in the runtime workbench which suggests that initialization is different when deployed.  Anyway, once I've got my local build working I'll confirm my fix.

Thanks!

**Comment by devoncarew** [comment]
I very briefly looked at this - it looks like `createUIComponents()` is called by some magic `$$$setupUI$$$` method; probably auto-magically generated by IntelliJ for the form file. We're mostly likely missing some set in the gradle build to compile the form correctly.

**Comment by pq** [comment]
The plot thickens!

I've got another thought but am hitting snags in getting a local test environment setup to verify  (see #114)  -- input welcome. 👍

**Comment by pq** [comment]
Testing on CE, I'm seeing this too:

```
java.lang.NullPointerException
	at io.flutter.module.FlutterGeneratorPeer.<init>(FlutterGeneratorPeer.java:43)
	at io.flutter.module.FlutterModuleBuilder$FlutterModuleWizardStep.<init>(FlutterModuleBuilder.java:114)
	at io.flutter.module.FlutterModuleBuilder.getCustomOptionsStep(FlutterModuleBuilder.java:70)
	at com.intellij.ide.projectWizard.ProjectTypeStep.showCustomOptions(ProjectTypeStep.java:465)
	at com.intellij.ide.projectWizard.ProjectTypeStep.projectTypeChanged(ProjectTypeStep.java:392)
	at com.intellij.ide.projectWizard.ProjectTypeStep$9.valueChanged(ProjectTypeStep.java:217)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2210)
	at javax.swing.JList.setSelectedValue(JList.java:2360)
	at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:242)
	at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:50)
	at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
	at com.intellij.ide.actions.NewProjectAction.actionPerformed(NewProjectAction.java:30)
```

@devoncarew : what product were you testing against?

**Comment by devoncarew** [comment]
CE; I suspect some missing config in our gradle file

**Comment by pq** [comment]
@devoncarew is this fixed?

**Comment by devoncarew** [comment]
No, still some gradle build file spelunking to do.

**Comment by devoncarew** [comment]
Not critical for now, we can manually build the plugin.
