### ISSUE TITLE
Connected Android Device not Seen after IDE internal exception

### ISSUE THREAD

**Issue by zringlelabs** [flutter/flutter-intellij#1096]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new .

---

## What happened
Cannot see any connected Android Device
(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2017.1.3` • Flutter plugin `14.0` • Dart plugin `171.4424.63`

Error getting Flutter sdk information.

## Exception

A Flutter device daemon stopped unexpectedly.
Details: Daemon #6 exited. Exit code: 255. Stderr:

```
Unhandled exception:
Exception: adb not responding
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:92)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:123)
<asynchronous suspension>
#3      _deviceToMap (package:flutter_tools/src/commands/daemon.dart:685)
<asynchronous suspension>
#4      DeviceDomain._onDeviceEvent.<anonymous closure>.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:571)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1128)
#6      _CustomZone.runUnary (dart:async/zone.dart:1012)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:665)
#10     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:928)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:375)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

```
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
	at io.flutter.run.daemon.DeviceService.daemonStopped(DeviceService.java:188)
	at io.flutter.run.daemon.DeviceDaemon$Listener.processTerminated(DeviceDaemon.java:368)
	at io.flutter.run.daemon.DaemonApi$1.processTerminated(DaemonApi.java:142)
	at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy15.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:184)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:260)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:165)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:187)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:92)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:152)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:137)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Version info

Please paste the output of running `flutter doctor` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by eseidelGoogle** [comment]
Looks like this and https://github.com/flutter/flutter-intellij/issues/1097 are the same?

**Comment by eseidelGoogle** [comment]
Looks like this is coming from ADB itself?
https://stackoverflow.com/questions/17851480/adb-not-responding-you-can-wait-more-or-kill-adb-exe-windows-8
https://stackoverflow.com/questions/18059334/adb-not-responding-you-can-wait-more-or-kill-adb-exe-process-manually-and-cli

**Comment by pq** [comment]
@zringlelabs : does killing `adb` help?  (It should restart itself.)

**Comment by MartinFreire** [comment]
Hi, I've been trying to run flutter for the last 5 hours without being able to succeed with a similar error:
simply running gives me this log:
```
flutter run
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.

```
And flutter doctor gives me this:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [VersiÃ³n 10.0.16299.309], locale es-AR)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android SDK file not found: C:\Users\martin.freire\AppData\Local\Android\sdk\build-tools\27.0.3\aapt.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[!] VS Code, 64-bit edition (version 1.20.1)
adb not responding

```
I'm running on Windows 10, with everything I could updated. I install flutter today, for the first time, I was trying to try it
I killed the process and I see it coming back, but nothing changes.

Any ideas?

Thanks in advance

**Comment by devoncarew** [comment]
@MartinFreire, I believe this issue is unrelated to what you're seeing; can you open a new issue here: https://github.com/flutter/flutter ? You'll want to include the full output from `flutter doctor -v`.

**Comment by aroussie** [comment]
Hello every one, I encountered the exact same issue. 
I've been able to fix it by restarting `adb` as @pq  suggested. 

For those who don't know how to restart `adb`: 
Go in your Android sdk folder, probably located in `~/Library/Android/sdk/platform-tools/`
Then run the following:
`adb kill-server`
`adb start-server`

Rerun `flutter doctor [-v]` and everything should be green :) 
Happy coding !
