### ISSUE TITLE
Error updating flutter sdk in intelli j

### ISSUE THREAD

**Issue by pilotpat** [flutter/flutter-intellij#1099]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Running Flutter update
## Version information

IntelliJ IDEA `2017.1.4` • Flutter plugin `14.0` • Dart plugin `171.4424.63`

Error getting Flutter sdk information.

## Exception

Flutter device daemon #2: process exited during startup. Exit code: 1, stderr:
unzip:  cannot find or open /Users/patw/Documents/flutter/bin/cache/dart-sdk.zip, /Users/patw/Documents/flutter/bin/cache/dart-sdk.zip.zip or /Users/patw/Documents/flutter/bin/cache/dart-sdk.zip.ZIP.

```
com.intellij.execution.ExecutionException: Flutter device daemon #2: process exited during startup. Exit code: 1, stderr:
unzip:  cannot find or open /Users/patw/Documents/flutter/bin/cache/dart-sdk.zip, /Users/patw/Documents/flutter/bin/cache/dart-sdk.zip.zip or /Users/patw/Documents/flutter/bin/cache/dart-sdk.zip.ZIP.

	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:222)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:220)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pq** [comment]
Thanks for the report!  It looks like your flutter install isn't complete... Could you run `flutter doctor` in a terminal and paste in the results?

**Comment by pilotpat** [comment]
Thanks Phil, I looked at it closer and you are correct, the install was not correct. I just reinstalled it with a fresh pull and it worked properly. Thanks.

**Comment by pq** [comment]
Great!  This is good feedback all the same since it's clear we can do a bit better at detecting and communicating around the installation issues.

Thanks for the report!
