### ISSUE TITLE
IntelliJ being open interferes with switching Flutter branches

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter-intellij#1155]
I was switching Flutter branches using `git bisect` while IntelliJ was also open.  The IDE shows an error:

```
Flutter device daemon #1: process exited during startup. Exit code: 1, stderr:
/Users/jackson/git/flutter/bin/flutter: line 89: /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory

com.intellij.execution.ExecutionException: Flutter device daemon #1: process exited during startup. Exit code: 1, stderr:
/Users/jackson/git/flutter/bin/flutter: line 89: /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/dart: No such file or directory

	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:222)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:220)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I then got a different error trying to `flutter run` on the command line.

```
$ flutter run -d i
Downloading Dart SDK 1.24.0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.9M  100 57.9M    0     0  13.9M      0  0:00:04  0:00:04 --:--:-- 13.9M
warning:  cannot set modif./access times for /Users/jackson/git/flutter/bin/cache/dart-sdk/lib/dev_compiler/common/dart_sdk.js.map
          No such file or directory
  error:  invalid compressed data to inflate /Users/jackson/git/flutter/bin/cache/dart-sdk/lib/front_end/lib/src/fasta/source/outline_builder.dart
file #1421:  bad zipfile offset (lseek):  58490880
file #1422:  bad zipfile offset (local header sig):  58495304
file #1423:  bad zipfile offset (local header sig):  58496332
file #1424:  bad zipfile offset (local header sig):  58498113
file #1425:  bad zipfile offset (lseek):  58499072
file #1426:  bad zipfile offset (lseek):  58507264
file #1427:  bad zipfile offset (local header sig):  58509862
file #1428:  bad zipfile offset (local header sig):  58510765
file #1429:  bad zipfile offset (local header sig):  58511331
file #1430:  bad zipfile offset (local header sig):  58512760
file #1431:  bad zipfile offset (local header sig):  58512863
file #1432:  bad zipfile offset (local header sig):  58513650
file #1433:  bad zipfile offset (lseek):  58515456
file #1434:  bad zipfile offset (local header sig):  58516605
file #1435:  bad zipfile offset (local header sig):  58517162
file #1436:  bad zipfile offset (local header sig):  58519982

...

warning:  set times/attribs failed for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/resources/css/
warning:  cannot set modif./access times for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/resources/
          No such file or directory
warning:  cannot set permissions for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/resources/
          No such file or directory
warning:  set times/attribs failed for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/resources/
warning:  cannot set modif./access times for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/
          No such file or directory
warning:  cannot set permissions for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/
          No such file or directory
warning:  set times/attribs failed for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/dartdoc/
warning:  cannot set modif./access times for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/
          No such file or directory
warning:  cannot set permissions for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/
          No such file or directory
warning:  set times/attribs failed for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/resources/
warning:  cannot set modif./access times for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/
          No such file or directory
warning:  cannot set permissions for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/
          No such file or directory
warning:  set times/attribs failed for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/snapshots/
warning:  cannot set modif./access times for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/
          No such file or directory
warning:  cannot set permissions for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/
          No such file or directory
warning:  set times/attribs failed for /Users/jackson/git/flutter/bin/cache/dart-sdk/bin/

It appears that the downloaded file is corrupt; please try the operation again later.
If this problem persists, please report the problem at
https://github.com/flutter/flutter/issues/new

```

## Version info

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision be228eae78 (2 hours ago), 2017-06-29 11:54:18 -0700
    • Engine revision 009d470d50
    • Tools Dart version 1.24.2

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/jackson/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b, 
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 15.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • iPhone 7 Plus • F8A917C4-9848-49C2-8F0D-664B49E0B635 • ios • iOS 10.3 (simulator)

**Comment by pq** [comment]
@devoncarew : optimistically bumping this to `M16`; feel free to un-bump 👍 .
