### ISSUE TITLE
ClassCastException on project creation

### ISSUE THREAD

**Issue by hi7** [flutter/flutter-intellij#1234]
## What happened

An ClassCastException occurred while creating a new flutter Project after 'flutter upgrade' from alpha channel. I set the flutter sdk path before but it seams to be lost in process of creation.

## Version information

WebStorm `2017.2` • Flutter plugin `15.1` • Dart plugin `172.3317.70` • Ubuntu 17.04

No Flutter sdk configured.

## Exception

java.lang.Object cannot be cast to java.lang.String

```
java.lang.ClassCastException: java.lang.Object cannot be cast to java.lang.String
	at io.flutter.module.FlutterSmallIDEProjectGenerator.generateProject(FlutterSmallIDEProjectGenerator.java:25)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.a(AbstractNewProjectStep.java:217)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:270)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:222)
	at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:168)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:142)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
...
```

**Comment by branflake2267** [comment]
The exception doesn't match the line number in the source file. And it doesn't seem to match historically either. I'm no help at this time, but I'll be testing this out today when I work on some form enhancements.
 
https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/module/FlutterSmallIDEProjectGenerator.java

**Comment by devoncarew** [comment]
Thanks for the report! Looks like we had a fix for this in https://github.com/flutter/flutter-intellij/commit/7bc8131a302236653dd89de9d018cd762e4772ae, about 2 days after we cut the M15 release. Short term you can work around this via:

```
flutter create foo_bar
webstorm foo_bar
```

The next release w/ the fix will be out ~the end of the month. We'll have to decide whether we want to push out a 15.2 w/ the fix for this between now and then.

**Comment by devoncarew** [comment]
Pushed `15.2` with the fix; thanks!
