### ISSUE TITLE
Hot reloading did not work

### ISSUE THREAD

**Issue by salmansamie** [flutter/flutter-intellij#1324]
## What happened:
Using physical device (OnePlus 2) as an emulator. The device display went dark due to timeout. Woke it up. Then hot reloading did not work at multiple trials after making a change to fix a syntax error. Had to restart my IDE to fix this.

## Version information

IntelliJ IDEA `2017.1.5` • Flutter plugin `17.0` • Dart plugin `171.4694.29`

Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 1c372c6803 (9 days ago) • 2017-08-31 15:54:45 -0700
Engine • revision f9e00a7c72
Tools • Dart 1.25.0-dev.11.0

## Exception

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 21,4,Idea Thread Group] 1013325667
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2017.1.5#IU-171.4694.70 IDEA, eap:false, os:Mac OS X 10.12.6, java-version:JetBrains s.r.o 1.8.0_112-release-736-b21,6,main] 2082803449

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1068)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.getCachedPsiFile(FileManagerImpl.java:403)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:179)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:156)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getPsiFile(PsiDocumentManagerBase.java:116)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.getPsiFile(PsiDocumentManagerImpl.java:90)
	at io.flutter.run.FlutterReloadManager.hasErrors(FlutterReloadManager.java:275)
	at io.flutter.run.FlutterReloadManager.lambda$handleSaveAllNotification$1(FlutterReloadManager.java:184)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
Thanks for the report (and the exception trace)!

**Comment by devoncarew** [comment]
@salmansamie, we have a fix out for review. This issue only occurs with IntelliJ 2017.1 however - if you upgrade to 2017.2 (and upgrade to the corresponding version of the Dart plugin), that should also address the issue.

**Comment by salmansamie** [comment]
Thanks @devoncarew I have now upgraded IntelliJ to 2017.2.3. Issue no longer exist.
