### ISSUE TITLE
Argument 3 for @NotNull parameter of io/flutter/run/test/TestLaunchState.<init> must not be null

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#1380]
## Version information

IntelliJ IDEA `2017.2.5` • Flutter plugin `18.0` • Dart plugin `172.4155.35`

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 4e48a737eb (2 days ago) • 2017-10-06 19:24:34 -0700
Engine • revision 459f722b86
Tools • Dart 1.25.0-dev.11.0

## Exception

Argument 3 for @NotNull parameter of io/flutter/run/test/TestLaunchState.<init> must not be null

```
java.lang.IllegalArgumentException: Argument 3 for @NotNull parameter of io/flutter/run/test/TestLaunchState.<init> must not be null
	at io.flutter.run.test.TestLaunchState.$$$reportNull$$$4(Unknown Source)
	at io.flutter.run.test.TestLaunchState.<init>(Unknown Source)
	at io.flutter.run.test.TestLaunchState.create(Unknown Source)
	at io.flutter.run.test.TestConfig.getState(Unknown Source)
	at io.flutter.run.test.TestConfig.getState(Unknown Source)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfigurationAsync(ProgramRunnerUtil.java:125)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:58)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:112)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:441)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
I can run/debug other things (`lib/main.dart`), but `Flutter test` configurations don't seem to work. By default (clicking run or debug in the context menu in the project window creates a `Dart test` run configuration instead of `Flutter test`, but manually creating a `Flutter test` config instead causes above error message.

I think this is since the update to the new Flutter plugin version.
At least I'm quite sure this still worked a few days ago and the test is only a very basic example test.

**Comment by devoncarew** [comment]
/cc @pq 

We should fail better here; @zoechi, from that assert message, it looks like there may not be a test file or directory set for the test launch configuration?

**Comment by zoechi** [comment]
"Test scope" "All in file" and "Test file" are set.

**Comment by pq** [comment]
@zoechi : I'm working on reproducing this but not having any luck.

![image](https://user-images.githubusercontent.com/67586/31346688-c307c0a6-acce-11e7-991a-6626930ef3fe.png)

My sample test is essentially a no-op:

```dart
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('test 5', (WidgetTester tester) async {
    // ...
  });

  test('bar test', () {
  });
}
```

(but it shouldn't matter).

**Comment by pq** [comment]
Tracing through things I'm wondering if there isn't something curious about your project structure.  Do you have a pubspec?  A `.packages` file?  A `lib` directory?

**Comment by zoechi** [comment]
Yes, all there. It already worked fine some days ago. I think the latest plugin update broke it.
I'm not sure though and couldn't find a way to downgrade.

**Comment by pq** [comment]
Hmmm.  Out of curiosity, what happens if you delete the configuration and create a new one?  Or what if you create another test and try and run it?

Thanks for the help in tracking this down @zoechi!

**Comment by zoechi** [comment]
I recreated the configuration several times without effect.
It doesn't seem related to the content. I commented out everything so it only contains an empty main, but no difference.
The test runs fine with `flutter test test/unit_test.dart`

I created a new test. 
When I launched it using the context menu, it created a Dart test run config, instead of a Flutter test config.
Creating a Flutter test config manually, I got again above error mrssage.

A plugin update today didn't change anything.

**Comment by pq** [comment]
Thanks!

Could you check that the Dart SDK set in Preferences is the same for Dart as it is under Flutter?

![image](https://user-images.githubusercontent.com/67586/31401542-0be45788-ada8-11e7-9523-e5d11e03ef52.png)

**Comment by zoechi** [comment]
Yes, they are pointing to the same directory (Dart 2 directories deeper)

**Comment by pq** [comment]
Thanks for the follow-up.  One more thing to try...

Does this same problem arise with a fresh project?

That is, if you create a new Flutter project and try and run the sample test, are you seeing the same behavior?

**Comment by zoechi** [comment]
I couldn't reproduce in a new project created with `flutter create`.
I want to investigate further, but I don't have too much time currently.

**Comment by pq** [comment]
Thanks @zoechi.  No need to bang on this.  Let's re-open if it recurs or if we get a lead on a repro.

As always, your help is really appreciated!
