### ISSUE TITLE
Creating a new project fails

### ISSUE THREAD

**Issue by beldur** [flutter/flutter-intellij#1435]
## What happened

Create a new flutter project

## Version information

Android Studio `3.0` • Flutter plugin `18.2` • Dart plugin `171.4424`

No Flutter sdk configured.

## Exception

com/intellij/platform/ProjectGeneratorPeer

```
java.lang.NoClassDefFoundError: com/intellij/platform/ProjectGeneratorPeer
	at io.flutter.project.FlutterProjectCreator$2.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.platform.ProjectGeneratorPeer PluginClassLoader[io.flutter, 18.2]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

**Comment by mit-mit** [comment]
@devoncarew was this NPE fixed in 18.3?

**Comment by devoncarew** [comment]
No, but we do hope to have 18.4 out shortly with a fix.

**Comment by devoncarew** [comment]
This should be fixed with the latest published release.
