### ISSUE TITLE
Flutter throws exception when generating new project in Android Studio 3.0

### ISSUE THREAD

**Issue by loloof64** [flutter/flutter-intellij#1452]
## What happened

Just generated a new Flutter Project.

## Version information

Android Studio `3.0` • Flutter plugin `18.2` • Dart plugin `171.4424`

No Flutter sdk configured.

## Exception

com/intellij/platform/ProjectGeneratorPeer

```
java.lang.NoClassDefFoundError: com/intellij/platform/ProjectGeneratorPeer
	at io.flutter.project.FlutterProjectCreator$2.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.intellij.platform.ProjectGeneratorPeer PluginClassLoader[io.flutter, 18.2]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

## $ flutter doctor
[✓] Flutter (on Linux, locale fr_FR.UTF-8, channel alpha)
    • Flutter at /home/laurent-bernabe/Programmes/SDK/flutter
    • Framework revision 4424892c79 (il y a 3 semaines), 2017-10-10 16:45:11 -0700
    • Engine revision 2a84f18c79
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /home/laurent-bernabe/Android/Sdk
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /home/laurent-bernabe/Android/Sdk
    • Java binary at: /home/laurent-bernabe/Programmes/IDE/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /home/laurent-bernabe/Programmes/IDE/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • Flutter plugin version 18.1
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

**Comment by devoncarew** [comment]
@loloof64, thanks for the report, and sorry for the issue. This is a dup of https://github.com/flutter/flutter-intellij/issues/1435; we're working on that now, and expect to have a fix today.
