### ISSUE TITLE
exception from WidgetInspectorService.toId()

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1544]
Not sure of the exact repro steps, but I was selecting nodes in the widget tree.

```
Error evaluating expression:
Unhandled exception:
'dart:collection-patch/dart:collection/compact_hash.dart': Failed assertion: line 213: '(index & hashPattern) == 0': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
#1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin._insert (dart:collection-patch/dart:collection/compact_hash.dart:213)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.[]= (dart:collection-patch/dart:collection/compact_hash.dart:258)
#4      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:193:25)
#5      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:337:24)
#6      WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:349:69)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterable.toList (dart:_internal/iterable.dart:218)
#9      WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:349:99)
#10     WidgetInspectorService._pathNodeToJson (package:flutter/src/widgets/widget_inspector.dart:314:19)
#11     WidgetInspectorService.getParentChain.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:306:64)
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#13     ListIterable.toList (dart:_internal/iterable.dart:218)
#14     WidgetInspectorService.getParentChain (package:flutter/src/widgets/widget_inspector.dart:306:98)
#15     Eval (evaluate:source:1:39)

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:98)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:455)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)


java.util.concurrent.CompletionException: java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@12e2b32e
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:99)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:455)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
Caused by: java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@12e2b32e
	... 5 more
```

@jacob314

**Comment by jacob314** [comment]
Really strange. If I am reading the stack trace correctly, you are hitting a bug in the LinkedHashMap class.
https://github.com/dart-lang/sdk/blob/master/runtime/lib/compact_hash.dart#L213

**Comment by devoncarew** [comment]
Assuming this is stale
