### ISSUE TITLE
Crash in inspector

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1567]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

1. Was simply selecting a few nodes in the tree

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 171.4249.39` • Dart plugin `171.4424`

Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 2352e31f4e (3 hours ago) • 2017-12-05 13:39:24 +0100
Engine • revision b57fca02b5
Tools • Dart 1.25.0-dev.11.0

## Exception

```
Error evaluating expression:
Unhandled exception:
Build scheduled during frame.
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree. This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.
#0      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:522)
#1      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:541)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2077)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3416)
#4      State.setState (package:flutter/src/widgets/framework.dart:1101)
#5      _WidgetInspectorState.initState.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:474)
#6      WidgetInspectorService.setSelection (package:flutter/src/widgets/widget_inspector.dart:284)
#7      WidgetInspectorService.setSelectionById (package:flutter/src/widgets/widget_inspector.dart:260)
#8      Eval (evaluate:source:1:39)
#9      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart)
#10     new _TransformedRect (package:flutter/src/widgets/widget_inspector.dart:764)
#11     _InspectorOverlayLayer.addToScene (package:flutter/src/widgets/widget_inspector.dart:872)
#12     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:420)
#13     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:636)
#14     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:190)
#15     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:265)
#16     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:628)
#17     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:200)
#18     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:713)
#19     BindingBase&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:649)
#20     _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:113)
#21     _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:102)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:98)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:410)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by mit-mit** [comment]
cc @jacob314
