### ISSUE TITLE
exception at startup; symptom is we lose the flutter sdk setting

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#157]
Perhaps a lifecycle issue with when we call `ApplicationLibraryTable.getApplicationTable()`? I'm not as familiar when it is or isn't available to call this method (called from io.flutter.sdk.FlutterSdk.getGlobalFlutterSdk(FlutterSdk.java:97).

/cc @pq @stevemessick 

```
[   4900]  ERROR - rationStore.ComponentStoreImpl - Cannot init libraryTable component state 
java.lang.IllegalArgumentException: Unknown macro $APP_CONFIG$
	at com.intellij.configurationStore.StateStorageManagerImpl.expandMacro(StateStorageManagerImpl.kt:353)
	at com.intellij.configurationStore.ApplicationStorageManager.expandMacros(ApplicationStoreImpl.kt:113)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:212)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:165)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:136)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistentComponent(ComponentStoreImpl.kt:275)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:91)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:237)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at com.intellij.openapi.roots.impl.libraries.ApplicationLibraryTable.getApplicationTable(ApplicationLibraryTable.java:46)
	at io.flutter.sdk.FlutterSdk.getGlobalFlutterSdk(FlutterSdk.java:97)
	at io.flutter.run.daemon.FlutterDaemonController.createCommandLine(FlutterDaemonController.java:172)
	at io.flutter.run.daemon.FlutterDaemonController.forkProcess(FlutterDaemonController.java:118)
	at io.flutter.run.daemon.FlutterAppManager.startDevicePoller(FlutterAppManager.java:138)
	at io.flutter.run.daemon.FlutterDaemonService.lambda$schedulePolling$7(FlutterDaemonService.java:152)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[   4904]  ERROR - rationStore.ComponentStoreImpl - IntelliJ IDEA 2016.2.4  Build #IC-162.2032.8 
[   4905]  ERROR - rationStore.ComponentStoreImpl - JDK: 1.8.0_73 
[   4905]  ERROR - rationStore.ComponentStoreImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
[   4905]  ERROR - rationStore.ComponentStoreImpl - Vendor: Oracle Corporation 
[   4905]  ERROR - rationStore.ComponentStoreImpl - OS: Mac OS X 
```

```
[   4966]  ERROR - daemon.FlutterDaemonController - The Flutter SDK is not configured 
com.intellij.execution.ExecutionException: The Flutter SDK is not configured
	at io.flutter.run.daemon.FlutterDaemonController.createCommandLine(FlutterDaemonController.java:194)
	at io.flutter.run.daemon.FlutterDaemonController.forkProcess(FlutterDaemonController.java:118)
	at io.flutter.run.daemon.FlutterAppManager.startDevicePoller(FlutterAppManager.java:138)
	at io.flutter.run.daemon.FlutterDaemonService.lambda$schedulePolling$7(FlutterDaemonService.java:152)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

**Comment by stevemessick** [comment]
Did this happen on start up, before the window was fully drawn? Might be
due to a late change I made to FlutterInitializer because of EAP
incompatibility. We might need a better way to populate the device list.
However, it works with my stable Ultimate config -- at least some times😉

**Comment by devoncarew** [comment]
It does happen somewhere in `FlutterDaemonService`, when starting polling for devices. I've only seen this on stable, on IntelliJ CE (and on WebStorm stable).

**Comment by pq** [comment]
Are you able to repro this in a runtime workbench?

**Comment by pq** [comment]
I did some poking around and think I have an idea for this.  I'll have a PR once I get the kid to school...
