### ISSUE TITLE
exception thrown from the inspector view after a full restart

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1623]
## What happened

I performed a full restart when the Flutter Inspector view was open (I had not interacted with the inspector view).

## Version information

IntelliJ IDEA `2017.3.2` • Flutter plugin `io.flutter 20.0` • Dart plugin `173.4127.31`

Flutter • channel unknown • unknown source
Framework • revision 6b1808dc24 (4 hours ago) • 2018-01-09 12:29:54 -0800
Engine • revision 16e365e722
Tools • Dart 1.25.0-dev.11.0

## Exception

null

```
java.lang.AssertionError
	at io.flutter.inspector.EvalOnDartLibrary.<init>(EvalOnDartLibrary.java:44)
	at io.flutter.inspector.InspectorService.getInspectorLibrary(InspectorService.java:74)
	at io.flutter.inspector.InspectorService.invokeServiceMethod(InspectorService.java:94)
	at io.flutter.inspector.InspectorService.getRootRenderObject(InspectorService.java:242)
	at io.flutter.inspector.InspectorService.getRoot(InspectorService.java:67)
	at io.flutter.view.InspectorPanel.recomputeTreeRoot(InspectorPanel.java:173)
	at io.flutter.view.InspectorPanel.onFlutterFrame(InspectorPanel.java:260)
	at io.flutter.inspector.InspectorService.lambda$onVmServiceReceived$9(InspectorService.java:330)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
This is pretty consistent.

**Comment by jacob314** [comment]
This was fix for M21.
