### ISSUE TITLE
Exception in Android Studio frequently

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter-intellij#1631]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 20.0.1` • Dart plugin `171.4424`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.view.InspectorPanel.recomputeTreeRoot(InspectorPanel.java:170)
	at io.flutter.view.InspectorPanel.onFlutterFrame(InspectorPanel.java:257)
	at io.flutter.inspector.InspectorService.lambda$onVmServiceReceived$7(InspectorService.java:286)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

## Exception

null

```
java.lang.NullPointerException
```

**Comment by devoncarew** [comment]
The source locations for this code has changed quite a bit, and I suspect that the underlaying issue probably isn't still a problem for the current codebase, but cc'ing @jacob314 in any case.

Thanks for the report!

**Comment by devoncarew** [comment]
Closing; I believe this is addressed
