### ISSUE TITLE
IndexOutOfBoundsException from Inspector

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1636]
This is from Android Studio 3.0, with the inspector from head.

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.google.common.collect.Iterables.get(Iterables.java:723)
	at io.flutter.inspector.EvalOnDartLibrary.<init>(EvalOnDartLibrary.java:45)
	at io.flutter.inspector.InspectorService.getInspectorLibrary(InspectorService.java:74)
	at io.flutter.inspector.InspectorService.invokeServiceMethod(InspectorService.java:94)
	at io.flutter.inspector.InspectorService.getRootWidget(InspectorService.java:238)
	at io.flutter.inspector.InspectorService.getRoot(InspectorService.java:65)
	at io.flutter.view.InspectorPanel.recomputeTreeRoot(InspectorPanel.java:174)
	at io.flutter.view.InspectorPanel.onFlutterFrame(InspectorPanel.java:261)
	at io.flutter.inspector.InspectorService.lambda$onVmServiceReceived$9(InspectorService.java:330)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jacob314** [comment]
I'm guessing this was hitting "run" not debug. Under a run build I'm reproducing a race condition where the isolate doesn't show up in the list of isolates but a flutter frame has already been rendered. I'm investigating a fix now.

**Comment by devoncarew** [comment]
Yes, I think this was with 'run'.

**Comment by jacob314** [comment]
This is fixed. We now manually listen for  the isolate loaded event ourselves if the race condition occurs in the dart plugin.
