### ISSUE TITLE
Crash in Flutter plugin after updating android SDK

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#1657]
## What happened

I just updated android SDK and emulator, and the Flutter plugin and IntelliJ gave the exception below.

## Version information

IntelliJ IDEA `2017.3.3` • Flutter plugin `io.flutter 21.0.3` • Dart plugin `173.4301.22`

Flutter • channel unknown • unknown source
Framework • revision 9872e5245c (28 hours ago) • 2018-01-22 10:57:40 -0800
Engine • revision e45eb692b1
Tools • Dart 2.0.0-dev.16.0

## Flutter Doctor output

This claims that I don't have Cocoapods which is definitely installed: it was version 1.3.1, although 1.4.0 is available.  running "brew upgrade" did fix this.

```
[✓] Flutter (on Mac OS X 10.13.2 17C205, locale en-US, channel unknown)
    • Flutter version unknown at /Users/gspencer/code/flutter
    • Framework revision 9872e5245c (28 hours ago), 2018-01-22 10:57:40 -0800
    • Engine revision e45eb692b1
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.93d8c9fe2a2c22dc95ec85866af108cfab71ad06

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.3)
    • Android SDK at /Users/gspencer/Library/Android/sdk
    • Android NDK at /Users/gspencer/Library/Android/sdk/ndk-bundle
    • Platform android-25, build-tools 25.0.3
    • ANDROID_HOME = /Users/gspencer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[-] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.3.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[-] Connected devices
    • None
```

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.sdk.FlutterSdkVersion.isSupported(FlutterSdkVersion.java:74)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:76)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

(same exception, repeated multiple times)

**Comment by devoncarew** [comment]
> This claims that I don't have Cocoapods which is definitely installed: it was version 1.3.1, although 1.4.0 is available. running "brew upgrade" did fix this.

/cc @cbracken and @xster for the Cocoapods check

**Comment by devoncarew** [comment]
@gspencergoog, I think you're hitting https://github.com/flutter/flutter-intellij/issues/1646; we should probably patch that fix into the (currently shipping) M21 version.
