### ISSUE TITLE
Getting NullPointerException on InteliJ startup

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter-intellij#1662]
When the InteliJ startups up I get an error message and the exception that is attached below.
I have reinstalled the IntelliJ, both Flutter & Dart plugins as well as Flutter libraries but it does not make any difference.

Also not sure if this is related but I am unable to run Flutter tests in the IDE getting this message:
 
Testing started at 20:56 ...
D:\repo__dart_flutter\__flutter\bin\cache\dart-sdk\bin\dart.exe --enable-vm-service:53420 D:\repo__dart_flutter\__flutter\bin\cache\dart-sdk\bin\snapshots\pub.dart.snapshot run test -r json D:/repo__at/_moneyvore/lib_utils/test/util/num_utils_test.dart
Observatory listening on http://127.0.0.1:53420/

Flutter is not available. If this is a Flutter project, make sure to always run
pub through the "flutter" executable.

Process finished with exit code 1

## Version information

IntelliJ IDEA `2017.3.3` • Flutter plugin `io.flutter 21.0.3` • Dart plugin `173.4301.22`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.sdk.FlutterSdkVersion.isSupported(FlutterSdkVersion.java:74)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:76)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
This  flutter doctor command output

[√] Flutter (on Microsoft Windows [Version 10.0.16299.192], locale en-GB, channel master)
    • Flutter version unknown at D:\repo__dart_flutter\__flutter
    • Framework revision 5ae770345a (23 hours ago), 2018-01-23 13:46:14 -0800
    • Engine revision 171d032f86
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.93d8c9fe2a2c22dc95ec85866af108cfab71ad06

[√] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at C:\DevTools\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 26.0.3
    • ANDROID_HOME = C:\DevTools\Android\sdk
    • Java binary at: C:\DevTools\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\DevTools\Android\AndroidStudio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 21.0.3
    • Dart plugin version 173.4301.22

[√] Connected devices
    • SM A300FU • c096d8a0 • android-arm • Android 6.0.1 (API 23)

**Comment by kostaa** [comment]
Just to add that when I run the tests from the command line I get this error for each test:

Shell: error: Unable to read Dart source 'package:test\src\runner\plugin\remote_platform_helpers.dart'.

**Comment by kostaa** [comment]
Just noticed that the same issue was previously raised but is is closed now
https://github.com/flutter/flutter-intellij/issues/1646

**Comment by kostaa** [comment]
I have rolled back Flutter plugin back to 20.0.3 but getting the same exception and the tests do not run either .....

**Comment by kostaa** [comment]
Deleted all .packages and pubspec.lock files & rerun lutter packages get 

Testing started at 23:35 ...
D:\repo__dart_flutter\__flutter\bin\cache\dart-sdk\bin\dart.exe --enable-vm-service:60367 D:\repo__dart_flutter\__flutter\bin\cache\dart-sdk\bin\snapshots\pub.dart.snapshot run test -r json D:/repo__at/_moneyvore/lib_utils/test/util/date_utils_test.dart
Observatory listening on http://127.0.0.1:60367/

**D:\repo__dart_flutter\__flutter\bin\packages\flutter_test\pubspec.yaml has changed since the pubspec.lock file was generated, please run "pub get" again.**

Process finished with exit code 65

**D:\repo__dart_flutter\__flutter**  is the directory where I cloned flutter repository.
Needless to say that there is no **packages\flutter_test\pubspec.yaml**  subdirectory under the bin directory .... not sure what is going on.

**Comment by devoncarew** [comment]
This should be addressed with the (just published) latest version of the plugin.

**Comment by kostaa** [comment]
Unfortunately the exception is still there with a slightly different stack though.

Is there anything I should check? I have suspicion that there are some 'external' factors involved here. I have the same IDE/plugins installed at work and have no issues.

null
java.lang.NullPointerException
	at io.flutter.sdk.FlutterSdkVersion.isMinRecommendedSupported(FlutterSdkVersion.java:65)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:76)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NullPointerException
	at io.flutter.sdk.FlutterSdkVersion.isMinRecommendedSupported(FlutterSdkVersion.java:65)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:76)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NullPointerException
	at io.flutter.sdk.FlutterSdkVersion.isMinRecommendedSupported(FlutterSdkVersion.java:65)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:76)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$5(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by devoncarew** [comment]
Can you verify that the flutter sdk path in your settings points to a Flutter sdk? Also, if you can include the contents of the `version` file from your sdk, that would be great.

From the stack trace, the issue looks like we must be locating the `<flutter-sdk>/version` file, but the contents don't parse into a valid semver like version.

**Comment by kostaa** [comment]
These are my settings

Flutter SDK directory "D:\repo__dart_flutter\__flutter"
Is on the path "PATH=.....\nodejs\;D:\repo__dart_flutter\__flutter\bin;C:\Program....."
Ii have also this environment variable "FLUTTER_ROOT=D:\repo__dart_flutter\__flutter\bin" (set up in desperation :-) )
Dart version 2.0.0-dev.16.0

But "D:\repo__dart_flutter\__flutter\version" content says **unknown**.

**Comment by devoncarew** [comment]
Is that the value you have in the Settings dialog, in `Languages & Frameworks > Flutter`?

<img width="265" alt="screen shot 2018-01-27 at 8 08 38 am" src="https://user-images.githubusercontent.com/1269969/35473753-86a70f88-0339-11e8-8f62-58cbe7ab1228.png">

> But "D:\repo__dart_flutter__flutter\version" content says unknown.

So, that file doesn't exist? What do you see if you run `flutter --version`?

**Comment by kostaa** [comment]
Sorry I have not explained that well. 

The version file D:\repo__dart_flutter__flutter\version" exists but it contains a single line with the 'unknown' string.

The Settings in Languages & Frameworks > Flutter dialog returns:

![image](https://user-images.githubusercontent.com/7585117/35473868-f2a208fc-037d-11e8-9dd8-3e66392fe7cf.png)

**Comment by devoncarew** [comment]
Ah! Thanks for digging into this.

/cc @tvolkert and @Hixie; it looks like in some cases flutter_tools will write `unknown` into the `version` file.

**Comment by Hixie** [comment]
It should write `0.0.0-unknown` now. It may have been doing that due to an only git version, in which case it should now give the right answer also. It might also give unknown if you used `--depth` to fetch the repo.

**Comment by devoncarew** [comment]
This should be addressed with the latest release.
