### ISSUE TITLE
Crash report when added Dart support to newly created project(created from existing sources)

### ISSUE THREAD

**Issue by aam** [flutter/flutter-intellij#1666]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Added Dart support to newly created project. Project was created from existing sources.

## Version information

IntelliJ IDEA `2017.3.3` • Flutter plugin `io.flutter 21.0.3` • Dart plugin `173.4301.22`

Flutter • channel master • git@github.com:aam/flutter.git
Framework • revision 75b97b00df (29 hours ago) • 2018-01-25 02:09:37 -0800
Engine • revision 93296fb4ea
Tools • Dart 2.0.0-dev.16.0

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.sdk.FlutterSdkVersion.isSupported(FlutterSdkVersion.java:74)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:76)
	at io.flutter.inspections.SdkConfigurationNotificationProvider.createNotificationPanel(SdkConfigurationNotificationProvider.java:30)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:236)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:187)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
fixed (and just pushed a new version to the plugin store)
