### ISSUE TITLE
Unexpected error while opening an existing flutter based project in Android Studio

### ISSUE THREAD

**Issue by sarah-fernandez** [flutter/flutter-intellij#1734]
## What happened

Unidentifierd error while opening an existing Flutter based project. Android Studio 3.1 Beta 1. Ubuntu 16.04.4 LTS, 8GB RAM.

## Version information

Android Studio `3.1 Beta 1` • Flutter plugin `io.flutter 21.2.3` • Dart plugin `173.4301.22`

Flutter 0.0.23-pre.26 • channel master • https://github.com/flutter/flutter.git
Framework • revision 08823595b0 (2 days ago) • 2018-02-01 20:23:40 -0800
Engine • revision de34a3e272
Tools • Dart 2.0.0-dev.19.0

## Exception

class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]

```
com.intellij.diagnostic.PluginException: class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.error(ActionManagerImpl.java:196)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:488)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:476)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:358)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:316)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen.collectAllActions(FlatWelcomeFrame.java:529)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen.collectAllActions(FlatWelcomeFrame.java:531)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen.createActionPanel(FlatWelcomeFrame.java:403)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen.createBody(FlatWelcomeFrame.java:275)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame$FlatWelcomeScreen.<init>(FlatWelcomeFrame.java:264)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.<init>(FlatWelcomeFrame.java:83)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrameProvider.createFrame(FlatWelcomeFrameProvider.java:28)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.customizeFlatWelcomeFrame(FirstRunWizardFrameProvider.java:65)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.createFrame(FirstRunWizardFrameProvider.java:46)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.showNow(WelcomeFrame.java:162)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:359)
	at com.intellij.idea.IdeaApplication.lambda$run$0(IdeaApplication.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:209)
	at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader[io.flutter, 21.2.3] com.intellij.ide.plugins.cl.PluginClassLoader@12e384c4
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
	... 34 more


```## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (on Linux, locale en_US.UTF-8, channel master)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0
[bug-report.txt](https://github.com/flutter/flutter-intellij/files/1692207/bug-report.txt)

**Comment by devoncarew** [comment]
Thanks for the report! The plugin currently does not work in Android Studio; you can track progress on that here: https://github.com/flutter/flutter-intellij/issues/1650.

**Comment by devoncarew** [comment]
(/cc @stevemessick)
