### ISSUE TITLE
Flutter plugin breaks enter action/option popup in Android Studio 3.2

### ISSUE THREAD

**Issue by scana** [flutter/flutter-intellij#1752]
## What happened

After installing Flutter plugin and restarting Android Studio, **Enter action or option name**  (via `CTRL+SHIFT+A` or `CMD+SHIFT+A`) popup becomes unusable (does not show any actions).

## Version information

Android Studio `3.2 Canary 1` • Flutter plugin `io.flutter 21.2.3` • Dart plugin `173.4301.22`

No Flutter sdk configured.

## Exception

class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]

```
com.intellij.diagnostic.PluginException: class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.error(ActionManagerImpl.java:196)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:488)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:476)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:358)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:316)
	at com.intellij.ide.actions.NewActionGroup.getChildren(NewActionGroup.java:34)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:306)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:313)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:313)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:313)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:313)
	at com.intellij.ide.util.gotoByName.GotoActionModel.<init>(GotoActionModel.java:94)
	at com.intellij.ide.util.gotoByName.GotoActionModel.<init>(GotoActionModel.java:84)
	at com.intellij.ide.actions.GotoActionAction.gotoActionPerformed(GotoActionAction.java:74)
	at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:69)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:561)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:464)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader[io.flutter, 21.2.3] com.intellij.ide.plugins.cl.PluginClassLoader@27baa02d
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
	... 30 more
```

**Comment by devoncarew** [comment]
Thanks for the report! We don't currently support AS canaries; you can track that work here: https://github.com/flutter/flutter-intellij/issues/1650.
