### ISSUE TITLE
`FlutterSdkUtilTest` test failing.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#177]
Like #173 says, this should really fail the build.  But it also shouldn't be broken!

```
io.flutter.sdk.FlutterSdkUtilTest > testSetup STANDARD_ERROR
    [   6379]   WARN - impl.local.LocalFileSystemBase - Invalid path: light_idea_test_case.iml 
    [   6506]   WARN - impl.local.LocalFileSystemBase - Invalid path: light_idea_test_case.iml 
    [   6718]   WARN - impl.local.LocalFileSystemBase - Invalid path: light_idea_test_case.iml 
    ERROR: The Flutter SDK is not configured
    com.intellij.execution.ExecutionException: The Flutter SDK is not configured
        at io.flutter.run.daemon.FlutterDaemonController.createCommandLine(FlutterDaemonController.java:195)
        at io.flutter.run.daemon.FlutterDaemonController.forkProcess(FlutterDaemonController.java:119)
        at io.flutter.run.daemon.FlutterAppManager.startDevicePoller(FlutterAppManager.java:138)
        at io.flutter.run.daemon.FlutterDaemonService.lambda$schedulePolling$3(FlutterDaemonService.java:152)
        at io.flutter.run.daemon.FlutterDaemonService$$Lambda$169/1330409629.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    ERROR: The Flutter SDK is not configured
    java.lang.AssertionError: The Flutter SDK is not configured
        at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:63)
        at com.intellij.testFramework.TestLogger.error(TestLogger.java:38)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
        at io.flutter.run.daemon.FlutterDaemonController.forkProcess(FlutterDaemonController.java:125)
        at io.flutter.run.daemon.FlutterAppManager.startDevicePoller(FlutterAppManager.java:138)
        at io.flutter.run.daemon.FlutterDaemonService.lambda$schedulePolling$3(FlutterDaemonService.java:152)
        at io.flutter.run.daemon.FlutterDaemonService$$Lambda$169/1330409629.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:308)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mit-mit** [comment]
Closing, we will address this as part of #173
