### ISSUE TITLE
Restart after plugin install throws Fatal IDE Exception.

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#178]
![screen shot 2016-09-28 at 10 04 33 am](https://cloud.githubusercontent.com/assets/67586/18923939/19b38c12-8563-11e6-81fc-b638509b7861.png)

![screen shot 2016-09-28 at 10 04 43 am](https://cloud.githubusercontent.com/assets/67586/18923943/1bb7a07a-8563-11e6-8527-eba515830a26.png)

**Comment by pq** [comment]
The work-around is to set the SDK and restart.  (Restart is required to get the daemon rebooted.)

**Comment by devoncarew** [comment]
Ran into this again (on a fresh install):

```
The Flutter SDK is not configured
com.intellij.execution.ExecutionException: The Flutter SDK is not configured
	at io.flutter.run.daemon.FlutterDaemonController.createCommandLine(FlutterDaemonController.java:210)
	at io.flutter.run.daemon.FlutterDaemonController.forkProcess(FlutterDaemonController.java:118)
	at io.flutter.run.daemon.FlutterAppManager.startDevicePoller(FlutterAppManager.java:153)
	at io.flutter.run.daemon.FlutterDaemonService.lambda$schedulePolling$0(FlutterDaemonService.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pq** [comment]
@stevemessick before I go mucking around in here, I wonder if this is on your radar...  If so, please re-assign.  In any event, we should coordinate.

**Comment by stevemessick** [comment]
I'm not looking at this. Today is vacation anyway.

**Comment by pq** [comment]
Did a bit of plumbing in this weekend and have a few questions.  Maybe we can chat today.
