### ISSUE TITLE
exception from the widget inspector

### ISSUE THREAD

**Issue by Gautineo** [flutter/flutter-intellij#1834]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 22.0.1` • Dart plugin `171.4424`

Error getting Flutter sdk information.

## Exception

```
Error evaluating expression:
Unhandled exception:
Id does not exist.
#0      WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:222)
#1      WidgetInspectorService.getChildren (package:flutter/src/widgets/widget_inspector.dart:386)
#2      Eval (evaluate:source:1:39)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.[]= (dart:collection-patch/dart:collection/compact_hash.dart:248)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin._init (dart:collection-patch/dart:collection/compact_hash.dart:188)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin._rehash (dart:collection-patch/dart:collection/compact_hash.dart:164)
#6      _HashVMBase&MapMixin&&_LinkedHashMapMixin._insert (dart:collection-patch/dart:collection/compact_hash.dart:208)
#7      _HashVMBase&MapMixin&&_LinkedHashMapMixin.[]= (dart:collection-patch/dart:collection/compact_hash.dart:258)
#8      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:194)
#9      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:355)
#10     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:373)
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#12     ListIterable.toList (dart:_internal/iterable.dart:219)
#13     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:373)
#14     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:380)
#15     Eval (evaluate:source:1:39)
#16     Eval (evaluate:source:1:4)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:121)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:410)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
@jacob314 

It looks like we had trouble getting the version of the flutter sdk; it's possible this is from an old flutter.

**Comment by jacob314** [comment]
I've seen this as well but only very sporadically. From what I can tell from the one time I had it paused in a debugger, there is a bug in the vm implementation of identity hash map which is strange.

**Comment by devoncarew** [comment]
assumed fixed with the recent work to serialize service protocol resuests
