### ISSUE TITLE
Exception when using the inspector: Id does not exist

### ISSUE THREAD

**Issue by the4thfloor** [flutter/flutter-intellij#1861]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2018.1 EAP` • Flutter plugin `io.flutter 22.2.3` • Dart plugin `181.3870.1`

Flutter 0.1.8-pre.7 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6993b203c0 (35 hours ago) • 2018-02-27 17:39:49 -0800
Engine • revision e133da723c
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

## Exception

Error evaluating expression:
```
Unhandled exception:
Id does not exist.
#0      WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:222:7)
#1      Eval (evaluate:source:1:39)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin._init (dart:collection-patch/dart:collection/compact_hash.dart:184)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin._rehash (dart:collection-patch/dart:collection/compact_hash.dart:164)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin._insert (dart:collection-patch/dart:collection/compact_hash.dart:208)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.[]= (dart:collection-patch/dart:collection/compact_hash.dart:258)
#6      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:194:25)
#7      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:355:24)
#8      WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:373:69)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#10     ListIterable.toList (dart:_internal/iterable.dart:219)
#11     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:373:99)
#12     WidgetInspectorService._pathNodeToJson (package:flutter/src/widgets/widget_inspector.dart:332:19)
#13     WidgetInspectorService.getParentChain.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:324:64)
#14     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#15     ListIterable.toList (dart:_internal/iterable.dart:219)
#16     WidgetInspectorService.getParentChain (package:flutter/src/widgets/widget_inspector.dart:324:98)
#17     Eval (evaluate:source:1:39)
#18     _StringBase.substring (dart:core-patch/dart:core/string_patch.dart:362)
#19     describeEnum (package:flutter/src/foundation/diagnostics.dart:2056:22)
#20     DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1773:28)
#21     FlagProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1374:53)
#22     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:353:43)
#23     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:373:69)
#24     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#25     ListIterable.toList (dart:_internal/iterable.dart:219)
#26     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:373:99)
#27     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:380:24)
#28     Eval (evaluate:source:1:39)
```

```
java.lang.Throwable: Error evaluating expression:
Unhandled exception:
Id does not exist.
#0      WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:222:7)
#1      Eval (evaluate:source:1:39)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin._init (dart:collection-patch/dart:collection/compact_hash.dart:184)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin._rehash (dart:collection-patch/dart:collection/compact_hash.dart:164)
#4      _HashVMBase&MapMixin&&_LinkedHashMapMixin._insert (dart:collection-patch/dart:collection/compact_hash.dart:208)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.[]= (dart:collection-patch/dart:collection/compact_hash.dart:258)
#6      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:194:25)
#7      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:355:24)
#8      WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:373:69)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#10     ListIterable.toList (dart:_internal/iterable.dart:219)
#11     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:373:99)
#12     WidgetInspectorService._pathNodeToJson (package:flutter/src/widgets/widget_inspector.dart:332:19)
#13     WidgetInspectorService.getParentChain.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:324:64)
#14     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#15     ListIterable.toList (dart:_internal/iterable.dart:219)
#16     WidgetInspectorService.getParentChain (package:flutter/src/widgets/widget_inspector.dart:324:98)
#17     Eval (evaluate:source:1:39)
#18     _StringBase.substring (dart:core-patch/dart:core/string_patch.dart:362)
#19     describeEnum (package:flutter/src/foundation/diagnostics.dart:2056:22)
#20     DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1773:28)
#21     FlagProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1374:53)
#22     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:353:43)
#23     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:373:69)
#24     MappedListIterable.elementAt (dart:_internal/iterable.dart:414)
#25     ListIterable.toList (dart:_internal/iterable.dart:219)
#26     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:373:99)
#27     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:380:24)
#28     Eval (evaluate:source:1:39)

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:121)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Exception

java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@43415610

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@43415610
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:122)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
Caused by: java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@43415610
	... 5 more
```

**Comment by jacob314** [comment]
This should be fixed by https://github.com/flutter/flutter-intellij/pull/1980
