### ISSUE TITLE
printing a List of Maps on iOS simulator displays an exception in IntelliJ

### ISSUE THREAD

**Issue by habdulkafi** [flutter/flutter-intellij#1879]
## What happened

relevant code (in main):

```
  List<Map> expectedList = [
    {"name": "updated name", "id": 1, "value": 9876, "num": 456.789},
    {"name": "another name", "id": 2, "value": 12345678, "num": 3.1416}
  ];
  print(expectedList);

```

This happens on build (full restart) for iOS in the iPhone X simulator.  Does not happen when building (full restart) on an android phone plugged in.  

Simpler examples such as:

```
  List<String> l = ["hello", "bye"];
  print(l);
```
and
```
  Map m = {"name": "updated name", "id": 1, "value": 9876, "num": 456.789};
  print(m);
```
work as expected

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 22.2.1` • Dart plugin `171.4424`

Flutter 0.1.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f914e701c5 (12 days ago) • 2018-02-19 21:12:17 +0000
Engine • revision 13cf22c284
Tools • Dart 2.0.0-dev.27.0-flutter-0d5cf900b0

flutter doctor -v:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (on Mac OS X 10.13.3 17D102, locale en-US, channel beta)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] Connected devices

• No issues found!
Process finished with exit code 0

## Exception

Unable to parse response from Flutter daemon: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 24 path $.name

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 24 path $.name
	at com.google.gson.internal.Streams.parse(Streams.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:84)
	at com.google.gson.JsonParser.parse(JsonParser.java:59)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:161)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:133)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy15.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:201)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:290)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:84)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:162)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 24 path $.name
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:495)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:742)
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
	at com.google.gson.internal.Streams.parse(Streams.java:48)
	... 23 more
```

**Comment by stevemessick** [comment]
I saw this output from the iOS simulator. It is not valid json; there are no string delimiters, and there is no indication it is a list.
```
{name: updated name, id: 1, value: 9876, num: 456.789}, {name: another name, id: 2, value: 12345678, num: 3.1416}
```

cc @cbracken

**Comment by cbracken** [comment]
Based on `Unable to parse response from Flutter daemon`,
/cc @devoncarew @danrubel who know all about the daemon and might have some thoughts on what's going on (or at least point to the relevant bit of the code).

**Comment by devoncarew** [comment]
Yes, this is an artifact of how we're passing stdout and stderr from the app to the IDE. This will only hit in rare cases. We should likely harden this a bit - so we don't throw parse errors - and look into a better way of encoding the stdout so these types of issues aren't possible.

**Comment by brianegan** [comment]
Ran into this today as well:

## What happened

  1. Clone this repo: https://startflutter.com/themes/crypto_market/
  2. Run the app on iOS 8 Simulator
  3. See crash appear in IntelliJ

## Version information

IntelliJ IDEA `2017.3.5` • Flutter plugin `io.flutter 22.2.2` • Dart plugin `173.4548.30`

Flutter 0.1.5 • channel beta • git@github.com:flutter/flutter.git
Framework • revision 3ea4d06340 (4 weeks ago) • 2018-02-22 11:12:39 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759

## Exception

Unable to parse response from Flutter daemon: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 428 path $

```
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 428 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:161)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:133)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:239)
	at com.sun.proxy.$Proxy16.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:213)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 428 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 23 more
```

**Comment by devoncarew** [comment]
Thanks for the reports! Moving this to something to address shortly.
