### ISSUE TITLE
Emulator not "visible" after system restore from hibernation and ADB process crashing

### ISSUE THREAD

**Issue by mslavkovski** [flutter/flutter-intellij#1899]
## What happened

After system restore from hibernation the android emulator is not visible to the IDE, the app can't run. When starting the app Android Studio gives message "No devices attached" and the adb.exe is crashing in some kind loop. It fills the start menu taskbar. Clicking "Close the program" button only reduces the number of active messages but they keep filling up the taskbar. The only solution is to restart the PC.

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 22.2.1` • Dart plugin `171.4424`

Error getting Flutter sdk information.

## Exception

A Flutter device daemon stopped unexpectedly.
```
Details: Daemon #8 exited. Exit code: 255. Stderr:

Unhandled exception:
Exception: adb not responding
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:97)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:128)
<asynchronous suspension>
#3      _deviceToMap (package:flutter_tools/src/commands/daemon.dart:710)
<asynchronous suspension>
#4      DeviceDomain._onDeviceEvent.<anonymous closure>.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:590)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:662)
#10     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#17     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:152)
	at io.flutter.run.daemon.DeviceService.daemonStopped(DeviceService.java:189)
	at io.flutter.run.daemon.DeviceDaemon$Listener.processTerminated(DeviceDaemon.java:357)
	at io.flutter.run.daemon.DaemonApi$1.processTerminated(DaemonApi.java:146)
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy15.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:184)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:260)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:165)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:187)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:92)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:152)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:137)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pq** [comment]
c @devoncarew

**Comment by devoncarew** [comment]
This issue was moved to flutter/flutter#15810
