### ISSUE TITLE
Error getting Flutter sdk information.

### ISSUE THREAD

**Issue by HackSoul** [flutter/flutter-intellij#1900]
---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2017.3.4` • Flutter plugin `io.flutter 22.2.2` • Dart plugin `173.4548.30`

Error getting Flutter sdk information.

## Exception

Editor of class com.intellij.openapi.editor.impl.EditorImpl hasn't been released:

```
com.intellij.openapi.util.TraceableDisposable.ObjectNotDisposedException: See stack trace responsible for creation of unreleased object below 
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:146)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:220)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:190)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:68)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:903)
	at com.intellij.execution.impl.ConsoleViewImpl.m(ConsoleViewImpl.java:880)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.execution.impl.ConsoleViewImpl.n(ConsoleViewImpl.java:879)
	at com.intellij.execution.impl.ConsoleViewImpl.e(ConsoleViewImpl.java:452)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:431)
	at net.orfjackal.sbt.plugin.SbtConsole.attachToToolWindow(SbtConsole.java:133)
	at net.orfjackal.sbt.plugin.SbtConsole.ensureAttachedToToolWindow(SbtConsole.java:122)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.registerToolWindow(SbtRunnerComponent.java:112)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent.access$400(SbtRunnerComponent.java:35)
	at net.orfjackal.sbt.plugin.SbtRunnerComponent$2.run(SbtRunnerComponent.java:91)
	at com.intellij.ide.startup.impl.StartupManagerImpl.c(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:359)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:197)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:415)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
It looks like this is coming from the `idea-sbt-plugin`?

cc @devoncarew for a second opinion

**Comment by pq** [comment]
@HackSoul : would you mind running  `flutter doctor -v` from the command line and pasting the results here?  That context will help us debug.

Thanks!


Could you paste the full output of running `flutter doctor -v` here (available from the command
line)?
