### ISSUE TITLE
Exception when starting emulator

### ISSUE THREAD

**Issue by consulion** [flutter/flutter-intellij#1907]
## What happened

Created virtual device and started it.

## Version information

Android Studio `3.0.1` • Flutter plugin `io.flutter 22.2.1` • Dart plugin `171.4424`

Error getting Flutter sdk information.

## Exception

A Flutter device daemon stopped unexpectedly.
Details: Daemon #3 exited. Exit code: 255. Stderr:
```
Unhandled exception:
Exception: adb not responding
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
#1      AndroidDevice._getProperty (package:flutter_tools/src/android/android_device.dart:97)
<asynchronous suspension>
#2      AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart:128)
<asynchronous suspension>
#3      _deviceToMap (package:flutter_tools/src/commands/daemon.dart:710)
<asynchronous suspension>
#4      DeviceDomain._onDeviceEvent.<anonymous closure>.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:590)
<asynchronous suspension>
#5      _rootRunUnary (dart:async/zone.dart:1134)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:662)
#10     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:342)
#11     _rootRun (dart:async/zone.dart:1126)
#12     _CustomZone.run (dart:async/zone.dart:1023)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:391)
#17     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:152)
	at io.flutter.run.daemon.DeviceService.daemonStopped(DeviceService.java:189)
	at io.flutter.run.daemon.DeviceDaemon$Listener.processTerminated(DeviceDaemon.java:357)
	at io.flutter.run.daemon.DaemonApi$1.processTerminated(DaemonApi.java:146)
	at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy15.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$3.run(ProcessHandler.java:184)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:260)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:165)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.BaseOSProcessHandler.onOSProcessTerminated(BaseOSProcessHandler.java:187)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:92)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:152)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:137)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pq** [comment]
Thanks for the report @consulion !

Could you paste the full output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`)?  That will help us diagnose.

**Comment by consulion** [comment]
Hi,
unfortunately I can't reproduce said behaviour anymore;
anyway - here is the output of `fluttr doctor -v`  - just in case you are still interested:

```
> flutter doctor -v
[√] Flutter (Channel @u, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale de-DE)
    • Flutter version 0.1.5 at C:\Users\username\flutter
    • Framework revision 3ea4d06340 (3 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at C:\Users\username\AppData\Local\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = C:\Users\username\AppData\Local\Android\android-sdk
    • Java binary at: C:\Users\username\Downloads\android-studio-ide-171.4101728-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Users\username\Downloads\android-studio-ide-171.4101728-windows\android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-736)

[√] Connected devices (1 available)
    • sdk google phone armv7 • emulator-5554 • android-arm • Android 6.0 (API 23) (emulator)

• No issues found!
```

**Comment by pq** [comment]
Thanks for following up!
