### ISSUE TITLE
"Matrix cannot be inverted" exception from the inspector

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1948]
When entering inspect mode, and clicking on a widget in the app, I saw the following exception:

```
The following ArgumentError was thrown while handling a gesture:
Invalid argument (other): Matrix cannot be inverted: Instance of 'Matrix4'

When the exception was thrown, this was the stack:
#0      new Matrix4.inverted (file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.5/lib/src/vector_math_64/matrix4.dart:226:7)
#1      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:567:33)
#2      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#3      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#4      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#5      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#6      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#7      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#8      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#9      _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#10     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#11     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#12     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#13     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#14     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#15     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#16     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#17     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#18     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#19     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#20     _WidgetInspectorState._hitTestHelper (package:flutter/src/widgets/widget_inspector.dart:584:11)
#21     _WidgetInspectorState.hitTest (package:flutter/src/widgets/widget_inspector.dart:613:5)
#22     _WidgetInspectorState._inspectAt (package:flutter/src/widgets/widget_inspector.dart:631:41)
#23     _WidgetInspectorState._handlePanDown (package:flutter/src/widgets/widget_inspector.dart:640:5)
#24     DragGestureRecognizer.addPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:123:46)
#25     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#26     DragGestureRecognizer.addPointer (package:flutter/src/gestures/monodrag.dart:123:9)
#27     RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:602:18)
#28     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2397:14)
#29     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#30     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#31     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#32     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#33     _invoke1 (dart:ui/hooks.dart:134:13)
#34     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

This was when running with preview dart 2, though I don't know if its related.

Marking this as a P1 with the assumption that this is ~widespread; if no, we can deprioritize.

**Comment by devoncarew** [comment]
I also see this in non-dart 2 mode.
