### ISSUE TITLE
Error while drilling down the tree in the "Flutter Inspector"

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter-intellij#2001]
## What happened

I was drilling down the widget tree in the "Flutter Inspector". When I reached `SliverList` and iterated over its `AutomaticKeepAlive` children, this happened. It seems the inspector attempts to automatically expand the nodes, but does this asynchronously. By the time it expands I already moved on to another item. It takes focus back to a different item in the list. After a few rounds of this back'n'forth, I see this error.

## Version information

IntelliJ IDEA `2017.3.5` • Flutter plugin `io.flutter 22.2.2` • Dart plugin `173.4548.30`

Flutter 0.2.5-pre.26 • channel unknown • unknown source
Framework • revision aba0379dcc (27 hours ago) • 2018-03-22 13:21:07 -0700
Engine • revision 6280adbfb1
Tools • Dart 2.0.0-dev.39.0.flutter-06949dc985

## Exception

Error evaluating expression:
```
Unhandled exception:
Id does not exist.
#0      WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:224:7)
#1      WidgetInspectorService.getParentChain (package:flutter/src/widgets/widget_inspector.dart:328:26)
#2      Eval (evaluate:source:1:39)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._init (dart:collection/runtime/libcompact_hash.dart:190:15)
#5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._rehash (dart:collection/runtime/libcompact_hash.dart:166:7)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._insert (dart:collection/runtime/libcompact_hash.dart:210:7)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart:260:7)
#8      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:196:25)
#9      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:368:24)
#10     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:402:69)
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#12     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#13     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:402:99)
#14     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:409:24)
#15     Eval (evaluate:source:1:39)
#16     _CompactLinkedHashSet._init (dart:collection/runtime/libcompact_hash.dart)
#17     _CompactLinkedHashSet._rehash (dart:collection/runtime/libcompact_hash.dart:496:7)
#18     _CompactLinkedHashSet.add (dart:collection/runtime/libcompact_hash.dart:546:7)
#19     WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:197:13)
#20     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:368:24)
#21     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:402:69)
#22     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#23     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#24     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:402:99)
#25     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:409:24)
#26     Eval (evaluate:source:1:39)
```

```
java.lang.Throwable: Error evaluating expression:
Unhandled exception:
Id does not exist.
#0      WidgetInspectorService.toObject (package:flutter/src/widgets/widget_inspector.dart:224:7)
#1      WidgetInspectorService.getParentChain (package:flutter/src/widgets/widget_inspector.dart:328:26)
#2      Eval (evaluate:source:1:39)
#3      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._init (dart:collection/runtime/libcompact_hash.dart:190:15)
#5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._rehash (dart:collection/runtime/libcompact_hash.dart:166:7)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._insert (dart:collection/runtime/libcompact_hash.dart:210:7)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart:260:7)
#8      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:196:25)
#9      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:368:24)
#10     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:402:69)
#11     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#12     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#13     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:402:99)
#14     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:409:24)
#15     Eval (evaluate:source:1:39)
#16     _CompactLinkedHashSet._init (dart:collection/runtime/libcompact_hash.dart)
#17     _CompactLinkedHashSet._rehash (dart:collection/runtime/libcompact_hash.dart:496:7)
#18     _CompactLinkedHashSet.add (dart:collection/runtime/libcompact_hash.dart:546:7)
#19     WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:197:13)
#20     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:368:24)
#21     WidgetInspectorService._nodesToJson.<anonymous closure> (package:flutter/src/widgets/widget_inspector.dart:402:69)
#22     MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#23     ListIterable.toList (dart:_internal/iterable.dart:219:19)
#24     WidgetInspectorService._nodesToJson (package:flutter/src/widgets/widget_inspector.dart:402:99)
#25     WidgetInspectorService.getProperties (package:flutter/src/widgets/widget_inspector.dart:409:24)
#26     Eval (evaluate:source:1:39)

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:121)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Exception

java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@28a0c34e

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@28a0c34e
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:122)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
Caused by: java.lang.RuntimeException: org.dartlang.vm.service.element.ErrorRef@28a0c34e
	... 5 more
```

**Comment by devoncarew** [comment]
This may be addressed by a recent fix from @jacob314; he would know for sure.

**Comment by jacob314** [comment]
The intellij side of what I am 95% confident will fix this. The flutter sdk fix is pending review.
https://github.com/flutter/flutter/pull/15876

**Comment by yjbanov** [comment]
Feel free to close if you are sufficiently certain that this is fixed.
