### ISSUE TITLE
errors written to the console on hot reload

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#201]
```
Error: Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$4
  but received {"type":"Sentinel","kind":"Collected","valueAsString":"<collected>"}
```

This will probably require changes to the debugger code; it needs to be more tolerant of sentinels being returned instead of the expected values, and we shouldn't spam library errors to the console.

**Comment by devoncarew** [comment]
```
Expected response for class com.jetbrains.lang.dart.ide.runner.server.vmService.VmServiceWrapper$4
  but received {"type":"Sentinel","kind":"Collected","valueAsString":"<collected>"}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcessZ$2.logError(DartVmServiceDebugProcessZ.java:161)
	at org.dartlang.vm.service.VmServiceBase.logUnknownResponse(VmServiceBase.java:341)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:511)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:99)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by pq** [comment]
@devoncarew : Does #205 fix this?

**Comment by devoncarew** [comment]
They're not written to the console, but we need to make some changes to the Java debugger library (`org.dartlang.vm.service`) to fix the underlying issue.

**Comment by pq** [comment]
@devoncarew is this a candidate for the external alpha?

**Comment by devoncarew** [comment]
Sure, it's good cleanup.

**Comment by mit-mit** [comment]
Doesn't seem critical for 0.1, bumping to 0.2

**Comment by devoncarew** [comment]
I no longer see this.
