### ISSUE TITLE
Auto generated flutter plugin error Android Studio 3.1

### ISSUE THREAD

**Issue by sebasbad** [flutter/flutter-intellij#2037]
## What happened

Running a flutter app on an android emulator and an android device using Android Studio

## Version information

Android Studio `3.1` • Flutter plugin `io.flutter 23.1.2` • Dart plugin `173.4700`

Flutter • channel alpha • https://github.com/flutter/flutter.git
Framework • revision 8f65fec5f5 (4 months ago) • 2017-12-12 09:50:14 -0800
Engine • revision edaecdc8b8
Tools • Dart 1.25.0-dev.11.0

## Exception

Error evaluating expression:
```
Unhandled exception:
NoSuchMethodError: Class 'WidgetInspectorService' has no instance method 'isWidgetTreeReady'.
Receiver: Instance of 'WidgetInspectorService'
Tried calling: isWidgetTreeReady("intellij_inspector_5")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Eval (evaluate:source:1:39)
#2      Eval (evaluate:source:1:39)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:124)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Exception

Error evaluating expression:
Unhandled exception:
NoSuchMethodError: Class 'WidgetInspectorService' has no instance method 'isWidgetTreeReady'.
Receiver: Instance of 'WidgetInspectorService'
Tried calling: isWidgetTreeReady("intellij_inspector_5")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      Eval (evaluate:source:1:39)

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:124)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
@sebasbad, thanks for the report!

> revision 8f65fec5f5 (4 months ago)

The flutter alpha channel is pretty old at this point. I would:

- git checkout master
- git pull
- flutter channel beta
- flutter upgrade

**Comment by devoncarew** [comment]
That will leave you up-to-date, and on the beta channel.
