### ISSUE TITLE
NPE on rebuild after restoring Android Studio

### ISSUE THREAD

**Issue by colintheshots** [flutter/flutter-intellij#2040]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Android Studio Flutter build for Android froze on full restart of my Flutter app, so I restarted it and did a full rebuild again. The build worked and ran, but I get a NullPointerException.

## Version info

flutter doctor -v
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.2.3 at /Users/colinlee/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/colinlee/Library/Android/sdk
    • Android NDK at /Users/colinlee/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.0.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 3 categories.

---

## What happened

NullPointer Exception. Stacktrace below.

## Version information

Android Studio `3.1` • Flutter plugin `io.flutter 23.1.2` • Dart plugin `173.4700`

Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (3 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:176)
	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:155)
	at io.flutter.view.FlutterView.displayEmptyContent(FlutterView.java:304)
	at io.flutter.view.FlutterView.access$300(FlutterView.java:64)
	at io.flutter.view.FlutterView$2.lambda$connectionClosed$0(FlutterView.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jwren** [comment]
@devoncarew    A null is being returned from createContent from this line:

`emptyContent = contentManager.getFactory().createContent(panel, null, false);`

which should not be possible from the IntelliJ platform.

**Comment by devoncarew** [comment]
Yes, but looking into it, I'm not sure why or how it would throw.

**Comment by scheglov** [comment]
Do we talk about this line?
```dart
        addSelectedContent(content);
```

The exception might be a a different line, there might have been changes in Android Studio. I wish there was a way to look at exactly this method in AS.

Anyway, its does not seem probably to me that `content` is `null`. There are two other dereferences of `content`, e.g. `((ContentImpl)content).setManager(this);` Two other fields - `myContents` and `mySelection` are final. But `myUI` is not final, and is set to `null` in `dispose`. So, I think the toolWindow or/and its ContentManager has been disposed and we need to check for this situation in our event handler.

**Comment by devoncarew** [comment]
Thanks for the analysis! Seems reasonable re: `myUI` being the null culprit.

**Comment by stevemessick** [comment]
AS is built on 2017.3.5. In that version line 176 in that file is:
```java
    if (myUI.isToSelectAddedContent() || mySelection.isEmpty() && !myUI.canBeEmptySelection()) {
```
Which supports @scheglov's analysis of an improper dispose call.
