### ISSUE TITLE
the flutter plugin installs into the new Android Studio 3.2 canary, but throws an exception at runtime

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2074]
The new Android Studio canary has moved to being based on the 2018.1 IntelliJ platform. We install into it, but then throw an exception at runtime (a missing class or some such). We need to change our 2018.1 build to also build the android studio parts of the plugin.

@stevemessick

**Comment by stevemessick** [comment]
I'm working on it. We have compile issues. The version of Dart plugin used in current development does not work in Canary 10. The version that does causes compile errors in two Flutter classes. Nothing to do with Android Studio, though. Once the compile issues are solved I'll look at runtime problems.

**Comment by devoncarew** [comment]
OK; re: the compile errors, it could be that some of the Dart plugin changes didn't make it back to that specific version. If that's the case, we could just ask for them to be backported.

**Comment by stevemessick** [comment]
Or, it looks like I can just drop back to the sources for branch 173. That eliminated the compile errors.

Need more info about the exception you saw. Opening AS c10 works for me. I saw an exception down in some Kotlin thing when I created a project but couldn't reproduce it.

**Comment by devoncarew** [comment]
I think this is from the Flutter plugin declaring a class in the plugin.xml, but the build not including the Android Studio Flutter classes - I think we just need to build 2018.1 with the AS sources.

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: io.flutter.FlutterStudioStartupActivity PluginClassLoader[io.flutter, 23.2.3] com.intellij.ide.plugins.cl.PluginClassLoader@27a591d2
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:161)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:241)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:190)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:108)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:101)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:96)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:149)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$openProject$8(ProjectManagerImpl.java:404)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:435)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:418)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:495)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:486)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:326)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:575)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.flutter.FlutterStudioStartupActivity PluginClassLoader[io.flutter, 23.2.3] com.intellij.ide.plugins.cl.PluginClassLoader@27a591d2
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:158)
	... 29 more
```

**Comment by stevemessick** [comment]
That sounds right. I'm getting close to a clean build but not quite there yet.

**Comment by stevemessick** [comment]
With #2080 we are close to having this fixed. We still need a new version of the Dart plugin before we can fully test our plugin in Android Studio 3.2.

The exception I mentioned earlier is also thrown when creating an Android project, so it will probably be fixed in the next Canary update.
