### ISSUE TITLE
IDE Crash Report

### ISSUE THREAD

**Issue by ndemari** [flutter/flutter-intellij#2082]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

I was debuging an app on iOS. I was scrolling up and down a list view

## Version information

Android Studio `3.1.1` • Flutter plugin `io.flutter 23.2.2` • Dart plugin `173.4700`

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (10 days ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

## Exception

Error evaluating expression:
```
Unhandled exception:
NoSuchMethodError: The getter 'count' was called on null.
Receiver: null
Tried calling: count
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:201:23)
#2      WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:370:23)
#3      WidgetInspectorService._serialize (package:flutter/src/widgets/widget_inspector.dart:396:24)
#4      WidgetInspectorService.getRootRenderObject (package:flutter/src/widgets/widget_inspector.dart:428:12)
#5      Eval (evaluate:source:1:39)
#6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._findValueOrInsertPoint (dart:collection/runtime/libcompact_hash.dart:224:7)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart:255:19)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._init (dart:collection/runtime/libcompact_hash.dart:190:15)
#9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._rehash (dart:collection/runtime/libcompact_hash.dart:166:7)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin._insert (dart:collection/runtime/libcompact_hash.dart:210:7)
#11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.[]= (dart:collection/runtime/libcompact_hash.dart:260:7)
#12     WidgetInspectorService.toId (package:flutter/src/widgets/widget_inspector.dart:196:25)
#13     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:368:24)
#14     WidgetInspectorService._serialize (package:flutter/src/widgets/widget_inspector.dart:396:24)
#15     WidgetInspectorService.getRootWidget (package:flutter/src/widgets/widget_inspector.dart:422:12)
#16     Eval (evaluate:source:1:39)
```

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at io.flutter.inspector.EvalOnDartLibrary$2.received(EvalOnDartLibrary.java:124)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:456)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
I'm going to optimistically assume that this has been addressed as part of the inspector / service protocol refactor.
