### ISSUE TITLE
Null exception after reload of project.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#2103]
## What happened

It was restarting after a `git reset --hard`.

After the reset, IntelliJ told me that it couldn't handle the file changes, and needed to reload the project, so I say "yes, go ahead, reload", and this error occurred after it restarted.

## Version information

IntelliJ IDEA `2017.3.5` • Flutter plugin `io.flutter 23.2.2` • Dart plugin `173.4700`

Flutter 0.3.1-pre.37 • channel widget_image • git@github.com:gspencergoog/flutter.git
Framework • revision 0a76df892b (18 hours ago) • 2018-04-18 16:21:38 -0700
Engine • revision 8973c733a5
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:173)
	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:152)
	at io.flutter.view.FlutterView.displayEmptyContent(FlutterView.java:304)
	at io.flutter.view.FlutterView.access$300(FlutterView.java:64)
	at io.flutter.view.FlutterView$2.lambda$connectionClosed$0(FlutterView.java:272)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
Thanks for the report @gspencergoog!

I think this is the same issue reported in https://github.com/flutter/flutter-intellij/issues/2087.  I'm taking a second look to make sure it's fixed in the next release.
