### ISSUE TITLE
Adding --profile to options causes problem

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#2148]
## What happened

I tried running the gallery, but I added "--profile" to the "additional options" in the run configuration. That caused the attached error.

## Version information

IntelliJ IDEA `2017.3.5` • Flutter plugin `io.flutter 23.2.2` • Dart plugin `173.4700`

Flutter 0.3.6-pre.10 • channel master • git@github.com:flutter/flutter.git
Framework • revision 76aa02875e (71 minutes ago) • 2018-04-25 11:35:35 -0700
Engine • revision 9859af123e
Tools • Dart 2.0.0-dev.49.0.flutter-29d6e96370

## Exception

org.dartlang.vm.service.element.RPCError@255eb205

```
java.lang.Throwable: org.dartlang.vm.service.element.RPCError@255eb205
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:139)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:106)
	at io.flutter.inspector.EvalOnDartLibrary$2.onError(EvalOnDartLibrary.java:118)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:464)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Exception

org.dartlang.vm.service.element.RPCError@42f07c7b

```
java.lang.Throwable: org.dartlang.vm.service.element.RPCError@42f07c7b
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:139)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:106)
	at io.flutter.inspector.EvalOnDartLibrary$2.onError(EvalOnDartLibrary.java:118)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:464)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Doctor output

```
[✓] Flutter (Channel master, v0.3.6-pre.10, on Linux, locale en_US.UTF-8)
    • Flutter version 0.3.6-pre.10 at /usr/local/google/home/gspencer/code/flutter
    • Framework revision 76aa02875e (72 minutes ago), 2018-04-25 11:35:35 -0700
    • Engine revision 9859af123e
    • Dart version 2.0.0-dev.49.0.flutter-29d6e96370

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /usr/local/google/home/gspencer/Android/Sdk
    • Android NDK at /usr/local/google/home/gspencer/Android/Sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /usr/local/google/home/gspencer/Android/Sdk
    • Java binary at: /opt/android-studio-with-blaze-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-with-blaze-3.0
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio-with-blaze-2.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1)
    • IntelliJ at /opt/intellij-ce-2017.1
    • Flutter plugin version 18.4
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at /opt/intellij-ce-2017.2
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1)
    • IntelliJ at /opt/intellij-ue-2017.1
    • Flutter plugin version 18.2
    • Dart plugin version 171.4694.29

[✓] Connected devices (1 available)
    • Nexus 6P • 84B7N15A07007628 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by devoncarew** [comment]
Hmm, yeah, that would cause problems. We think that's a debug mode run, so we expect to be able to do things like interact with the debugger. In profile mode, the service protocol is still available, but you're more limited in what you can do.

For this case, I'd use the `Run > Flutter Run in Profile Mode` menu item.

**Comment by devoncarew** [comment]
@gspencergoog, I'm going to close this since the latest release has improved support for running in profile mode - users will be less likely to manually enter `--profile` into launch configs.
