### ISSUE TITLE
java.lang.AssertionError

### ISSUE THREAD

**Issue by xxnjdlys** [flutter/flutter-intellij#2152]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2018.1` • Flutter plugin `io.flutter 23.2.3` • Dart plugin `181.4203.498`

Flutter 0.3.6-pre.7 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8f03d27fa7 (27 hours ago) • 2018-04-24 19:14:39 -0700
Engine • revision 6a93ef1c70
Tools • Dart 2.0.0-dev.48.0.flutter-fe606f890b

## Exception

null

```
java.lang.AssertionError
	at io.flutter.inspector.EvalOnDartLibrary$1.received(EvalOnDartLibrary.java:58)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:586)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:450)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by pq** [comment]
@jacob314

**Comment by jacob314** [comment]
This is fixed in M24. We now use better logic to determine which isolate is running Flutter code.
