### ISSUE TITLE
IntelliJ popup alerted me to problem, asked me to file this

### ISSUE THREAD

**Issue by dresserm** [flutter/flutter-intellij#2156]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Launching app in debug mode.  No apparent problems with running the app but got this error message

## Version info

IntelliJ IDEA `2017.3.3 EAP` • Flutter plugin `io.flutter 23.2.2` • Dart plugin `173.4700`

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (3 weeks ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

## Exception

null

```
java.lang.AssertionError
	at io.flutter.inspector.EvalOnDartLibrary.<init>(EvalOnDartLibrary.java:72)
	at io.flutter.inspector.InspectorService.getInspectorLibrary(InspectorService.java:146)
	at io.flutter.inspector.InspectorService.invokeServiceMethodObservatory(InspectorService.java:170)
	at io.flutter.inspector.InspectorService.invokeServiceMethodReturningNode(InspectorService.java:446)
	at io.flutter.inspector.InspectorService.getRootRenderObject(InspectorService.java:473)
	at io.flutter.inspector.InspectorService.getRoot(InspectorService.java:139)
	at io.flutter.view.InspectorPanel.recomputeTreeRoot(InspectorPanel.java:236)
	at io.flutter.view.InspectorPanel.onFlutterFrame(InspectorPanel.java:303)
	at io.flutter.inspector.InspectorService.lambda$onVmServiceReceived$21(InspectorService.java:571)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
cc @jacob314

**Comment by jacob314** [comment]
This should be fixed in M24 which cleaned up logic for when we started running. Likely either your app had multiple isolates or the code in EvalOnDartLibrary ran before any isolates had started.
