### ISSUE TITLE
exception when the selection changes and the outline view isn't visible

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2176]
To repro, interact with the Flutter Outline view, then bring another view to the front (like the inspector), and change the selection in the active editor.

```
Source component not connected to component tree hierarchy
java.lang.Error: Source component not connected to component tree hierarchy
	at javax.swing.SwingUtilities.convertPoint(SwingUtilities.java:177)
	at javax.swing.SwingUtilities.convertRectangle(SwingUtilities.java:217)
	at io.flutter.preview.SelectionEditPolicy.activate(SelectionEditPolicy.java:35)
	at io.flutter.preview.PreviewArea.select(PreviewArea.java:209)
	at io.flutter.preview.PreviewView.applyEditorSelectionToTree(PreviewView.java:833)
	at io.flutter.preview.PreviewView.access$600(PreviewView.java:85)
	at io.flutter.preview.PreviewView$2.lambda$caretPositionChanged$0(PreviewView.java:153)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun$$$capture(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

@scheglov

**Comment by devoncarew** [comment]
This may be worth back-porting.
