### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Comori** [flutter/flutter-intellij#2198]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.1.2` • Flutter plugin `io.flutter 24.0.1` • Dart plugin `173.4700`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.analysis.server.protocol.FlutterOutline.fromJson(FlutterOutline.java:176)
	at io.flutter.dart.FlutterDartAnalysisServer.processNotification(FlutterDartAnalysisServer.java:177)
	at io.flutter.dart.FlutterDartAnalysisServer.processResponse(FlutterDartAnalysisServer.java:133)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:729)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:581)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:51)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:989)
```

**Comment by scheglov** [comment]
Outline is coming from the Dart analysis server.
The older version did not have it.
So, upgrade to the latest Dart SDK should help.
