### ISSUE TITLE
Flutter Outline Expansion in Android Studio causes NPE

### ISSUE THREAD

**Issue by aeroperf** [flutter/flutter-intellij#2212]
## What happened

In Android Studio, clicked on Flutter Outline side pane tab to expand it while main.dart was showing.

## Version information

Android Studio `3.1.2` • Flutter plugin `io.flutter 24.1.1` • Dart plugin `173.4700`

Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (8 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.analysis.server.protocol.FlutterOutline.fromJson(FlutterOutline.java:176)
	at io.flutter.dart.FlutterDartAnalysisServer.processNotification(FlutterDartAnalysisServer.java:177)
	at io.flutter.dart.FlutterDartAnalysisServer.processResponse(FlutterDartAnalysisServer.java:133)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:729)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:581)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:51)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:989)
```

**Comment by devoncarew** [comment]
Unfortunately, this is a known issue when using the current Flutter plugin against older Flutter SDKs (see https://github.com/flutter/flutter-intellij/issues/2198). 

@scheglov, if this is common, we may want to consider a fix on the plugin side.

**Comment by pq** [comment]
Unless it's really involved, I'd vote for considering a fix on the plugin side and a quick patch release.

**Comment by stevemessick** [comment]
Could we display a balloon with a link to start the SDK upgrade?
