### ISSUE TITLE
Flutter plugin causing internal IDE errors on Intellij

### ISSUE THREAD

**Issue by eddywm** [flutter/flutter-intellij#2218]
---

## What happened

Flutter plugin causing internal IDE errors on Intellij

## Version information

IntelliJ IDEA `2017.3.5` • Flutter plugin `io.flutter 24.1.1` • Dart plugin `173.4700`

Flutter 0.2.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5a58b36e36 (8 weeks ago) • 2018-03-13 13:20:13 -0700
Engine • revision e61bb9ac3a
Tools • Dart 2.0.0-dev.35.flutter-290c576264

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.analysis.server.protocol.FlutterOutline.fromJson(FlutterOutline.java:176)
	at io.flutter.dart.FlutterDartAnalysisServer.processNotification(FlutterDartAnalysisServer.java:177)
	at io.flutter.dart.FlutterDartAnalysisServer.processResponse(FlutterDartAnalysisServer.java:133)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:729)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:581)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:51)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:989)
```

**Comment by pq** [comment]
Unfortunately, this is a known issue when using the current Flutter plugin against older Flutter SDKs (see #2198); updating Flutter should resolve it.

Sorry for the inconvenience!
