### ISSUE TITLE
layout Inspector is not working

### ISSUE THREAD

**Issue by hemandroid** [flutter/flutter-intellij#2276]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Version information and logcat

Android Studio `3.0.1` • Flutter plugin `io.flutter 23.2.1` • Dart plugin `171.4424`

Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (2 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

## Exception

java.io.IOException: unexpected response: {"id":253,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getProperties({arg: inspector-1059, objectGroup: intellij_inspector_0, isolateId: isolates/607263317})"}

```
java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":253,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getProperties({arg: inspector-1059, objectGroup: intellij_inspector_0, isolateId: isolates/607263317})"}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:365)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:171)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:131)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:227)
	at com.sun.proxy.$Proxy15.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:201)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:290)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:84)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:162)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: unexpected response: {"id":253,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getProperties({arg: inspector-1059, objectGroup: intellij_inspector_0, isolateId: isolates/607263317})"}
	... 20 more
```

**Comment by jacob314** [comment]
1. Does the issue still occur if you upgrade to the latest intellij plugin (version 24)?
2. Does the inspector open and then failr or does this error occur immediately?
3. Is the debugger getting paused at a breakpoint for a long period of time. The timeout might make sense if you have been paused at a breakpoint for a while so the flutter daemon is never responding to the request.

**Comment by jacob314** [comment]
We fixed common timeout issues if using the inspector paused at a breakpoint.
