### ISSUE TITLE
Reformat on save leads to dead lock

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter-intellij#2286]
I've experienced some handing of the IDE lately and I think it's because of the reformatting on save.
this are my dumps:
[dump.zip](https://github.com/flutter/flutter-intellij/files/2052048/dump.zip)

**Comment by devoncarew** [comment]
Likely related:

```
there's a a deadlock on format on save, due to analysis server calls on a write action
- re-work to call the server first, then apply the response in a write action
- can’t use file offsets manager when under a write action
```

**Comment by alexander-doroshko** [comment]
Yes, that's the deadlock we discussed at the meeting. The relevant stack is inside auto-saved thread dumps in the attached zip:
```
"AWT-EventQueue-0 2018.1.4#IU-181.5087.20 IDEA, eap:false, os:Mac OS X 10.13.4, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b39" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on com.jetbrains.lang.dart.analyzer.FileOffsetsManager@441f316d owned by "ServerResponseReaderThread" Id=78
	at com.jetbrains.lang.dart.analyzer.FileOffsetsManager.getLineOffsets(FileOffsetsManager.java)
	at com.jetbrains.lang.dart.analyzer.FileOffsetsManager.getOriginalOffset(FileOffsetsManager.java:54)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.getOriginalOffset(DartAnalysisServerService.java:418)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.edit_format(DartAnalysisServerService.java:1319)
	at io.flutter.editor.FlutterSaveActionsManager.performFormat(FlutterSaveActionsManager.java:146)
	at io.flutter.editor.FlutterSaveActionsManager.access$200(FlutterSaveActionsManager.java:43)
	at io.flutter.editor.FlutterSaveActionsManager$2.run(FlutterSaveActionsManager.java:134)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:238)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:175)
	at com.intellij.openapi.command.WriteCommandAction$$Lambda$2117/1202322539.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:174)
	at com.intellij.openapi.command.WriteCommandAction$$Lambda$2115/1051729828.run(Unknown Source)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:214)
	at com.intellij.openapi.command.WriteCommandAction$$Lambda$2116/528403290.run(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:105)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:216)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:172)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:155)
	at io.flutter.editor.FlutterSaveActionsManager.lambda$performOrganizeThenFormat$0(FlutterSaveActionsManager.java:136)
	at io.flutter.editor.FlutterSaveActionsManager$$Lambda$3569/146140152.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"ServerResponseReaderThread" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.openapi.application.impl.ReadMostlyRWLock@59df19c5
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.waitABit(ReadMostlyRWLock.java:113)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.readLock(ReadMostlyRWLock.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.startRead(ApplicationImpl.java:939)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:929)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.project.ProjectLocatorImpl.guessProjectForFile(ProjectLocatorImpl.java:49)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.guessProject(EncodingManagerImpl.java:252)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.getEncoding(EncodingManagerImpl.java:229)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.getDefaultCharsetFromEncodingManager(LoadTextUtil.java:232)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.guessFromContent(LoadTextUtil.java:296)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectHardCharset(LoadTextUtil.java:214)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectInternalCharsetAndSetBOM(LoadTextUtil.java:248)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectCharsetAndSetBOM(LoadTextUtil.java:225)
	at com.jetbrains.lang.dart.analyzer.FileOffsetsManager.loadLineOffsets(FileOffsetsManager.java:90)
	at com.jetbrains.lang.dart.analyzer.FileOffsetsManager.getLineOffsets(FileOffsetsManager.java:78)
	at com.jetbrains.lang.dart.analyzer.FileOffsetsManager.getConvertedOffset(FileOffsetsManager.java:47)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.getConvertedOffset(DartAnalysisServerService.java:407)
	at com.jetbrains.lang.dart.analyzer.DartServerData.computedHighlights(DartServerData.java:95)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService$1.computedHighlights(DartAnalysisServerService.java:239)
	at com.google.dart.server.internal.BroadcastAnalysisServerListener.computedHighlights(BroadcastAnalysisServerListener.java:77)
	at com.google.dart.server.internal.remote.processor.NotificationAnalysisHighlightsProcessor.process(NotificationAnalysisHighlightsProcessor.java:43)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processNotification(RemoteAnalysisServerImpl.java:523)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:583)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:51)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:989)
```
