### ISSUE TITLE
Got exception in flutter plugin while rebuilding app.  - IDE Fatal Error

### ISSUE THREAD

**Issue by Sacchid** [flutter/flutter-intellij#2310]
Got exception in flutter plugin while rebuilding app.   - IDE Fatal Error
## Exception

java.util.concurrent.CompletionException: java.lang.RuntimeException: org.dartlang.vm.service.element.Sentinel@5899b193

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$67(InspectorService.java:875)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Version information

Android Studio `3.1.2` • Flutter plugin `io.flutter 25.0.1` • Dart plugin `173.4700`

Error getting Flutter sdk information.

 Flutter (Channel dev, v0.2.2-pre.2, on Microsoft Windows [Version 10.0.16299.309], locale en-IN)

**Comment by jacob314** [comment]
We fixed a suite of bugs that target similar issues. If the bug isn't fixed, please let me know.
