### ISSUE TITLE
Request to Dart VM Service timed out

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [flutter/flutter-intellij#2311]
## What happened

running an app. Don't recall what else.

## Version information

IntelliJ IDEA `2018.1.4` • Flutter plugin `io.flutter 25.0.2` • Dart plugin `181.4892.1`

Flutter 0.4.5-pre.52 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8717a5e6f7 (2 weeks ago) • 2018-05-19 03:19:35 +0300
Engine • revision 1179c38a42
Tools • Dart 2.0.0-dev.55.0.flutter-43635d3372

## Exception

java.io.IOException: unexpected response: {"id":2,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getSelectedSummaryWidget({objectGroup: selection_4, isolateId: isolates/905839199})"}

```
java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":2,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getSelectedSummaryWidget({objectGroup: selection_4, isolateId: isolates/905839199})"}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:375)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:181)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:141)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy21.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: unexpected response: {"id":2,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getSelectedSummaryWidget({objectGroup: selection_4, isolateId: isolates/905839199})"}
	... 22 more
```

**Comment by jacob314** [comment]
We made a suite of changes to handle these timeout changes. Let me know if this issue still occurs.
