### ISSUE TITLE
StringIndexOutOfBoundsException from FlutterConsoleFilter.java:124

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2329]
```
java.lang.StringIndexOutOfBoundsException: <elided>
at java.lang.String.substring(String.java:1967)
at io.flutter.console.FlutterConsoleFilter.applyFilter(FlutterConsoleFilter.java:124)
at com.intellij.execution.filters.CompositeFilter.applyFilter(CompositeFilter.java:75)
at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeLine(AsyncFilterRunner.java:214)
at com.intellij.execution.impl.AsyncFilterRunner$HighlighterJob.analyzeNextLine(AsyncFilterRunner.java:199)
at com.intellij.execution.impl.AsyncFilterRunner.runTasks(AsyncFilterRunner.java:151)
```

**Comment by devoncarew** [comment]
ah, this was fixed in https://github.com/flutter/flutter-intellij/commit/0c794ac550230ae96cf13c2365d8bb4400bf0b2d#diff-6c86c5c183f19063995d114ea112b9e6
