### ISSUE TITLE
Exception in DaemonApi$1.onTextAvailable.

### ISSUE THREAD

**Issue by idealopamp** [flutter/flutter-intellij#2332]
Per Android Studio:  Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Received a pop-up about an exception that prompted me to submit this bug report.  The error
occurred shortly after performing hot restart, but it does not seem to be reproducible when
performing the most recent actions again.

## Version information

Android Studio `3.1.2` • Flutter plugin `io.flutter 24.2.1` • Dart plugin `173.4700`

Flutter 0.4.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f9bb4289e9 (4 weeks ago) • 2018-05-11 21:44:54 -0700
Engine • revision 06afdfe54e
Tools • Dart 2.0.0-dev.54.0.flutter-46ab040e58

## Exception

java.io.IOException: unexpected response: {"id":24,"error":"Bad state: No element"}

```
java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":24,"error":"Bad state: No element"}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:365)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:171)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:131)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:239)
	at com.sun.proxy.$Proxy16.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:213)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: unexpected response: {"id":24,"error":"Bad state: No element"}
	... 22 more
```

## Steps to Reproduce

The error occurred shortly after performing hot restart, but it does not seem to be reproducible when
performing the most recent actions again.

## Version info

[✓] Flutter (Channel beta, v0.4.4, on Linux, locale en_US.UTF-8)
    • Flutter version 0.4.4 at /home/idealmike/flutter
    • Framework revision f9bb4289e9 (4 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/idealmike/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /home/idealmike/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/181.5087.20
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1

[!] IntelliJ IDEA Community Edition (version 2017.2)
    • IntelliJ at /home/idealmike/Downloads/idea-IC-172.4343.14
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by devoncarew** [comment]
Hmm, I saw hoping that https://github.com/flutter/flutter-intellij/pull/2321 would give us a bit more insight into what was going on here.

**Comment by stevemessick** [comment]
The root cause of this problem is an error thrown by the Dart code in the flutter tool. Without more information there isn't much we can do. See #2657 for more detail.
