### ISSUE TITLE
class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]

### ISSUE THREAD

**Issue by xxnjdlys** [flutter/flutter-intellij#2369]
---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.2 Canary 16` • Flutter plugin `io.flutter 23.2.3` • Dart plugin `181.4203.498`

No Flutter sdk configured.

## Exception

class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]

```
com.intellij.diagnostic.PluginException: class with name 'io.flutter.actions.FlutterNewProjectAction' not found [Plugin: io.flutter]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.error(ActionManagerImpl.java:183)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:145)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:478)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:466)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:358)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:316)
	at com.intellij.ide.actions.NewActionGroup.getChildren(NewActionGroup.java:34)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:323)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:330)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:330)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:330)
	at com.intellij.ide.util.gotoByName.GotoActionModel.collectActions(GotoActionModel.java:330)
	at com.intellij.ide.util.gotoByName.GotoActionModel.<init>(GotoActionModel.java:109)
	at com.intellij.ide.util.gotoByName.GotoActionModel.<init>(GotoActionModel.java:99)
	at com.intellij.ide.actions.GotoActionAction.gotoActionPerformed(GotoActionAction.java:75)
	at com.intellij.ide.actions.GotoActionBase.actionPerformed(GotoActionBase.java:71)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:561)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:464)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:695)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader[io.flutter, 23.2.3] com.intellij.ide.plugins.cl.PluginClassLoader@1b22c672
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:141)
	... 30 more
```

**Comment by devoncarew** [comment]
@stevemessick for FYI

@xxnjdlys, thanks for the report! We don't currently support Android Studio canary builds - we'll plan to support 3.2 once it goes beta. Thanks!
