### ISSUE TITLE
I don't know what is this, but here it is

### ISSUE THREAD

**Issue by arsensaruhanyan2611** [flutter/flutter-intellij#2395]
```
Exception:

java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":4,"error":"TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getRootWidgetSummaryTree({objectGroup: tree_3, isolateId: isolates/72995244})"}

com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$67(InspectorService.java:875)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Steps to Reproduce
I don't know how I did this, because everything was alright

## Version info
The latest Flutter 0.0.4

**Comment by stevemessick** [comment]
@jacob314 Does this look like something we should worry about?

My guess is that without more complete version info we cannot do much. Can we get the version of IntelliJ or Android Studio in use? And the output of `flutter doctor`?

**Comment by jacob314** [comment]
Did you happen to be paused at a breakpoint? Timeout errors could occur in that case and we aren't currently to suppress them as they are not a concern if that is what happened.

**Comment by arsensaruhanyan2611** [comment]
Android Studio 3.1.3 installed on my computer. **flutter doctor -v** doesn't give too much information. I mean it doesn't give any weird information and everything works fine.

My apologies, I may be opened this issue too in a hurry without any other reasons to that.

BTW, all I remember is that I was testing my application and Flutter Inspector gives some error about my layout. Then I got this kinda issue from Android Studio and I really have no idea what caused it.

**Comment by stevemessick** [comment]
It doesn't sound like we're going to be able to do any work based on this report, so I'll close it. If you get any more details about what's going on then please reopen it and we'll take another look. Thanks!
