### ISSUE TITLE
exception when creating an empty file

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2407]
## What happened

I created an empty file.

## Version information

IntelliJ IDEA `2018.1.5` • Flutter plugin `io.flutter 181.5281.24` • Dart plugin `181.4892.1`

Flutter 0.5.6-pre.51 • channel master • https://github.com/flutter/flutter.git
Framework • revision f5f055113a (12 hours ago) • 2018-06-21 22:22:59 -0700
Engine • revision 549c855e89
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2

## Exception

lineNumber:0. Must be in [0, -1]

```
java.lang.IndexOutOfBoundsException: lineNumber:0. Must be in [0, -1]
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addLineHighlighter(MarkupModelImpl.java:66)
	at io.flutter.coverage.EditorCoverageDecorations.lambda$addBlankMarker$0(EditorCoverageDecorations.java:49)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun$$$capture(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Ah, turns out this only happens if you have `public static final boolean ENABLE_LIVE_COVERAGE = true;`.
