### ISSUE TITLE
Android Studio 3.2 beta cannot create projects

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#2420]
Project creation throws an exception related to the ProjectSystem implementation. New projects get reparented to the Android module, hiding all Flutter and iOS sources.

```java
Failed to get providers from io.flutter.project.FlutterProjectSystem.: io.flutter.project.FlutterProjectSystem.getPsiElementFinders()Ljava/util/Collection;
java.lang.AbstractMethodError: io.flutter.project.FlutterProjectSystem.getPsiElementFinders()Ljava/util/Collection;
	at com.android.tools.idea.res.ProjectSystemPsiElementFinder.getFinders(ProjectSystemPsiElementFinder.kt:36)
	at com.android.tools.idea.res.ProjectSystemPsiElementFinder.findClass(ProjectSystemPsiElementFinder.kt:46)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:125)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:102)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.lambda$nullabilityAnnotationsNotAvailable$0(NullableStuffInspectionBase.java:417)
	at com.intellij.util.containers.ContainerUtil.find(ContainerUtil.java:857)
	at com.intellij.util.containers.ContainerUtil.find(ContainerUtil.java:828)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.nullabilityAnnotationsNotAvailable(NullableStuffInspectionBase.java:417)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.buildVisitor(NullableStuffInspectionBase.java:80)
	at com.intellij.codeInspection.LocalInspectionTool.buildVisitor(LocalInspectionTool.java:125)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:53)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:278)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:246)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:223)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by devoncarew** [comment]
I assume this can be moved out of M26 (or closed)?

**Comment by stevemessick** [comment]
I think closing it is fine since it is not reproducible.
