### ISSUE TITLE
org.dartlang.vm.service.element.RPCError@5c9159a3

### ISSUE THREAD

**Issue by xxnjdlys** [flutter/flutter-intellij#2428]
## Version information

Android Studio `3.1.3` • Flutter plugin `io.flutter 25.0.1` • Dart plugin `173.4700`

Flutter 0.5.6-pre.74 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3351423a42 (10 hours ago) • 2018-06-25 19:28:42 -0700
Engine • revision 549c855e89
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2

## Exception

org.dartlang.vm.service.element.RPCError@5c9159a3

```
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:140)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:106)
	at io.flutter.inspector.EvalOnDartLibrary$1.onError(EvalOnDartLibrary.java:166)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:464)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
closing as likely stale
