### ISSUE TITLE
java.io.IOException: unexpected response (Bad state: No element)

### ISSUE THREAD

**Issue by botaniQQQ** [flutter/flutter-intellij#2467]
## What happened

After install, click Run.

## Version information

IntelliJ IDEA `2018.1.5` • Flutter plugin `io.flutter 26.0.2` • Dart plugin `181.4892.1`

Error getting Flutter sdk information.

## Exceptiona

java.io.IOException: unexpected response: {"id":3,"error":"Bad state: No element"}

```
java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":3,"error":"Bad state: No element"}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:375)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:181)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:141)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy18.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: unexpected response: {"id":3,"error":"Bad state: No element"}
	... 22 more
```

**Comment by botaniQQQ** [comment]
After change text:

```
Initializing hot reload...
Unable to hot reload. No instance of Flutter is currently running.
Unhandled exception:
Bad state: No element
#0      List.first (dart:core-patch/dart:core/array.dart:165)
#1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:542)
#2      _rootRunUnary (dart:async/zone.dart:1134)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#6      Future._propagateToListeners (dart:async/future_impl.dart:662)
#7      Future._completeWithValue (dart:async/future_impl.dart:477)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)

```

**Comment by pq** [comment]
Thanks for the report.  It looks like this is duplicates #2332 and #2319.  Closing here in favor of tracking just once.  (Slated for this milestone though, so again thanks!)
