### ISSUE TITLE
Dartfmt on save throwing errors

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#2495]
Reported from a user:

Android Studio Version: 3.0.1
Dart Plugin Version: 171.4424
Flutter Plugin Version: 23.2.1

```
Assertion failed
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:170)
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:179)
    at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.awaitForLatchCheckingCanceled(DartAnalysisServerService.java:1649)
    at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.awaitForLatchCheckingCanceled(DartAnalysisServerService.java:1640)
    at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.edit_format(DartAnalysisServerService.java:1148)
    at io.flutter.editor.FlutterSaveActionsManager.performFormat(FlutterSaveActionsManager.java:146)
    at io.flutter.editor.FlutterSaveActionsManager.access$200(FlutterSaveActionsManager.java:43)
    at io.flutter.editor.FlutterSaveActionsManager$2.run(FlutterSaveActionsManager.java:134)
    at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:234)
    at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
    at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:171)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
    at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:170)
    at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:210)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:149)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
    at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:212)
    at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:168)
    at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:151)
    at io.flutter.editor.FlutterSaveActionsManager.lambda$performOrganizeThenFormat$0(FlutterSaveActionsManager.java:136)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

This output is written to the shell where Android Studio was launched.

[ 160964]  ERROR - terminal.emulator.JediEmulator - Unhandled Control sequence
parsed                        :ESC[?2004h
bytes read                    :ESC[ 
[ 228404]   WARN - o.flutter.run.daemon.DaemonApi - can't write command to Flutter process: {"method":"app.restart","params":{"appId":"1a432e72-aa73-43d8-a769-27aa4fc43c96","fullRestart":true,"pause":false},"id":1} 
[ 228453]   WARN - n.process.BaseOSProcessHandler - Stream closed 
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.intellij.execution.process.BaseOSProcessHandler.closeStreams(BaseOSProcessHandler.java:238)
	at com.intellij.execution.process.BaseOSProcessHandler.destroyProcessImpl(BaseOSProcessHandler.java:210)
	at com.intellij.execution.process.ProcessHandler$1.run(ProcessHandler.java:114)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:260)
	at com.intellij.execution.process.ProcessHandler.destroyProcess(ProcessHandler.java:109)
	at io.flutter.run.daemon.FlutterAppListener.onAppStopped(FlutterAppListener.java:155)
	at io.flutter.run.daemon.DaemonEvent$AppStopped.accept(DaemonEvent.java:274)
	at io.flutter.run.daemon.DaemonEvent.dispatch(DaemonEvent.java:52)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:160)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:131)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
....
```

**Comment by devoncarew** [comment]
On a closer look, `server` also can't be null.

Given that this happened on a relatively old Dart plugin version (for 2017.1), and has only been reported once, I'm going to close this out as assumed stale. If we see it again we can re-investigate.
