### ISSUE TITLE
"error":"Bad state: No element"

### ISSUE THREAD

**Issue by parasthekoder** [flutter/flutter-intellij#2521]
## What happened

Ran main.dart from IDE.

## Version information

Android Studio `3.1.3` • Flutter plugin `io.flutter 26.0.1` • Dart plugin `173.4700`

## Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.5.7, on Microsoft Windows [Version 10.0.17134.191], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected devices (1 available)

• No issues found!
Process finished with exit code 0
```

## Exception

java.io.IOException: unexpected response: {"id":3,"error":"Bad state: No element","trace":"#0      List.first (dart:core-patch/dart:core/growable_array.dart:211)\n#1      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:469)\n<asynchronous suspension>\n#2      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:189)\n#3      new Future.sync (dart:async/future.dart:222)\n#4      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:187)\n#5      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:145)\n#6      _rootRunUnary (dart:async/zone.dart:1134)\n#7      _CustomZone.runUnary (dart:async/zone.dart:1031)\n#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)\n#12     _MapStream._handleData (dart:async/stream_pipe.dart:232)\n#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)\n#14     _rootRunUnary (dart:async/zone.dart:1134)\n#15     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)\n#20     _WhereStream._handleData (dart:async/stream_pipe.dart:207)\n#21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)\n#22     _rootRunUnary (dart:async/zone.dart:1134)\n#23     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)\n#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)\n#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)\n#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#34     _rootRunUnary (dart:async/zone.dart:1134)\n#35     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)\n#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)\n#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)\n#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)\n#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#47     _rootRunUnary (dart:async/zone.dart:1134)\n#48     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)\n#53     _StreamController._add (dart:async/stream_controller.dart:639)\n#54     _StreamController.add (dart:async/stream_controller.dart:585)\n#55     _Socket._onData (dart:io-patch/socket_patch.dart:1672)\n#56     _rootRunUnary (dart:async/zone.dart:1138)\n#57     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)\n#62     _StreamController._add (dart:async/stream_controller.dart:639)\n#63     _StreamController.add (dart:async/stream_controller.dart:585)\n#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)\n#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)\n#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)\n#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)\n"}

```
java.util.concurrent.CompletionException: java.io.IOException: unexpected response: {"id":3,"error":"Bad state: No element","trace":"#0      List.first (dart:core-patch/dart:core/growable_array.dart:211)\n#1      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:469)\n<asynchronous suspension>\n#2      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:189)\n#3      new Future.sync (dart:async/future.dart:222)\n#4      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:187)\n#5      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:145)\n#6      _rootRunUnary (dart:async/zone.dart:1134)\n#7      _CustomZone.runUnary (dart:async/zone.dart:1031)\n#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)\n#12     _MapStream._handleData (dart:async/stream_pipe.dart:232)\n#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)\n#14     _rootRunUnary (dart:async/zone.dart:1134)\n#15     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)\n#20     _WhereStream._handleData (dart:async/stream_pipe.dart:207)\n#21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)\n#22     _rootRunUnary (dart:async/zone.dart:1134)\n#23     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)\n#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)\n#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)\n#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#34     _rootRunUnary (dart:async/zone.dart:1134)\n#35     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)\n#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)\n#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)\n#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)\n#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#47     _rootRunUnary (dart:async/zone.dart:1134)\n#48     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)\n#53     _StreamController._add (dart:async/stream_controller.dart:639)\n#54     _StreamController.add (dart:async/stream_controller.dart:585)\n#55     _Socket._onData (dart:io-patch/socket_patch.dart:1672)\n#56     _rootRunUnary (dart:async/zone.dart:1138)\n#57     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)\n#62     _StreamController._add (dart:async/stream_controller.dart:639)\n#63     _StreamController.add (dart:async/stream_controller.dart:585)\n#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)\n#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)\n#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)\n#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)\n"}
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:375)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:181)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:141)
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:239)
	at com.sun.proxy.$Proxy16.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:213)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:295)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:194)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: unexpected response: {"id":3,"error":"Bad state: No element","trace":"#0      List.first (dart:core-patch/dart:core/growable_array.dart:211)\n#1      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:469)\n<asynchronous suspension>\n#2      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:189)\n#3      new Future.sync (dart:async/future.dart:222)\n#4      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:187)\n#5      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:145)\n#6      _rootRunUnary (dart:async/zone.dart:1134)\n#7      _CustomZone.runUnary (dart:async/zone.dart:1031)\n#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)\n#12     _MapStream._handleData (dart:async/stream_pipe.dart:232)\n#13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)\n#14     _rootRunUnary (dart:async/zone.dart:1134)\n#15     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132)\n#20     _WhereStream._handleData (dart:async/stream_pipe.dart:207)\n#21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164)\n#22     _rootRunUnary (dart:async/zone.dart:1134)\n#23     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)\n#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)\n#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)\n#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#34     _rootRunUnary (dart:async/zone.dart:1134)\n#35     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)\n#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)\n#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)\n#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)\n#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#47     _rootRunUnary (dart:async/zone.dart:1134)\n#48     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)\n#53     _StreamController._add (dart:async/stream_controller.dart:639)\n#54     _StreamController.add (dart:async/stream_controller.dart:585)\n#55     _Socket._onData (dart:io-patch/socket_patch.dart:1672)\n#56     _rootRunUnary (dart:async/zone.dart:1138)\n#57     _CustomZone.runUnary (dart:async/zone.dart:1031)\n#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)\n#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)\n#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263)\n#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)\n#62     _StreamController._add (dart:async/stream_controller.dart:639)\n#63     _StreamController.add (dart:async/stream_controller.dart:585)\n#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)\n#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)\n#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)\n#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)\n"}
	... 22 more
```

**Comment by pq** [comment]
Thanks for the report @parasthekoder.  We just released a new version of the Flutter Plugin (27.0) that may address this issue.   At the same time, make sure you're on the latest flutter (`flutter upgrade` from the command line, or Tools > Flutter from the IDE).  Let us know if the issue persists after upgrades.

Cheers!
