### ISSUE TITLE
Possible Flutter inspector memory leak

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#2571]
Saw this in the debugger console while running a debuggable Android Studio. I had two projects open in separate AS windows. The active window was for an Android project that had a debugger running. The other window was a Flutter project for a module used in the Android project. Oddly enough, the Android project had a right-side tab labeled `Flutter Outline` and another `Flutter Inspector`. I wouldn't expect to see either in a project window for a non-Flutter project.
@pq @jacob314 

```java
[1848183]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: 'io.flutter.inspector.EvalOnDartLibrary@6819f98e' of class io.flutter.inspector.EvalOnDartLibrary
See the cause for the corresponding Disposer.register() stacktrace:
 
java.lang.RuntimeException: Memory leak detected: 'io.flutter.inspector.EvalOnDartLibrary@6819f98e' of class io.flutter.inspector.EvalOnDartLibrary
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:247)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:146)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:255)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:800)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:770)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:759)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:755)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:722)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:717)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$null$3(MacOSApplicationProvider.java:107)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$submit$7(MacOSApplicationProvider.java:200)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun$$$capture(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.objectTree.ObjectNode.<init>(ObjectNode.java:56)
	at com.intellij.openapi.util.objectTree.ObjectTree.createNodeFor(ObjectTree.java:122)
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:84)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.util.Alarm.<init>(Alarm.java:139)
	at io.flutter.inspector.EvalOnDartLibrary.<init>(EvalOnDartLibrary.java:113)
	at io.flutter.inspector.InspectorService.create(InspectorService.java:59)
	at io.flutter.view.FlutterView.debugActive(FlutterView.java:355)
	at io.flutter.view.FlutterViewFactory.lambda$initFlutterView$1(FlutterViewFactory.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	... 22 more
[1848183]  ERROR - api.util.objectTree.ObjectTree - Android Studio 3.3 Canary 8  Build #182.3911.36.33.SNAPSHOT 
```

**Comment by devoncarew** [comment]
Closing as likely stale.
