### ISSUE TITLE
Intellij 2018.2.2 RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false 

### ISSUE THREAD

**Issue by kosiara** [flutter/flutter-intellij#2579]
## What happened

creating a brand new project
lang:  Kotlin & Swift 

## Version information

IntelliJ IDEA `2018.2.2` • Flutter plugin `io.flutter 27.1.3` • Dart plugin `182.4129.13`

Flutter 0.6.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 9299c02cf7 (2 weeks ago) • 2018-08-16 00:35:12 +0200
Engine • revision e3687f70c7
Tools • Dart 2.1.0-dev.0.0.flutter-be6309690f

## Exception

Access is allowed from event dispatch thread only.

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@7ec316e7
Current thread: Thread[flutter,4,Idea Thread Group] 1803328764
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1590639637
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1123)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1112)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.assertDispatchThread(FocusManagerImpl.java:520)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.getFocusOwner(FocusManagerImpl.java:273)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.getFocusOwner(IdeFocusManagerImpl.java:101)
	at com.intellij.ui.messages.JBMacMessages.getForemostWindow(JBMacMessages.java:104)
	at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:187)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:800)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.commitStepData(AbstractProjectWizard.java:250)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.doNextAction(AbstractProjectWizard.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.flutter.module.FlutterGeneratorPeer.requestNextStep(FlutterGeneratorPeer.java:217)
	at io.flutter.actions.InstallSdkAction$InstallAction.requestNextStep(InstallSdkAction.java:141)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$FlutterPrecacheCommand.onSuccess(InstallSdkAction.java:398)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$InstallCommand$1.processTerminated(InstallSdkAction.java:292)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy17.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$4.run(ProcessHandler.java:180)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:256)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:157)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:113)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:120)
	at com.intellij.execution.process.BaseOSProcessHandler$2$1.consume(BaseOSProcessHandler.java:105)
	at com.intellij.execution.process.ProcessWaitFor$1$1.run(ProcessWaitFor.java:65)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by toby78** [comment]
I had the same now with Android Studio 3.4 - fresh install when I tried to build a previous project (Android Studio Update failed and I had to install it again)

**Comment by stevemessick** [comment]
Covered by #3626, which has better diagnostic info.
