### ISSUE TITLE
NPE during debugging

### ISSUE THREAD

**Issue by mdudek** [flutter/flutter-intellij#2617]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.1.4` • Flutter plugin `io.flutter 28.0.1` • Dart plugin `173.4700`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.Script.getSource(Script.java:43)
	at io.flutter.run.ObservatoryFile.createSnapshot(ObservatoryFile.java:109)
	at io.flutter.run.ObservatoryFile.<init>(ObservatoryFile.java:54)
	at io.flutter.run.ObservatoryFile$Cache.downloadOrGet(ObservatoryFile.java:152)
	at io.flutter.run.PositionMapper.getSourcePosition(PositionMapper.java:259)
	at io.flutter.run.PositionMapper.getSourcePosition(PositionMapper.java:232)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.getSourcePosition(DartVmServiceDebugProcess.java:461)
	at io.flutter.server.vmService.frame.DartVmServiceStackFrame.<init>(DartVmServiceStackFrame.java:46)
	at io.flutter.server.vmService.VmServiceWrapper$9.lambda$received$0(VmServiceWrapper.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jacob314** [comment]
That is a surprising exception. Do you have a Dart source project that can reproduce the problem?

**Comment by mdudek** [comment]
Can you please send me your email address so I can send you my flutter project sources.

**Comment by kevmoo** [comment]
I just hit this, too.

```
IntelliJ IDEA `2018.2.4` • Flutter plugin `io.flutter 29.0.4` • Dart plugin `182.4323.44`

Flutter 0.9.5 • channel dev • ssh://git@github.com/flutter/flutter
Framework • revision 020fd590b0 (7 days ago) • 2018-09-26 14:28:26 -0700
Engine • revision 38a646e14c
Tools • Dart 2.1.0-dev.5.0.flutter-4cf2d3990b
```

**Comment by devoncarew** [comment]
It's the same underlying issue as https://github.com/dart-lang/sdk/issues/34666.
