### ISSUE TITLE
NPE from the logging view

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2622]
---

## What happened

Developing an app w/ the new logging view enabled.

## Version information

IntelliJ IDEA `2018.2.4` • Flutter plugin `io.flutter 28.0.4` • Dart plugin `182.4323.44`

Flutter 0.9.3-pre.18 • channel master • https://github.com/flutter/flutter.git
Framework • revision 762c86995d (23 hours ago) • 2018-09-22 14:44:09 -0700
Engine • revision f3a3d0ce7f
Tools • Dart 2.1.0-dev.5.0.flutter-654c4babc8

## Exception

null

```
java.lang.NullPointerException: at index 27
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:225)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:215)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:209)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:341)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:253)
	at io.flutter.logging.FlutterLog.getEntries(FlutterLog.java:97)
	at io.flutter.logging.FlutterLogTree.lambda$reload$6(FlutterLogTree.java:620)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

@pq

**Comment by pq** [comment]
Thanks!

**Comment by pq** [comment]
Doing a bit of investigating this issue hit the log tree before @quangson91's refactoring.  The good news is the troubling code path (that could lead to a race between clearing and iterating over logs) is gone.  This issue shouldn't hit us anymore.  (Or if it does, it will manifest a bit differently.) . I'll do a bit of local testing...

Again, thanks for the report!
