### ISSUE TITLE
App crash on native side. No stack traces. Plugin crash.

### ISSUE THREAD

**Issue by reaperdtme** [flutter/flutter-intellij#2629]
## What happened
iOS.

Geolocator crashed on the native side. 
Don't get stack trace from application.
Get Lost connection to device.
App screen goes black, dead.

## Version information

Android Studio `3.2` • Flutter plugin `io.flutter 28.0.2` • Dart plugin `181.5616`

Flutter 0.9.3-pre.26 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6014f29b5a (12 hours ago) • 2018-09-24 16:00:35 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044

## Exception

java.io.IOException: Application terminated

```
java.util.concurrent.CompletionException: java.io.IOException: Application terminated
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:375)
	at io.flutter.run.daemon.DaemonApi.cancelPending(DaemonApi.java:87)
	at io.flutter.run.daemon.FlutterApp.lambda$shutdownAsync$6(FlutterApp.java:488)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Application terminated
	... 7 more
```

**Comment by devoncarew** [comment]
Thanks for the report!

**Comment by devoncarew** [comment]
I think the right solution here is for `DaemonAPI.cancelPending()` to cancel with some well-known marker, and for call-back sites to recognize and ignore (not report as crashes) when a request has been cancelled.

**Comment by kidcosmic** [comment]
@devoncarew Updated with more info, was a crash in the native implementation of Geolocator

**Comment by stevemessick** [comment]
The root cause of this problem is an error thrown by the Dart code in the flutter tool. Without more information there isn't much we can do. See #2657 for more detail. (Leaving open because it has useful context.)

**Comment by OmarBakry-Globalits** [comment]
This issue still happening to me using Xcode 14.0, any updates or any reason for that ??
