### ISSUE TITLE
Flutter Exception

### ISSUE THREAD

**Issue by scottdewald** [flutter/flutter-intellij#2651]
## What happened

Sorry, I don't know when this happened, I just saw this error at the bottom of the IDE while I was developing. Even though I don't have the steps to reproduce it, I wanted to give you the stacktrace if it is helpful.

## Version information

IntelliJ IDEA `2018.2.4` • Flutter plugin `io.flutter 28.0.4` • Dart plugin `182.4323.44`

Flutter 0.8.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5ab9e70727 (4 weeks ago) • 2018-09-07 12:33:05 -0700
Engine • revision 58a1894a1c
Tools • Dart 2.1.0-dev.3.1.flutter-760a9690c2

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.InstanceRef.getKind(InstanceRef.java:42)
	at io.flutter.server.vmService.frame.DartVmServiceValue.computeVarHavingStringValuePresentation(DartVmServiceValue.java:189)
	at io.flutter.server.vmService.frame.DartVmServiceValue.computePresentation(DartVmServiceValue.java:148)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:56)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.lambda$addChildren$0(XValueContainerNode.java:89)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:104)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:101)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! This should be addressed by the M29 version of the plugin - I see that you're on `28.0.4`. Closing as assumed fixed.
