### ISSUE TITLE
NullPointerException on opening Dart project in Android Studio

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter-intellij#2692]
## What happened
I just opened Android Studio to an [existing Dart library](https://pub.dartlang.org/packages/zart) (which doesn't contain any Flutter code). This seems to be reproducible. 

## Version information
Android Studio `3.2.1` • Flutter plugin `io.flutter 29.1.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception
null

```
java.lang.NullPointerException
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:108)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:57)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:100)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:431)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Flutter Doctor output

```
[C:\Users\timsneath] flutter doctor -v
[√] Flutter (Channel master, v0.10.1-pre.37, on Microsoft Windows [Version 10.0.16299.726], locale en-US)
    • Flutter version 0.10.1-pre.37 at c:\git\flutter
    • Framework revision a3670a2f85 (2 hours ago), 2018-10-12 18:08:57 +0200
    • Engine revision 3ffa362952
    • Dart version 2.1.0-dev.7.0.flutter-b99bcfd309

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\timsneath\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.28.1)
    • VS Code at C:\Users\timsneath\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.19.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

## Flutter Plugin Settings

![image](https://user-images.githubusercontent.com/2319867/46887694-2f6a5b80-ce13-11e8-88ff-e3719b7b8f6a.png)

## Dart Plugin Settings
![image](https://user-images.githubusercontent.com/2319867/46887710-3c874a80-ce13-11e8-819c-9c7d8641aca4.png)

**Comment by stevemessick** [comment]
Fixed with #2698
