### ISSUE TITLE
NoReadAccessException from XDebugSessionImpl.initBreakpoints

### ISSUE THREAD

**Issue by Adrianogba** [flutter/flutter-intellij#2693]
## What happened

I've changed from OpenJDK to the Oracle's JDK 8 (build 1.8.0_181-b13) while running the project on Genymotion.

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 29.1.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[Thread-9,4,Idea Thread Group] 904958190
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 3.2#AI-181.5540.7.32.5056338 Studio, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b06,6,Idea Thread Group] 346058534

```
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1057)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:297)
	at io.flutter.server.vmService.VmServiceWrapper.attachIsolate(VmServiceWrapper.java:247)
	at io.flutter.server.vmService.VmServiceWrapper$1$1$1$1.received(VmServiceWrapper.java:148)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:646)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:625)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```
## flutter doctor -v

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.18247.1001], locale pt-BR)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[!] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • Custom Phone, 5 1 0, API 22, 768x1280 • 192.168.181.101:5555 • android-x86 • Android 5.1 (API 22)

! Doctor found issues in 1 category.
```

**Comment by pq** [comment]
@devoncarew: any ideas?
