### ISSUE TITLE
Flutter SDK Information

### ISSUE THREAD

**Issue by daBlaqSuit** [flutter/flutter-intellij#2709]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

"I created new flutter project, loaded the sdk file path and clicked on the finish button. Error occurred during the project load"

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 29.1.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[Thread-8,4,Idea Thread Group] 2000456886
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 3.2#AI-181.5540.7.32.5056338 Studio, eap:false, os:Windows 10 10.0, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b06,6,Idea Thread Group] 1153642803

```
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1057)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:297)
	at io.flutter.server.vmService.VmServiceWrapper.attachIsolate(VmServiceWrapper.java:247)
	at io.flutter.server.vmService.VmServiceWrapper$1$1$1$1.received(VmServiceWrapper.java:148)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:646)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:625)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
Thanks for the report! I believe this was addressed recently (thanks @stevemessick!), and will be available with our next release.
