### ISSUE TITLE
Flutter plugin exception after manually restart the dart analysis server.

### ISSUE THREAD

**Issue by rockingdice** [flutter/flutter-intellij#2726]
## What happened

I clicked Restart Dart Analysis Server, then the Flutter plugin threw the exception.

## Version information

IntelliJ IDEA `2018.2.1` • Flutter plugin `io.flutter 27.1.3` • Dart plugin `182.3911.37`

Flutter 0.8.3-pre.7 • channel unknown • unknown source
Framework • revision c0132e70a5 (3 days ago) • 2018-10-23 11:58:45 +0800
Engine • revision 3860a43379
Tools • Dart 2.1.0-dev.7.1.flutter-b99bcfd309

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.Element.jsonArrayToListString(Element.java:64)
	at org.dartlang.vm.service.element.Element.getListString(Element.java:38)
	at org.dartlang.vm.service.element.Isolate.getExtensionRPCs(Isolate.java:67)
	at io.flutter.perf.PerfService$2$1.lambda$received$0(PerfService.java:85)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
``` 
## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[✓] Flutter (Channel unknown, v0.8.3-pre.7, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
    • Flutter version 0.8.3-pre.7 at /Users/li9s/github/flutter
    • Framework revision c0132e70a5 (3 days ago), 2018-10-23 11:58:45 +0800
    • Engine revision 3860a43379
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/li9s/Library/Android/sdk
    • Android NDK at /Users/li9s/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                            •
      android-x86 • Android 9 (API 28) (emulator)

**Comment by devoncarew** [comment]
Thanks for the report! I see you're on a slightly older version of the Flutter IntelliJ plugin - `27.1.3`. If you check for updates, you should see a new version available - I believe that will address this issue.
