### ISSUE TITLE
NoReadAccessException from VmServiceWrapper.attachIsolate

### ISSUE THREAD

**Issue by xuexin** [flutter/flutter-intellij#2734]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 29.1.1` • Dart plugin `181.5656`

Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (5 weeks ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044

## Exception

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[Thread-20,4,Idea Thread Group] 250097765
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 3.2#AI-181.5540.7.32.5056338 Studio, eap:false, os:Mac OS X 10.14, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b06,6,Idea Thread Group] 971206853

```
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1057)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:297)
	at io.flutter.server.vmService.VmServiceWrapper.attachIsolate(VmServiceWrapper.java:247)
	at io.flutter.server.vmService.VmServiceWrapper$1$1$1$1.received(VmServiceWrapper.java:148)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:646)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:625)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
Thanks for the report! This race condition was fixed recently, and will be in the release due out at the end of the week.
