### ISSUE TITLE
[Android] Cannot run an application from IDE after changing the ordering of activities declared in AndroidManifest

### ISSUE THREAD

**Issue by hnvn** [flutter/flutter-intellij#2742]
I found a weird case. In my project, I need to add a plugin (it called `image_cropper`) and this plugin requires me to add an activity in `AndroidManifest` file. The interesting thing is that I have to place additional `activity` tag below the default `.MainActivity` of flutter project, otherwise the application will be crashed when I click on run button. The following is my `AndroidManifest` in two cases, working and failed:

* Working code:
```
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="image_cropper_example"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
    </application>
```

* Failed code:
```
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="image_cropper_example"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
```

* Error log:
```
Finished with error: ProcessException: Process "/Users/hunghd/Library/Android/sdk/platform-tools/adb" exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=vn.hunghd.flutter.plugins.imagecropperexample/com.yalantis.ucrop.UCropActivity (has extras) }

Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=vn.hunghd.flutter.plugins.imagecropperexample/com.yalantis.ucrop.UCropActivity (has extras) } from null (pid=7592, uid=2000) not exported from uid 10085

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=vn.hunghd.flutter.plugins.imagecropperexample/com.yalantis.ucrop.UCropActivity (has extras) } from null (pid=7592, uid=2000) not exported from uid 10085
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1788)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:717)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:544)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:486)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5120)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5094)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16005)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3592)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3291)
	at android.os.Binder.execTransact(Binder.java:731)
  Command: /Users/hunghd/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true vn.hunghd.flutter.plugins.imagecropperexample/com.yalantis.ucrop.UCropActivity
```

As far as I read from these logs, when I click run button, platform-tools will start the first activity in `AndroidManifest` file despite whether or not this activity is `LAUNCHER` activity.

By the way, if I run the application by clicking on its app icon in my device, it runs normally. The issues only occurs when using run button on Android Studio.

**Comment by devoncarew** [comment]
@hnvn, thanks for the feedback! I think this is more Flutter runtime specific than IDE specific - I'll move the issue over to the main flutter repo.
