### ISSUE TITLE
Hard Crash when using AMD cpu (Intel works fine). First Flutter app. Using master channel.

### ISSUE THREAD

**Issue by SocialMammoth** [flutter/flutter-intellij#2752]
## What happened

Works (launches) only the first time when a clean emulator is being used (This is the basic unmodified Flutter template code). Subsequent launches do not work after that (crash). When all data is wiped from the emulator it will work again only for the first launch and keep crashing after that. This only seems to happen on AMD cpus (I have tried on multiple different Intel CPUs and it only happens on AMD cpus).

I would really appreciate it if you could reach out to me, I can try and help with anything.

Thanks!

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 29.1.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

java.util.concurrent.CompletionException: java.io.IOException: Application terminated

```
java.lang.Throwable: java.util.concurrent.CompletionException: java.io.IOException: Application terminated
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$67(InspectorService.java:875)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

```
 flutter doctor -v
[√] Flutter (Channel master, v0.10.2-pre.134, on Microsoft Windows [Version 10.0.17134.376], locale en-CA)
    • Flutter version 0.10.2-pre.134 at C:\src\flutter
    • Framework revision e92ac48431 (31 minutes ago), 2018-11-01 22:30:44 +0530
    • Engine revision e91e4db7e0
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ppari\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by SocialMammoth** [comment]
I also get this in the event log:

```
2018-11-01
22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glAttachShader:294 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glAttachShader:294 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetProgramiv:2256 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetUniformLocation:2580 error 0x501

22:37	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetProgramiv:2256 error 0x501

```

**Comment by SocialMammoth** [comment]
I also get this in the event log:

```
22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glAttachShader:294 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glAttachShader:294 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetProgramiv:2256 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetUniformLocation:2580 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetProgramiv:2256 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glAttachShader:294 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glAttachShader:294 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glBindAttribLocation:323 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetProgramiv:2256 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetUniformLocation:2580 error 0x501

22:42	Emulator: android/android-emugl/host/libs/Translator/GLES_V2/GLESv2Imp.cpp:glGetProgramiv:2256 error 0x501

```

**Comment by devoncarew** [comment]
@SocialMammoth, I'm not sure whether this is a general Flutter framework issue or something specific to the Inspector. In order to separate those out, can you try closing the Inspector tool window. If you still see the problem we should likely move this issue over to the flutter/flutter repo.

**Comment by curtisrutland** [comment]
Want to add that I'm experiencing the same issue, without the inspector open. I get the same event log output with the same errors. I am using an Intel processor though, so it might be a broader issue than previously thought.
