### ISSUE TITLE
Memory Profiler load failure in IDEA

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#2774]
## What happened

  1. Create a new Flutter Project using IntelliJ Ultimate
  2. Open Android Emulator (haven't tried iOS)
  2. Run/Debug Flutter project
  3. Builds fine, then deployed to app
  4. When app is launched, see Exception pop up in IntelliJ.
  5. Perhaps related? Unable to see the Widget tree in the Flutter Inspector.

## Solutions Tried / Other bits

  1. I tried disabling the `--track-widget-creation` option. No effect.
  2. Everything seems to be working, except the Widget tree (setting break points, performance view, etc).
  3. No errors received in Android Studio, Widget tree shown.
  4. Tried Beta / Dev / Master branches, none worked.

Overall, I'd love to use IntelliJ Ultimate instead of Android Studio, since I work in a few different languages and it's a pain to constantly switch IDEs / reconfigure all settings / etc. 

## Version information

IntelliJ IDEA `2018.2.5` • Flutter plugin `io.flutter 30.0.2` • Dart plugin `182.4999`

Flutter 0.10.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d8cbb80206 (11 days ago) • 2018-10-26 01:30:21 -0400
Engine • revision 6c2ade9fa2
Tools • Dart 2.1.0-dev.8.0.flutter-bf26f760b1

## Exception

null

```
java.lang.NoClassDefFoundError: com/android/tools/adtui/model/updater/Updatable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:278)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:274)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:243)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:142)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:74)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.flutter.view.InspectorMemoryTab.<init>(InspectorMemoryTab.java:65)
	at io.flutter.view.FlutterView.addMemoryTab(FlutterView.java:343)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:236)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:409)
	at io.flutter.view.FlutterView.lambda$debugActive$2(FlutterView.java:369)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:35)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.adtui.model.updater.Updatable PluginClassLoader[io.flutter, 30.0.2] com.intellij.ide.plugins.cl.PluginClassLoader@8f3db52
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
```

### Flutter Doctor

```
[✓] Flutter (Channel dev, v0.10.2, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.10.2 at /Users/phillywiggins/lab/flutter
    • Framework revision d8cbb80206 (11 days ago), 2018-10-26 01:30:21 -0400
    • Engine revision 6c2ade9fa2
    • Dart version 2.1.0-dev.8.0.flutter-bf26f760b1

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/phillywiggins/Library/Android/sdk
    • Android NDK at /Users/phillywiggins/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/phillywiggins/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4999

[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by pq** [comment]
Hey @brianegan!

It looks like the memory profiler isn't working in IDEA...  You should be able to disable it in your Flutter preferences:

![image](https://user-images.githubusercontent.com/67586/48069236-d2e82b00-e189-11e8-9bf7-8d06b5388110.png)

(last item).

Thanks for the catch!

/cc @terrylucas @jacob314

**Comment by brianegan** [comment]
My bad -- thought I'd disabled that one as well. Thanks!

**Comment by pq** [comment]
Well, it shouldn't crash like that so actually, thanks for the catch!

**Comment by devoncarew** [comment]
I've seen this as well:

```
java.lang.NoClassDefFoundError: com/android/tools/adtui/model/updater/Updatable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:278)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:274)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:243)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:142)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:74)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.flutter.view.InspectorMemoryTab.<init>(InspectorMemoryTab.java:65)
	at io.flutter.view.FlutterView.addMemoryTab(FlutterView.java:343)
```

**Comment by stevemessick** [comment]
@terrylucas The memory profiler UI depends on a number of classes and frameworks distributed with Android Studio that are not (yet, if ever?) available in IntelliJ. Are you planning to bundle a library containing those classes with the Flutter plugin? If not, I can look into disabling the UI affordances in IntelliJ so that these errors won't happen.

**Comment by jibbers42** [comment]
If possible, I would prefer all Android Studio features (including plugin features) be able to work in IntelliJ. I'd like to not have to have both IDEs installed and keep my preferences sync'd up if I don't have too. :smiley: 

According to the FAQ (https://blog.jetbrains.com/idea/2013/05/intellij-idea-and-android-studio-faq/), Android Studio isn't supposed to have anything that isn't in or can't be added to IntelliJ, but I don't know how well they've been able to stick with that.

**Comment by devoncarew** [comment]
We should rule this out as a general issue, or address in the M31 timeframe.
