### ISSUE TITLE
NPE on app debug

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#282]
```
@NotNull method io/flutter/run/FlutterAppState.startProcess must not return null
java.lang.IllegalStateException: @NotNull method io/flutter/run/FlutterAppState.startProcess must not return null
    at io.flutter.run.FlutterAppState.startProcess(FlutterAppState.java:92)
    at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
    at com.jetbrains.lang.dart.ide.runner.DartRunner.doExecuteDartDebug(DartRunner.java:125)
    at com.jetbrains.lang.dart.ide.runner.DartRunner.doExecute(DartRunner.java:84)
    at io.flutter.run.FlutterRunner.doExecute(FlutterRunner.java:77)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
```

To repro (this scenario is not a common one for users):
- open an existing flutter project
- install the flutter plugin
- restart
- set the path to the flutter sdk
- devices now show up in the device pulldown
- hit debug; see exception

**Comment by pq** [comment]
cc @stevemessick -- I'm curious if this is still valid?

**Comment by mit-mit** [comment]
Bumping to second external release

**Comment by pq** [comment]
@devoncarew @stevemessick : is this still valid?

**Comment by stevemessick** [comment]
Someone other than me will need to test it. I suspect it is fixed, though.

**Comment by pq** [comment]
👍  Thanks Steve!

Optimistically closing.  @devoncarew : feel free to re-open if it persists.
