### ISSUE TITLE
Error creating New Project Wizard

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#2838]
Launch Android Studio from IntelliJ EAP. Try to create a Flutter project. It is broken, and it looks like it might be related to #2826 but I can't debug $$$setupUI$$$(). Refreshing the cache didn't help.

```java
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at io.flutter.project.FlutterProjectStep.$$$setupUI$$$(FlutterProjectStep.java)
	at io.flutter.project.FlutterProjectStep.<init>(FlutterProjectStep.java:78)
	at io.flutter.module.FlutterDescriptionProvider$FlutterApplicationGalleryEntry.createFlutterStep(FlutterDescriptionProvider.java:151)
	at io.flutter.project.ChoseProjectTypeStep.createDependentSteps(ChoseProjectTypeStep.java:98)
	at com.android.tools.idea.wizard.model.ModelWizard.addStep(ModelWizard.java:226)
	at com.android.tools.idea.wizard.model.ModelWizard.<init>(ModelWizard.java:93)
	at com.android.tools.idea.wizard.model.ModelWizard.<init>(ModelWizard.java:47)
	at com.android.tools.idea.wizard.model.ModelWizard$Builder.build(ModelWizard.java:553)
	at io.flutter.actions.FlutterNewProjectAction.actionPerformed(FlutterNewProjectAction.java:48)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
```

**Comment by devoncarew** [comment]
I see that code path as wanting to use `FlutterIcons.AndroidStudioNewProject`. That's using the same icon path as before the PR (`/icons/template_new_project.png`). The name of the field has changed.

**Comment by stevemessick** [comment]
The problem is a missing icon file: resources/flutter/icons/navigation/cancel.png. It was removed in #2820. The missing file breaks both the Android Studio wizard and the IntelliJ new module wizard. The file is referenced (apparently) in a GUI form. I can't find the reference, but it shows up in javap output.
```javap
    1010: ldc_w         #1042               // String /flutter/icons/navigation/cancel.png
    1013: invokevirtual #1048               // Method java/lang/Class.getResource:(Ljava/lang/String;)Ljava/net/URL;
    1016: invokespecial #1051               // Method javax/swing/ImageIcon."<init>":(Ljava/net/URL;)V
```
Is resources/flutter/icons.properties still useful? It has references to lots of deleted icon files.

I think the safest move is to restore the flutter/icons directory, at least until we can find out how many forms reference custom icons.

**Comment by devoncarew** [comment]
Ah, sorry about the breakage, and thanks for tracking this down. Do you want me to work on a fix?

`resources/flutter/icons` is entirely generated. I don't think we should reply on icons from there outside of the code that shows icon previews in the editor gutter. If we want to use an icon from there, we should likely just manually copy it to someplace like `resources/icons`.

`resources/flutter/icons.properties` can be deleted - we instead use `resources/flutter/cupertino_icons.properties` and `resources/flutter/material_icons.properties`.

**Comment by devoncarew** [comment]
> The problem is a missing icon file: resources/flutter/icons/navigation/cancel.png. It was removed...

I believe this is now available in `resources/flutter/material/cancel.png`.

**Comment by stevemessick** [comment]
I looked for "flutter/icons" and only found two references, both in the forms that are broken. So we probably don't have to worry too much about additional problems. PR in flight.
