### ISSUE TITLE
Need to start marking daemon processes

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#2839]
I submitted a PR (#2815) to do this earlier but closed w/o merging it because it requires modifying the build script.

```java
[ 145955]   WARN - n.process.BaseOSProcessHandler - Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: /Users/messick/src/flutter/flutter/bin/flutter daemon 
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:34)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:89)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:192)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:223)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:217)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
This is now done.
