### ISSUE TITLE
Issue running default app example from android Studio.

### ISSUE THREAD

**Issue by Eduardoveras** [flutter/flutter-intellij#2846]
---

## What happened

Just running the default example (the empty app that counts button presses)
running on latest AVD Pixel 2 with android 9 pie,
the apk was built, but something crashed while running on the ADV.

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 30.0.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

java.util.concurrent.CompletionException: java.io.IOException: Application terminated

```
java.lang.Throwable: java.util.concurrent.CompletionException: java.io.IOException: Application terminated
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$69(InspectorService.java:880)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Eduardoveras** [comment]
Flutter doctor output

```


[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.407], locale en-US)
    • Flutter version 0.11.3 at C:\flutter
    • Framework revision 72bf075e8d (10 days ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)


[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by Eduardoveras** [comment]
And more logs

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
I/Choreographer( 5704): Skipped 377 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation( 5704): eglMakeCurrent: 0xebeab9a0: ver 3 0 (tinfo 0xd36fd8b0)
Syncing files to device Android SDK built for x86...
I/OpenGLRenderer( 5704): Davey! duration=7586ms; Flags=1, IntendedVsync=1256471300438, Vsync=1262754633520, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1262758393790, AnimationStart=1262758622060, PerformTraversalsStart=1262759553040, DrawStart=1262815591490, SyncQueued=1262831909370, SyncStart=1262876635170, IssueDrawCommandsStart=1262876950900, SwapBuffers=1263119069080, FrameCompleted=1264102742670, DequeueBufferDuration=541205000, QueueBufferDuration=1459000, 
I/OpenGLRenderer( 5704): Davey! duration=760ms; Flags=0, IntendedVsync=1264119385525, Vsync=1264186052189, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1264187542740, AnimationStart=1264187637460, PerformTraversalsStart=1264187856340, DrawStart=1264190412930, SyncQueued=1264190503390, SyncStart=1264190719280, IssueDrawCommandsStart=1264198503820, SwapBuffers=1264199490270, FrameCompleted=1264880375760, DequeueBufferDuration=588438000, QueueBufferDuration=6666000, 
I/flutter ( 5704): addToOverlay
D/        ( 5704): HostConnection::get() New Host Connection established 0xea09d500, tid 5760
D/EGL_emulation( 5704): eglMakeCurrent: 0xebeaafe0: ver 3 0 (tinfo 0xea083470)
D/skia    ( 5704): Program linking failed.
E/emuglGLESv2_enc( 5704): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glLinkProgram:1533 GL error 0x501
E/emuglGLESv2_enc( 5704): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetProgramBinary:4066 GL error 0x502
E/emuglGLESv2_enc( 5704): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glUseProgram:1779 GL error 0x501
E/emuglGLESv2_enc( 5704): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glUseProgram:1779 GL error 0x501
D/skia    ( 5704): Program linking failed.
E/emuglGLESv2_enc( 5704): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glLinkProgram:1533 GL error 0x501
E/emuglGLESv2_enc( 5704): device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glGetProgramBinary:4066 GL error 0x502
Lost connection to device.

```

**Comment by pq** [comment]
Thanks for the report @Eduardoveras.

@jacob314: are you aware of any issues on Windows w/ the `11-09` beta?

@Eduardoveras: perhaps try a `flutter upgrade`?

**Comment by jacob314** [comment]
All the application terminated issues were due to a race condition in the dartvm that was recently fixed in tip of trunk Flutter.

**Comment by pq** [comment]
Ah, yes.  So this is in tip (but not the beta channel)?

@Eduardoveras: you might try changing to the `master` channel; it sounds like that will get you going:

https://flutter.io/docs/development/tools/sdk/upgrading

Cheers!
