### ISSUE TITLE
Flutter outline, preview doesn't work with Redux

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#2905]
When using redux we get the following exception from the preview: 

```
Error: No StoreProvider<AppState> found. To fix, please try:
          
  * Using Dart 2 (required) by using the --preview-dart-2 flag
  * Wrapping your MaterialApp with the StoreProvider<State>, 
  rather than an individual Route
  * Providing full type information to your Store<State>, 
  StoreProvider<State> and StoreConnector<State, ViewModel>
  * Ensure you are using consistent and complete imports. 
  E.g. always use `import 'package:my_app/app_state.dart';
  
If none of these solutions work, please file a bug at:
https://github.com/brianegan/flutter_redux/issues/new
      
#0      StoreProvider.of (package:flutter_redux/flutter_redux.dart:29:27)
#1      StoreConnector.build (package:flutter_redux/flutter_redux.dart:230:28)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#32     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#98     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#102    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#111    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#114    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#126    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#127    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#131    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#139    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#140    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#141    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#143    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#147    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#148    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#152    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#158    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#164    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#168    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#172    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#180    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#187    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#190    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
#191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#193    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
#194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#199    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#200    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#201    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#204    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#205    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#209    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#210    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#214    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#215    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#216    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#219    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#220    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#222    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#223    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#226    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#227    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#228    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#229    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#230    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#234    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#235    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#236    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#237    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#238    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#239    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#243    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#244    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#245    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#249    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#250    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#251    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#252    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#253    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#254    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#255    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#256    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#257    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#260    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#261    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#262    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#263    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#264    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#266    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#267    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#268    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#269    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#271    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#272    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#273    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#274    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#275    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#276    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#277    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#278    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#279    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#280    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#281    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#282    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#283    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#284    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#285    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#286    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#287    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#288    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#289    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#290    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#291    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#292    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#294    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#295    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#296    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#297    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#298    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#299    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#300    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#301    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#302    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#303    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#304    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#305    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#306    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#307    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#308    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#309    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#310    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#311    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#312    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#313    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#314    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#315    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#316    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#317    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#318    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#319    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#320    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#321    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#322    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#323    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#324    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#325    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#326    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#327    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#328    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#329    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#330    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#332    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#333    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#334    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#335    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#336    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#337    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#338    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
#339    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
#340    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
#341    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
#342    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
#343    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
#344    renderOnce (file:///Users/jaumard/StudioProjects/kiwi_mobile/.dart_tool/flutter/designer/render_server.dart:69:13)
#345    main.<anonymous closure> (file:///Users/jaumard/StudioProjects/kiwi_mobile/.dart_tool/flutter/designer/render_server.dart:38:22)
#346    _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#347    main.<anonymous closure> (file:///Users/jaumard/StudioProjects/kiwi_mobile/.dart_tool/flutter/designer/render_server.dart:35:15)
#348    BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:438:32)
#349    _RootZone.runUnary (dart:async/zone.dart:1379:54)
#350    _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#351    Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#352    Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#353    Future._complete (dart:async/future_impl.dart:476:7)
#354    new Future.delayed.<anonymous closure> (dart:async/future.dart:316:16)
#355    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#356    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#357    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#358    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

The error is normal as you need a StoreProvider for StoreConnector to works. 
I have no idea how we can make this to work...

**Comment by stevemessick** [comment]
This sounds like something @scheglov and @brianegan should look into.

**Comment by jaumard** [comment]
I'm not using redux anymore so I'll not be able to help more on this :) I let you guys closing it or keep it if it's still something you want to dig in :)

**Comment by stevemessick** [comment]
I think the lack of activity indicates we should close it. Thanks for getting back to us!
