### ISSUE TITLE
method not available: ext.flutter.inspector.getSelectedSummaryWidget

### ISSUE THREAD

**Issue by pyitphyoaung** [flutter/flutter-intellij#2907]
## What happened

Just trying to run a simple application and this happened.  I'm not sure about the way to reproduce the issue as I don't hit this issue anymore after subsequent runs.

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 30.0.1` • Dart plugin `181.5656`

Flutter 0.11.9 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d48e6e433c (11 days ago) • 2018-11-20 22:05:23 -0500
Engine • revision 5c8147450d
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

java.io.IOException: error from app.callServiceExtension: "method not available: ext.flutter.inspector.getSelectedSummaryWidget"

```
java.util.concurrent.CompletionException: java.io.IOException: error from app.callServiceExtension: "method not available: ext.flutter.inspector.getSelectedSummaryWidget"
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:375)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:181)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:141)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy17.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error from app.callServiceExtension: "method not available: ext.flutter.inspector.getSelectedSummaryWidget"
	... 22 more

**Comment by stevemessick** [comment]
We fixed a lot of bugs similar to this in M31, which was released last week. @jacob314 does this look like one of the cases we fixed?

**Comment by jacob314** [comment]
Yes likely fixed in M31.
