### ISSUE TITLE
NPE in WidgetPerfSummaryView.<init>

### ISSUE THREAD

**Issue by maitret** [flutter/flutter-intellij#2911]
## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.1.1` • Dart plugin `181.5656`

Flutter 0.11.13 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 58c8489fcd (5 days ago) • 2018-11-29 19:20:18 -0500
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.view.WidgetPerfSummaryView.<init>(WidgetPerfSummaryView.java:48)
	at io.flutter.view.InspectorPerfTab.buildUI(InspectorPerfTab.java:252)
	at io.flutter.view.InspectorPerfTab.<init>(InspectorPerfTab.java:82)
	at io.flutter.view.FlutterPerfView.addPerformanceTab(FlutterPerfView.java:216)
	at io.flutter.view.FlutterPerfView.addPerformanceViewContent(FlutterPerfView.java:173)
	at io.flutter.view.FlutterPerfView.debugActive(FlutterPerfView.java:100)
	at io.flutter.view.FlutterPerfViewFactory.lambda$initPerfView$1(FlutterPerfViewFactory.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevemessick** [comment]
@jacob314 something to add to the point release?

**Comment by jacob314** [comment]
This was fixed by.
https://github.com/flutter/flutter-intellij/pull/3182
