### ISSUE TITLE
Create project throws null when creating module

### ISSUE THREAD

**Issue by navneetkarnani** [flutter/flutter-intellij#2913]
## What happened

Created a new Flutter project as a "Module" along with my kotlin server project

## Version information

IntelliJ IDEA `2018.3` • Flutter plugin `io.flutter 31.1.4` • Dart plugin `183.4733`

No Flutter sdk configured.

## Exception

null

```
java.lang.Throwable: Assertion failed: steps: [com.intellij.ide.projectWizard.ProjectTypeStep, com.intellij.ide.projectWizard.ChooseTemplateStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, org.jetbrains.idea.maven.wizards.MavenModuleWizardStep, org.jetbrains.idea.maven.wizards.SelectPropertiesStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, org.jetbrains.plugins.gradle.service.project.wizard.GradleModuleWizardStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, Project Settings] current: Project Settings
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:174)
	at com.intellij.ide.wizard.AbstractWizard.doNextAction(AbstractWizard.java:398)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.doNextAction(AbstractProjectWizard.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.flutter.module.FlutterGeneratorPeer.requestNextStep(FlutterGeneratorPeer.java:217)
	at io.flutter.actions.InstallSdkAction$InstallAction.requestNextStep(InstallSdkAction.java:142)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$FlutterPrecacheCommand.onSuccess(InstallSdkAction.java:399)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$InstallCommand$1.processTerminated(InstallSdkAction.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy19.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$4.run(ProcessHandler.java:180)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:256)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:161)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:157)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:112)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:102)
	at com.intellij.execution.process.BaseOSProcessHandler$1$1.consume(BaseOSProcessHandler.java:87)
	at com.intellij.execution.process.ProcessWaitFor$1$1.run(ProcessWaitFor.java:65)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.execution.process.ProcessWaitFor$1.run(ProcessWaitFor.java:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stevemessick** [comment]
@pq We should probably disallow project creation if the SDK has not been configured.

**Comment by pq** [comment]
Good call @stevemessick and agreed.  I'll take a look.  Thanks for the report @navneetkarnani!
