### ISSUE TITLE
Came up on my IDE so posting it

### ISSUE THREAD

**Issue by drumsapkota** [flutter/flutter-intellij#2921]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.1.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

null

```
"#0      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:502:7)
<asynchronous suspension>
#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:193:34)
#2      new Future.sync (dart:async/future.dart:224:31)
#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:191:9)
#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:147:26)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#11     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#19     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#52     _StreamController._add (dart:async/stream_controller.dart:639:7)
#53     _StreamController.add (dart:async/stream_controller.dart:585:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#61     _StreamController._add (dart:async/stream_controller.dart:639:7)
#62     _StreamController.add (dart:async/stream_controller.dart:585:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
"
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:391)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:195)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:149)
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy17.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error from app.callServiceExtension: "method not available: ext.flutter.inspector.getSelectedWidget"
"#0      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:502:7)
<asynchronous suspension>
#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:193:34)
#2      new Future.sync (dart:async/future.dart:224:31)
#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:191:9)
#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:147:26)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#11     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#19     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#52     _StreamController._add (dart:async/stream_controller.dart:639:7)
#53     _StreamController.add (dart:async/stream_controller.dart:585:5)
#54     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#55     _rootRunUnary (dart:async/zone.dart:1136:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#61     _StreamController._add (dart:async/stream_controller.dart:639:7)
#62     _StreamController.add (dart:async/stream_controller.dart:585:5)
#63     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#67     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
"
	... 22 more

```

**Comment by stevemessick** [comment]
What version of Flutter are you using? This looks like a problem that was fixed before 1.0 came out.
