### ISSUE TITLE
Error message after hot reload

### ISSUE THREAD

**Issue by MisterJimson** [flutter/flutter-intellij#2938]
## What happened

Debugging after hot reload changes

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.1.1` • Dart plugin `181.5656`

Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (11 days ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.Element.getListListInt(Element.java:46)
	at org.dartlang.vm.service.element.Script.getTokenPosTable(Script.java:51)
	at io.flutter.run.ObservatoryFile.<init>(ObservatoryFile.java:53)
	at io.flutter.run.ObservatoryFile$Cache.downloadOrGet(ObservatoryFile.java:157)
	at io.flutter.run.PositionMapper.getSourcePosition(PositionMapper.java:259)
	at io.flutter.run.PositionMapper.getSourcePosition(PositionMapper.java:232)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.getSourcePosition(DartVmServiceDebugProcess.java:487)
	at io.flutter.server.vmService.frame.DartVmServiceStackFrame.<init>(DartVmServiceStackFrame.java:46)
	at io.flutter.server.vmService.VmServiceWrapper$10.lambda$received$0(VmServiceWrapper.java:456)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
Thanks for the report!
