### ISSUE TITLE
don't report some flutter_tools errors as exceptions

### ISSUE THREAD

**Issue by iGenMO** [flutter/flutter-intellij#2941]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

It was happened on  page pushing after network request error .

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.1.1` • Dart plugin `181.5656`

Flutter 0.9.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f37c235c32 (3 months ago) • 2018-09-25 17:45:40 -0400
Engine • revision 74625aed32
Tools • Dart 2.1.0-dev.5.0.flutter-a2eb050044

## Exception

null

```
"#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:848:9)
<asynchronous suspension>
#1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:1111:15)
#2      Isolate.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:1238:20)
<asynchronous suspension>
#3      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:501:55)
<asynchronous suspension>
#4      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:192:34)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:190:9)
#7      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:146:26)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#14     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#22     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#55     _StreamController._add (dart:async/stream_controller.dart:639:7)
#56     _StreamController.add (dart:async/stream_controller.dart:585:5)
#57     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#63     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#64     _StreamController._add (dart:async/stream_controller.dart:639:7)
#65     _StreamController.add (dart:async/stream_controller.dart:585:5)
#66     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#67     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#70     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
"
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:391)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:195)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:149)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy17.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error from app.callServiceExtension: "TimeoutException: Request to Dart VM Service timed out: ext.flutter.inspector.getSelectedWidget({objectGroup: selection_4, isolateId: isolates/765894587})"
"#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:848:9)
<asynchronous suspension>
#1      Isolate.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:1111:15)
#2      Isolate.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:1238:20)
<asynchronous suspension>
#3      AppDomain.callServiceExtension (package:flutter_tools/src/commands/daemon.dart:501:55)
<asynchronous suspension>
#4      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:192:34)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:190:9)
#7      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:146:26)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#14     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#22     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#55     _StreamController._add (dart:async/stream_controller.dart:639:7)
#56     _StreamController.add (dart:async/stream_controller.dart:585:5)
#57     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1714:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#63     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#64     _StreamController._add (dart:async/stream_controller.dart:639:7)
#65     _StreamController.add (dart:async/stream_controller.dart:585:5)
#66     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1276:33)
#67     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:14)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#70     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
"
	... 22 more

```

**Comment by devoncarew** [comment]
I think that in cases like these, we should not be reporting them as exceptions. Depending on the situation, we should either silently ignore them (if the action was not triggered by a user), or do something subtle, like reporting the issue as a temporary toast in the status line.

**Comment by devoncarew** [comment]
This is now complete.
