### ISSUE TITLE
The app disregrades calling some functions

### ISSUE THREAD

**Issue by dipinarora9** [flutter/flutter-intellij#2995]
## What happened

The app disregards to call some void functions.

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.3.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

org.dartlang.vm.service.element.RPCError@7c4bab3

```
java.lang.Throwable: org.dartlang.vm.service.element.RPCError@7c4bab3
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:131)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:92)
	at io.flutter.inspector.EvalOnDartLibrary$1.onError(EvalOnDartLibrary.java:142)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:639)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by pq** [comment]
Hi @dipinarora9, we've had a few quick releases of the flutter plugin since `31.3.1` to address a number of issues.  Could you try updating and seeing if your problem persists?

If it does, could you append the output of running `flutter doctor -v` in a terminal here?

Thanks!
