### ISSUE TITLE
When Run app in a device it starts then it closing saying Flutter  Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:54771/ws

### ISSUE THREAD

**Issue by henrytz** [flutter/flutter-intellij#3040]
## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.2.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

java.util.concurrent.CompletionException: java.io.IOException: Application terminated

```
java.lang.Throwable: java.util.concurrent.CompletionException: java.io.IOException: Application terminated
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$69(InspectorService.java:872)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pq** [comment]
@jacob314 : is there more logging we could add that would make these exceptions more actionable?  Or any ideas what's up with this one?

**Comment by olefasting** [comment]
I solved this by using a Pie image, in stead of a Q image, when making my VM

**Comment by stevemessick** [comment]
Closing as likely obsolete considering the changes that have been made. Please re-open if the problem occurs again.
