### ISSUE TITLE
IllegalArgumentException: Wrong end: 8736; document length=8466 from io.flutter.perf.EditorPerfDecorations.addRangeHighlighter()

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter-intellij#3045]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Hi,
i was switching between files and this error happened.
Don't know at what is related

## Version information

Android Studio `3.3 RC 3` • Flutter plugin `io.flutter 31.3.3` • Dart plugin `182.5124`

Flutter 1.1.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63b2daff7f (8 days ago) • 2018-12-28 10:43:06 -0800
Engine • revision f0a1d6f91d
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 d1817ddc91)

## Exception

null

```
java.lang.IllegalArgumentException: Wrong end: 8736; document length=8466; start=8732
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:49)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:42)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:68)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:115)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:166)
	at io.flutter.perf.EditorPerfDecorations.addRangeHighlighter(EditorPerfDecorations.java:159)
	at io.flutter.perf.EditorPerfDecorations.setPerfInfo(EditorPerfDecorations.java:134)
	at io.flutter.perf.FlutterWidgetPerf.showReports(FlutterWidgetPerf.java:313)
	at io.flutter.perf.FlutterWidgetPerf.performRequest(FlutterWidgetPerf.java:293)
	at io.flutter.perf.FlutterWidgetPerf.lambda$requestRepaint$0(FlutterWidgetPerf.java:148)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! It looks like we're feeding incorrect or out of date info in as editor ranges:

```
        at io.flutter.perf.EditorPerfDecorations.addRangeHighlighter(EditorPerfDecorations.java:159)
	at io.flutter.perf.EditorPerfDecorations.setPerfInfo(EditorPerfDecorations.java:134)
	at io.flutter.perf.FlutterWidgetPerf.showReports(FlutterWidgetPerf.java:313)
	at io.flutter.perf.FlutterWidgetPerf.performRequest(FlutterWidgetPerf.java:293)
	at io.flutter.perf.FlutterWidgetPerf.lambda$requestRepaint$0(FlutterWidgetPerf.java:148)
```

**Comment by devoncarew** [comment]
cc @jacob314

**Comment by kenzieschmoll** [comment]
Another duplicate from plugin version 38.2.4
https://github.com/flutter/flutter-intellij/issues/3826
