### ISSUE TITLE
Already disposed: Project exception from FlutterInitializer.java:165

### ISSUE THREAD

**Issue by razorree** [flutter/flutter-intellij#3046]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

There were many windows asking for sending anonymous info about usage (right bottom corner), after clicking about 6-8 times in every window (and then actual one was disappearing and i was clicking on next one), there was small windows complaining that it didn;t work (and this stacktrace/info after opening that bug)

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.3.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

Already disposed: Project (Disposed) cashmngr

```
java.lang.AssertionError: Already disposed: Project (Disposed) cashmngr
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:247)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:43)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:927)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:245)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:238)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:148)
	at com.intellij.openapi.module.ModuleManager.getInstance(ModuleManager.java:44)
	at io.flutter.utils.FlutterModuleUtils.getModules(FlutterModuleUtils.java:175)
	at io.flutter.utils.FlutterModuleUtils.declaresFlutter(FlutterModuleUtils.java:182)
	at io.flutter.FlutterInitializer$1.actionPerformed(FlutterInitializer.java:165)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.notification.Notification.fire(Notification.java:247)
	at com.intellij.notification.impl.NotificationsManagerImpl$14.linkSelected(NotificationsManagerImpl.java:794)
	at com.intellij.notification.impl.NotificationsManagerImpl$14.linkSelected(NotificationsManagerImpl.java:791)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:342)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:319)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! It looks like we need at add a guard for disposed projects in or around `io.flutter.utils.FlutterModuleUtils.getModules(FlutterModuleUtils.java:175)`.

**Comment by razorree** [comment]
also remember that i had many small windows asking for anonymous data usage - and i guess one is enough :)

**Comment by devoncarew** [comment]
> so maybe something was disposed after closing first 'anonymous usage window', but there were still few other windows, and later they tried to operate on disposed state.

Gotcha - I think this is what was going on. We were indexing through the list of projects after `Sounds good!` was pressed, including querying some projects which had been disposed.

**Comment by razorree** [comment]
and another bug was showing me few (about 5?) the same windows asking for 'anonymous data collection' :)

**Comment by devoncarew** [comment]
Thanks @razorree; do you mind filing a separate issue about that?
