### ISSUE TITLE
in DaemonApi.cancelPending, don't send exceptions through the completers

### ISSUE THREAD

**Issue by Skala** [flutter/flutter-intellij#3049]
## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.3.1` • Dart plugin `181.5656`

Error getting Flutter sdk information.

## Exception

java.io.IOException: Application terminated

```
java.util.concurrent.CompletionException: java.io.IOException: Application terminated
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.flutter.run.daemon.DaemonApi$Command.completeExceptionally(DaemonApi.java:391)
	at io.flutter.run.daemon.DaemonApi.cancelPending(DaemonApi.java:97)
	at io.flutter.run.daemon.FlutterApp.lambda$shutdownAsync$7(FlutterApp.java:528)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Application terminated
	... 7 more
```

**Comment by devoncarew** [comment]
Thanks for the report! I suspect that in `DaemonApi.cancelPending(DaemonApi.java:97)` we should move away from sending exceptions through the completers.
