### ISSUE TITLE
Android Studio - intellij - issue

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter-intellij#3135]
## What happened

Unsure of what happened. Studio suggests to raise an issue.

## Version information

Android Studio `3.1.4` • Flutter plugin `io.flutter 29.0.1` • Dart plugin `173.4700`

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (9 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[Thread-29,4,Idea Thread Group] 334526420
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 3.1#AI-173.4907809 Studio, eap:false, os:Mac OS X 10.14, java-version:JetBrains s.r.o 1.8.0_152-release-1024-b01,6,main] 2028485421

```
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1050)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.initBreakpoints(XDebugSessionImpl.java:314)
	at io.flutter.server.vmService.VmServiceWrapper.attachIsolate(VmServiceWrapper.java:247)
	at io.flutter.server.vmService.VmServiceWrapper$1$1$1$1.received(VmServiceWrapper.java:148)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:622)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:625)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by devoncarew** [comment]
Thanks for the report! We have newer versions of the plugin available now - you're on `29.0.1`, and we released v32 last week. I'd suggest upgrading to a newer version of Android Studio, which will pick up newer versions of the Flutter plugin.
