### ISSUE TITLE
Profile mode start crash

### ISSUE THREAD

**Issue by filiph** [flutter/flutter-intellij#3162]
## What happened

Starting a Flutter app in Profile mode on a physical android device

## Version information

Android Studio `3.2.1` • Flutter plugin `io.flutter 31.3.1` • Dart plugin `181.5656`

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (10 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

org.dartlang.vm.service.element.RPCError@5da87bc4

```
java.lang.Throwable: org.dartlang.vm.service.element.RPCError@5da87bc4
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:131)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:92)
	at io.flutter.inspector.EvalOnDartLibrary$1.onError(EvalOnDartLibrary.java:142)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:639)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:432)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by kenzieschmoll** [comment]
Error coming from https://github.com/flutter/flutter-intellij/blob/master/src/io/flutter/inspector/EvalOnDartLibrary.java#L142.

@jacob314 thoughts?

**Comment by devoncarew** [comment]
@filiph, thanks for the report! I see that you're on `31.3.1` - v32 is out and available now. It does include several fixes for crashes. Not sure if that includes what you reported, but it's worth upgrading the plugin.

**Comment by jacob314** [comment]
This is interesting. We shouldn't be calling EvalOnDartLibrary at all in a profile build as eval is not supported in profile.

**Comment by filiph** [comment]
FWIW, I upgraded and haven't seen the issue since.
