### ISSUE TITLE
AS exception with Java support enabled

### ISSUE THREAD

**Issue by akireyev** [flutter/flutter-intellij#3176]
## What happened

This happens every time I open a project for which I have checked 'Enable code completion... for Java/Kotlin'

## Version information

Android Studio `3.3.1` • Flutter plugin `io.flutter 32.0.1` • Dart plugin `182.5215`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NoSuchMethodError: com.android.tools.idea.gradle.project.sync.GradleSyncInvoker$Request.projectModified()Lcom/android/tools/idea/gradle/project/sync/GradleSyncInvoker$Request;
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:237)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:83)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:198)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevemessick** [comment]
It appears the API changed in the upgrade to 3.3.1. I just checked with 3.3 and it works.

I'd like to say this will be fixed in the next release, but the schedule is a little goofy and it might not make it. We'll try.

**Comment by devoncarew** [comment]
@akireyev, thanks for the report. M33 is out now - can you try updating and see if this issue is resolved?

**Comment by akireyev** [comment]
I have been able to open the same project without exceptions. The project now has better understanding of the Kotlin code. Thank you!
