### ISSUE TITLE
IllegalArgumentException: Wrong [index] from EditorPerfDecorations.addRangeHighlighter

### ISSUE THREAD

**Issue by sensuikan1973** [flutter/flutter-intellij#3179]
## What happened

`java.lang.IllegalArgumentException` occured.
I debugged with my real device 'iphone6'.
This is only real device!
This Error occured when try to watch wiedget building information at navigation bar of android studio.

here
![image](https://user-images.githubusercontent.com/23427957/52572468-35bd2280-2e5b-11e9-9e93-c4113309b065.png)

## Version information
* Android Studio `3.3.1` 
* Flutter plugin `io.flutter 32.0.1`
* Dart plugin `182.5215`

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (2 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception
```
java.lang.IllegalArgumentException: Wrong end: 1289; document length=1269; start=1277
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:49)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:42)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.<init>(RangeHighlighterImpl.java:68)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighterAndChangeAttributes(MarkupModelImpl.java:115)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.addRangeHighlighter(MarkupModelImpl.java:166)
	at io.flutter.perf.EditorPerfDecorations.addRangeHighlighter(EditorPerfDecorations.java:159)
	at io.flutter.perf.EditorPerfDecorations.setPerfInfo(EditorPerfDecorations.java:134)
	at io.flutter.perf.FlutterWidgetPerf.showReports(FlutterWidgetPerf.java:313)
	at io.flutter.perf.FlutterWidgetPerf.performRequest(FlutterWidgetPerf.java:293)
	at io.flutter.perf.FlutterWidgetPerf.lambda$requestRepaint$0(FlutterWidgetPerf.java:148)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
This is potentially a duplicate.

**Comment by devoncarew** [comment]
There have been several fixes in this area; tentatively closing, and we can address if we get additional reports.
