### ISSUE TITLE
Update plugin to 33.0.1 and an error occured.

### ISSUE THREAD

**Issue by superyyl** [flutter/flutter-intellij#3203]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Update the Flutter Plugin from 32.0.1 to 33.0.1, and restart Android Studio.

## Version information

Android Studio `3.3.1` • Flutter plugin `io.flutter 33.0.1` • Dart plugin `182.5215`

Flutter 1.1.9 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 1407091bfb (5 weeks ago) • 2019-01-08 20:40:19 -0800
Engine • revision e5ec3cf3ea
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 2cb346bd0c)

## Exception

null

```
java.lang.NoSuchMethodError: com.android.tools.idea.gradle.project.sync.GradleSyncInvoker$Request.projectModified()Lcom/android/tools/idea/gradle/project/sync/GradleSyncInvoker$Request;
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:237)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:83)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:198)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
@stevemessick, I can reproduce this as well. I'm using AS 3.3.1; you need to have the preference enabled for gradle build integration.

```
java.lang.NoSuchMethodError: com.android.tools.idea.gradle.project.sync.GradleSyncInvoker$Request.projectModified()Lcom/android/tools/idea/gradle/project/sync/GradleSyncInvoker$Request;
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:237)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:83)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:198)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:438)
```
