### ISSUE TITLE
On click of run button sometimes keyboard in intelliJ hangs and it throws error.

### ISSUE THREAD

**Issue by kaushiksamanta** [flutter/flutter-intellij#3216]
---

## What happened

On click of run button sometimes keyboard in intelliJ hangs and it throws this error.

## Version information

IntelliJ IDEA `2018.3.4` • Flutter plugin `io.flutter 32.0.3` • Dart plugin `183.5901`

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.run.daemon.FlutterApp.hasServiceExtension(FlutterApp.java:458)
	at io.flutter.perf.FlutterWidgetPerfManager.syncBooleanServiceExtension(FlutterWidgetPerfManager.java:239)
	at io.flutter.perf.FlutterWidgetPerfManager.debugActive(FlutterWidgetPerfManager.java:191)
	at io.flutter.perf.FlutterWidgetPerfManager.lambda$new$0(FlutterWidgetPerfManager.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:331)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy153.debugActive(Unknown Source)
	at io.flutter.view.FlutterViewMessages.sendDebugActive(FlutterViewMessages.java:45)
	at io.flutter.run.FlutterDebugProcess.onVmConnected(FlutterDebugProcess.java:68)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.onConnectSucceeded(DartVmServiceDebugProcess.java:582)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.lambda$scheduleConnect$2(DartVmServiceDebugProcess.java:275)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stevemessick** [comment]
@kenzieschmoll @jacob314

I believe this is a dup of #3206 from the previous version of the plugin, although the symptom is different.
