### ISSUE TITLE
Logger performance

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter-intellij#3219]
In my app I'm doing a synchro of a lot of data, and each http request and sql command is logged, which grow a lot (like 4500 lines in few seconds). During the time the log panel show all those entries, I can't do anything, no refactoring, no open file as it doesn't do the search. On log panel I can't filter by level or search a keyword :/  

```
[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

```

**Comment by jaumard** [comment]
Same after the update: 
```
[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

```

**Comment by stevemessick** [comment]
@pq

**Comment by pq** [comment]
Thanks for the report @jaumard!

**Comment by pq** [comment]
@jaumard: I'm looking into this.  Do you have a shareable repro?  (I've got some ideas but nothing beats the real thing.)

Thanks in advance!

**Comment by jaumard** [comment]
I'm having this at work on our private project, let me see if I can create a smaller project to reproduce this

**Comment by pq** [comment]
Thanks!

**Comment by pq** [comment]
I'd be curious if you're seeing any exceptions when things bog down as well.

**Comment by jaumard** [comment]
The fastest and easiest way I was able to get close to what I get in my project is by using: 

```
import 'dart:developer';
import 'package:logging';
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Logger test'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            var test= 9;
            for (var i = 0; i < 10000000; i++) {
              log(
                'this is a super long message for it to be truncated in order for the plugin to ask the longer version for each line, even if the line is not on the screen anymore or not at all showed because filter selection prevent it',
                name: 'loggerTest',
                level: 200,
                time: DateTime.now(),
              );
            }
          },
          child: Text('GO LOG ! :)'),
        ),
      ), 
    );
  }
}
```
This is a really dumb reproduction but I guess it's close enough. 
During the log trying to do some modification that trigger a hot reload, or after some time to even use the stop button ^^  

From what I've see, I don't have any exceptions, it just freeze until everything is processed ^^

**Comment by jaumard** [comment]
If I close the project during the freeze I get: 

```
java.lang.AssertionError: Already disposed: Module: 'flutter_log_perf'
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:149)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:35)
	at io.flutter.console.FlutterConsoleFilter.fileAtPath(FlutterConsoleFilter.java:83)
	at io.flutter.console.FlutterConsoleFilter.applyFilter(FlutterConsoleFilter.java:155)
	at io.flutter.logging.text.LineParser.parse(LineParser.java:94)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineStyle(FlutterLogEntryParser.java:299)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineInfo(FlutterLogEntryParser.java:317)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseEntry(FlutterLogEntryParser.java:322)
	at io.flutter.logging.FlutterLogEntryParser.parseLoggingEvent(FlutterLogEntryParser.java:134)
	at io.flutter.logging.FlutterLogEntryParser.parse(FlutterLogEntryParser.java:238)
	at io.flutter.logging.FlutterLog.onVmServiceReceived(FlutterLog.java:197)
	at io.flutter.logging.FlutterLog.access$200(FlutterLog.java:35)
	at io.flutter.logging.FlutterLog$2.received(FlutterLog.java:182)
	at org.dartlang.vm.service.VmServiceBase.forwardEvent(VmServiceBase.java:365)
	at org.dartlang.vm.service.VmServiceBase.processNotification(VmServiceBase.java:570)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:429)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by jaumard** [comment]
Full details: 
```
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.3.2` • Flutter plugin `io.flutter 33.3.1` • Dart plugin `182.5215`

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (4 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

## Exception

null

```
java.lang.AssertionError: Already disposed: Module: 'flutter_log_perf'
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:149)
	at com.intellij.openapi.roots.ModuleRootManager.getInstance(ModuleRootManager.java:35)
	at io.flutter.console.FlutterConsoleFilter.fileAtPath(FlutterConsoleFilter.java:83)
	at io.flutter.console.FlutterConsoleFilter.applyFilter(FlutterConsoleFilter.java:155)
	at io.flutter.logging.text.LineParser.parse(LineParser.java:94)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineStyle(FlutterLogEntryParser.java:299)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineInfo(FlutterLogEntryParser.java:317)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseEntry(FlutterLogEntryParser.java:322)
	at io.flutter.logging.FlutterLogEntryParser.parseLoggingEvent(FlutterLogEntryParser.java:134)
	at io.flutter.logging.FlutterLogEntryParser.parse(FlutterLogEntryParser.java:238)
	at io.flutter.logging.FlutterLog.onVmServiceReceived(FlutterLog.java:197)
	at io.flutter.logging.FlutterLog.access$200(FlutterLog.java:35)
	at io.flutter.logging.FlutterLog$2.received(FlutterLog.java:182)
	at org.dartlang.vm.service.VmServiceBase.forwardEvent(VmServiceBase.java:365)
	at org.dartlang.vm.service.VmServiceBase.processNotification(VmServiceBase.java:570)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:429)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:96)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

```
