### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by nickolas-pohilets** [flutter/flutter-intellij#3226]
## What happened

Switching to IDE after clicking a button in iOS simulator.

## Version information

IntelliJ IDEA `2018.2.2` • Flutter plugin `io.flutter 31.3.2` • Dart plugin `182.4129.13`

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

## Exception

null

```
java.lang.NullPointerException
	at org.dartlang.vm.service.element.Element.getListListInt(Element.java:46)
	at org.dartlang.vm.service.element.Script.getTokenPosTable(Script.java:51)
	at io.flutter.run.ObservatoryFile.<init>(ObservatoryFile.java:53)
	at io.flutter.run.ObservatoryFile$Cache.downloadOrGet(ObservatoryFile.java:157)
	at io.flutter.run.PositionMapper.getSourcePosition(PositionMapper.java:259)
	at io.flutter.run.PositionMapper.getSourcePosition(PositionMapper.java:232)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.getSourcePosition(DartVmServiceDebugProcess.java:471)
	at io.flutter.server.vmService.frame.DartVmServiceStackFrame.<init>(DartVmServiceStackFrame.java:46)
	at io.flutter.server.vmService.VmServiceWrapper$10.lambda$received$0(VmServiceWrapper.java:456)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
Thanks for the report! Re: the Flutter plugin version in use: `31.3.2` - this is an older version at this point. I see you're using IntelliJ `2018.2.2`. If you upgrade to 2018.3, that'll select a newer version of the Flutter plugin, which should address this issue.
