### ISSUE TITLE
Error when opening project in GoLand (Missing IOUtils)

### ISSUE THREAD

**Issue by Michael77** [flutter/flutter-intellij#3237]
## What happened

I opened a preexisting flutter project in GoLand.

## Version information

GoLand `2018.3.4` • Flutter plugin `io.flutter 33.3.2` • Dart plugin `183.5901`

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (2 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

## Exception

null

```
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at io.flutter.samples.FlutterSampleManager.readSampleIndex(FlutterSampleManager.java:57)
	at io.flutter.samples.FlutterSampleManager.readSampleIndex(FlutterSampleManager.java:64)
	at io.flutter.samples.FlutterSampleManager.loadSamples(FlutterSampleManager.java:79)
	at io.flutter.samples.FlutterSampleManager.getSamples(FlutterSampleManager.java:51)
	at io.flutter.samples.FlutterSampleNotificationProvider.getSamplesForFile(FlutterSampleNotificationProvider.java:60)
	at io.flutter.samples.FlutterSampleNotificationProvider.createNotificationPanel(FlutterSampleNotificationProvider.java:42)
	at io.flutter.samples.FlutterSampleNotificationProvider.createNotificationPanel(FlutterSampleNotificationProvider.java:24)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:136)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:977)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils PluginClassLoader[io.flutter, 33.3.2] com.intellij.ide.plugins.cl.PluginClassLoader@3f7a3fb7
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
```

**Comment by stevemessick** [comment]
The Flutter plugin works in IntelliJ Ultimate and Community editions, and in Android Studio. We don't test against GoLand, AppCode, CLion, etc. It looks like GoLand doesn't have some of the Apache libraries we need. However, the dependency on IOUtils was added in the latest release, and might be something we could reverse.

Over to @pq for comment and closing if appropriate.

**Comment by pq** [comment]
Sorry to see you hit this snag @Michael77.    

> the dependency on IOUtils was added in the latest release, and might be something we could reverse.

Yeah, [`IOUtils.toString`](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/IOUtils.html#toString(java.net.URI,%20java.nio.charset.Charset)) is really handy but we can inline this if needed.  Alternatively, maybe @alexander-doroshko can point me to a similar util that be generally available in IDEA IDEs?

**Comment by alexander-doroshko** [comment]
I don't know.

**Comment by devoncarew** [comment]
Yup, agreed that GoLand and others aren't supported (mostly due to the larger test matrix). That said, we may want to remove the org/apache/commons/io/IOUtils dep - it looks like it's our only use of the apache library.
