### ISSUE TITLE
Plugin tool test command not working

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter-intellij#3282]
I'm looking to update release 33 with a cherrypick, and when I run the tests I get the following:

```
➜  flutter-intellij git:(release_33) $ dart tool/plugin/bin/main.dart test 
  
Getting artifacts:
  artifacts/intellij-javac2.zip exists in cache
  artifacts/android-studio-ide-182.5264788-linux.zip exists in cache
  artifacts/Dart-182.5215.zip exists in cache
  
Compiling test sources:
  type 'List<FileSystemEntity>' is not a subtype of type 'List<File>'
  #0      findJars (package:plugin_tool/plugin.dart:98:3)
#1      TestCommand.doit (package:plugin_tool/plugin.dart:1027:18)
<asynchronous suspension>
#2      ProductCommand.run (package:plugin_tool/plugin.dart:974:20)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:111:11)
#7      main (package:plugin_tool/plugin.dart:26:25)
<asynchronous suspension>
#8      main (file:///usr/local/google/home/djshuckerow/Code/github.com/DaveShuckerow/flutter-intellij/tool/plugin/bin/main.dart:11:14)
<asynchronous suspension>
#9      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

**Comment by devoncarew** [comment]
cc @stevemessick 

That looks like a dart2 issue; I suspect that command hasn't been run since the strong mode by default change.

The commands I normally run at `plugin generate` and `plugin build`; I run the unit tests for the plugin from the IntelliJ UI.

**Comment by stevemessick** [comment]
I have a Dart Test run configuration with the file set to
` .../flutter-intellij/tool/plugin/test/plugin_test.dart`

I don't think anyone uses the `test` or `publish` commands in the plugin tool.

We really should update the plugin code someday.
