### ISSUE TITLE
NullPointerException when renaming root project dir

### ISSUE THREAD

**Issue by romikzo** [flutter/flutter-intellij#3306]
## What happened

I just renamed root dir to `even-wallet-dar`t from `even_wallet` in `Project files` tab from sidebar

## Version information

Android Studio `3.3.2` • Flutter plugin `io.flutter 33.4.1` • Dart plugin `182.5215`

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (5 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.editor.NativeEditorNotificationProvider.findRootDir(NativeEditorNotificationProvider.java:83)
	at io.flutter.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:45)
	at io.flutter.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:24)
	at com.intellij.ui.EditorNotificationsImpl$3.performInReadAction(EditorNotificationsImpl.java:149)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runUnderProgress$4(ProgressIndicatorUtils.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runUnderProgress(ProgressIndicatorUtils.java:225)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$100(ProgressIndicatorUtils.java:33)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:176)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by pq** [comment]
Thanks for the report!

For whoever looks at this, one observation is that `even-wallet-dart` is not a legal Dart (or Flutter) project name (`pub` won't like the name).  My gut is that we should try and add some kind of rename participant to prevent problematic renames.  (I'm not sure this is supported by IDEA but am working from memory with Eclipse where I'm pretty sure this was possible.)

**Comment by romikzo** [comment]
Yea, Android Studio forbade to create such a name. I just rename dir name, not package name in `pubspec.yaml`

**Comment by stevemessick** [comment]
The Flutter plugin expects the directory name to match the project name. I think Flutter itself also expects that. @pq I don't think there is additional work to be done here, unless we want to add a check when the IDE gets focus to see if someone did an OS-level directory rename.
