### ISSUE TITLE
Android Studio is barely usable for Flutter in the moment and productivity suffers

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter-intellij#3375]
## What happened
I see Android Studio freezing and flickering. A forces restart seems to fix that. That happens approx 2-3 times a day.
In the Console I see often these Error Messages:

----Error Messages in Console
16:09:05.776 402 info flutter.tools [        ] -> toStringDeep()
16:09:05.776 403 info flutter.tools [        ] -> ^^^^^^^^^^^^

Seems like flutter clean is clearing that up when I also disable all breakpoint.
The overall stability and is getting not better with flutter upgrade.

I converted my app to androidX - not sure if that makes a difference

----Error Messages in Console
16:09:05.776 402 info flutter.tools [        ] -> toStringDeep()
16:09:05.776 403 info flutter.tools [        ] -> ^^^^^^^^^^^^

## Version information
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.4.19, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code, 32-bit edition (version 1.30.1)
[√] Connected device (1 available)

## Exception 

null

```
java.lang.ArrayIndexOutOfBoundsException: 276 >= 276
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:245)
	at com.intellij.ui.treeStructure.treetable.ListTreeTableModelOnColumns.getChild(ListTreeTableModelOnColumns.java:56)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1485)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:109)
	at javax.swing.plaf.basic.BasicTreeUI.configureLayoutCache(BasicTreeUI.java:1821)
	at javax.swing.plaf.basic.BasicTreeUI.completeUIInstall(BasicTreeUI.java:689)
	at com.intellij.util.ui.tree.WideSelectionTreeUI.completeUIInstall(WideSelectionTreeUI.java:127)
	at javax.swing.plaf.basic.BasicTreeUI.installUI(BasicTreeUI.java:649)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JTree.setUI(JTree.java:700)
	at com.intellij.ui.treeStructure.Tree.setUI(Tree.java:125)
	at javax.swing.JTree.updateUI(JTree.java:716)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree.updateUI(TreeTableTree.java:54)
	at com.intellij.ui.treeStructure.treetable.TreeTable.updateUI(TreeTable.java:139)
	at io.flutter.logging.FlutterLogTree$TreeModel.update(FlutterLogTree.java:243)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:394)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
Sorry for the hassle @ride4sun.  Could you run `flutter doctor -v` and paste the results?

Thanks!

**Comment by ride4sun** [comment]
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.5
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[√] VS Code, 32-bit edition (version 1.30.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • moto g 6 • ZY322W3HK7 • android-arm • Android 8.0.0 (API 26)

• No issues found!

**Comment by devoncarew** [comment]
Thanks for the report! I see some of our code on the stack trace:

```
java.lang.ArrayIndexOutOfBoundsException: 276 >= 276
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:245)
	at com.intellij.ui.treeStructure.treetable.ListTreeTableModelOnColumns.getChild(ListTreeTableModelOnColumns.java:56)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1485)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:109)
	at javax.swing.plaf.basic.BasicTreeUI.configureLayoutCache(BasicTreeUI.java:1821)
	at javax.swing.plaf.basic.BasicTreeUI.completeUIInstall(BasicTreeUI.java:689)
	at com.intellij.util.ui.tree.WideSelectionTreeUI.completeUIInstall(WideSelectionTreeUI.java:127)
	at javax.swing.plaf.basic.BasicTreeUI.installUI(BasicTreeUI.java:649)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JTree.setUI(JTree.java:700)
	at com.intellij.ui.treeStructure.Tree.setUI(Tree.java:125)
	at javax.swing.JTree.updateUI(JTree.java:716)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree.updateUI(TreeTableTree.java:54)
	at com.intellij.ui.treeStructure.treetable.TreeTable.updateUI(TreeTable.java:139)
	at io.flutter.logging.FlutterLogTree$TreeModel.update(FlutterLogTree.java:243)
```

but am not sure that it's related to the issue you're reporting. Do you have the new logging view enabled (`Enable experimental Flutter logging view`)? If so, can you try disabling it, restarting Android Studio, and checking if you still see issues?

**Comment by jaumard** [comment]
more related to https://github.com/flutter/flutter/issues/30267 or https://github.com/flutter/flutter/issues/30381

**Comment by vvinogradsky** [comment]
I am pretty sure this happens when you re-run the debugger after the application you debug encounters an exception. At least this is what I am seeing. Perhaps abnormal termination has something to do with these bogus toStringDeep() complaints?

**Comment by ride4sun** [comment]
Could well be - I will keep an eye on it.

**Comment by stevemessick** [comment]
Closing as likely obsolete. If this problem occurs again please re-open.
