### ISSUE TITLE
IDE crash report

### ISSUE THREAD

**Issue by santhoshgutta** [flutter/flutter-intellij#3447]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.4` • Flutter plugin `io.flutter 35.1.1` • Dart plugin `183.6270`

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

## Exception

null

```
java.lang.IndexOutOfBoundsException: Wrong offset: 2141. Should be in range: [0, 2117]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:172)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1008)
	at io.flutter.editor.WidgetIndentsHighlightingPass.computeLocation(WidgetIndentsHighlightingPass.java:670)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:708)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:741)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:741)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:741)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:741)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:741)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:741)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:546)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:522)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:299)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$null$1(WidgetIndentsHighlightingPassFactory.java:196)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! This should be addressed by the just released M35.2 release.
