### ISSUE TITLE
After IntelliJ flutter update the IDE crashed. 

### ISSUE THREAD

**Issue by kaushiksamanta** [flutter/flutter-intellij#3476]
## What happened

After IntelliJ flutter update the IDE crashed. 

## Version information

IntelliJ IDEA `2019.1.2` • Flutter plugin `io.flutter 35.2.3` • Dart plugin `191.7019`

Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (9 days ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

## Exception

null

```
java.lang.IndexOutOfBoundsException: Index out of range: 14036
	at com.intellij.util.text.ImmutableText.findLeaf(ImmutableText.java:234)
	at com.intellij.util.text.ImmutableText.charAt(ImmutableText.java:226)
	at com.intellij.openapi.editor.impl.DocumentImpl$1.charAt(DocumentImpl.java:102)
	at io.flutter.editor.WidgetIndentsHighlightingPass.computeLocation(WidgetIndentsHighlightingPass.java:682)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:709)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.buildWidgetDescriptors(WidgetIndentsHighlightingPass.java:742)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:547)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:523)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:299)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$null$1(WidgetIndentsHighlightingPassFactory.java:196)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
There's an update - just out - which should fix this. If you still see issues after updating please let us know.
