### ISSUE TITLE
Issue on reformatting

### ISSUE THREAD

**Issue by rota2000** [flutter/flutter-intellij#3491]
## What happened

Changed text and saved. After that on reformatting such issue occured

## Version information

Android Studio `3.4` • Flutter plugin `io.flutter 35.3.1` • Dart plugin `183.6270`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Incorrect offsets: startOffset=15342, endOffset=15288, text length=15288
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:523)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:243)
	at io.flutter.editor.OutlineLocation.track(OutlineLocation.java:110)
	at io.flutter.editor.WidgetIndentGuideDescriptor.trackLocations(WidgetIndentGuideDescriptor.java:69)
	at io.flutter.editor.WidgetIndentsHighlightingPass$WidgetCustomHighlighterRenderer.<init>(WidgetIndentsHighlightingPass.java:111)
	at io.flutter.editor.WidgetIndentsHighlightingPass.createHighlighter(WidgetIndentsHighlightingPass.java:772)
	at io.flutter.editor.WidgetIndentsHighlightingPass.lambda$doApplyIndentInformationToEditor$2(WidgetIndentsHighlightingPass.java:659)
	at com.intellij.util.DocumentUtil.executeInBulk(DocumentUtil.java:48)
	at io.flutter.editor.WidgetIndentsHighlightingPass.doApplyIndentInformationToEditor(WidgetIndentsHighlightingPass.java:657)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:555)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:526)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:327)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$createHighlightingPass$4(WidgetIndentsHighlightingPassFactory.java:295)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevemessick** [comment]
@jacob314

**Comment by stevemessick** [comment]
Added the P1 label since it is being reported often.

**Comment by devoncarew** [comment]
Closing this as likely stale.
