### ISSUE TITLE
NPE Report

### ISSUE THREAD

**Issue by kikuchy** [flutter/flutter-intellij#3515]
## What happened

Only IDE Error notification has shown.

## Version information

IntelliJ IDEA `2019.1.2` • Flutter plugin `io.flutter 35.3.3` • Dart plugin `191.7221`

Flutter 1.5.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0ba67226ee (4 weeks ago) • 2019-04-24 17:18:28 -0700
Engine • revision c63d1cf9c9
Tools • Dart 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.preview.RenderHelper.setOffset(RenderHelper.java:104)
	at io.flutter.preview.PreviewView.applyEditorSelectionToTree(PreviewView.java:858)
	at io.flutter.preview.PreviewView.updateOutline(PreviewView.java:648)
	at io.flutter.preview.PreviewView.access$500(PreviewView.java:85)
	at io.flutter.preview.PreviewView$1.lambda$outlineUpdated$0(PreviewView.java:137)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report!

The preview area in the outline view was an experimental feature. After gathering user feedback on it and other ways to visualize your UI, we've decided to instead concentrate on the UI Guides work - helping to bring some of the outline view into the editing area. As such, we've removed the preview area for the next release.
