### ISSUE TITLE
Crash when running (and cancelling) project creation

### ISSUE THREAD

**Issue by whosthatgeek** [flutter/flutter-intellij#3518]
## What happened

* install flutter plugin
* download sdk from intellij
* create new flutter project
* cancel project creation
* crackkkk

## Version information

IntelliJ IDEA `2019.1.2` • Flutter plugin `io.flutter 35.3.3` • Dart plugin `191.7221`

No Flutter sdk configured.

## Exception

null

```
java.lang.Throwable: Assertion failed: steps: [com.intellij.ide.projectWizard.ProjectTypeStep, com.intellij.ide.projectWizard.ChooseTemplateStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.j2meplugin.module.settings.ui.J2MEModuleTypeStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.spring.boot.initializr.SpringInitializrApplicationInfoStep, com.intellij.spring.boot.initializr.dependencies.SpringInitializrDependenciesStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, org.jetbrains.plugins.gradle.service.project.wizard.GradleModuleWizardStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, org.jetbrains.idea.maven.wizards.MavenModuleWizardStep, org.jetbrains.idea.maven.wizards.SelectPropertiesStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, com.intellij.openapi.externalSystem.service.project.wizard.ExternalModuleSettingsStep, Project Settings] current: Project Settings
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.ide.wizard.AbstractWizard.doNextAction(AbstractWizard.java:398)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.doNextAction(AbstractProjectWizard.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.flutter.module.FlutterGeneratorPeer.requestNextStep(FlutterGeneratorPeer.java:225)
	at io.flutter.actions.InstallSdkAction$InstallAction.requestNextStep(InstallSdkAction.java:142)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$FlutterPrecacheCommand.onSuccess(InstallSdkAction.java:399)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$InstallCommand$1.processTerminated(InstallSdkAction.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy23.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:172)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:155)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:151)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:112)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:99)
	at com.intellij.execution.process.ProcessWaitFor.lambda$null$0(ProcessWaitFor.java:61)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pq** [comment]
Thanks for the report @whosthatgeek!

**Comment by stevemessick** [comment]
Covered by #3626, which has better diagnostic info.
