### ISSUE TITLE
Error on breakpoint in M36

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#3544]
Repro: Install M36 RC build.
Create sample project.
Set breakpoint on counter++ line.
Tap counter button in app.
Error generated when breakpoint hit.

`Access is allowed from event dispatch thread only.`
```java
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@727485ce
Current thread: Thread[ApplicationImpl pooled thread 3,4,Idea Thread Group] 1444411203
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 907030465
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1133)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1122)
	at com.intellij.ui.AppIcon.assertIsDispatchThread(AppIcon.java:672)
	at com.intellij.ui.AppIcon.access$300(AppIcon.java:51)
	at com.intellij.ui.AppIcon$MacAppIcon.requestFocus(AppIcon.java:208)
	at com.intellij.ide.impl.ProjectUtil.focusProjectWindow(ProjectUtil.java:333)
	at io.flutter.server.vmService.DartVmServiceDebugProcess$1.sessionPaused(DartVmServiceDebugProcess.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:133)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:25)
	at com.intellij.util.EventDispatcher$3.invoke(EventDispatcher.java:96)
	at com.sun.proxy.$Proxy153.sessionPaused(Unknown Source)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.positionReachedInternal(XDebugSessionImpl.java:882)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.breakpointReached(XDebugSessionImpl.java:776)
	at com.intellij.xdebugger.impl.XDebugSessionImpl.breakpointReached(XDebugSessionImpl.java:738)
	at io.flutter.server.vmService.DartVmServiceListener.onIsolatePaused(DartVmServiceListener.java:183)
	at io.flutter.server.vmService.DartVmServiceListener.lambda$received$0(DartVmServiceListener.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
It looks like that's caused by this code:

```
ProjectUtil.focusProjectWindow(project, true);
```

I don't know why we're choosing to explicitly focus the IDE window; I'd think we'd want the default IntelliJ platform behavior.

**Comment by devoncarew** [comment]
If we do choose to do this, we should likely call this from the EDT thread.

**Comment by stevemessick** [comment]
I think it is because the active window is the emulator (unless using a
phone) and we want the debugger to pop to top.

**Comment by pq** [comment]
@stevemessick: that's correct IIRC.

**Comment by pq** [comment]
> If we do choose to do this, we should likely call this from the EDT thread.

👍 That should do it.
