### ISSUE TITLE
 Flutter UI Guide line randomly shown

### ISSUE THREAD

**Issue by erlangp** [flutter/flutter-intellij#3561]
## Steps to Reproduce

Move widget up

## Version info

[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.2.9200], locale id-ID)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7830

## What happened

Flutter UI Guide line randomly shown

## Version information

IntelliJ IDEA `2019.1.3` • Flutter plugin `io.flutter 36.0.4` • Dart plugin `191.7830`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Incorrect offsets: startOffset=8590, endOffset=8544, text length=8544
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:506)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:243)
	at io.flutter.editor.OutlineLocation.track(OutlineLocation.java:110)
	at io.flutter.editor.WidgetIndentGuideDescriptor.trackLocations(WidgetIndentGuideDescriptor.java:69)
	at io.flutter.editor.WidgetIndentsHighlightingPass$WidgetCustomHighlighterRenderer.<init>(WidgetIndentsHighlightingPass.java:114)
	at io.flutter.editor.WidgetIndentsHighlightingPass.createHighlighter(WidgetIndentsHighlightingPass.java:775)
	at io.flutter.editor.WidgetIndentsHighlightingPass.lambda$doApplyIndentInformationToEditor$2(WidgetIndentsHighlightingPass.java:662)
	at com.intellij.util.DocumentUtil.executeInBulk(DocumentUtil.java:48)
	at io.flutter.editor.WidgetIndentsHighlightingPass.doApplyIndentInformationToEditor(WidgetIndentsHighlightingPass.java:660)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:558)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:529)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:316)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$createHighlightingPass$4(WidgetIndentsHighlightingPassFactory.java:284)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kenzieschmoll** [comment]
cc @jacob314
