### ISSUE TITLE
list of flaky tests

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3583]
The list of tests we've disabled due to flakes:
-  [ ] WorkspaceCacheTest.shouldDetectConfigFileChanges
-  [ ] WorkspaceCacheTest.shouldDetectModuleRootChange
-  [ ] FlutterWidgetPerfTest.testFileStatsCalculation
-  [x] FlutterWidgetPerfTest.testOverallStatsCalculation

**Comment by stevemessick** [comment]
This one fails frequently on travis, but usually passes locally:
```java
  io.flutter.run.bazelTest.LaunchCommandsTest
    ✘ producesCorrectCommandLineForTestName (10.3s)
      junit.framework.AssertionFailedError: Not disposed java.swing.Timer: 
        Timer (listeners: [io.flutter.perf.FlutterWidgetPerf$$Lambda$5/1164268997@6c32798]) (delayed for 1ms); queue:TimerQueue (javax.swing.Timer@4becde8d)
```
The failure has nothing to do with that test, though. It looks to me like a Timer created in FlutterWidgetPerf was not properly disposed. FlutterWidgetPerf is often the first test class that runs. In this case, we have a lot of tests running after it:
```java
  io.flutter.perf.FlutterWidgetPerfTest
    ✔ testFileStatsCalculation
    ✔ testOverallStatsCalculation
  io.flutter.perf.SlidingWindowStatsTest
    ✔ duplicateSlidingWindowStatTimestamps
    ✔ simpleSlidingWindowStats
    ✔ totalSinceNavigation
    ✔ clearSlidingWindowStats
  io.flutter.samples.FlutterSampleTest
    ✔ testScaffoldDescription
    ✔ testParseShortHtmlDescription
    ✔ testParseCardDescription
    ✔ testParseHtmlDescription
    ✔ testParseDocLink
    ✔ testParseEscapes
  io.flutter.devtools.DevToolsUtilsTest
    ✔ validDevToolsUrl (3.4s)
  io.flutter.run.bazelTest.BazelTestFieldsTest
    ✔ shouldUpgradeFieldsFromOldXml
    ✔ shouldReadFieldsFromXml
    ✔ roundTripShouldPreserveFields
  io.flutter.run.bazelTest.LaunchCommandsTest
    ✘ producesCorrectCommandLineForTestName (10.3s)
```
I bet we can stabilize the tests by not running FlutterWidgetPerfTest.

I have noticed in integration testing that, in that context, there are a LOT of objects that do not get disposed in the Inspector and Perf views. I thought I was perhaps not creating those views correctly, but perhaps there is a real problem. The code looks like it ought to be disposing things, but perhaps the dispose does not get run in a testing context.

@jacob314 @terrylucas for insight here
@DaveShuckerow should `producesCorrectCommandLineForTestName()` take 10s to run? Or could it be getting charged for clean-up caused by some other test? And, @kenzieschmoll would you expect `validDevToolsUrl()` to take 3.4s to run?

**Comment by devoncarew** [comment]
Here are the current failures:

```
 io.flutter.bazel.WorkspaceCacheTest
    ✘ shouldDetectConfigFileChanges
      java.lang.AssertionError: expected a workspace but it doesn't exist
          at io.flutter.bazel.WorkspaceCacheTest.checkNoConfig(WorkspaceCacheTest.java:95)
io.flutter.logging.FlutterConsoleLogManagerTest
    ✘ testNoLoggerName (1.1s)
      java.lang.AssertionError
          at io.flutter.logging.FlutterConsoleLogManagerTest.testNoLoggerName(FlutterConsoleLogManagerTest.java:46)
    ✘ testBasicLogging
      java.lang.AssertionError
          at io.flutter.logging.FlutterConsoleLogManagerTest.testBasicLogging(FlutterConsoleLogManagerTest.java:33)
    ✘ testWithError
      java.lang.AssertionError
          at io.flutter.logging.FlutterConsoleLogManagerTest.testWithError(FlutterConsoleLogManagerTest.java:59)
    ✘ testWithStacktrace
      java.lang.AssertionError
          at io.flutter.logging.FlutterConsoleLogManagerTest.testWithStacktrace(FlutterConsoleLogManagerTest.java:72)
```

**Comment by devoncarew** [comment]
I see only one flaky test now:

```
io.flutter.run.bazelTest.BazelTestConfigurationFactoryTest
    ✘ factoryConfigTypesMatch (8.1s)
      java.lang.RuntimeException: junit.framework.AssertionFailedError: Not disposed java.swing.Timer: Timer (listeners: [io.flutter.perf.FlutterWidgetPerf$$Lambda$5/735153787@139c85e3]) (delayed for 97ms); queue:TimerQueue (javax.swing.Timer@2f9a1ee2)
```

which failed because that was when the Timer from a previous test choose to fire. I think we should enable all tests on the bot, and disable the test w/ the timer (and open an issue for it).

**Comment by devoncarew** [comment]
Disabling the two `FlutterWidgetPerfTest`s due to the Timer from those tests causing async downstream failures in other tests.

```
junit.framework.AssertionFailedError: Not disposed java.swing.Timer: Timer (listeners: [io.flutter.perf.FlutterWidgetPerf$$Lambda$5/735153787@139c85e3]) (delayed for 97ms); queue:TimerQueue (javax.swing.Timer@2f9a1ee2)
```

**Comment by devoncarew** [comment]
`io.flutter.bazel.WorkspaceCacheTest::shouldDetectConfigFileChanges` appears to be flaky; disabling that as well.

**Comment by stevemessick** [comment]
io.flutter.analytics.AnalyticsTest are throwing an exception with the current release so they have been disabled.

**Comment by devoncarew** [comment]
The flaks due to resource leaks have been taken care of. The remaining failing tests are:
- shouldDetectModuleRootChange
- shouldDetectConfigFileChanges

**Comment by stevemessick** [comment]
Adding a few more that just started to fail with the M45 release.
```java
io.flutter.run.bazelTest.BazelTestConfigProducerTest

      ✘ producesFileConfigurationInsideABazelWorkspace

        java.lang.IllegalArgumentException: could not find extension implementation class io.flutter.run.bazelTest.FlutterBazelTestConfigurationType
            at io.flutter.run.bazelTest.BazelTestConfigProducerTest.getEmptyBazelTestConfig(BazelTestConfigProducerTest.java:147)

      ✘ producesNoConfigurationWithAnInvalidTestFile

        java.lang.IllegalArgumentException: could not find extension implementation class io.flutter.run.bazelTest.FlutterBazelTestConfigurationType
            at io.flutter.run.bazelTest.BazelTestConfigProducerTest.getEmptyBazelTestConfig(BazelTestConfigProducerTest.java:147)

      ✘ producesNoConfigurationOutsideABazelWorkspace

        java.lang.IllegalArgumentException: could not find extension implementation class io.flutter.run.bazelTest.FlutterBazelTestConfigurationType
            at io.flutter.run.bazelTest.BazelTestConfigProducerTest.getEmptyBazelTestConfig(BazelTestConfigProducerTest.java:147)

      ✘ producesTestNameConfigurationInsideABazelWorkspace

        java.lang.IllegalArgumentException: could not find extension implementation class io.flutter.run.bazelTest.FlutterBazelTestConfigurationType
            at io.flutter.run.bazelTest.BazelTestConfigProducerTest.getEmptyBazelTestConfig(BazelTestConfigProducerTest.java:147)

io.flutter.editor.ActiveEditorsOutlineServiceTest

      ✘ notifiesOutlineChangedWhenOpeningAndClosingFiles

        CompositeException (10 nested):
        ------------------------------
        [0]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [1]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [2]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [3]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [4]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [5]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [6]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [7]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [8]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [9]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        ------------------------------
            at io.flutter.editor.ActiveEditorsOutlineServiceTest.lambda$notifiesOutlineChangedWhenOpeningAndClosingFiles$3(ActiveEditorsOutlineServiceTest.java:116)

      ✘ notifiesWhenOutlinesChange

        CompositeException (10 nested):
        ------------------------------
        [0]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [1]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [2]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [3]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [4]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [5]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [6]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [7]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [8]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [9]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        ------------------------------
            at io.flutter.editor.ActiveEditorsOutlineServiceTest.lambda$notifiesWhenOutlinesChange$0(ActiveEditorsOutlineServiceTest.java:87)

      ✘ getIfUpdatedDeterminesOutlineValidity

        CompositeException (10 nested):
        ------------------------------
        [0]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [1]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [2]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [3]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [4]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [5]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [6]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [7]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [8]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        [9]: com.intellij.testFramework.LoggedErrorProcessor$TestLoggerAssertionError: null
        ------------------------------
            at io.flutter.editor.ActiveEditorsOutlineServiceTest.lambda$getIfUpdatedDeterminesOutlineValidity$6(ActiveEditorsOutlineServiceTest.java:154)
```

**Comment by stevemessick** [comment]
Added all of AndroidxTest, too. The problem is LocalFileSystem.findFileByPath() is returning null for projects created by the test framework. I haven't found a work-around yet.

**Comment by pq** [comment]
Closing in favor of tracking in https://github.com/flutter/flutter-intellij/issues/8189
