### ISSUE TITLE
NullPointerError

### ISSUE THREAD

**Issue by l0g1c-80m8** [flutter/flutter-intellij#3594]
What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.3` • Flutter plugin `io.flutter 34.0.1` • Dart plugin `182.5215`

Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (4 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.run.daemon.FlutterApp.hasServiceExtension(FlutterApp.java:485)
	at io.flutter.perf.FlutterWidgetPerfManager.syncBooleanServiceExtension(FlutterWidgetPerfManager.java:245)
	at io.flutter.perf.FlutterWidgetPerfManager.debugActive(FlutterWidgetPerfManager.java:193)
	at io.flutter.perf.FlutterWidgetPerfManager.lambda$new$0(FlutterWidgetPerfManager.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:376)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:364)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:357)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:208)
	at com.sun.proxy.$Proxy160.debugActive(Unknown Source)
	at io.flutter.view.FlutterViewMessages.sendDebugActive(FlutterViewMessages.java:45)
	at io.flutter.run.FlutterDebugProcess.onVmConnected(FlutterDebugProcess.java:69)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.onConnectSucceeded(DartVmServiceDebugProcess.java:582)
	at io.flutter.server.vmService.DartVmServiceDebugProcess.lambda$scheduleConnect$2(DartVmServiceDebugProcess.java:275)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jacob314** [comment]
Your Flutter Intellij Plugin version is old (34 compared to version 36). If you are able to reproduce after updating to the latest plugin please reopen the bug.

**Comment by l0g1c-80m8** [comment]
Thank you jacob314, the issue has been resolved.
