### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Relz** [flutter/flutter-intellij#3601]
## What happened

I test Flutter for web: open hello_world example, run project in debug mode.
Chrome browser is executed, red text 'Hello World' was appeared.
Then I changed text literal 'Hello World' to 'Hello World!'. Boom =)

## Version information

IntelliJ IDEA `2019.1.3` • Flutter plugin `io.flutter 36.1.4` • Dart plugin `191.7830`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.server.vmService.HeapMonitor$HeapObject.getAsJsonObject(HeapMonitor.java:55)
	at io.flutter.server.vmService.HeapMonitor$HeapObject.getEntries(HeapMonitor.java:59)
	at io.flutter.server.vmService.HeapMonitor$IsolateObject.getHeaps(HeapMonitor.java:92)
	at io.flutter.inspector.HeapState.handleIsolatesInfo(HeapState.java:104)
	at io.flutter.inspector.HeapDisplay$1.lambda$handleIsolatesInfo$0(HeapDisplay.java:64)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! Closing as a dup of https://github.com/flutter/flutter-intellij/issues/3590.
