### ISSUE TITLE
IntelliJ Flutter demon crash

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter-intellij#3605]
## What happened

Opened Flutter project and clicked the device drop-down.

## Version information

Android Studio `3.4.1` • Flutter plugin `io.flutter 36.1.1` • Dart plugin `183.6270`

Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b beta https://github.com/flutter/flutter.git

## Exception

null

```
java.lang.Throwable: Flutter device daemon #2: process exited during startup. Exit code: 1, stderr:

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:248)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:224)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by devoncarew** [comment]
From the comment at the top:

```
Error: The Flutter directory is not a clone of the GitHub project.
The flutter tool requires Git in order to operate properly;
to set up Flutter, run the following command:
```

There may be an issue with your flutter install?

**Comment by efortuna** [comment]
oh geez. sorry about that. I wasn't reading the error because it just told me to make a Flutter issue. Closing!
