### ISSUE TITLE
"Access is allowed from event dispatch thread only" on project creation when used with the 'Install SDK' option

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter-intellij#3626]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2019.2 EAP` • Flutter plugin `io.flutter 36.1.5` • Dart plugin `192.5281.24`

Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (5 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

## Exception

Access is allowed from event dispatch thread only.

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@48cda804
Current thread: Thread[flutter,4,Idea Thread Group] 231686009
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2#IU-192.5281.24 IDEA, eap:true, os:Mac OS X 10.14.5, java-version:JetBrains s.r.o 11.0.3+12-b304.2 2019.2#IU-192.5281.24 IDEA, eap:true, os:Mac OS X 10.14.5, java-version:JetBrains s.r.o 11.0.3+12-b304.2,6,Idea Thread Group] 935227418
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1070)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1059)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.assertDispatchThread(FocusManagerImpl.java:433)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.getFocusOwner(FocusManagerImpl.java:231)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.getFocusOwner(IdeFocusManagerImpl.java:102)
	at com.intellij.ui.messages.JBMacMessages.getForemostWindow(JBMacMessages.java:104)
	at com.intellij.ui.messages.JBMacMessages.showErrorDialog(JBMacMessages.java:187)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:799)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.commitStepData(AbstractProjectWizard.java:236)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.doNextAction(AbstractProjectWizard.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.flutter.module.FlutterGeneratorPeer.requestNextStep(FlutterGeneratorPeer.java:225)
	at io.flutter.actions.InstallSdkAction$InstallAction.requestNextStep(InstallSdkAction.java:142)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$FlutterPrecacheCommand.onSuccess(InstallSdkAction.java:399)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$InstallCommand$1.processTerminated(InstallSdkAction.java:293)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy20.processTerminated(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:172)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:247)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:155)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:151)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:61)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:168)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:99)
	at com.intellij.execution.process.ProcessWaitFor.lambda$null$0(ProcessWaitFor.java:61)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:43)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by stevemessick** [comment]
Thanks for the report. Unfortunately, I can't reproduce this problem. Can you give any more information about what was going on prior to this error?

Adding the output of 'flutter doctor -v' might help.

**Comment by lookfirst** [comment]
Looking at the stack trace, it appears to be something with installing the SDK

```
	at io.flutter.actions.InstallSdkAction$InstallAction.requestNextStep(InstallSdkAction.java:142)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$FlutterPrecacheCommand.onSuccess(InstallSdkAction.java:399)
	at io.flutter.actions.InstallSdkAction$GitCloneAction$InstallCommand$1.processTerminated(InstallSdkAction.java:293)
```

You probably can't reproduce it locally since your system has already been setup. This was on a new install.

**Comment by lookfirst** [comment]
I had an endless stream of issues on a new install. Lots of things that needed to get fixed in `flutter doctor`... which is fine... but it wasn't easy. The iphone app was fairly easy, but getting the android app up and running was really hard due to a lot of outdated dependencies in the default sample project. especially around the build system.

**Comment by stevemessick** [comment]
Thanks. We'll try again with a fresh install. It is quite possible some API changes require an update to the code behind the `Install SDK` button.

@pq

**Comment by stevemessick** [comment]
As indicated, the problem occurs when the `Install SDK` button is used to download the Flutter SDK. The SDK is downloaded and the project is created correctly, but the error is shown when the project opens.

@pq probably has the best context here.
