### ISSUE TITLE
Error getting Flutter sdk information.

### ISSUE THREAD

**Issue by subfuzion** [flutter/flutter-intellij#3632]
## What happened

New Flutter web project, just clicked the run button after configuring Dart/Flutter SDK.

## Version information

IntelliJ IDEA `2019.2 EAP` • Flutter plugin `io.flutter 36.1.5` • Dart plugin `192.5438.26`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.server.vmService.HeapMonitor$HeapObject.getAsJsonObject(HeapMonitor.java:55)
	at io.flutter.server.vmService.HeapMonitor$HeapObject.getEntries(HeapMonitor.java:59)
	at io.flutter.server.vmService.HeapMonitor$IsolateObject.getHeaps(HeapMonitor.java:92)
	at io.flutter.inspector.HeapState.handleIsolatesInfo(HeapState.java:104)
	at io.flutter.inspector.HeapDisplay$1.lambda$handleIsolatesInfo$0(HeapDisplay.java:64)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:782)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:731)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:396)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by devoncarew** [comment]
Thanks for the report! Should be fixed by https://github.com/flutter/flutter-intellij/pull/3625.
