### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rhymelph** [flutter/flutter-intellij#3646]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2019.1.1` • Flutter plugin `io.flutter 35.3.2` • Dart plugin `191.7019`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Incorrect offsets: startOffset=12584, endOffset=12379, text length=12379
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarker(DocumentImpl.java:506)
	at com.intellij.openapi.editor.Document.createRangeMarker(Document.java:243)
	at io.flutter.editor.OutlineLocation.track(OutlineLocation.java:110)
	at io.flutter.editor.WidgetIndentGuideDescriptor.trackLocations(WidgetIndentGuideDescriptor.java:69)
	at io.flutter.editor.WidgetIndentsHighlightingPass$WidgetCustomHighlighterRenderer.<init>(WidgetIndentsHighlightingPass.java:111)
	at io.flutter.editor.WidgetIndentsHighlightingPass.createHighlighter(WidgetIndentsHighlightingPass.java:772)
	at io.flutter.editor.WidgetIndentsHighlightingPass.lambda$doApplyIndentInformationToEditor$2(WidgetIndentsHighlightingPass.java:659)
	at com.intellij.util.DocumentUtil.executeInBulk(DocumentUtil.java:48)
	at io.flutter.editor.WidgetIndentsHighlightingPass.doApplyIndentInformationToEditor(WidgetIndentsHighlightingPass.java:657)
	at io.flutter.editor.WidgetIndentsHighlightingPass.setOutline(WidgetIndentsHighlightingPass.java:555)
	at io.flutter.editor.WidgetIndentsHighlightingPass.run(WidgetIndentsHighlightingPass.java:526)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.runWidgetIndentsPass(WidgetIndentsHighlightingPassFactory.java:327)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.lambda$createHighlightingPass$4(WidgetIndentsHighlightingPassFactory.java:295)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
## Version information

IntelliJ IDEA `2019.1.1` • Flutter plugin `io.flutter 35.3.2` • Dart plugin `191.7019`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.IndexOutOfBoundsException: Wrong offset: -1. Should be in range: [0, 12395]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:176)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:991)
	at io.flutter.editor.WidgetIndentsHighlightingPass$WidgetCustomHighlighterRenderer.updateSelected(WidgetIndentsHighlightingPass.java:142)
	at io.flutter.editor.WidgetIndentsHighlightingPass.onCaretPositionChanged(WidgetIndentsHighlightingPass.java:491)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory$1.caretPositionChanged(WidgetIndentsHighlightingPassFactory.java:110)
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:132)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:26)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:90)
	at com.sun.proxy.$Proxy100.caretPositionChanged(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:132)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:26)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:90)
	at com.sun.proxy.$Proxy100.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:569)
	at com.intellij.openapi.editor.impl.CaretImpl.doMoveToVisualPosition(CaretImpl.java:631)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$moveToVisualPosition$4(CaretImpl.java:567)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:453)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:567)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:563)
	at com.intellij.openapi.editor.impl.CaretModelImpl.moveToVisualPosition(CaretModelImpl.java:134)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.processMousePressed(EditorImpl.java:3960)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.lambda$runMousePressedCommand$0(EditorImpl.java:3778)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMousePressedCommand(EditorImpl.java:3783)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:3712)
	at java.awt.Component.processMouseEvent(Component.java:6547)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:741)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:686)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
@rhymelph - can you update to a more recent version of the plugin (you're on `35.3.2`). That should address the issue.

**Comment by rhymelph** [comment]
ok,tx
