### ISSUE TITLE
flutter hot reload error on mac os 

### ISSUE THREAD

**Issue by abdhojamyl** [flutter/flutter-intellij#3667]
Trying to enable hot-reload 

## Version information
IntelliJ IDEA `2019.1.3` • Flutter plugin `io.flutter 37.0.3` • Dart plugin `191.7830`

Flutter 1.8.2-pre.30 • channel master • https://github.com/flutter/flutter.git
Framework • revision 13382f41c0 (28 hours ago) • 2019-07-12 23:24:04 -0700
Engine • revision 919e353236
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

## Exception

null

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.dartlang.vm.service.VmServiceBase.connectionClosed(VmServiceBase.java:375)
	at org.dartlang.vm.service.VmService.connectionClosed(VmService.java:51)
	at org.dartlang.vm.service.VmServiceBase$1.onClose(VmServiceBase.java:83)
	at de.roderick.weberknecht.WebSocket.close(WebSocket.java:103)
	at de.roderick.weberknecht.WebSocket.handleReceiverError(WebSocket.java:173)
	at de.roderick.weberknecht.WebSocketReceiver.handleError(WebSocketReceiver.java:79)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:68)
```

**Comment by devoncarew** [comment]
Thanks for the report! It looks like this was fixed in https://github.com/dart-lang/vm_service_drivers/pull/228, and will be available in the next release.
