### ISSUE TITLE
Flutter error

### ISSUE THREAD

**Issue by squalltua** [flutter/flutter-intellij#3668]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.4.2` • Flutter plugin `io.flutter 37.0.1` • Dart plugin `183.6270`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Flutter device daemon #1: process exited during startup. Exit code: 254, stderr:
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart:34:6: Error: Error when reading '.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_utils.dart': No such file or directory
part 'src/intl/bidi_utils.dart';
     ^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart:34:6: Error: Can't use '.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_utils.dart' as a part, because it has no 'part of' declaration.
part 'src/intl/bidi_utils.dart';
     ^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:58:3: Error: Type 'TextDirection' not found.
  TextDirection contextDirection;
  ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:96:49: Error: Type 'TextDirection' not found.
      {bool isHtml: false, bool resetDir: true, TextDirection direction}) {
                                                ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:131:49: Error: Type 'TextDirection' not found.
      {bool isHtml: false, bool resetDir: true, TextDirection direction}) {
                                                ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:145:3: Error: Type 'TextDirection' not found.
  TextDirection estimateDirection(String text, {bool isHtml: false}) {
  ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:155:33: Error: Type 'TextDirection' not found.
  String _resetDir(String text, TextDirection direction, bool isHtml) {
                                ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:58:3: Error: 'TextDirection' isn't a type.
  TextDirection contextDirection;
  ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:68:28: Error: Getter not found: 'TextDirection'.
      : contextDirection = TextDirection.LTR,
                           ^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/src/intl/bidi_formatter.dart:68:28: Error: The getter 'TextDirection' isn't defined for the class 'BidiFormatter'.
 - 'BidiFormatter' is from 'package:intl/intl.dart' ('.pub-cache/hosted/pub.dartlang.org/intl-0.15.8/lib/intl.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextDirection'.
      : contextDirection = TextDirection.LTR,
                           ^^^^^^^^^^^^^

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:240)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:225)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by terrylucas** [comment]
Does your pubspec reference:

dependencies:
  intl: ^0.15.7

Also, pub get or pub update will be necessary.

See https://stackoverflow.com/questions/51705701/how-to-import-intl-library-in-flutter

**Comment by squalltua** [comment]
not work

**Comment by terrylucas** [comment]
Not work?

Does your pubspec have a dependency on intl?
Can you send the output of the pub get and/or pub update?
