### ISSUE TITLE
StringIndexOutOfBoundsException from FlutterLogEntryParser

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter-intellij#3672]
## What happened

Every time I open a Flutter project I see this error. I saw there was a similar report from 2016 but the issue was closed, so I've opened a new issue for visibility.

## Version information

IntelliJ IDEA `2019.1.3` • Flutter plugin `io.flutter 37.0.3` • Dart plugin `191.7830`

Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b712a172f9 (7 days ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0

## Exception

null

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy23.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:188)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:179)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:211)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:195)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:149)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:77)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:155)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at io.flutter.logging.text.LineParser.parse(LineParser.java:112)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineStyle(FlutterLogEntryParser.java:289)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineInfo(FlutterLogEntryParser.java:307)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseEntry(FlutterLogEntryParser.java:312)
	at io.flutter.logging.FlutterLogEntryParser.parseDaemonEvent(FlutterLogEntryParser.java:348)
	at io.flutter.logging.FlutterLogEntryParser.parseDaemonEvent(FlutterLogEntryParser.java:272)
	at io.flutter.logging.FlutterLog$1.onTextAvailable(FlutterLog.java:168)
	... 19 more
```

**Comment by devoncarew** [comment]
Thanks for the report (and the stack trace)!

**Comment by devoncarew** [comment]
Do you have the setting for the Flutter Logging view enabled (in the Experiments section of the preferences)?

**Comment by brianegan** [comment]
Ack, sorry about the delay, a bit under the weather this week -- Yep! I do have that enabled.

**Comment by stevemessick** [comment]
@pq are you taking this one or should I?

**Comment by pq** [comment]
I'm not...  If you don't get to it, feel free to assign to me.
