### ISSUE TITLE
Crash while parsing log output

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#3721]
## What happened

Not really sure why this is crashing.  I was running an app, and it failed to compile, producing some log output, which seems related to this stack trace.

## Version information

IntelliJ IDEA `2019.2` • Flutter plugin `io.flutter 37.1.4` • Dart plugin `192.5728.98`

Flutter 1.8.4-pre.53 • channel master • git@github.com:gspencergoog/flutter.git
Framework • revision ea32385162 (2 hours ago) • 2019-08-01 07:33:20 -0700
Engine • revision b41c172bcd
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 bd049f5b53)

## Exception

null

```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy21.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:188)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:179)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:211)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:195)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:149)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:77)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:155)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.StringIndexOutOfBoundsException: begin -1, end -1, length 61
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at io.flutter.logging.text.LineParser.parse(LineParser.java:112)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineStyle(FlutterLogEntryParser.java:289)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseLineInfo(FlutterLogEntryParser.java:307)
	at io.flutter.logging.FlutterLogEntryParser$LineHandler.parseEntry(FlutterLogEntryParser.java:312)
	at io.flutter.logging.FlutterLogEntryParser.parseDaemonEvent(FlutterLogEntryParser.java:348)
	at io.flutter.logging.FlutterLogEntryParser.parseDaemonEvent(FlutterLogEntryParser.java:272)
	at io.flutter.logging.FlutterLog$1.onTextAvailable(FlutterLog.java:168)
	... 19 more
```

**Comment by pq** [comment]
Thanks for the report @gspencergoog.  This is likely the same issue as #3693.

I'd recommend disabling the experimental logging view for now; you'll avoid this issue and pick up a bunch of improvements @devoncarew landed on the default one to boot.

**Comment by pq** [comment]
(Closing as duplicate; feel free to re-open if anyone thinks that's a mistake!)
