### ISSUE TITLE
NPE when parsing a PlatformTarget value

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3736]
```
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at io.flutter.view.PlatformTarget.valueOf(TogglePlatformAction.java:137)
	at io.flutter.view.TogglePlatformAction.lambda$update$0(TogglePlatformAction.java:48)
	at io.flutter.utils.EventStream.listen(EventStream.java:115)
	at io.flutter.view.TogglePlatformAction.update(TogglePlatformAction.java:47)
```

cc @kenzieschmoll; I think we should write our own `PlatformTarget.parseValue` method which is lenient towards bad or unknown values.

**Comment by devoncarew** [comment]
I'm seeing this against flutter master:

```

java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Enum.java:238)
	at io.flutter.view.PlatformTarget.valueOf(TogglePlatformAction.java:137)
	at io.flutter.view.TogglePlatformAction.lambda$update$0(TogglePlatformAction.java:48)
	at io.flutter.utils.EventStream.listen(EventStream.java:115)
	at io.flutter.view.TogglePlatformAction.update(TogglePlatformAction.java:47)
```

We'll likely want this included in a patch for M38.

**Comment by kenzieschmoll** [comment]
Devon, do you happen to have a repro case for this? I think I have a fix for the NPE but would like to verify.

**Comment by devoncarew** [comment]
I've seen this on flutter on master; I suspect that a new platform value got added.

You probably need to enable web support to see this. Something like: 'flutter config --enable-web'.

**Comment by kenzieschmoll** [comment]
Hmm.. looks like we still have the same three values here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/platform.dart#L41

Interestingly, when running an app against the Chrome(web) target, "ext.flutter.platformOverride" returns the platform value of android. 

I'm still unable to reproduce, but based on the error it seems like the name we are passing to `valueOf` is null (see [Java enum docs](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#valueOf(java.lang.Class,%20java.lang.String))). I have a fix that should work and be safe.
