### ISSUE TITLE
Update failed for ActionGroup: null (null)[null]

### ISSUE THREAD

**Issue by KyllianDM** [flutter/flutter-intellij#3743]
## Version information

Android Studio `3.4.2` • Flutter plugin `io.flutter 38.1.1` • Dart plugin `183.6270`

Error getting Flutter sdk information.

## Exception

update failed for ActionGroup: null (null)[null]

```
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at io.flutter.view.PlatformTarget.valueOf(TogglePlatformAction.java:137)
	at io.flutter.view.TogglePlatformAction.lambda$update$0(TogglePlatformAction.java:48)
	at io.flutter.utils.EventStream.listen(EventStream.java:115)
	at io.flutter.view.TogglePlatformAction.update(TogglePlatformAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1120)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:53)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:101)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:93)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1113)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:213)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at com.intellij.ui.JBSplitter.addNotify(JBSplitter.java:109)
	at java.awt.Container.addImpl(Container.java:1122)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.openapi.ui.ThreeComponentsSplitter.setLastComponent(ThreeComponentsSplitter.java:492)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.setComponent(ToolWindowsPane.java:332)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.access$400(ToolWindowsPane.java:47)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddAndSplitDockedComponentCmd.run(ToolWindowsPane.java:851)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.CommandProcessor.execute(CommandProcessor.java:50)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:596)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:576)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.java:826)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.java:185)
	at io.flutter.view.FlutterPerfView.activateToolWindow(FlutterPerfView.java:353)
	at io.flutter.view.FlutterPerfView.addPerformanceViewContent(FlutterPerfView.java:221)
	at io.flutter.view.FlutterPerfView.debugActive(FlutterPerfView.java:109)
	at io.flutter.view.FlutterPerfViewFactory.lambda$initPerfView$1(FlutterPerfViewFactory.java:32)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
I think this was address in https://github.com/flutter/flutter-intellij/pull/3742; cc @kenzieschmoll .
