### ISSUE TITLE
ConcurrentModificationException from io.flutter.editor.ActiveEditorsOutlineService.notifyOutlineUpdated

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#3746]
## What happened

I just started IntelliJ, and this "problem" notification appeared.

## Version information

IntelliJ IDEA `2019.2` • Flutter plugin `io.flutter 38.1.4` • Dart plugin `192.5728.98`

Flutter 1.8.4-pre.130 • channel focus_shortcuts • git@github.com:gspencergoog/flutter.git
Framework • revision fcfd3af2a8 (17 hours ago) • 2019-08-06 16:05:41 -0700
Engine • revision 80f80b14e0
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 574c4a51c6)

## Exception

null

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at io.flutter.editor.ActiveEditorsOutlineService.notifyOutlineUpdated(ActiveEditorsOutlineService.java:154)
	at io.flutter.editor.ActiveEditorsOutlineService.access$400(ActiveEditorsOutlineService.java:43)
	at io.flutter.editor.ActiveEditorsOutlineService$OutlineListener.outlineUpdated(ActiveEditorsOutlineService.java:258)
	at io.flutter.dart.FlutterDartAnalysisServer.processNotification(FlutterDartAnalysisServer.java:137)
	at io.flutter.dart.FlutterDartAnalysisServer.processResponse(FlutterDartAnalysisServer.java:110)
	at io.flutter.dart.FlutterDartAnalysisServer.processString(FlutterDartAnalysisServer.java:103)
	at io.flutter.dart.FlutterDartAnalysisServer.access$300(FlutterDartAnalysisServer.java:29)
	at io.flutter.dart.FlutterDartAnalysisServer$CompatibleResponseListener.onResponse(FlutterDartAnalysisServer.java:153)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:868)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:705)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:48)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:1127)
```

**Comment by devoncarew** [comment]
Thanks for the report! This is fixed in https://github.com/flutter/flutter-intellij/pull/3726; we should have a new release out in the near term with the fix.
