### ISSUE TITLE
IDE Error  when closing tabs

### ISSUE THREAD

**Issue by davidsowerby** [flutter/flutter-intellij#3751]
## What happened

Seemed to occur as I closed a set of editor tabs ('close other tabs') in Android Studio

## Version information

Android Studio `3.4.2` • Flutter plugin `io.flutter 38.1.1` • Dart plugin `183.6270`

Flutter 1.7.8+hotfix.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (3 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

## Exception

null

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at io.flutter.editor.ActiveEditorsOutlineService.notifyOutlineUpdated(ActiveEditorsOutlineService.java:154)
	at io.flutter.editor.ActiveEditorsOutlineService.access$400(ActiveEditorsOutlineService.java:43)
	at io.flutter.editor.ActiveEditorsOutlineService$OutlineListener.outlineUpdated(ActiveEditorsOutlineService.java:258)
	at io.flutter.dart.FlutterDartAnalysisServer.processNotification(FlutterDartAnalysisServer.java:137)
	at io.flutter.dart.FlutterDartAnalysisServer.processResponse(FlutterDartAnalysisServer.java:110)
	at io.flutter.dart.FlutterDartAnalysisServer.access$200(FlutterDartAnalysisServer.java:29)
	at io.flutter.dart.FlutterDartAnalysisServer$CompatibleResponseListener.onResponse(FlutterDartAnalysisServer.java:148)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:798)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:638)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:48)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:1059)
```

## Version info

flutter doctor -v
[✓] Flutter (Channel beta, v1.7.8+hotfix.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/david/flutter/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/david/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /snap/android-studio/77/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/77/android-studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /home/david/idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • SM T530 • ca1c194806eefa93 • android-arm • Android 5.0.2 (API 21)

! Doctor found issues in 3 categories.

**Comment by devoncarew** [comment]
Thanks for the report! I think this will be addressed by an upcoming patch to the M38 release.
