### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by gboumis** [flutter/flutter-intellij#3755]
## What happened

Probably editing source code and running/hot reloading

## Version information

Android Studio `3.4.2` • Flutter plugin `io.flutter 38.1.1` • Dart plugin `183.6270`

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (3 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

## Exception

null

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at io.flutter.editor.ActiveEditorsOutlineService.notifyOutlineUpdated(ActiveEditorsOutlineService.java:154)
	at io.flutter.editor.ActiveEditorsOutlineService.access$400(ActiveEditorsOutlineService.java:43)
	at io.flutter.editor.ActiveEditorsOutlineService$OutlineListener.outlineUpdated(ActiveEditorsOutlineService.java:258)
	at io.flutter.dart.FlutterDartAnalysisServer.processNotification(FlutterDartAnalysisServer.java:137)
	at io.flutter.dart.FlutterDartAnalysisServer.processResponse(FlutterDartAnalysisServer.java:110)
	at io.flutter.dart.FlutterDartAnalysisServer.access$200(FlutterDartAnalysisServer.java:29)
	at io.flutter.dart.FlutterDartAnalysisServer$CompatibleResponseListener.onResponse(FlutterDartAnalysisServer.java:148)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.notifyResponseListeners(RemoteAnalysisServerImpl.java:798)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.processResponse(RemoteAnalysisServerImpl.java:638)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl.access$600(RemoteAnalysisServerImpl.java:48)
	at com.google.dart.server.internal.remote.RemoteAnalysisServerImpl$ServerResponseReaderThread.run(RemoteAnalysisServerImpl.java:1059)
```

Seems sligtly differenet from #3746 and #3725 as the lines of `HashMap` implementation are different.
```
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
```

**Comment by stevemessick** [comment]
Could you update the Flutter plugin to 38.2 and see if the problem still occurs? We believe this has been fixed. Please reopen if not.
