### ISSUE TITLE
something happened, idk what

### ISSUE THREAD

**Issue by da-revo** [flutter/flutter-intellij#3788]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

idk

## Version information

Android Studio `3.4.2` • Flutter plugin `io.flutter 38.2.1` • Dart plugin `183.6270`

Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b712a172f9 (5 weeks ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0

## Exception

update failed for ActionGroup: null (null)[null]

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at io.flutter.view.TogglePlatformAction.update(TogglePlatformAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1120)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:53)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:101)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:93)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1113)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.java:213)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at java.awt.Container.addNotify(Container.java:2774)
	at javax.swing.JComponent.addNotify(JComponent.java:4741)
	at com.intellij.ui.JBSplitter.addNotify(JBSplitter.java:109)
	at java.awt.Container.addImpl(Container.java:1122)
	at java.awt.Container.add(Container.java:417)
	at com.intellij.openapi.ui.ThreeComponentsSplitter.setFirstComponent(ThreeComponentsSplitter.java:468)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.setComponent(ToolWindowsPane.java:324)
	at com.intellij.openapi.wm.impl.ToolWindowsPane.access$400(ToolWindowsPane.java:47)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$AddAndSplitDockedComponentCmd.run(ToolWindowsPane.java:851)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.commands.ApplyWindowInfoCmd.run(ApplyWindowInfoCmd.java:50)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.commands.FinalizableCommand.finish(FinalizableCommand.java:36)
	at com.intellij.openapi.wm.impl.ToolWindowsPane$RemoveSplitAndDockedComponentCmd.run(ToolWindowsPane.java:1075)
	at com.intellij.openapi.wm.impl.CommandProcessor.runNext(CommandProcessor.java:78)
	at com.intellij.openapi.wm.impl.CommandProcessor.run(CommandProcessor.java:59)
	at com.intellij.openapi.wm.impl.CommandProcessor.execute(CommandProcessor.java:50)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:596)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:576)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.java:826)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.java:185)
	at io.flutter.view.FlutterPerfView.activateToolWindow(FlutterPerfView.java:353)
	at io.flutter.view.FlutterPerfView.addPerformanceViewContent(FlutterPerfView.java:221)
	at io.flutter.view.FlutterPerfView.debugActive(FlutterPerfView.java:109)
	at io.flutter.view.FlutterPerfViewFactory.lambda$initPerfView$1(FlutterPerfViewFactory.java:32)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! I think this is a dup of https://github.com/flutter/flutter-intellij/issues/3771.
