### ISSUE TITLE
Flutter device daemon #3

### ISSUE THREAD

**Issue by otavioafpedro** [flutter/flutter-intellij#3793]
## What happened

While opening the IDE the error showed up.

## Version information

IntelliJ IDEA `2019.2` • Flutter plugin `io.flutter 38.2.4` • Dart plugin `192.6459`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Flutter device daemon #3: process exited during startup. Exit code: 1, stderr:

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:239)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:230)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by devoncarew** [comment]
Nothing jumps out at me here about why this may be happening...
