### ISSUE TITLE
problem while running flutter web project

### ISSUE THREAD

**Issue by ocelili** [flutter/flutter-intellij#3918]
when I just opened my web flutter project in the visual studio code and tried debugging without changing any files, an error occurred 
```
> 

> [INFO] Connecting to the build daemon...
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 1.6s
> [INFO]
> [INFO] Starting daemon...
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 1.0s
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 33.1s
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 1.0s
> [INFO]
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 33.1s
> [INFO]
> [INFO] Setting up file watchers...
> [INFO] Setting up file watchers completed, took 10ms
> [INFO]
> [INFO] Registering build targets...
> [INFO] Starting initial build...
> [INFO] Serving DevTools at http://127.0.0.1:62497
> [INFO] Starting resource servers...
> [INFO] Serving `web` on http://127.0.0.1:62484
> [INFO] About to build [web]...
> [INFO] Running build...
> [INFO] 1.0s elapsed, 0/0 actions completed.
> [INFO] Running build completed, took 1.5s
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 777ms
> [INFO] Succeeded after 2.3s with 0 outputs (0 actions)
> Unhandled exception:
> FormatException: Unexpected character (at character 1)
> Not Found
> ^
> 
> #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1392:5)
> flutter/flutter#1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1259:9)
> flutter/flutter#2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:924:22)
> flutter/flutter#3      _parseJson  (dart:convert-patch/convert_patch.dart:29:10)
> flutter/flutter#4      JsonDecoder.convert  (dart:convert/json.dart:493:36)
> flutter/flutter#5      JsonCodec.decode  (dart:convert/json.dart:151:41)
> flutter/flutter#6      jsonDecode  (dart:convert/json.dart:94:10)
> flutter/flutter#7      parse
> flutter/flutter#8      Sources.scriptParsed  (package:dwds/src/sources.dart:55:19)
> <asynchronous suspension>
> flutter/flutter#9      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
> flutter/flutter#10     CastStreamSubscription._onData  (dart:_internal/async_cast.dart:81:11)
> flutter/flutter#11     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
> flutter/flutter#12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
> flutter/flutter#13     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:263:7)
> flutter/flutter#14     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:68:11)
> flutter/flutter#15     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)
> flutter/flutter#16     WipDomain.eventStream.<anonymous closure>.<anonymous closure>  (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)
> flutter/flutter#17     _HandlerEventSink.add  (dart:async/stream_transformers.dart:228:7)
> flutter/flutter#18     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:120:24)
> flutter/flutter#19     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
> flutter/flutter#20     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
> flutter/flutter#21     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)
> flutter/flutter#22     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)
> flutter/flutter#23     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)
> flutter/flutter#24     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
> flutter/flutter#25     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
> flutter/flutter#26     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:116:13)
> flutter/flutter#27     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:173:5)
> 
> Exited (255)
```
I have followed [this](I have followed this)
but still an error

**Comment by devoncarew** [comment]
I'm going to close this as a dup of https://github.com/dart-lang/sdk/issues/37490. If it's the same issue, that was verified as fixed Aug 27; the fix should be in flutter master.
