### ISSUE TITLE
NPE from VMServiceManager.getFlutterViewsList() (VMServiceManager.java:662)

### ISSUE THREAD

**Issue by lookfirst** [flutter/flutter-intellij#3925]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

I have no idea.

## Version information

IntelliJ IDEA `2019.3 EAP` • Flutter plugin `io.flutter 40.0.5` • Dart plugin `193.3793.14`

No Flutter sdk configured.
(Untrue... it just isn't being detected here?)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.vmService.VMServiceManager.getFlutterViewsList(VMServiceManager.java:662)
	at io.flutter.vmService.VMServiceManager.getFlutterViewId(VMServiceManager.java:647)
	at io.flutter.vmService.VMServiceManager.getDisplayRefreshRate(VMServiceManager.java:607)
	at io.flutter.vmService.VMServiceManager.lambda$onFrameEventReceived$1(VMServiceManager.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by devoncarew** [comment]
@kenzieschmoll, can you take a look at this? This is from the latest release. If we get multiple reports of this we may consider patching M40.

**Comment by kenzieschmoll** [comment]
Pending fix here: https://github.com/flutter/flutter-intellij/pull/3927
