### ISSUE TITLE
Plugin error in IntelliJ with a non-Flutter project

### ISSUE THREAD

**Issue by tanis2000** [flutter/flutter-intellij#3938]
## What happened

I'm working with a Spring Boot project, but for some reason the Flutter plugin is thinking that this is a Flutter project and it's throwing the following error.

## Version information

IntelliJ IDEA `2019.2.3` • Flutter plugin `io.flutter 40.0.4` • Dart plugin `192.6817.14`

No Flutter sdk configured.

## Exception

null

```
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/project/sync/GradleSyncState
	at io.flutter.utils.AndroidUtils$1.condition(AndroidUtils.java:309)
	at com.intellij.util.WaitFor$1$1.condition(WaitFor.java:68)
	at com.intellij.util.WaitFor.<init>(WaitFor.java:51)
	at com.intellij.util.WaitFor.<init>(WaitFor.java:41)
	at com.intellij.util.WaitFor$1$1.<init>(WaitFor.java:65)
	at com.intellij.util.WaitFor$1.run(WaitFor.java:65)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.gradle.project.sync.GradleSyncState PluginClassLoader[io.flutter, 40.0.4] com.intellij.ide.plugins.cl.PluginClassLoader@3e00b3fe
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
```

**Comment by stevemessick** [comment]
Thanks for the report. We'll have an update to fix this soon.

**Comment by ControlTheBit** [comment]
@stevemessick is there an ETA on the update? This is quite annoying. Thank you for your ongoing work in this project :)
