### ISSUE TITLE
Error while running project in Android Emulator

### ISSUE THREAD

**Issue by Gabrielhn** [flutter/flutter-intellij#3962]
## What happened

I was running my application on android emulator

## Version information

IntelliJ IDEA `2019.2.3` • Flutter plugin `io.flutter 40.1.4` • Dart plugin `192.6817.14`

Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (2 weeks ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.vmService.VMServiceManager.getFlutterViewsList(VMServiceManager.java:662)
	at io.flutter.vmService.VMServiceManager.getFlutterViewId(VMServiceManager.java:647)
	at io.flutter.vmService.VMServiceManager.getDisplayRefreshRate(VMServiceManager.java:607)
	at io.flutter.vmService.VMServiceManager.lambda$onFrameEventReceived$1(VMServiceManager.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by devoncarew** [comment]
@stevemessick - did 4e06a19f74c4fed5b583bdb7292b0f1ab11444de make it into M40.1? From the reported line positions above, it doesn't look like `40.1.4` contains the fix.

**Comment by stevemessick** [comment]
I don't have a git log handy (I'm OOO) but IIRC there were two PRs included. One from @devoncarew and one from me. Neither of which appear to be the one in question.

**Comment by devoncarew** [comment]
Ah. My concurrency one was a lower volume issue for users. The NPE in `VMServiceManager.getFlutterViewsList()` was a higher frequency issue from the M40 release.

**Comment by devoncarew** [comment]
Dup of #3925.

**Comment by stevemessick** [comment]
4e06a19 is scheduled for M41,
