### ISSUE TITLE
Bug running app

### ISSUE THREAD

**Issue by rlechetaudemy** [flutter/flutter-intellij#3987]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.5.1` • Flutter plugin `io.flutter 40.1.2` • Dart plugin `191.8423`

Flutter 1.10.15-pre.81 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7ab653c6ca (6 hours ago) • 2019-10-11 07:16:11 -0700
Engine • revision 8dabfb90a1
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 965b8cb1d8)

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.vmService.VMServiceManager.getFlutterViewsList(VMServiceManager.java:662)
	at io.flutter.vmService.VMServiceManager.getFlutterViewId(VMServiceManager.java:647)
	at io.flutter.vmService.VMServiceManager.getDisplayRefreshRate(VMServiceManager.java:607)
	at io.flutter.vmService.VMServiceManager.lambda$onFrameEventReceived$1(VMServiceManager.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
flutter doctor -v
[✓] Flutter (Channel master, v1.10.15-pre.168, on Mac OS X 10.14.6 18G103,
    locale en-BR)
    • Flutter version 1.10.15-pre.168 at /Users/rlecheta/flutter
    • Framework revision 1982a5c3ec (10 hours ago), 2019-10-17 19:47:16 -0700
    • Engine revision 508146f0de
    • Dart version 2.6.0 (build 2.6.0-dev.8.0 f020ce5d23)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rlecheta/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/rlecheta/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • FB7DA44C-589B-4E77-83D7-177023A39C6F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 77.0.3865.120
    • Headless Server   • headless-server                      • web-javascript • Flutter Tools

• No issues found!

**Comment by kenzieschmoll** [comment]
please update your plugin to the latest 40.2 to resolve this issue. Thanks.
