### ISSUE TITLE
Flutter Outline unable to open.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#4007]
## What happened

Tried to open Flutter Outline. Would not open.

## Version information

IntelliJ IDEA `2019.2.3` • Flutter plugin `io.flutter 40.2.4` • Dart plugin `192.6817.14`

Flutter 1.10.11-pre.198 • channel master • git@github.com:kenzieschmoll/flutter.git
Framework • revision 1982a5c3ec (6 days ago) • 2019-10-17 19:47:16 -0700
Engine • revision 508146f0de
Tools • Dart 2.6.0 (build 2.6.0-dev.8.0 f020ce5d23)

## Exception

update failed for ActionGroup: Hide (Hide active tool window)[Hide]

```
java.lang.IllegalThreadStateException: window with id="Flutter Outline" is unknown
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.getRegisteredInfoOrLogError(ToolWindowManagerImpl.java:706)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.isToolWindowVisible(ToolWindowManagerImpl.java:1599)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.isVisible(ToolWindowImpl.java:204)
	at com.intellij.openapi.wm.impl.ToolWindowHeader$HideAction.update(ToolWindowHeader.java:395)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:378)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$null$1(ActionUpdater.java:78)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$2(ActionUpdater.java:79)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:364)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:231)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$19(ActionUpdater.java:215)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1609)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:139)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:131)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupWithTimeout$11(ActionUpdater.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:260)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1113)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:52)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.java:165)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:172)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:87)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:79)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.java:1095)
	at com.intellij.openapi.wm.impl.ToolWindowHeader.setAdditionalTitleActions(ToolWindowHeader.java:276)
	at com.intellij.openapi.wm.impl.InternalDecorator.setTitleActions(InternalDecorator.java:285)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setTitleActions(ToolWindowImpl.java:311)
	at io.flutter.preview.PreviewView.initToolWindow(PreviewView.java:257)
	at io.flutter.preview.PreviewViewFactory.lambda$createToolWindowContent$0(PreviewViewFactory.java:21)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:240)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$7(StartupManagerImpl.java:499)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:323)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:485)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:232)
	at io.flutter.preview.PreviewViewFactory.createToolWindowContent(PreviewViewFactory.java:20)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:533)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:356)
	at com.intellij.ide.actions.ResizeToolWindowAction.<init>(ResizeToolWindowAction.java:45)
	at com.intellij.ide.actions.ResizeToolWindowAction$Left.<init>(ResizeToolWindowAction.java:197)
	at com.intellij.openapi.wm.impl.InternalDecorator.createResizeActionGroup(InternalDecorator.java:431)
	at com.intellij.openapi.wm.impl.InternalDecorator.access$900(InternalDecorator.java:45)
	at com.intellij.openapi.wm.impl.InternalDecorator$GearActionGroup.<init>(InternalDecorator.java:459)
	at com.intellij.openapi.wm.impl.InternalDecorator.createPopupGroup(InternalDecorator.java:382)
	at com.intellij.openapi.wm.impl.InternalDecorator.createPopupGroup(InternalDecorator.java:377)
	at com.intellij.openapi.wm.impl.StripeButton.showPopup(StripeButton.java:303)
	at com.intellij.openapi.wm.impl.StripeButton.access$800(StripeButton.java:35)
	at com.intellij.openapi.wm.impl.StripeButton$MyPopupHandler.invokePopup(StripeButton.java:359)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:40)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6547)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.openapi.wm.impl.StripeButton.processMouseEvent(StripeButton.java:256)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:769)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
That's odd: `window with id="Flutter Outline" is unknown`. Everything's up to date?

If it repros, you may need to run the invalidate caches (from the File menu).

**Comment by kenzieschmoll** [comment]
Everything is up to date. Strange that this happened, but invalidate caches fixed it.
