### ISSUE TITLE
Unknown macro $PROJECT_FILE$

### ISSUE THREAD

**Issue by hoornet** [flutter/flutter-intellij#4046]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

started AS - that's all

## Version information

Android Studio `3.6 Beta 2` • Flutter plugin `io.flutter 41.0.3` • Dart plugin `192.7402`

Error getting Flutter sdk information.

## Exception

```
com.intellij.configurationStore.UnknownMacroException: Unknown macro $PROJECT_FILE$
	at com.intellij.configurationStore.StateStorageManagerImpl.expandMacro(StateStorageManagerImpl.kt:421)
	at com.intellij.configurationStore.ProjectStoreBase.getProjectFilePath(ProjectStoreBase.kt:62)
	at com.intellij.configurationStore.ProjectStoreImpl.getProjectName(ProjectStoreImpl.kt:53)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:270)
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:207)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:83)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:198)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:453)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Steps to Reproduce

I just started the Android Studio...

## Version info

C:\Users\SomeGuy\IdeaProjects\quizzler-flutter>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.449], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\DEV\flutter
    • Framework revision 68587a0916 (7 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\SomeGuy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio 3.6\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio 3.6
    • Flutter plugin version 41.0.3
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[!] Connected device
    ! No devices available

**Comment by devoncarew** [comment]
cc @stevemessick 

We've also received two reports of this exception from our crash reporting system, both for AS 3.6 Beta 2.
