### ISSUE TITLE
stdout output is duplicated when debugging

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter-intellij#406]
In the P5 usability study, all exceptions from the framework got garbled in the console output in IntelliJ. This made them borderline unusable.

The garbled output is also visible in: https://github.com/flutter/flutter/issues/6647

**Comment by pq** [comment]
cc @stevemessick for thoughts

A snippet from  flutter/flutter#6647 that illustrates the log issue:

```
When the exception was thrown, this was the stack:
#2      Text.Text (package:flutter/src/widgets/text.dart:139:12)
I/flutter : #2      Text.Text (package:flutter/src/widgets/text.dart:139:12)
I/flutter : #3      _MyHomePageState.build (/data/user/0/com.yourcompany.flutterSample2/cache/flutter-sample2mfnkhu/lib/main.dart:70:20)
I/flutter : #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2766:23)
I/flutter : #5      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2667:5)
I/flutter : #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:2897:5)
I/flutter : #7      Element.updateChild (package:flutter/src/widgets/framework.dart:1984:15)
I/flutter : #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2778:16)
#3      _MyHomePageState.build (/data/user/0/com.yourcompany.flutterSample2/cache/flutter-sample2mfnkhu/lib/main.dart:70:20)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2766:23)
I/flutter : #9      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2667:5)
I/flutter : #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:3015:5)
I/flutter : #11     Element.updateChild (package:flutter/src/widgets/framework.dart:1984:15)
I/flutter : #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2778:16)
I/flutter : #13     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2667:5)
I/flutter : #14     StatelessElement.update (package:flutter/src/widgets/framework.dart:2816:5)
#5      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2667:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:2897:5)I/flutter : #15     Element.updateChild (package:flutter/src/widgets/framework.dart:1984:15)

```

**Comment by devoncarew** [comment]
I think this is duplicating stdout output - once directly from the application over the service protocol connection, and once from the adb output. I've seen this before, and have a start at a fix.
