### ISSUE TITLE
IllegalStateException: Runner must be specified from RunFlutterAction.actionPerformed(RunFlutterAction.java:93)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4067]
We've seen multiple reports of this, from several Android Studio and IntelliJ versions, but it's not exactly clear how we're getting into this state.

`41.0.4`, `IntelliJ IDEA/2019.2.4`

```
java.lang.IllegalStateException: Runner must be specified
 	at c.i.execution.runners.ExecutionEnvironmentBuilder.build(ExecutionEnvironmentBuilder.java:181)
 	at io.flutter.actions.RunFlutterAction.actionPerformed(RunFlutterAction.java:93)
 	at c.i.o.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
 	at c.i.o.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
 	at c.i.o.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
 	at c.i.o.wm...
```

**Comment by devoncarew** [comment]
We now have a it more info about these types of exceptions:

`42.0.1`, `Android Studio/3.5.3`

```
java.lang.IllegalStateException: Runner must be specified (Run/profile/RunProfileFlutterApp)
  	at io.flutter.actions.RunFlutterAction.actionPerformed(RunFlutterAction.java:102)
  	at c.i.o.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
  	at c.i.o.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
  	at c.i.o.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
  	at c.i.o.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:28
  	...
```

**Comment by jwren** [comment]
Closing out.  Please re-open if this is still reproducible with recent versions of the Flutter IJ plugin.
