### ISSUE TITLE
Android Studio crash after installing emulator image update

### ISSUE THREAD

**Issue by mleonhard** [flutter/flutter-intellij#4112]
## What happened

I installed the recent Android emulator image update, putting it in the background.  Then when it was done, I clicked the install link on the popup, waited for it to install, and clicked Finish.  That's when the crash appeared.

## Version information

Android Studio `3.5.2` • Flutter plugin `io.flutter 41.1.2` • Dart plugin `191.8593`

Flutter 1.10.15-pre.326 • channel master • https://github.com/flutter/flutter.git
Framework • revision dc44c5668d (3 weeks ago) • 2019-10-29 20:41:06 -0400
Engine • revision 46c757be07
Tools • Dart 2.6.0 (build 2.6.0-dev.8.2 0b96f9f9ae)

## Exception

null

```
java.lang.Throwable: Assertion failed: Already disposed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:186)
	at com.intellij.util.Alarm.checkDisposed(Alarm.java:68)
	at com.intellij.util.Alarm._addRequest(Alarm.java:202)
	at com.intellij.util.Alarm.addRequest(Alarm.java:170)
	at io.flutter.utils.AsyncRateLimiter.scheduleRequest(AsyncRateLimiter.java:71)
	at io.flutter.utils.AsyncRateLimiter.lambda$scheduleRequest$0(AsyncRateLimiter.java:58)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:35)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report! This has been addressed in https://github.com/flutter/flutter-intellij/pull/4071; the fix will be available in the next release.
