### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by SPMXithing** [flutter/flutter-intellij#4127]
## What happened

Running the emulator for Android SDK (Pixel API 27)

## Version information

Android Studio `3.5.2` • Flutter plugin `io.flutter 41.1.2` • Dart plugin `191.8593`

Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (10 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

## Exception

null

```
java.lang.Throwable: Assertion failed: Already disposed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:186)
	at com.intellij.util.Alarm.checkDisposed(Alarm.java:68)
	at com.intellij.util.Alarm._addRequest(Alarm.java:202)
	at com.intellij.util.Alarm.addRequest(Alarm.java:170)
	at io.flutter.utils.AsyncRateLimiter.scheduleRequest(AsyncRateLimiter.java:71)
	at io.flutter.utils.AsyncRateLimiter.lambda$scheduleRequest$0(AsyncRateLimiter.java:58)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:35)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevemessick** [comment]
Thanks for the report! This is a dup of #4114, which has been fixed but not released yet.
