### ISSUE TITLE
Update plugin to ignore new events

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter-intellij#413]
As part of addressing, https://github.com/flutter/flutter/issues/6665, I'm adding new events sent by Flutter tools. Unfortunately, once added, when I launch a Flutter app using the Flutter IJ plugin, I'm seeing the following exceptions...
```
[ 105196]  ERROR - r.run.daemon.FlutterAppManager - Unknown flutter event: app.starting from json: {"event":"app.starting","params":{"appId":"9c7c73cf-af29-4020-ad87-3d009ad2a594","deviceId":"4444444444444444","directory":"/path/to/my/flutter/myapp","supportsRestart":true}} 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at io.flutter.run.daemon.FlutterAppManager.eventHandler(FlutterAppManager.java:337)
	at io.flutter.run.daemon.FlutterAppManager.handleEvent(FlutterAppManager.java:203)
	at io.flutter.run.daemon.FlutterAppManager.processInput(FlutterAppManager.java:170)
	at io.flutter.run.daemon.FlutterDaemonService$1.daemonInput(FlutterDaemonService.java:51)
	at io.flutter.run.daemon.FlutterDaemonController.onTextAvailable(FlutterDaemonController.java:167)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$4.invoke(ProcessHandler.java:226)
	at com.sun.proxy.$Proxy14.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:200)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:291)
```

**Comment by danrubel** [comment]
Apparently, even with these exceptions, the Flutter IJ plugin keeps working and debugging works fine... so the exception(s) are just a signal that we need to update the Flutter IJ plugin, not a blocking issue.

**Comment by devoncarew** [comment]
@danrubel, you're naming the event `app.started`?

**Comment by devoncarew** [comment]
What will the fields in the event be?

**Comment by devoncarew** [comment]
Just `appId`, or all the fields from the app.start event?

**Comment by danrubel** [comment]
> @danrubel, you're naming the event app.started?
See description in https://github.com/flutter/flutter/pull/6679 for what's changing

> What will the fields in the event be?
> Just appId, or all the fields from the app.start event?
In https://github.com/flutter/flutter/pull/6679, the `app.started` event just has the `appId`.
That said, I can add params as necessary.

**Comment by devoncarew** [comment]
Hmm, this is pretty visible to users. I get an 'exception happened' dialog, and it lists a stack trace:

```
Unknown flutter event: app.started from json: {"event":"app.started","params":{"appId":"770b7e1a-5c44-40cc-9a2d-cb62ee548caa"}}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at io.flutter.run.daemon.FlutterAppManager.eventHandler(FlutterAppManager.java:337)
	at io.flutter.run.daemon.FlutterAppManager.handleEvent(FlutterAppManager.java:203)
	at io.flutter.run.daemon.FlutterAppManager.processInput(FlutterAppManager.java:170)
```

Users will continue to see this until we rev and publish a new plugin version...

**Comment by pq** [comment]
@devoncarew : should we push out a new build today?

**Comment by devoncarew** [comment]
Yeah! If possible. I outlined a possible way to just push out this single commit; that would be preferable to pushing out all the new changes, but not a critical distinction.

**Comment by samiq** [comment]
for what is worth, I spent about 15min looking around just to see what was wrong with my code until I ended up in this thread from the milestones comments, funny google hasn't indexed this link for a quicker answer.

**Comment by pq** [comment]
Sorry for the inconvenience @samiq!  Left early sick.  We'll get this sorted out first thing Monday.

**Comment by pq** [comment]
https://github.com/flutter/flutter-intellij/pull/420
