### ISSUE TITLE
Error when building and running

### ISSUE THREAD

**Issue by nest-don** [flutter/flutter-intellij#4181]
## What happened

Error when building and running

## Version information

Android Studio `3.5.2` • Flutter plugin `io.flutter 41.1.2` • Dart plugin `191.8593`

Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

## Exception

null

```
java.lang.ClassCastException: javax.swing.JPanel cannot be cast to com.intellij.openapi.wm.impl.IdeGlassPaneEx
	at com.intellij.openapi.ui.impl.GlassPaneDialogWrapperPeer.createDialog(GlassPaneDialogWrapperPeer.java:152)
	at com.intellij.openapi.ui.impl.GlassPaneDialogWrapperPeer.<init>(GlassPaneDialogWrapperPeer.java:131)
	at com.intellij.openapi.progress.util.ProgressDialog$MyDialogWrapper.createPeer(ProgressDialog.java:300)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:304)
	at com.intellij.openapi.progress.util.ProgressDialog$MyDialogWrapper.<init>(ProgressDialog.java:283)
	at com.intellij.openapi.progress.util.ProgressDialog.show(ProgressDialog.java:246)
	at com.intellij.openapi.progress.util.ProgressWindow.showDialog(ProgressWindow.java:235)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$null$1(ProgressWindow.java:168)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:814)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:609)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:454)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:251)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:205)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:450)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:425)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:260)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:94)
	at io.flutter.project.FlutterStudioProjectOpenProcessor.doOpenProject(FlutterStudioProjectOpenProcessor.java:38)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:108)
	at com.android.tools.idea.actions.AndroidOpenFileAction.openOrImportProject(AndroidOpenFileAction.java:165)
	at com.android.tools.idea.actions.AndroidOpenFileAction.doOpenFile(AndroidOpenFileAction.java:135)
	at com.android.tools.idea.actions.AndroidOpenFileAction.lambda$actionPerformed$0(AndroidOpenFileAction.java:97)
	at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:137)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:112)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:90)
	at com.android.tools.idea.actions.AndroidOpenFileAction.actionPerformed(AndroidOpenFileAction.java:87)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:769)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by terrylucas** [comment]
Can you provide a little more information?

- Is this a new project or existing project?
- Did this work in a previous version of either Android Studio or the Flutter plugin (prior to M41)?
- Does it repro in other Flutter project or with a newly created sample Flutter app?
- Would you mind upgrading to M42?  We haven't seen this problem before and I don't expect to see this magically fixed in M42 but I'd be curious if with the latest plugin you're still seeing the problem?

Thank you.

**Comment by terrylucas** [comment]
@stevemessick noticed doOpenProject was added in M39.  Could there be a problem with older projects or another issue?  Awaiting more information from @nest-don.  Change in M39 e.g.,

```
final ProjectOpenProcessor importProvider = getDelegateImportProvider(virtualFile);
    // The superclass may have caused the project to be reloaded. Find the new Project object.
	    if (importProvider == null) return null;

    importProvider.doOpenProject(virtualFile, projectToClose, forceOpenInNewFrame);
    // A callback may have caused the project to be reloaded. Find the new Project object.
    Project project = FlutterUtils.findProject(virtualFile.getPath());
    Project project = FlutterUtils.findProject(virtualFile.getPath());
    if (project != null) {
	    if (project == null || project.isDisposed()) {
```

**Comment by stevemessick** [comment]
@terrylucas I don't think doOpenProject is the problem. I wonder what other plugins are installed?

**Comment by nest-don** [comment]
> @nest-don can you provide a little more information?''
>

I am using Android Studio the version below.

Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 31, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15

> * Is this a new project or existing project?

It's an existing project.  This error was auto generated. 

> * Did this work in a previous version of either Android Studio or the Flutter plugin (prior to M41)?

I only started using Flutter recently. So everything is new.  The version I have is the first one I have used.

> * Does it repro in other Flutter project or with a newly created sample Flutter app?

No.

> * Would you mind upgrading to M42?  We haven't seen this problem before and I don't expect to see this magically fixed in M42 but I'd be curious if with the latest plugin you're still seeing the problem?

I will upgrade Andriod Studio 3.5.2 -> to 3.5.3.  
I will let you know if the problem persists.

> 
> Thank you.

**Comment by terrylucas** [comment]
Do you have any other plugins installed?

**Comment by nest-don** [comment]
I have these plugins installed.
Dart  - v191.8593
Flutter - v42.1.1

**Comment by stevemessick** [comment]
@nest-don Do you see this problem in 3.5.3? This looks like a problem in IntelliJ, and I would expect it to be fixed in the current beta (RC1 today).

**Comment by nest-don** [comment]
> @nest-don Do you see this problem in 3.5.3? This looks like a problem in IntelliJ, and I would expect it to be fixed in the current beta (RC1 today).

Haven't seen it with the new software.  Thanks you for the fixes.
