### ISSUE TITLE
Error compiling on android emulator

### ISSUE THREAD

**Issue by lucalves** [flutter/flutter-intellij#4199]
## What happened

When I was compiling to test on the Android emulator, I presented this error.

## Version information

IntelliJ IDEA `2019.3` • Flutter plugin `io.flutter 42.0.4` • Dart plugin `193.5731`

Error getting Flutter sdk information.

## Exception

null

```
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.flutter.inspector.EvalOnDartLibrary.lambda$timeoutAfter$4(EvalOnDartLibrary.java:182)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException
	... 6 more
```

**Comment by terrylucas** [comment]
Run the command

> flutter doctor

and attach the output.

Also, doe the flutter demos (e.g., flutter_gallery) work?
