### ISSUE TITLE
AssertionError from PropertyEditorPanel.getOffset(PropertyEditorPanel.java:334)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4215]
`42.1.3` / `IntelliJ IDEA/2019.2.4`

```
java.lang.AssertionError
	at io.flutter.editor.PropertyEditorPanel.getOffset(PropertyEditorPanel.java:334)
	at io.flutter.editor.PropertyEditorPanel.updateWidgetDescription(PropertyEditorPanel.java:351)
	at io.flutter.editor.PropertyEditorPanel.maybeLoadProperties(PropertyEditorPanel.java:432)
	at io.flutter.editor.PropertyEditorPanel.outlinesChanged(PropertyEditorPanel.java:407)
	at io.flutter.utils.StreamSubscription.notify(StreamSubscription.java:43)
	at io.flutter.utils.EventStream.lambda$setValue...
```

cc @jacob314

**Comment by devoncarew** [comment]
fixed by #4215
