### ISSUE TITLE
android studio show some new blank window (w/ work-around)

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#4217]
## What happened

I open/create project normal

## Version information

Android Studio `3.5.3` • Flutter plugin `io.flutter 42.1.1` • Dart plugin `191.8593`

Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

## Exception

null

```
java.lang.AssertionError: Already disposed: Project (Disposed) android
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:245)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:236)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:146)
	at com.intellij.openapi.wm.ToolWindowManager.getInstance(ToolWindowManager.java:26)
	at com.intellij.openapi.wm.ToolWindowManager.getActiveId(ToolWindowManager.java:160)
	at com.intellij.openapi.wm.impl.Windows$ToolWindowProvider$1.eventDispatched(Windows.java:120)
	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2432)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2324)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2323)
	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2282)
	at java.awt.Component.dispatchEventImpl(Component.java:4795)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1015)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:639)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4770)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:814)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:210)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:609)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:454)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:251)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:205)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:450)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:425)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:260)
	at io.flutter.project.FlutterProjectCreator.createProject(FlutterProjectCreator.java:190)
	at io.flutter.project.FlutterProjectModel.handleFinished(FlutterProjectModel.java:165)
	at com.android.tools.idea.wizard.model.ModelWizard.handleFinished(ModelWizard.java:402)
	at com.android.tools.idea.wizard.model.ModelWizard.goForward(ModelWizard.java:330)
	at com.android.tools.idea.wizard.model.ModelWizardDialog$FinishAction.doAction(ModelWizardDialog.java:313)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1835)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1077)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
	at io.flutter.actions.FlutterNewProjectAction.actionPerformed(FlutterNewProjectAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
![Screenshot from 2019-12-14 17-16-24](https://user-images.githubusercontent.com/52562340/70847288-7af41b80-1e95-11ea-8904-bb680a24e9fc.png)
it open more 3 blank window when I create new project flutter

**Comment by terrylucas** [comment]
We need a little more information as I'm unable to duplicate.

Platform looks like Linux - right?
Can you attach a flutter doctor output?
What set of plugins are installed (beyond Dart and Flutter)?
What kind of Flutter project were you creating and what options if any you selected?

**Comment by tbm98** [comment]
Yes. I using linux (ubuntu 19.04)
doctor -v 
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/tbm98/Dev/FLUTTER_SDK/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tbm98/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/tbm98/Dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/tbm98/Dev/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/tbm98/Dev/idea-IC-193.5233.102
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] VS Code (version 1.41.0)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```
• Flutter plugin version 42.1.4
• Dart plugin version 193.5731
```
I create project with `use androidx artifacts` `kotlin` and `swift`

this error just appear in android studio 3.5.3 or 3.5.2
I tried to use intelij and android studio 3.4, they work normally

**Comment by Sp4Rx** [comment]
Same issue on windows also. Please provide a way to downgrade till it's fixed. This bug started from the latest version.

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.914], locale en-IN)
    • Flutter version 1.9.1+hotfix.4 at C:\Users\heysu\Documents\flutter
    • Framework revision cc949a8e8b (3 months ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\heysu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\heysu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

![screenshot](https://i.imgur.com/uPJ8kko.jpg)

**Comment by naka-ok** [comment]
This problem may be caused by your AndroidStudio config/system files.

I had exactly the same issue on AndroidStudio 3.5 (Windows).
I tried hard the clean install of Flutter, Android SDK, etc...
Finally, it was solved by the following method.

(1) Export current settings to "settings.zip". (File->Export Settings)
(2) Terminate AndroidStudio.
(3) Rename "C:\Users\xxxx\\.AndroidStudio3.5" to "C:\Users\xxxx\\.AndroidStudio3.5_old".
(4) Run AndroidStudio. (in a clean state)
(5) Import settings from "settings.zip", and re-install your reqired plugins.

Hope this helps you...

**Comment by Sp4Rx** [comment]
The solution by @naka-ok works. Thanks

**Comment by pq** [comment]
Perhaps something to add to known issues?

/cc @devoncarew

**Comment by buzzicards** [comment]
> This problem may be caused by your AndroidStudio config/system files.
> 
> I had exactly the same issue on AndroidStudio 3.5.3 (Windows) and flutter plugin 42.1.1.
> I tried hard the clean install of Flutter, Android SDK, and etc, but could not solve it.
> Finally, it was solved by the following method.
> 
> (1) Export current settings to "settings.zip". (File->Export Settings)
> (2) Terminate AndroidStudio.
> (3) Rename "C:\Users\xxxx\.AndroidStudio3.5" to "C:\Users\xxxx\.AndroidStudio3.5_old".
> (4) Run AndroidStudio. (in a clean state)
> (5) Import settings from "settings.zip", and re-install your reqired plugins.
> 
> Hope this helps you...

I tried this on my mac and its not working...  i go to preference then plugin but nothing shows up in the marketplace... i am new to this can some help... 

Note: when unitall and install 3.0 . was able to find the flutter plugin with no issues. Not sure if there is something wrong with the new android 3.5.3.

Hope to get the need..thanks in advance

**Comment by AlexVincent525** [comment]
> This problem may be caused by your AndroidStudio config/system files.
> 
> I had exactly the same issue on AndroidStudio 3.5.3 (Windows) and flutter plugin 42.1.1.
> I tried hard the clean install of Flutter, Android SDK, and etc, but could not solve it.
> Finally, it was solved by the following method.
> 
> (1) Export current settings to "settings.zip". (File->Export Settings)
> (2) Terminate AndroidStudio.
> (3) Rename "C:\Users\xxxx\.AndroidStudio3.5" to "C:\Users\xxxx\.AndroidStudio3.5_old".
> (4) Run AndroidStudio. (in a clean state)
> (5) Import settings from "settings.zip", and re-install your reqired plugins.
> 
> Hope this helps you...

This solution only works for a short time. After complete reinstallation for android studio, this issue happened again.

**Comment by naka-ok** [comment]
> This solution only works for a short time. After complete reinstallation for android studio, this issue happened again.

It's scary.

In my case, this problem occurred immediately after upgrading the "flutter-intellij plugin"
from ver.41.1.2 to 42.1.1.

For now, maybe we have to go back to the previous version...
https://plugins.jetbrains.com/plugin/9212-flutter/versions

**Comment by AlexVincent525** [comment]
> It's scary.
Yep. The only thing I can do is throw them in a separate virtual window. 😨

**Comment by AlexVincent525** [comment]
The blank window is running with gradle build.
![image](https://user-images.githubusercontent.com/15884415/71463963-04d7a900-27f3-11ea-8c0d-980f27295cb5.png)

**Comment by stevemessick** [comment]
@tbm98 @Sp4Rx @naka-ok @AlexVincent525 

What kind of Flutter project did you create? (app, module, etc)
Does Gradle run because you're running (or building) your app or is it automatically sync'ing?
Are you using add-to-app features?
Have you set the Flutter preference named "Enable code completion, navigation, etc. for Java / Kotlin"?

**Comment by AlexVincent525** [comment]
> Have you set the Flutter preference named "Enable code completion, navigation, etc. for Java / Kotlin"?

You remind me with this option, after enabled it, the blank window appeared. And disable it makes it work properly.
