### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/project/ProjectImportUtil

### ISSUE THREAD

**Issue by praharshbhatt** [flutter/flutter-intellij#4223]
## What happened

I Clicked "Open for Editing in Android Studio" when the following error occurred. This only started happening after the latest Flutter plugin update.

## Version information

Android Studio `3.5.3` • Flutter plugin `io.flutter 42.1.1` • Dart plugin `191.8593`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/project/ProjectImportUtil
	at io.flutter.actions.OpenAndroidModule.canImportAsGradleProject(OpenAndroidModule.java:100)
	at io.flutter.actions.OpenAndroidModule.openOrImportProject(OpenAndroidModule.java:60)
	at io.flutter.actions.OpenAndroidModule.actionPerformed(OpenAndroidModule.java:52)
	at io.flutter.actions.OpenInAndroidStudioAction.actionPerformed(OpenInAndroidStudioAction.java:49)
	at io.flutter.editor.NativeEditorNotificationProvider$NativeEditorActionsPanel.performAction(NativeEditorNotificationProvider.java:138)
	at com.intellij.ui.EditorNotificationPanel$1.hyperlinkActivated(EditorNotificationPanel.java:127)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:222)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:145)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:702)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.android.tools.idea.gradle.project.ProjectImportUtil PluginClassLoader[io.flutter, 42.1.1] com.intellij.ide.plugins.cl.PluginClassLoader@108d3b39
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
```

**Comment by devoncarew** [comment]
@stevemessick - are you aware of this issue? We've seen multiple reports of this from Android Studio 3.5.3 users.

**Comment by stevemessick** [comment]
I can't reproduce this issue. It looks like an out dated version of the android plugin is being used by IntelliJ. The missing class is present in my android.jar file for 3.5.3 (the class file is dated Nov 15).

@praharshbhatt check your IntelliJ installation to ensure the correct android plugin is being used. Let us know if that helps.

**Comment by stevemessick** [comment]
This is a dup of https://github.com/flutter/flutter-intellij/issues/4233

**Comment by SushantSinghRajput03** [comment]
Android Studio 4.1.1 • Flutter plugin io.flutter 52.2.2 • Dart plugin 201.9317

```
java.lang.NoClassDefFoundError: com/android/tools/idea/gradle/project/ProjectImportUtil
	at io.flutter.actions.OpenAndroidModule.canImportAsGradleProject(OpenAndroidModule.java:100)
	at io.flutter.actions.OpenAndroidModule.openOrImportProject(OpenAndroidModule.java:60)
	at io.flutter.actions.OpenAndroidModule.actionPerformed(OpenAndroidModule.java:52)
	at io.flutter.actions.OpenInAndroidStudioAction.actionPerformed(OpenInAndroidStudioAction.java:57)
	at io.flutter.editor.NativeEditorNotificationProvider$NativeEditorActionsPanel.performAction(NativeEditorNotificationProvider.java:140)
	at com.intellij.ui.EditorNotificationPanel$1.handlePanelActionClick(EditorNotificationPanel.java:238)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel$1.hyperlinkActivated(EditorNotificationPanel.java:284)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:11)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:225)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:148)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



```
