### ISSUE TITLE
Working in Android Studio Flutter Plugin

### ISSUE THREAD

**Issue by Sun3** [flutter/flutter-intellij#4245]
---

## What happened

I was working in Android Studio while working on a Flutter Plugin and received this error.

## Version information

Android Studio `3.5.3` • Flutter plugin `io.flutter 42.1.1` • Dart plugin `191.8593`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: example/lib/main.dart:emulator-5554 has already been disposed (see the cause for stacktrace) so the child: com.intellij.util.Alarm@5a43b2e0 will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:79)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.util.Alarm.<init>(Alarm.java:137)
	at io.flutter.utils.AsyncRateLimiter.<init>(AsyncRateLimiter.java:48)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:177)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:147)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:302)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:241)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:381)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:346)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:35)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevemessick** [comment]
Dup of #4214

**Comment by pq** [comment]
Related to the legacy inspector; closing as stale.
