### ISSUE TITLE
NPE from platform code when called by FlutterConsole.bringToFront(FlutterConsole.java:105)

### ISSUE THREAD

**Issue by surapuramakhil** [flutter/flutter-intellij#4336]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

error on getting flutter dart packages

## Version information

Android Studio `3.5.3` • Flutter plugin `io.flutter 42.1.1` • Dart plugin `191.8593`

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (6 months ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.openapi.wm.impl.ToolWindowsPane.createRemoveDecoratorCmd(ToolWindowsPane.java:286)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.appendRemoveDecoratorCmd(ToolWindowManagerImpl.java:1614)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.java:923)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showAndActivate(ToolWindowManagerImpl.java:613)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindowImpl(ToolWindowManagerImpl.java:661)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow(ToolWindowManagerImpl.java:634)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.activate(ToolWindowImpl.java:132)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.activate(ToolWindowImpl.java:122)
	at io.flutter.console.FlutterConsole.bringToFront(FlutterConsole.java:105)
	at io.flutter.console.FlutterConsoles.lambda$null$0(FlutterConsoles.java:45)
	at com.intellij.ui.content.impl.MessageViewImpl.runWhenInitialized(MessageViewImpl.java:53)
	at io.flutter.console.FlutterConsoles.lambda$displayProcessLater$1(FlutterConsoles.java:42)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
Thanks for the report!

**Comment by devoncarew** [comment]
From an initial look, this looks like an NPE from platform code when called by FlutterConsole.bringToFront(FlutterConsole.java:105) (perhaps while running the flutter package get command).

**Comment by stevemessick** [comment]
I'm closing this one as obsolete. The ToolWindowsPane class has had dozens of edits since the version in AS 3.5.3. Our usage of the API is correct.
