### ISSUE TITLE
 Unknown macro $PROJECT_FILE$

### ISSUE THREAD

**Issue by darrellpf** [flutter/flutter-intellij#4350]
## What happened

Updated the plugin to latest version. Restarted immediately. The bug appears on startup of the project.

Closed and restarted Android studio in case it was a one-time only problem from the update. The bug happened again.

## Version information

Android Studio `3.6 RC 2` • Flutter plugin `io.flutter 43.0.2` • Dart plugin `192.7761`

Flutter 1.14.4 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 5e1000cd85 (9 days ago) • 2020-01-23 13:27:01 -0800
Engine • revision 83a64b7233
Tools • Dart 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)

## Exception

null

```
com.intellij.configurationStore.UnknownMacroException: Unknown macro $PROJECT_FILE$
	at com.intellij.configurationStore.StateStorageManagerImpl.expandMacro(StateStorageManagerImpl.kt:421)
	at com.intellij.configurationStore.ProjectStoreBase.getProjectFilePath(ProjectStoreBase.kt:62)
	at com.intellij.configurationStore.ProjectStoreImpl.getProjectName(ProjectStoreImpl.kt:53)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:270)
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:213)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:89)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:204)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$7(DumbServiceImpl.java:453)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mtracdemo** [comment]
Thanks Steve for letting me know. 

It would be a great help if you can let me know how to revert back to Flutter Plugin version 43.0.1 .
Kamal

**Comment by stevemessick** [comment]
@mtracdemo Something changed in Android Studio 3.6 RC. 2 that causes this problem. You'd have to switch to 3.5 (stable) to eliminate the error message.

**Comment by stevemessick** [comment]
Hey all, good news: this problem does not occur if you switch to Android Studio 4.0 Canary 9. You may not be able to make that switch, I understand, but it is nice to know that the problem is fixable. We still have to fix the problem for 3.6, of course.

**Comment by stevemessick** [comment]
Note to self: `$PROJECT_FILE$` is defined in `ProjectStoreBase.setPath()` in 3.5 and 4.0. It must be done elsewhere in 3.6. We call `setPath` when preparing for a Gradle sync.

**Comment by mtracdemo** [comment]
Thanks Steve👍
