### ISSUE TITLE
Crash after stopping debugger soon after app was launched on emulator

### ISSUE THREAD

**Issue by ak2766** [flutter/flutter-intellij#4353]
## What happened

I simply clicked the green run button, gradle built the app, and it was subsequently deployed to
emulator.  I then terminated the run - maybe too soon.

However, what did not happen is that the app was left running on the emulator - it never got the
kill signal.

## Version information

Android Studio `3.5.3` • Flutter plugin `io.flutter 43.0.1` • Dart plugin `191.8593`

Flutter 1.14.7-pre.83 • channel master • git@github.com:flutter/flutter
Framework • revision e10df3c1a6 (2 days ago) • 2020-02-01 11:23:01 +0800
Engine • revision e625e174c5
Tools • Dart 2.8.0 (build 2.8.0-dev.6.0 5ae5aff640)

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: main.dart:emulator-5554 has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.actionSystem.AnAction$$Lambda$491/827383690@3137a70a will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:79)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:155)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:141)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.registerActionOnComponent(DebuggerUIUtil.java:413)
	at io.flutter.inspector.InspectorTree.registerShortcuts(InspectorTree.java:108)
	at io.flutter.inspector.InspectorTree.<init>(InspectorTree.java:97)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:185)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:148)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:301)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:241)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:380)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:345)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by terrylucas** [comment]
Duplicate https://github.com/flutter/flutter-intellij/issues/4214
