### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by passovich** [flutter/flutter-intellij#4362]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened
i was exited emulator
(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.5.3` • Flutter plugin `io.flutter 43.0.1` • Dart plugin `191.8593`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: main.dart:emulator-5554 has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.actionSystem.AnAction$$Lambda$578/1088757984@2b4e6711 will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:79)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:155)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:141)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.registerActionOnComponent(DebuggerUIUtil.java:413)
	at io.flutter.inspector.InspectorTree.registerShortcuts(InspectorTree.java:108)
	at io.flutter.inspector.InspectorTree.<init>(InspectorTree.java:97)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:185)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:148)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:301)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:241)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:380)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:345)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by terrylucas** [comment]
Duplicate https://github.com/flutter/flutter-intellij/issues/4214
