### ISSUE TITLE
Flutter plugin caused IDE freeze

### ISSUE THREAD

**Issue by markathomas** [flutter/flutter-intellij#4369]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2020.1 EAP` • Flutter plugin `io.flutter 43.0.4` • Dart plugin `201.4865.19`

No Flutter sdk configured.

## Exception

Freeze in EDT for 50 seconds
IDE KILLED! Sampled time: 42300ms, sampling rate: 100ms, GC time: 0ms (0%), Class loading: 0%, load average: 5.16

```
com.intellij.diagnostic.Freeze
	at java.base@11.0.6/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.6/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
	at java.base@11.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at java.base@11.0.6/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
	at java.base@11.0.6/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
	at io.flutter.vmService.DisplayRefreshRateManager.getDisplayRefreshRate(DisplayRefreshRateManager.java:87)
	at io.flutter.vmService.DisplayRefreshRateManager.lambda$queryRefreshRate$0(DisplayRefreshRateManager.java:41)
	at io.flutter.vmService.DisplayRefreshRateManager$$Lambda$6421/0x00000001035f3040.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:192)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:467)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:443)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:420)
	at java.desktop@11.0.6/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.6/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop@11.0.6/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.6/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.6/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.6/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.6/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
	at com.intellij.ide.IdeEventQueue$$Lambda$749/0x0000000100a83040.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:713)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
	at java.desktop@11.0.6/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.6/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.6/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.6/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.6/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.6/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by devoncarew** [comment]
We may want to switch from calling `CompletableFuture.join()` here to one of the async calls (`whenComplete`?); I believe that join() will block the thread until a value is received.

cc @kenzieschmoll

**Comment by kenzieschmoll** [comment]
@markathomas what version of flutter are you on?
