### ISSUE TITLE
Error getting Flutter sdk information.

### ISSUE THREAD

**Issue by rayk** [flutter/flutter-intellij#4456]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

```Flutter Pub Get```

## Version info

[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.4 19E266, locale en-AU)
    • Flutter version 1.15.17 at /Users/rayk/devlibs/flutter
    • Framework revision 2294d75bfa (4 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/rayk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/rayk/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6308749/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/rayk/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6308749/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Users/rayk/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Pixel 3 XL • 8A7Y0FKF5  • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
---

## What happened

Executing flutter pub get

## Version information

IntelliJ IDEA `2019.3.4` • Flutter plugin `io.flutter 44.0.3` • Dart plugin `193.6911.31`

Error getting Flutter sdk information.

## Exception

During querying provider Run line marker (class com.intellij.execution.lineMarker.RunLineMarkerProvider)

```
java.lang.NullPointerException
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.populateTestTypeMap(CommonTestConfigUtils.java:196)
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.populateTestTypeMap(CommonTestConfigUtils.java:210)
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.populateTestTypeMap(CommonTestConfigUtils.java:210)
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.populateTestTypeMap(CommonTestConfigUtils.java:210)
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.populateTestTypeMap(CommonTestConfigUtils.java:210)
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.<init>(CommonTestConfigUtils.java:182)
	at io.flutter.run.common.CommonTestConfigUtils$OutlineCache.<init>(CommonTestConfigUtils.java:175)
	at io.flutter.run.common.CommonTestConfigUtils.getTestsFromOutline(CommonTestConfigUtils.java:101)
	at io.flutter.run.common.CommonTestConfigUtils.findNamedTestCall(CommonTestConfigUtils.java:111)
	at io.flutter.run.common.CommonTestConfigUtils.asTestCall(CommonTestConfigUtils.java:58)
	at io.flutter.run.test.TestConfigUtils.asTestCall(TestConfigUtils.java:38)
	at io.flutter.run.common.TestLineMarkerContributor.getInfo(TestLineMarkerContributor.java:62)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:60)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:170)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:95)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:90)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by devoncarew** [comment]
Thanks for the report! I believe this may have been fixed by #4437.
