### ISSUE TITLE
IndexOutOfBoundsException from DartDocumentUtils.getDartdocFor(DartDocumentUtils.java:31)

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4532]
```
2020-05-02 20:21:55,101 [185297249]  ERROR - rains.concurrency.AsyncPromise - Wrong offset: 76510. Should be in range: [0, 76284] 
java.lang.IndexOutOfBoundsException: Wrong offset: 76510. Should be in range: [0, 76284]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:178)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:983)
	at io.flutter.samples.DartDocumentUtils.getDartdocFor(DartDocumentUtils.java:31)
	at io.flutter.samples.FlutterSampleNotificationProvider.getSamplesFromDoc(FlutterSampleNotificationProvider.java:110)
	at io.flutter.samples.FlutterSampleNotificationProvider.lambda$createNotificationPanel$0(FlutterSampleNotificationProvider.java:83)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:880)
	at io.flutter.samples.FlutterSampleNotificationProvider.createNotificationPanel(FlutterSampleNotificationProvider.java:81)
	at io.flutter.samples.FlutterSampleNotificationProvider.createNotificationPanel(FlutterSampleNotificationProvider.java:34)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:167)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$2(EditorNotificationsImpl.java:149)
...
```

**Comment by jwren** [comment]
Closing as a duplicate of https://github.com/flutter/flutter-intellij/issues/5634
