### ISSUE TITLE
NPE from FlutterModuleUtils.hasInternalDartSdkPath()

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4578]
We're seeing this from crash reporting:

```
java.lang.NullPointerException
	at io.flutter.utils.FlutterModuleUtils.hasInternalDartSdkPath(FlutterModuleUtils.java:102)
	at io.flutter.actions.DeviceSelectorRefresherAction.update(DeviceSelectorRefresherAction.java:32)
	at c.i.o.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:177)
	at c.i.o.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:453)
	at c.i.o.actionSystem.impl.ActionUpdater.lambda$null$1(ActionUpdater.java:93)
	at c.i.o.actionSystem.impl.ActionUpdater.callAction(Ac
```

**Comment by devoncarew** [comment]
@stevemessick - is this addressed by https://github.com/flutter/flutter-intellij/pull/4557 ?

**Comment by stevemessick** [comment]
No.

**Comment by stevemessick** [comment]
@helin24 Looks like we both missed another null check. Can you add it? We should get this into the release I'm working on now.

**Comment by devoncarew** [comment]
The good news here is that this was found in the dev channel - definitely a good way to flush out issues before they hit stable.
