### ISSUE TITLE
java.lang.RuntimeException: Sentinel calling getObject

### ISSUE THREAD

**Issue by SAGARSURI** [flutter/flutter-intellij#4596]
I got the following exception:

```java.util.concurrent.CompletionException: java.lang.RuntimeException: Sentinel calling getObject: org.dartlang.vm.service.element.Sentinel@42df8084
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.flutter.inspector.EvalOnDartLibrary.lambda$null$0(EvalOnDartLibrary.java:97)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.RuntimeException: Sentinel calling getObject: org.dartlang.vm.service.element.Sentinel@42df8084
	at io.flutter.inspector.EvalOnDartLibrary$3.received(EvalOnDartLibrary.java:236)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:788)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:630)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:437)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

```
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.2 at /Users/sagarsuri/development/flutter
    • Framework revision 5f21edf8b6 (5 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sagarsuri/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • ASUS ZS620KL • J7AAGF06H076S89 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories
```

**Comment by helin24** [comment]
Could you provide more details on what program you are running (Android studio?) and what you were doing when you got this error?

In the doctor output it looks like you don't have the Dart and Flutter plugins installed, so that may be causing problems. Did you already follow the instructions for installing the plugins here? https://flutter.dev/docs/get-started/editor?tab=androidstudio

**Comment by devoncarew** [comment]
@helin24 - for the issue w/ the plugins not looking like they're installed; IntelliJ changed where they install plugins, and the flutter cli tool hasn't yet been updated to check this location for 2020.1; https://github.com/flutter/flutter/issues/57753.

**Comment by helin24** [comment]
Ah thanks @devoncarew! I'm going to mark this as a bug as @jacob314 suggests we could be handling sentinel issues more gracefully. It may help to have some examples of when this occurs, do we know of any particular situations?
