### ISSUE TITLE
IntelliJ IDEA `2019.2.4` • Flutter plugin `io.flutter 44.0.2` • Dart plugin `192.7761`  Error getting Flutter sdk information.

### ISSUE THREAD

**Issue by kim03567** [flutter/flutter-intellij#4611]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2019.2.4` • Flutter plugin `io.flutter 44.0.2` • Dart plugin `192.7761`

Error getting Flutter sdk information.

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: Sentinel calling getObject: org.dartlang.vm.service.element.Sentinel@4e671b07
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.flutter.inspector.EvalOnDartLibrary.lambda$null$0(EvalOnDartLibrary.java:97)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.RuntimeException: Sentinel calling getObject: org.dartlang.vm.service.element.Sentinel@4e671b07
	at io.flutter.inspector.EvalOnDartLibrary$3.received(EvalOnDartLibrary.java:236)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:788)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:630)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:437)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by stevemessick** [comment]
This is a dup of #4596 and can be closed.

I'm curious why we're seeing these pop up now? Both these users have out-dated installations.
