### ISSUE TITLE
Issue running app

### ISSUE THREAD

**Issue by ahtesham007** [flutter/flutter-intellij#4626]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
## What happened

I was using gennymotion as virtual device.

## Version information

Android Studio `3.6.3` • Flutter plugin `io.flutter 45.1.1` • Dart plugin `192.7761`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: main.dart:192.168.55.101:5555 has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.actionSystem.AnAction$$Lambda$530/23248301@13fecbf9 will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:61)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:92)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:158)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:144)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.registerActionOnComponent(DebuggerUIUtil.java:415)
	at io.flutter.inspector.InspectorTree.registerShortcuts(InspectorTree.java:108)
	at io.flutter.inspector.InspectorTree.<init>(InspectorTree.java:97)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:185)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:148)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:299)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:239)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:378)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:343)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

C:\Users\James007>flutter doctor -v
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.10240], locale en-US)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (6 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\James007\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by pq** [comment]
Duplicate of #4372?

**Comment by jacob314** [comment]
It does look like a duplicate.
