### ISSUE TITLE
null exception on IntelliJ IDEA

### ISSUE THREAD

**Issue by ali-vafainia** [flutter/flutter-intellij#4705]
## Steps to Reproduce

testing web version of flutter app

## Version information

IntelliJ IDEA `2018.2.2` • Flutter plugin `io.flutter 31.3.2` • Dart plugin `182.4129.13`

Flutter 1.19.0-4.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8fe7655ed2 (2 weeks ago) • 2020-07-01 14:31:18 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)

## Exception

null

```
java.lang.Throwable: java.util.concurrent.CompletionException: java.io.IOException: error from app.callServiceExtension: "ext.flutter.inspector.getRootWidgetSummaryTree: (-32000) Service connection disposed"
""
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at io.flutter.view.InspectorPanel.lambda$recomputeTreeRoot$5(InspectorPanel.java:575)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$69(InspectorService.java:872)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by helin24** [comment]
Can you describe more what you were doing when this occurred and what happened? It sounds like you ran your application on web; did the run succeed? Were there other visible consequences of this error?

And finally, is this happening consistently?

**Comment by ali-vafainia** [comment]
running application on web server made this error but running on browser was successful

**Comment by helin24** [comment]
Just to clarify, you mean that your application ran successfully when you chose the 'Chrome' option but was not successful when you chose the 'Web server' option?

I'm noticing that your Flutter version is pretty new while your IntelliJ IDEA version and associated plugins are old. It's possible this would be fixed if you used a 2020 version of IntelliJ or reverted to an older version of Flutter.

**Comment by devoncarew** [comment]
To chime in on what @helin24 said, the current flutter plugin version is v48, and I see you're on v31. We release monthly, so v31 is about a year and a half out of date. I'd upgrade to a more recent version of IntelliJ - that should select a newer version of the Flutter plugin.

**Comment by ali-vafainia** [comment]
@helin24 , @devoncarew 
I updated IntlliJ  to versin 2020 and now I can run my app on webserver
