### ISSUE TITLE
Flutter plugin crashed and Create flutter project is missing

### ISSUE THREAD

**Issue by krupalbhardiya** [flutter/flutter-intellij#4725]
## Steps to Reproduce

1. Also create new Flutter project option from the Android Studio is missing now after installing Jetbrains Edutools plugin (https://plugins.jetbrains.com/plugin/10081-edutools/). 
Even after uninstalling Edutools plugin, Flutter plugin and Dart plugin, then completely uninstalling Android Studio, removing user settings directories and then complete fresh install of Android studio, Dart plugin and Flutter plugin, the option of creating new Flutter project is missing.
 
2. Flutter plugin crashed after opening Android module of existing Flutter project from re-installed Android Studio.

## Version info

Android Studio `4.0.1` • Flutter plugin `io.flutter 47.1.2` • Dart plugin `193.7361`

[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.17.5 at D:\flutter_sdk
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\android_sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Z50 • Z50418LA633363 • android-arm • Android 8.1.0 (API 27)

## Exception

null

```
com.intellij.diagnostic.PluginException: io.flutter.actions.FlutterNewProjectAction (flutter.NewProject.welcome): group with id "WelcomeScreen.QuickStart.IDEA" isn't registered; action will be added to the "Other" group [Plugin: io.flutter]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:382)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:377)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getParentGroup(ActionManagerImpl.java:882)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processAddToGroupNode(ActionManagerImpl.java:848)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionElement(ActionManagerImpl.java:625)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.processActionsChildElement(ActionManagerImpl.java:1018)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerPluginActions(ActionManagerImpl.java:491)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:143)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:18)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:29)
	at com.intellij.openapi.actionSystem.ex.ActionManagerEx.getInstanceEx(ActionManagerEx.java:17)
	at com.intellij.tools.ToolManager.<init>(ToolManager.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl$preloadServices$future$1.run(PlatformComponentManagerImpl.kt:622)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

![Screenshot (15)](https://user-images.githubusercontent.com/6060333/88796987-39b04200-d1c0-11ea-9882-d46a88d2afae.png)

**Comment by stevemessick** [comment]
I believe this is being tracked as https://youtrack.jetbrains.com/issue/EDU-2884.

Shut down Android Studio then make a copy of the `.idea` directory in your project. Delete `.idea` the restart Android Studio.

The complete list of directories that need to be deleted is here: https://www.jetbrains.com/help/idea/uninstall.html.

Let us know if that solves your problem.

**Comment by krupalbhardiya** [comment]
> 
> 
> I believe this is being tracked as https://youtrack.jetbrains.com/issue/EDU-2884.
> 
> Shut down Android Studio then make a copy of the `.idea` directory in your project. Delete `.idea` the restart Android Studio.
> 
> The complete list of directories that need to be deleted is here: https://www.jetbrains.com/help/idea/uninstall.html.
> 
> Let us know if that solves your problem.

This issue is different than what I am facing (https://youtrack.jetbrains.com/issue/EDU-2884).

Earlier I used to have the option of creating new flutter project from the App Homepage.

![1 oE6c-qulHky1v2v-cCXtwQ](https://user-images.githubusercontent.com/6060333/89495479-fc5a3e80-d7d5-11ea-9b7c-7044a4957905.png)

But now it is missing. I have deleted all data directories and removed android studio and installed the fresh copy of Android studio with latest Dart and Flutter plugin. But still the option is missing now.

Is it removed in the new plugin of flutter for all or is it the problem that i am facing now(I have been seeing this behavior after I installed Edutools plugin from Jetbrains and removed it).

**Comment by jacob314** [comment]
Fyi @stevemessick any other ideas?

**Comment by krupalbhardiya** [comment]
My platform details:

[✓] Flutter (Channel master, 1.22.0-10.0.pre.9, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.9 at D:\flutter_sdk
    • Framework revision 8fa5c55e54 (3 weeks ago), 2020-08-30 19:05:20 -0700
    • Engine revision 1e302a111d
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\android_sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.49.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.14.1

[!] Connected device
    ! No devices available


Here is the list of steps i have tried so far for different systems I have available 
1- Windows system
 - Uninstalled the active Android Studio 4.0
 - Removed the Android Studio configuration directories(All Android Studio config directories)
 (C:/Users/[Username]/.AndroidStudio4.0)
- Installed fresh copy of Android Studio.
- Installed the Flutter and Dart plugins
- Restarted Computer

2 - Mac system (In this system the option to create Flutter project from outside was available, but it went missing after I updated the Android Studio and Flutter and Dart plugins)
- Updated Android Studio from 3.6 to 4.0.1
- Updated Flutter and Dart (and some more outdated) plugins to the latest version till today and restarted Android Studio
now the option went missing after updating the plugins. So I performed all the steps again of uninstalling and reinstalling of Android Studio and deleting the config folder.

I have two separate systems on both of them i have performed these steps and still facing the same issue. 

![](https://user-images.githubusercontent.com/6060333/89495479-fc5a3e80-d7d5-11ea-9b7c-7044a4957905.png)

**Comment by stevemessick** [comment]
I did some investigation into what EduTools does with the Welcome screen. It can potentially add a several items, depending on which language support is available. I don't know how that gets persisted, but I think that is what is causing your problem. Somehow, the action group with id "WelcomeScreen.QuickStart.IDEA" got removed or renamed. I suggest checking with JetBrains at youtrack.jetbrains.com.

There is a rather awkward work-around. You could create an Android Studio project to get started. Once it is open you should be able to use `File > New > New Flutter Project` to create a new Flutter project. Of course, you can also run the Flutter tool from the command line then use `Open an existing Android Studio project` to open it from the Welcome screen.

**Comment by krupalbhardiya** [comment]
> 
> 
> I did some investigation into what EduTools does with the Welcome screen. It can potentially add a several items, depending on which language support is available. I don't know how that gets persisted, but I think that is what is causing your problem. Somehow, the action group with id "WelcomeScreen.QuickStart.IDEA" got removed or renamed. I suggest checking with JetBrains at youtrack.jetbrains.com.
> 
> There is a rather awkward work-around. You could create an Android Studio project to get started. Once it is open you should be able to use `File > New > New Flutter Project` to create a new Flutter project. Of course, you can also run the Flutter tool from the command line then use `Open an existing Android Studio project` to open it from the Welcome screen.

I am already using that awkward work-around. 

But there is still one point coming to my observation.
- In my Windows system, I had installed the EduTools plugins and after that I had upgraded Android Studio and Flutter/Dart plugins. Then after the option went missing, so i removed the Edutools, did clean installation of Android Studio with latest Flutter/Dart plugins (and did not install the Edutools), but still the problem persisted. So I can assume that there might still be a problem caused by edutools and still persist.

But on the other hand, in my Mac system, I have never installed the Edutools plugins. Create Flutter Project on welcome screen was there and then I upgraded Android Studio and Flutter/Dart plugins. After that the Create Flutter Project option on welcome screen went missing. So in this scenario, I dont think Edutools has created problem in the Mac system. Still I will raise issue there as well.

I will check out the issue in Virtual Machine in Linux and Windows as well, if it exists then i think problem might not be from the Edutools plugin but rather from Flutter/Dart plugin or Android Studio or IntelliJ side.

**Comment by krupalbhardiya** [comment]
Found the solution for the problem. After uninstalling the Android Studio, I had to remove the config directories
- .AndroidStudio[version] and
- .android

I had been removing the AndroidStudio directory only. After deleting .android directory only, the problem got fixed for me.

**Comment by stevemessick** [comment]
Thanks for the update!
