### ISSUE TITLE
Project system initialization issue

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4753]
It looks like the Flutter project system is getting initialized more than once. Running with canary 7 sources in the debugger.

```
2020-08-10 09:07:11,351 [  11282]   WARN - ectsystem.ProjectSystemService - FlutterProjectSystem project system has been detected 
java.lang.Throwable
	at com.android.tools.idea.projectsystem.ProjectSystemService.getProjectSystem(ProjectSystemService.kt:53)
	at com.android.tools.idea.projectsystem.ProjectSystemUtil.getProjectSystem(AndroidProjectSystem.kt:100)
	at com.android.tools.idea.gradle.run.MakeBeforeRunTaskProvider.configurationTypeIsSupported(MakeBeforeRunTaskProvider.java:191)
	at com.android.tools.idea.gradle.run.MakeBeforeRunTaskProvider.createTask(MakeBeforeRunTaskProvider.java:173)
	at com.android.tools.idea.gradle.run.MakeBeforeRunTaskProvider.createTask(MakeBeforeRunTaskProvider.java:119)
	at com.intellij.execution.impl.BeforeRunTaskHelperKt.getHardcodedBeforeRunTasks(BeforeRunTaskHelper.kt:36)
	at com.intellij.execution.impl.RunManagerImpl.createTemplateSettings$intellij_platform_execution_impl(RunManagerImpl.kt:330)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:316)
	at com.intellij.execution.impl.RunManagerImpl.readBeforeRunTasks$intellij_platform_execution_impl(RunManagerImpl.kt:970)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:248)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:65)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:48)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:22)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:65)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:175)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:216)
	at com.intellij.execution.impl.RunManagerImpl.loadSharedRunConfigurations(RunManagerImpl.kt:789)
	at com.intellij.execution.impl.RunManagerImpl.noStateLoaded(RunManagerImpl.kt:697)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:453)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:138)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:103)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:50)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:358)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:58)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:188)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer.serviceCreated(ProjectRunConfigurationInitializer.kt:28)
```

**Comment by stevemessick** [comment]
Not sure why they are logging this, but it is only initialized once.
