### ISSUE TITLE
Can't load Kernel binary after flutter upgrade

### ISSUE THREAD

**Issue by bobspeck** [flutter/flutter-intellij#4774]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Ran flutter upgrade

## Version information

Android Studio `3.4.1` • Flutter plugin `io.flutter 36.1.1` • Dart plugin `183.6270`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Flutter device daemon #1: process exited during startup. Exit code: 253, stderr:
Can't load Kernel binary: Invalid kernel binary format version.

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at io.flutter.run.daemon.DeviceDaemon$Command.start(DeviceDaemon.java:248)
	at io.flutter.run.daemon.DeviceService.chooseNextDaemon(DeviceService.java:224)
	at io.flutter.utils.Refreshable.runInBackground(Refreshable.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stevemessick** [comment]
@bobspeck Your version of the Flutter plugin is so old it cannot be used with the latest Flutter SDK. You'll need to either downgrade your SDK or switch to Android Studio 4.0.1. Let us know if that helps.

**Comment by bobspeck** [comment]
Hi Steve,
I upgraded Studio to 4.0.1 and then did a fresh install of Flutter (at this
point flutter would not launch to upgrade).  This has corrected my issues.

thank you for the support.

Bob Speck

**Comment by stevemessick** [comment]
Thanks for the quick reply @bobspeck!
