### ISSUE TITLE
DevTools is not working on Windows

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#4803]
## What happened

Attempted to start embedded DevTools on Windows.

## Version information

Android Studio `4.0.1` • Flutter plugin `io.flutter 49.0.2` • Dart plugin `193.7547`

Error getting Flutter sdk information.

## Exception

null

```
com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException: The current HARDWARE_ACCELERATED rendering mode is not supported
   at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.checkRenderingMode(BrowserSettingsImpl.java:370)
   at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.setTransparentBackgroundEnabled(BrowserSettingsImpl.java:358)
   at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.enableTransparentBackground(BrowserSettingsImpl.java:341)
   at io.flutter.jxbrowser.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:30)
   at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:402)
   at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
   at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
   at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
   at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
   at java.awt.EventQueue.access$500(EventQueue.java:98)
   at java.awt.EventQueue$3.run(EventQueue.java:715)
   at java.awt.EventQueue$3.run(EventQueue.java:709)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
   at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
   at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
   at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
   at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
   at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
   at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by KlausJokinen** [comment]
Same issue: IntelliJ IDEA `2020.2.1` • Flutter plugin `io.flutter 49.0.4` • Dart plugin `202.7206`
