### ISSUE TITLE
java.lang.IllegalStateException: Expected current state is DISPOSE_IN_PROGRESS, but actual state is ACTIVE

### ISSUE THREAD

**Issue by igorakkerman** [flutter/flutter-intellij#4809]
## What happened

Opening flutter project from JetBrains Toolbox.

## Version information

Android Studio `4.1 RC 2` • Flutter plugin `io.flutter 50.0.3-dev.1` • Dart plugin `201.9002`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.IllegalStateException: Expected current state is DISPOSE_IN_PROGRESS, but actual state is ACTIVE (Project (name=_android, containerState=ACTIVE, componentStore=<not initialized>) )
	at com.intellij.serviceContainer.ComponentManagerImpl.dispose(ComponentManagerImpl.kt:857)
	at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.java:332)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:184)
	at com.intellij.openapi.util.ObjectTree.executeUnregistered(ObjectTree.java:197)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:128)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:106)
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.lambda$null$2(AndroidModuleLibraryManager.java:368)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.lambda$initPre41$3(AndroidModuleLibraryManager.java:368)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:45)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:83)
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.initPre41(AndroidModuleLibraryManager.java:368)
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:218)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:95)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:209)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$8(DumbServiceImpl.java:623)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by helin24** [comment]
@stevemessick is this related to changes from last week?

**Comment by stevemessick** [comment]
It appears so. initPre41() should not be called in 4.1.
