### ISSUE TITLE
No Flutter sdk configured (Webstorm)

### ISSUE THREAD

**Issue by bigidea-kz** [flutter/flutter-intellij#4871]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

WebStorm `2020.1.3` • Flutter plugin `io.flutter 49.0.3` • Dart plugin `201.9002`

No Flutter sdk configured.

## Exception

null

```
java.lang.AssertionError
	at io.flutter.module.settings.ProjectType.computeAndroidXAvailability(ProjectType.java:142)
	at io.flutter.module.settings.ProjectType.<init>(ProjectType.java:81)
	at io.flutter.module.settings.FlutterCreateAdditionalSettingsFields.<init>(FlutterCreateAdditionalSettingsFields.java:45)
	at io.flutter.module.settings.FlutterCreateAdditionalSettingsFields.<init>(FlutterCreateAdditionalSettingsFields.java:36)
	at io.flutter.module.FlutterSmallIDEGeneratorPeer.<init>(FlutterSmallIDEGeneratorPeer.java:45)
	at io.flutter.module.FlutterSmallIDEProjectGenerator.createPeer(FlutterSmallIDEProjectGenerator.java:107)
	at io.flutter.module.FlutterSmallIDEProjectGenerator.createPeer(FlutterSmallIDEProjectGenerator.java:36)
	at com.intellij.platform.DirectoryProjectGenerator$1.compute(DirectoryProjectGenerator.java:51)
	at com.intellij.platform.DirectoryProjectGenerator$1.compute(DirectoryProjectGenerator.java:47)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.getPeer(ProjectSettingsStepBase.java:144)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.createAndFillContentPanel(ProjectSettingsStepBase.java:235)
	at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.createPanel(ProjectSettingsStepBase.java:92)
	at com.jetbrains.webstorm.WebStormNewProjectStep$WebStormSettingsStepBase.createPanel(WebStormNewProjectStep.java:66)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.lambda$null$2(FlatWelcomeFrame.java:1007)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.lambda$createActionGroupPanel$3(FlatWelcomeFrame.java:1007)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(JList.java:1804)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1818)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:186)
	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:723)
	at java.desktop/javax.swing.JList.setValueIsAdjusting(JList.java:2152)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(BasicListUI.java:2958)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6650)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by pq** [comment]
@stevemessick : thoughts on this?  Should we even install into Webstorm?

**Comment by stevemessick** [comment]
WebStorm is not supported. Not sure why it allowed the plugin to be installed, but this combo won't work.

**Comment by pq** [comment]
Thanks for the report @bigidea-kz.  Unfortunately, we do not currently support WebStorm.  How did you install the plugin?

**Comment by bigidea-kz** [comment]
Hello
https://plugins.jetbrains.com/plugin/9212-flutter
I downloaded from this link and placed in the plugins folder

**Comment by beansoft** [comment]
@pq My personal suggestion is adding platform check to the plugin's post start activity:
```java
      if(! (PlatformUtils.isIntelliJ() || isAndroidStudio()) ) {
         // post a notification msg that not supported so far and throw an error.
      }

  public static boolean isAndroidStudio() {
    return "AndroidStudio".equalsIgnoreCase(PlatformUtils.getPlatformPrefix());
  }
```
This could reduce some effort on explain that.

> Thanks for the report @bigidea-kz. Unfortunately, we do not currently support WebStorm. How did you install the plugin?

**Comment by stevemessick** [comment]
@beansoft God idea, thanks! Unfortunately, testing requires downloading another huge IDE, and I have very limited bandwidth.

Opened #4928 to track.
