### ISSUE TITLE
com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException: The current HARDWARE_ACCELERATED rendering mode is not supported

### ISSUE THREAD

**Issue by bkhezry** [flutter/flutter-intellij#4872]
## Steps to Reproduce
just open android studio and showing this error:
![Selection_185](https://user-images.githubusercontent.com/91809/93806072-785cf880-fc55-11ea-9df5-190b8e24b6fa.png)

```console
com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException: The current HARDWARE_ACCELERATED rendering mode is not supported
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.checkRenderingMode(BrowserSettingsImpl.java:370)
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.setTransparentBackgroundEnabled(BrowserSettingsImpl.java:358)
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.enableTransparentBackground(BrowserSettingsImpl.java:341)
	at io.flutter.jxbrowser.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:30)
	at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:402)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

## Version info
```console
[✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.4 at /home/bkhezry/flutter
    • Framework revision fba99f6cf9 (7 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/bkhezry/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/bkhezry/Android/Sdk
    • Java binary at: /home/bkhezry/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/bkhezry/android-studio
    • Flutter plugin version 50.0.2-dev.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • Redmi Note 7 (mobile) • 1762cc53 • android-arm64 • Android 10 (API 29)
```

**Comment by stevemessick** [comment]
@helin24 Is this something that should be fixed for M50?

**Comment by helin24** [comment]
This is the same error that was happening on windows (https://github.com/flutter/flutter-intellij/issues/4803), which has been fixed. I verified for Windows Android Studio 4.1 but I can check on Linux as well to make sure it's fixed there too.
