### ISSUE TITLE
Randomly getting IncorrectOperationException

### ISSUE THREAD

**Issue by SAGARSURI** [flutter/flutter-intellij#4997]
## Version information

IntelliJ IDEA `2020.2.3` • Flutter plugin `io.flutter 50.0` • Dart plugin `202.7319.5`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: main.dart:J7AAGF06H076S89 has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.actionSystem.AnAction$$Lambda$1074/0x0000000100ce2840@2ebddd8 will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:65)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:70)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:207)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:192)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.registerActionOnComponent(DebuggerUIUtil.java:416)
	at io.flutter.inspector.InspectorTree.registerShortcuts(InspectorTree.java:108)
	at io.flutter.inspector.InspectorTree.<init>(InspectorTree.java:97)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:183)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:146)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:347)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:287)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:554)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:391)
	at io.flutter.utils.AsyncUtils.lambda$whenCompleteUiThread$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by helin24** [comment]
Do you recall what you were doing at the time this happened? e.g.
- Was an app running or stopped?
- Was the inspector panel open?

**Comment by SAGARSURI** [comment]
Whenever I create an abstract class and import `Either` class from the `dartz` plugin. Then when I wrap it with Future. The autocomplete is completely broken. I have to restart the IDE to make the autocomplete function again. @helin24

**Comment by pq** [comment]
Related to the legacy inspector; closing as stale.
