### ISSUE TITLE
Adroid Studio parou de funcionar depois queinstalei o Flutter

### ISSUE THREAD

**Issue by luciano-vtn** [flutter/flutter-intellij#4998]
Boa Noite!

Tinha o Android Studio Funcionando na minha maquina e depois que instalei o flutter ele parou de funcionar e me retorna esta mensagem de erro:

Internal error. Please refer to https://code.google.com/p/android/issues
java.util.concurrent.CompletionException: org.picocontainer.PicoRegistrationException: Key io.flutter.settings.FlutterSettings duplicated
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
    at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
    at com.a.c.c.d.aw.a(aw.java:65)
    at com.a.c.c.d.aY.a(aY.java:98)
    at com.a.c.c.d.a1.b(a1.java:260)
    at com.a.c.c.d.a1.a(a1.java:122)
    at com.a.c.c.d.aC.a(aC.java:56)
    at com.intellij.idea.MainImpl.start(MainImpl.java:19)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
    at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.picocontainer.PicoRegistrationException: Key io.flutter.settings.FlutterSettings duplicated
    at com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:320)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:186)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
    at com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
    ... 20 more

-----
JRE 1.8.0_242-release-1644-b01 amd64 by JetBrains s.r.o
C:\Program Files\Android\Android Studio\jre\jre

solicito suporte para resolver esse erro.

Luciano.vtn

**Comment by stevemessick** [comment]
From Google translate:
> I had Android Studio working on my machine and after I installed the flutter it stopped working and returns this error message

How did you install the Flutter plugin?

Please append the output of `flutter doctor -v`. Thanks!

**Comment by luciano-vtn** [comment]
Já executei o Flutter doctor -v e ele só me retorna que o Android Studio
não está instalado.
O Android Studio está instalado e quando tento iniciar o mesmo ele me
retorna esta mensagem:

Internal error. Please refer to https://code.google.com/p/android/issues
java.util.concurrent.CompletionException:
org.picocontainer.PicoRegistrationException: Key
io.flutter.settings.FlutterSettings duplicated
    at
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at
java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
    at
java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
    at
java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
    at
java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
    at
com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt:379)
    at
com.intellij.idea.ApplicationLoader$initApplication$2.accept(ApplicationLoader.kt)
    at
java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
    at
java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
    at
java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
    at
java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:110)
    at
com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:376)
    at com.a.c.c.d.aw.a(aw.java:65)
    at com.a.c.c.d.aY.a(aY.java:98)
    at com.a.c.c.d.a1.b(a1.java:260)
    at com.a.c.c.d.a1.a(a1.java:122)
    at com.a.c.c.d.aC.a(aC.java:56)
    at com.intellij.idea.MainImpl.start(MainImpl.java:19)
    at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:303)
    at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:245)
    at
com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:47)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.picocontainer.PicoRegistrationException: Key
io.flutter.settings.FlutterSettings duplicated
    at
com.intellij.util.pico.DefaultPicoContainer.registerComponent(DefaultPicoContainer.java:119)
    at
com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:320)
    at
com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:186)
    at
com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
    at
com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt:93)
    at
com.intellij.idea.ApplicationLoader$registerAppComponents$1.apply(ApplicationLoader.kt)
    at
java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
    ... 20 more

-----
JRE 1.8.0_242-release-1644-b01 amd64 by JetBrains s.r.o
C:\Program Files\Android\Android Studio\jre\jre





Em seg., 26 de out. de 2020 às 19:37, stevemessick <notifications@github.com>
escreveu:

**Comment by stevemessick** [comment]
How did you install the Flutter plugin?

Please append the output of flutter doctor -v. Thanks!

**Comment by stevemessick** [comment]
Also, how did you install Android Studio?

**Comment by luciano-vtn** [comment]
Instalei utilizando a documentação do site
https://developer.android.com/studio?gclid=Cj0KCQjwit_8BRCoARIsAIx3Rj4dgbJiONfUodH2pAOxHTyX8p50WMx_ror2991sauSQkhimMNWc3rAaAoG5EALw_wcB&gclsrc=aw.ds

Em ter., 27 de out. de 2020 às 14:22, stevemessick <notifications@github.com>
escreveu:
