### ISSUE TITLE
java.lang.NoClassDefFoundError AndroidFrameworkDetector

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter-intellij#5013]
## What happened

Just open intelij Idea on an existing project after I starting my pc...

## Version information

IntelliJ IDEA `2020.2.3` • Flutter plugin `io.flutter 51.0.3-dev.4` • Dart plugin `202.7319.5`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NoClassDefFoundError: org/jetbrains/android/facet/AndroidFrameworkDetector
	at io.flutter.ProjectOpenActivity.excludeAndroidFrameworkDetector(ProjectOpenActivity.java:93)
	at io.flutter.ProjectOpenActivity.runActivity(ProjectOpenActivity.java:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:300)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:226)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:298)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.android.facet.AndroidFrameworkDetector PluginClassLoader[PluginDescriptor(name=Flutter, id=io.flutter, path=C:\Users\engue\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\flutter-intellij-kokoro, version=51.0.3-dev.4)] com.intellij.ide.plugins.cl.PluginClassLoader@6be4cf0
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
```

**Comment by EArminjon** [comment]
Seems to be fix with the new plugin version

**Comment by helin24** [comment]
Okay that's great to hear! Please reopen if the problem occurs again.

**Comment by EArminjon** [comment]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2020.2.4` • Flutter plugin `io.flutter 51.0.3-dev.4` • Dart plugin `202.8070`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NoClassDefFoundError: org/jetbrains/android/facet/AndroidFrameworkDetector
	at io.flutter.ProjectOpenActivity.excludeAndroidFrameworkDetector(ProjectOpenActivity.java:93)
	at io.flutter.ProjectOpenActivity.runActivity(ProjectOpenActivity.java:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:300)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:226)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:298)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.android.facet.AndroidFrameworkDetector PluginClassLoader[PluginDescriptor(name=Flutter, id=io.flutter, path=C:\Users\engue\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\flutter-intellij-kokoro, version=51.0.3-dev.4)] com.intellij.ide.plugins.cl.PluginClassLoader@1917e81a
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:95)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
```

**Comment by EArminjon** [comment]
!open

**Comment by EArminjon** [comment]
cannot reopen issue...

**Comment by omatty198** [comment]
I face this problem.
then I remove AndroidStudio cache, just do it.

```
rm -Rf ~/Library/Preferences/AndroidStudio*
rm ~/Library/Preferences/com.google.android.studio.plist
rm -Rf ~/Library/Application\ Support/Google/AndroidStudio*
rm -Rf ~/Library/Logs/AndroidStudio*
rm -Rf ~/Library/Caches/AndroidStudio*
rm -Rf ~/.gradle
rm -Rf ~/.android
rm -Rf ~/Library/Android*
```

**Comment by EArminjon** [comment]
> I face this problem.
> then I remove AndroidStudio cache, just do it.
> 
> ```
> rm -Rf ~/Library/Preferences/AndroidStudio*
> rm ~/Library/Preferences/com.google.android.studio.plist
> rm -Rf ~/Library/Application\ Support/Google/AndroidStudio*
> rm -Rf ~/Library/Logs/AndroidStudio*
> rm -Rf ~/Library/Caches/AndroidStudio*
> rm -Rf ~/.gradle
> rm -Rf ~/.android
> rm -Rf ~/Library/Android*
> ```

It's an old issue, upgrading intellij with then new version fix the issue.
