### ISSUE TITLE
I recently updated Flutter plugin, and just got this exception when Intellij started

### ISSUE THREAD

**Issue by zeusbaba** [flutter/flutter-intellij#5023]
## What happened

I recently updated Flutter plugin, and just got this exception when Intellij started

## Version information

IntelliJ IDEA `2020.2.3` • Flutter plugin `io.flutter 51.0.3` • Dart plugin `202.8070`

Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (3 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)

## Exception

null

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at java.desktop/sun.swing.SwingUtilities2.getFRCFromCache(SwingUtilities2.java:1259)
	at java.desktop/sun.swing.SwingUtilities2.getFRCProperty(SwingUtilities2.java:1232)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1204)
	at java.desktop/javax.swing.JComponent.getFontMetrics(JComponent.java:1649)
	at com.intellij.ui.HighlightableComponent.getPreferredSize(HighlightableComponent.java:401)
	at com.intellij.ui.HyperlinkLabel.adjustSize(HyperlinkLabel.java:101)
	at com.intellij.ui.HyperlinkLabel.updateOnTextChange(HyperlinkLabel.java:254)
	at com.intellij.ui.HyperlinkLabel.setText(HyperlinkLabel.java:174)
	at com.intellij.ui.HighlightedText.applyToComponent(HighlightedText.java:50)
	at com.intellij.ui.HyperlinkLabel.prepareText(HyperlinkLabel.java:165)
	at com.intellij.ui.HyperlinkLabel.setHyperlinkText(HyperlinkLabel.java:93)
	at com.intellij.ui.HyperlinkLabel.setHyperlinkText(HyperlinkLabel.java:88)
	at com.intellij.ui.HyperlinkLabel.<init>(HyperlinkLabel.java:72)
	at com.intellij.ui.HyperlinkLabel.<init>(HyperlinkLabel.java:63)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel.<init>(EditorNotificationPanel.java:278)
	at com.intellij.ui.EditorNotificationPanel$ActionHyperlinkLabel.<init>(EditorNotificationPanel.java:269)
	at com.intellij.ui.EditorNotificationPanel.createActionLabelImpl(EditorNotificationPanel.java:174)
	at com.intellij.ui.EditorNotificationPanel.createActionLabel(EditorNotificationPanel.java:160)
	at com.intellij.ui.EditorNotificationPanel.createActionLabel(EditorNotificationPanel.java:139)
	at io.flutter.editor.FlutterPubspecNotificationProvider$FlutterPubspecActionsPanel.<init>(FlutterPubspecNotificationProvider.java:86)
	at io.flutter.editor.FlutterPubspecNotificationProvider.createNotificationPanel(FlutterPubspecNotificationProvider.java:69)
	at io.flutter.editor.FlutterPubspecNotificationProvider.createNotificationPanel(FlutterPubspecNotificationProvider.java:27)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:170)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$2(EditorNotificationsImpl.java:148)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:508)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:456)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:473)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:397)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:186)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pq** [comment]
Thanks for the report!

@alexander-doroshko: any thoughts?

Here's where we call out to `createActionLabel`:

https://github.com/flutter/flutter-intellij/blob/959895b932fc94b491e1dbd528f01c99dacf4d66/src/io/flutter/editor/FlutterPubspecNotificationProvider.java#L86

**Comment by alexander-doroshko** [comment]
@pq Sorry, no idea. Maybe a Swing bug? According to our issue tracker, it's a very rare exception.

**Comment by pq** [comment]
OK, thanks!
