### ISSUE TITLE
Plugin Issue

### ISSUE THREAD

**Issue by wahabshah009** [flutter/flutter-intellij#5025]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## What happened
To be honest i have no idea when and why this exception occurred still i want to contribute for bug fixation...

## Version information

Android Studio `4.1` • Flutter plugin `io.flutter 51.0.2` • Dart plugin `201.9245`

Error getting Flutter sdk information.

## Exception

null

```
com.teamdev.jxbrowser.engine.UserDataDirectoryCreationException: Failed to create the user data directory: C:\WINDOWS\TEMP\UserData\064f1223-c100-4184-84c4-17bdd219aa43
	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:203)
	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:106)
	at io.flutter.jxbrowser.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:29)
	at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:407)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.teamdev.jxbrowser.internal.DirectoryCreationException: Failed to create directory: C:\WINDOWS\TEMP\UserData\064f1223-c100-4184-84c4-17bdd219aa43
	at com.teamdev.jxbrowser.internal.Files.createDirs(Files.java:28)
	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:196)
	... 31 more
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\TEMP
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(WindowsFileSystemProvider.java:342)
	at sun.nio.fs.WindowsFileSystemProvider.checkAccess(WindowsFileSystemProvider.java:366)
	at java.nio.file.Files.createDirectories(Files.java:746)
	at com.teamdev.jxbrowser.internal.Files.createDirs(Files.java:26)
	... 32 more
```

**Comment by pq** [comment]
@alexander-doroshko: is this a known issue?

**Comment by alexander-doroshko** [comment]
@pq  This is an exception from the Flutter plugin. I guess it shouldn't try to write to `C:\WINDOWS` folder.

**Comment by devoncarew** [comment]
I think the main issue is here: `com.teamdev.jxbrowser.engine.UserDataDirectoryCreationException: Failed to create the user data directory: C:\WINDOWS\TEMP\UserData\064f1223-c100-4184-84c4-17bdd219aa43`

@helin24 - do we have control over the directory that JxBrowser is trying to create - is this something we can configure w/ the plugin? Or is the resolution in the JxBrowser code?

**Comment by vlad-lubenskyi** [comment]
@devoncarew yes, [you have](https://jxbrowser-support.teamdev.com/javadoc/7.10/com/teamdev/jxbrowser/engine/EngineOptions.Builder.html#userDataDir-java.nio.file.Path-).

**Comment by helin24** [comment]
@vlad-lubenskyi thanks for the reference! I'll change the directory to be within the IntelliJ plugin area.

Regarding this note:
> Important: the user data directory cannot be used at the same time by multiple Engine instances running in a single or different applications.

Will this be fulfilled by calling `engine.close()` before starting a new engine, if we want to use the same directory? And the engine probably remains running if its browsers are no longer visible?
