### ISSUE TITLE
Bug: com.teamdev.jxbrowser.engine.ChromiumProcessStartupFailureException

### ISSUE THREAD

**Issue by deliciafernandes** [flutter/flutter-intellij#5076]
## What happened
When I was running my app, my android emulator kept giving me the app not responding popup and then this bug occured.

## Version information

Android Studio `4.1.1` • Flutter plugin `io.flutter 51.0.2` • Dart plugin `201.9245`

Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (12 days ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

## Exception

null

```
com.teamdev.jxbrowser.engine.ChromiumProcessStartupFailureException: Process exit code: 139
	at com.teamdev.jxbrowser.engine.internal.EngineImpl.throwExceptionAndCleanup(EngineImpl.java:459)
	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:278)
	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:106)
	at io.flutter.jxbrowser.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:29)
	at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:407)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vlad-lubenskyi** [comment]
@helin24 FYI 

The exceptions or logs reporting a non-zero exit code mean a native crash. To debug this kind of issue, we always need the crashdumps.

Here is how you and your users can collect them: https://jxbrowser-support.teamdev.com/docs/guides/troubleshooting.html#unexpected-chromium-process-termination (at the moment of writing, there is a typo, the correct property name is `jxbrowser.crash.dump.dir`).

**Comment by helin24** [comment]
@vlad-lubenskyi thanks for the link! 

@deliciafernandes would you be able to find the crash dump files for your system and attach them?

**Comment by deliciafernandes** [comment]
> @helin24 FYI
> 
> The exceptions or logs reporting a non-zero exit code mean a native crash. To debug this kind of issue, we always need the crashdumps.
> 
> Here is how you and your users can collect them: https://jxbrowser-support.teamdev.com/docs/guides/troubleshooting.html#unexpected-chromium-process-termination (at the moment of writing, there is a typo, the correct property name is `jxbrowser.crash.dump.dir`).

Thanks a lot!

**Comment by deliciafernandes** [comment]
> @vlad-lubenskyi thanks for the link!
> 
> @deliciafernandes would you be able to find the crash dump files for your system and attach them?

Hey @helin24 how can i do so? Using a mac updated with big sur.

**Comment by jacob314** [comment]
I don't think the IntellJ issue is causing the app not responding isuse. After you restart your android emulator do you still see the JxBrowser issue or do you continue to see it without the app not responding issue?

**Comment by deliciafernandes** [comment]
> I don't think the IntellJ issue is causing the app not responding isuse. After you restart your android emulator do you still see the JxBrowser issue or do you continue to see it without the app not responding issue?

Same I agree. It's definitely not the android emulators fault

**Comment by deliciafernandes** [comment]
> I don't think the IntellJ issue is causing the app not responding isuse. After you restart your android emulator do you still see the JxBrowser issue or do you continue to see it without the app not responding issue?

Mostly occurs whenever i start android studio itself

**Comment by vlad-lubenskyi** [comment]
@deliciafernandes @helin24 JxBrowser doesn't work on BigSur reliably at this moment. We're already working on fixing it.
