### ISSUE TITLE
Fail in ui_dart_state.cc

### ISSUE THREAD

**Issue by valdeirsoares** [flutter/flutter-intellij#5095]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

When trying to run the application it displays the error below:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Waiting for Android SDK built for x86 to report its views...
Debug service listening on ws://127.0.0.1:9230/Q4In2p9-Lsw=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 6894): eglMakeCurrent: 0xa33a9f60: ver 2 0 (tinfo 0xb0b767b0)
I/flutter ( 6894): -- AppModule INITIALIZED
E/flutter ( 6894): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: setState() or markNeedsBuild() called during build.
E/flutter ( 6894): This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
E/flutter ( 6894): The widget on which setState() or markNeedsBuild() was called was:
E/flutter ( 6894):   Overlay-[LabeledGlobalKey<OverlayState>#f55ad]
E/flutter ( 6894): The widget which was currently being built when the offending call was made was:
E/flutter ( 6894):   _DisposableWidget
E/flutter ( 6894): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
E/flutter ( 6894): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
E/flutter ( 6894): #2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
E/flutter ( 6894): #3      OverlayState.rearrange (package:flutter/src/widgets/overlay.dart:400:5)
E/flutter ( 6894): #4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3287:16)
E/flutter ( 6894): #5      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:3610:5)
E/flutter ( 6894): #6      NavigatorState.pushReplacementNamed (package:flutter/src/widgets/navigator.dart:3452:12)
E/flutter ( 6894): #7      ModularNavigator.pushReplacementNamed (package:flutter_modular/src/navigator/modular_navigator.dart:94:17)
E/flutter ( 6894): #8      _SplashPageState.efetuandoLogin (package:servico_rapido/pages/splash_page.dart:81:16)
E/flutter ( 6894): #9      _SplashPageState.startTimeout (package:servico_rapido/pages/splash_page.dart:42:12)
E/flutter ( 6894): #10     _SplashPageState.initState (package:servico_rapido/pages/splash_page.dart:91:5)
E/flutter ( 6894): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter ( 6894): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 6894): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6894): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6894): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6894): #16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6894): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6894): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 6894): #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter ( 6894): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 6894): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6894): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6894): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6894): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter ( 6894): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter ( 6894): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter ( 6894): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6894): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6894): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 6894): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6894): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6894): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter ( 6894): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter ( 6894): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter ( 6894): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter ( 6894): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter ( 6894): #37 
E/flutter ( 6894): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2416 pos 18: '!navigator._debugLocked': is not true.
E/flutter ( 6894): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 6894): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 6894): #2      _RouteEntry.handlePush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:2416:18)
E/flutter ( 6894): #3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:399:15)
E/flutter ( 6894): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 6894): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 6894): #6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 6894): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 6894): #8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 6894): #9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 6894): #10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 6894): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 6894): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 6894): #13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 6894): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 6894): #15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6894): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 6894): 

## Version info

[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [versÃ£o 10.0.19042.662], locale pt-BR)
    • Flutter version 1.22.4 at D:\Android\flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_SDK_ROOT = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\valde\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

! Doctor found issues in 1 category.

**Comment by valdeirsoares** [comment]
Problem solved
