### ISSUE TITLE
Completion Exception

### ISSUE THREAD

**Issue by Phaeton20** [flutter/flutter-intellij#5107]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2020.2.4` • Flutter plugin `io.flutter 52.0.4` • Dart plugin `202.8070`

Error getting Flutter sdk information.

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@61ec2981
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.flutter.inspector.EvalOnDartLibrary.lambda$addRequest$0(EvalOnDartLibrary.java:97)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@61ec2981
	at io.flutter.inspector.EvalOnDartLibrary$3.onError(EvalOnDartLibrary.java:226)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:629)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by stevemessick** [comment]
@jacob314
