### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by KrisLetaeva** [flutter/flutter-intellij#5110]
## What happened

creating a new flutter project

## Version information

Android Studio `4.1.1` • Flutter plugin `io.flutter 52.0.1` • Dart plugin `201.9245`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:214)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:95)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:209)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$8(DumbServiceImpl.java:623)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stevemessick** [comment]
I cannot reproduce this problem. Please add the output of `flutter doctor -v`.

Is it reproducible for you? If so, screen shots of the new project wizard (all three pages) might be helpful. Also a screen shot of your Flutter settings/preferences page might be useful. Do you have additional plugins installed?

**Comment by KrisLetaeva** [comment]
I also can't reproduce it any more. Now i'm back where i started yesterday
struggling with the emulator.
I attached step-by-step screenshots, console output and flutter doctor
output

вт, 8 дек. 2020 г. в 18:57, stevemessick <notifications@github.com>:

**Comment by stevemessick** [comment]
> I attached step-by-step screenshots, console output and flutter doctor
output

Must've been a glitch. I don't see any of that.
