### ISSUE TITLE
IntelliJ Apple Silicon build does not communicate with simulator

### ISSUE THREAD

**Issue by cliffordh** [flutter/flutter-intellij#5118]
---

## What happened

Running IntelliJ ARM Apple Silicon build. Simulator launches, app installs, but connection to simulator cannot be made.

## Version information

IntelliJ IDEA `2020.3` • Flutter plugin `io.flutter 52.0.5` • Dart plugin `203.5981.152`

Error getting Flutter sdk information.

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@433e5a44
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.flutter.inspector.EvalOnDartLibrary.lambda$addRequest$0(EvalOnDartLibrary.java:97)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@433e5a44
	at io.flutter.inspector.EvalOnDartLibrary$3.onError(EvalOnDartLibrary.java:226)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:629)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by helin24** [comment]
@cliffordh are you able to run your app and connect to it on the simulator when using `flutter run` on the command line? Support for different device types should be part of the Flutter SDK.
