### ISSUE TITLE
UserDataDirectoryAlreadyInUseException

### ISSUE THREAD

**Issue by vladostaci** [flutter/flutter-intellij#5139]
## What happened
I was just writing my code. Nothing special. It might be related to another issue I'm having which I described here https://github.com/flutter/flutter-intellij/issues/3456#issuecomment-748031624

## Version information

Android Studio `4.1.1` • Flutter plugin `io.flutter 52.1.1` • Dart plugin `201.9245`

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (9 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

## Exception

null

```
com.teamdev.jxbrowser.engine.UserDataDirectoryAlreadyInUseException: The user data directory is already in use: C:\Users\user_name\AppData\Roaming\Google\AndroidStudio4.1\plugins\flutter-intellij\jxbrowser\user-data\flutter-project
	at com.teamdev.jxbrowser.engine.internal.EngineImpl.newInstance(EngineImpl.java:209)
	at com.teamdev.jxbrowser.engine.Engine.newInstance(Engine.java:106)
	at io.flutter.jxbrowser.EmbeddedBrowser.<init>(EmbeddedBrowser.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:53)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:660)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:394)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:24)
	at io.flutter.jxbrowser.EmbeddedBrowser.getInstance(EmbeddedBrowser.java:38)
	at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:370)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by helin24** [comment]
@vladostaci thanks for this report; I think we will be able to shut down the browser process more completely to solve this.

I'm also interested to hear if this happened after an action like shutting down and restarting Android Studio, restarting a project, or re-running an application (if you recall).

**Comment by vladostaci** [comment]
@helin24 Yes, it might have happened after closing/reopening the same project in Android Studio. I was closing and reopening the project often because the Autocomple is completely broken once you run the app as I described here https://github.com/flutter/flutter-intellij/issues/3456#issuecomment-748031624
I was showing up in the logs a few times, so it's not hard to reproduce. I'm more worried that because you're using the JxBrowser for the DevTools Window it's somehow breaking the Autocomplete because somehow after you run the app the Autocomplete stops working.

**Comment by helin24** [comment]
@vladostaci I'm making a fix for this issue. I'm not sure whether this breaks autocomplete; potentially if the plugin has crashed then possibly? You could try updating to our [dev channel release](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel), which catches exceptions opening the embedded browser. That way if the browser fails to open, everything else should continue to work normally.

You can also disable this feature by unchecking "Enable embedded browser.. " in Preferences -> Languages and Frameworks -> Flutter -> Experiments.

**Comment by helin24** [comment]
This should be fixed in the dev channel release now.
