### ISSUE TITLE
Installing JxBrowser and DevTools ends with error

### ISSUE THREAD

**Issue by makhosravi** [flutter/flutter-intellij#5170]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `3.6.3` • Flutter plugin `io.flutter 49.0.1` • Dart plugin `192.8052`

Error getting Flutter sdk information.

## Exception

null

```
com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException: The current HARDWARE_ACCELERATED rendering mode is not supported
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.checkRenderingMode(BrowserSettingsImpl.java:370)
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.setTransparentBackgroundEnabled(BrowserSettingsImpl.java:358)
	at com.teamdev.jxbrowser.browser.internal.BrowserSettingsImpl.enableTransparentBackground(BrowserSettingsImpl.java:341)
	at io.flutter.jxbrowser.EmbeddedBrowser.openPanel(EmbeddedBrowser.java:30)
	at io.flutter.devtools.DevToolsInstance.lambda$openPanel$1(DevToolsManager.java:402)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vlad-lubenskyi** [comment]
@helin24 transparent backgrounds are not supported in HA mode in Linux and Windows at this moment.

**Comment by helin24** [comment]
@makhosravi this has been fixed in later versions of the plugin, so I recommend updating to v52.

**Comment by makhosravi** [comment]
thank you very much for your answers
