### ISSUE TITLE
Bug report from Android Studio

### ISSUE THREAD

**Issue by nicolasvac** [flutter/flutter-intellij#5243]
## What happened

I simply opened Android Studio and this happened.

## Version information

Android Studio `4.1.2` • Flutter plugin `io.flutter 52.2.1` • Dart plugin `201.9317`

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (8 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

## Exception

null

```
java.lang.UnsatisfiedLinkError: Unable to load library 'CoreFoundation':
dlopen(libCoreFoundation.dylib, 9): image not found
dlopen(libCoreFoundation.dylib, 9): image not found
Native library (darwin/libCoreFoundation.dylib) not found in resource path (/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/bootstrap.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/extensions.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/util.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/jdom.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/log4j.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/trove4j.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/jna.jar:/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/jre/jdk/Contents/Home/lib/tools.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at com.intellij.util.text.DateFormatUtil.getMacFormats(DateFormatUtil.java:363)
	at com.intellij.util.text.DateFormatUtil.getDateTimeFormats(DateFormatUtil.java:303)
	at com.intellij.util.text.DateFormatUtil.<clinit>(DateFormatUtil.java:46)
	at com.intellij.openapi.wm.impl.status.StatusPanel$5.run(StatusPanel.java:196)
	at com.intellij.openapi.wm.impl.status.StatusPanel.updateText(StatusPanel.java:205)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel.setText(InfoAndProgressPanel.java:517)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.lambda$setInfo$5(IdeStatusBarImpl.java:398)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.setInfo(IdeStatusBarImpl.java:396)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy70.setInfo(Unknown Source)
	at com.intellij.openapi.wm.StatusBar$Info.set(StatusBar.java:52)
	at com.intellij.notification.LogModel.setStatusMessage(LogModel.java:72)
	at com.intellij.notification.LogModel.addNotification(LogModel.java:44)
	at com.intellij.notification.EventLog$ProjectTracker.printNotification(EventLog.java:507)
	at com.intellij.notification.EventLog$ProjectTracker.access$400(EventLog.java:446)
	at com.intellij.notification.EventLog$MyNotificationListener.notify(EventLog.java:660)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:139)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy69.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:84)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:73)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:73)
	at com.intellij.notification.Notification.notify(Notification.java:349)
	at com.intellij.configurationStore.FileBasedStorage.processReadException(FileBasedStorage.kt:252)
	at com.intellij.configurationStore.FileBasedStorage.access$processReadException(FileBasedStorage.kt:33)
	at com.intellij.configurationStore.FileBasedStorage.loadLocalData(FileBasedStorage.kt:384)
	at com.intellij.configurationStore.XmlElementStorage.loadElement(XmlElementStorage.kt:67)
	at com.intellij.configurationStore.XmlElementStorage.loadElement$default(XmlElementStorage.kt:50)
	at com.intellij.configurationStore.XmlElementStorage.loadData(XmlElementStorage.kt:48)
	at com.intellij.configurationStore.XmlElementStorage.loadData(XmlElementStorage.kt:31)
	at com.intellij.configurationStore.StateStorageBase.getStorageData(StateStorageBase.kt:52)
	at com.intellij.configurationStore.StateStorageBase.getStorageData(StateStorageBase.kt:32)
	at com.intellij.configurationStore.FileBasedStorage.preloadStorageData(FileBasedStorage.kt:161)
	at com.intellij.configurationStore.ModuleStoreBase$setPath$1.invoke(ModuleStoreImpl.kt:79)
	at com.intellij.configurationStore.ModuleStoreBase$setPath$1.invoke(ModuleStoreImpl.kt:54)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:168)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage$default(StateStorageManagerImpl.kt:159)
	at com.intellij.configurationStore.ModuleStoreBase.setPath(ModuleStoreImpl.kt:66)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$null$2(ModuleManagerImpl.java:377)
	at com.intellij.openapi.module.impl.ModuleImpl.init(ModuleImpl.java:99)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.initModule(ModuleManagerImpl.java:384)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$loadModuleInternal$3(ModuleManagerImpl.java:377)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.loadModuleInternal(ModuleManagerImpl.java:375)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$null$0(ModuleManagerImpl.java:299)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:54)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$loadModules$1(ModuleManagerImpl.java:297)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.SameThreadExecutorService.execute(SameThreadExecutorService.java:54)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.loadModules(ModuleManagerImpl.java:295)
	at com.intellij.openapi.module.impl.ModuleManagerComponent$MyProjectServiceContainerInitializedListener.serviceCreated(ModuleManagerComponent.java:63)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion$notifyThatComponentCreated$$inlined$runHandler$1.accept(projectLoader.kt:110)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion$notifyThatComponentCreated$$inlined$runHandler$1.accept(projectLoader.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:285)
	at com.intellij.openapi.project.ProjectLoadHelper$Companion.notifyThatComponentCreated(projectLoader.kt:114)
	at com.intellij.openapi.project.ProjectLoadHelper.notifyThatComponentCreated(projectLoader.kt)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:281)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.init41(AndroidModuleLibraryManager.java:336)
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:218)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:95)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:209)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$8(DumbServiceImpl.java:623)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreFoundation.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 127 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreFoundation.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 127 more
	Suppressed: java.io.IOException: Native library (darwin/libCoreFoundation.dylib) not found in resource path (/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/bootstrap.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/extensions.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/util.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/jdom.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/log4j.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/trove4j.jar:/private/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/lib/jna.jar:/var/folders/lh/q0hqgm493gz88x8mymn5k9080000gn/T/AppTranslocation/2008EF13-3BF4-4A9F-9665-3EC3CE6CD830/d/Android Studio.app/Contents/jre/jdk/Contents/Home/lib/tools.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 127 more
```

**Comment by devoncarew** [comment]
Thanks for the report! I don't think we can act on this bug however - it indicates an issue starting Android Studio on your machine. You might try re-installing, or, following up with a issue against Android Studio.
