### ISSUE TITLE
com.intellij.util.IncorrectOperationException: Sorry but parent: prod:AYJJKZPFS4MZGEV8 has already been disposed

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter-intellij#5262]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `4.1.2` • Flutter plugin `io.flutter 52.2.1` • Dart plugin `201.9317`

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (4 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: prod:AYJJKZPFS4MZGEV8 has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.actionSystem.AnAction$$Lambda$453/699496731@6f9dc608 will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:59)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:65)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:203)
	at com.intellij.openapi.actionSystem.AnAction.registerCustomShortcutSet(AnAction.java:188)
	at com.intellij.xdebugger.impl.ui.DebuggerUIUtil.registerActionOnComponent(DebuggerUIUtil.java:416)
	at io.flutter.inspector.InspectorTree.registerShortcuts(InspectorTree.java:108)
	at io.flutter.inspector.InspectorTree.<init>(InspectorTree.java:97)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:183)
	at io.flutter.view.InspectorPanel.<init>(InspectorPanel.java:146)
	at io.flutter.view.FlutterView.addInspectorPanel(FlutterView.java:376)
	at io.flutter.view.FlutterView.addInspectorViewContent(FlutterView.java:316)
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:621)
	at io.flutter.view.FlutterView.lambda$debugActive$3(FlutterView.java:420)
	at io.flutter.utils.AsyncUtils.lambda$null$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
Related to the legacy inspector; closing as stale.
