### ISSUE TITLE
Android Studio IDE does not close

### ISSUE THREAD

**Issue by Daniyal-Ahmad358** [flutter/flutter-intellij#5299]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

When I close the ide the android studio gives me this error in the log, and the ide does not close.

## Version information

Android Studio `4.1.2` • Flutter plugin `io.flutter 53.1.1` • Dart plugin `201.9317`

Error getting Flutter sdk information.

## Exception

null

java.lang.IllegalStateException: Failed to receive the response.
	at com.teamdev.jxbrowser.internal.rpc.transport.CommonThreadResponseConsumer.await(CommonThreadResponseConsumer.java:55)
	at com.teamdev.jxbrowser.internal.rpc.transport.CommonThreadCallExecutor.execute(CommonThreadCallExecutor.java:26)
	at com.teamdev.jxbrowser.internal.rpc.UniversalServiceConnection.invoke(UniversalServiceConnection.java:182)
	at com.teamdev.jxbrowser.browser.internal.BrowserImpl.tryToClose(BrowserImpl.java:480)
	at com.teamdev.jxbrowser.browser.internal.BrowserImpl.close(BrowserImpl.java:450)
	at com.teamdev.jxbrowser.browser.internal.BrowserImpl.close(BrowserImpl.java:435)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.teamdev.jxbrowser.engine.internal.EngineImpl.close(EngineImpl.java:644)
	at io.flutter.jxbrowser.EmbeddedBrowserEngine$1.canExitApplication(EmbeddedBrowserEngine.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.canExit(ApplicationImpl.java:764)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:608)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:578)
	at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:85)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.quitApp(CloseProjectWindowHelper.kt:57)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing(CloseProjectWindowHelper.kt:35)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper$2.windowClosing(ProjectFrameHelper.java:231)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.CustomHeader.close(CustomHeader.kt:237)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.CustomHeader$myCloseAction$1.invoke(CustomHeader.kt:234)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.CustomHeader$myCloseAction$1.invoke(CustomHeader.kt:38)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.CustomHeader$CustomFrameAction.actionPerformed(CustomHeader.kt:244)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: The connection has been closed.
	at com.teamdev.jxbrowser.internal.rpc.transport.CommonThreadCallExecutor.lambda$execute$0(CommonThreadCallExecutor.java:21)
	at com.teamdev.jxbrowser.deps.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:79)
	at com.teamdev.jxbrowser.deps.com.google.protobuf.RpcUtil$1.run(RpcUtil.java:70)
	at com.teamdev.jxbrowser.internal.rpc.ServiceChannel$1.onError(ServiceChannel.java:70)
	at com.teamdev.jxbrowser.internal.rpc.transport.SharedMemoryChannel.send(SharedMemoryChannel.java:78)
	at com.teamdev.jxbrowser.internal.rpc.transport.SharedMemoryConnection.send(SharedMemoryConnection.java:73)
	at com.teamdev.jxbrowser.internal.rpc.ServiceChannel.callMethod(ServiceChannel.java:48)
	at com.teamdev.jxbrowser.browser.internal.rpc.BrowserStub.close(BrowserStub.java:156)
	at com.teamdev.jxbrowser.internal.rpc.transport.CommonThreadCallExecutor.execute(CommonThreadCallExecutor.java:19)
	... 73 more

**Comment by stevemessick** [comment]
@helin24

**Comment by Daniyal-Ahmad358** [comment]
> @helin24

I've just started learning flutter and I know nothing about such errors at all. Please explain what should I do.

**Comment by helin24** [comment]
@Daniyal-Ahmad358 sorry about this issue. For now, if you keep getting this problem, I recommend just using force quit to close your IDE. The fix I made will most likely be available this weekend as part of our plugin's dev release; at that point you can follow the instructions [here](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel) to get that version.

Overall this error shouldn't impact your use of Flutter and the other features of the plugin. Let me know if you're finding otherwise.

**Comment by Daniyal-Ahmad358** [comment]
> @Daniyal-Ahmad358 sorry about this issue. For now, if you keep getting this problem, I recommend just using force quit to close your IDE. The fix I made will most likely be available this weekend as part of our plugin's dev release; at that point you can follow the instructions [here](https://github.com/flutter/flutter-intellij/wiki/Dev-Channel) to get that version.
> 
> Overall this error shouldn't impact your use of Flutter and the other features of the plugin. Let me know if you're finding otherwise.

Ok thankyou very much. I'll just force quit that until a stable release is out with the fix.
