### ISSUE TITLE
UnsupportedRenderingModeException from JxBrowser

### ISSUE THREAD

**Issue by torlarse** [flutter/flutter-intellij#5321]
---

## What happened

Debugging, staying relatively long time on breakpoints.

## Version information

IntelliJ IDEA `2020.3.2` • Flutter plugin `io.flutter 54.1.3` • Dart plugin `203.7759`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NoClassDefFoundError: com/teamdev/jxbrowser/browser/UnsupportedRenderingModeException
	at io.flutter.view.FlutterView.debugActiveHelper(FlutterView.java:675)
	at io.flutter.view.FlutterView.lambda$debugActive$5(FlutterView.java:447)
	at io.flutter.utils.AsyncUtils.lambda$whenCompleteUiThread$0(AsyncUtils.java:37)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.teamdev.jxbrowser.browser.UnsupportedRenderingModeException PluginClassLoader[PluginDescriptor(name=Flutter, id=io.flutter, path=C:\Users\teril\AppData\Roaming\JetBrains\IntelliJIdea2020.3\plugins\flutter-intellij, version=54.1.3)] com.intellij.ide.plugins.cl.PluginClassLoader@5b9c5964
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 32 more
```

**Comment by stevemessick** [comment]
@helin24

**Comment by torlarse** [comment]
I am getting these regularly. I really don't see a specific pattern for when these errors occur, I am usually having an emulator open and IntelliJ running a debug session.

**Comment by stevemessick** [comment]
You can eliminate the error by disabling the embedded DevTools option in Settings/Preferences. It is the bottom one in the Experimental section.

<img width="709" alt="Screen Shot 2021-03-17 at 9 03 17 AM" src="https://user-images.githubusercontent.com/8518285/111499065-cc760080-86ff-11eb-988e-47af148f9c64.png">

**Comment by helin24** [comment]
@torlarse it looks like there may have been a problem with loading JxBrowser classes initially. Could you attach your logs so I can check if there were any error messages during class loading? If you go to Help > Show log in finder/explorer, there should be a file named `idea.log` or `idea`.

**Comment by torlarse** [comment]
@helin24 Thanks, I sent a file link to the gmail-address in your Github profile :)

**Comment by helin24** [comment]
@torlarse thanks! I actually don't see any attempt to install JxBrowser in your logs. That would explain the problem, but I'll have to investigate why. Your project definitely has a pubspec.yaml file with a dependency on flutter, right?

**Comment by torlarse** [comment]
My pubspec.yaml:

```
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.0
  google_maps_flutter: ^1.0.3
  http: ^0.12.1
  json_serializable: ^3.5.1 
  location: ^3.2.4
  google_maps_webservice: ^0.0.19
  uuid: ^2.2.2

  cupertino_icons: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
```
