### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <:> at index 2

### ISSUE THREAD

**Issue by clounie** [flutter/flutter-intellij#5327]
Searched for a couple of the strings in the error, didn't find in open/closed issues.

## What happened

I just installed flutter + dart plugins earlier, and restarted IntelliJ after that.

1. Run `flutter create my_app` in Powershell
2. Run `dart migrate --apply-changes` in Powershell (to enable null safety in Dart)
2. Click `Open` from the "Welcome to IntelliJ" modal that lists your projects (can get to it by pressing `File` --> `Close Project` when you have an existing project open)
2. Select `my_app` folder (NOT any file in it - top level folder) and click`Ok`
3. This error pops up

#### Relevant notes
* I tried this with both the normal version of the plugin, and the dev channel
* This error only happens on initial project import. After that it seems to work fine

## Version information
Interesting nugget on this..the plugin couldn't find the flutter information - it put this in the template instead: `Error getting Flutter sdk information.`
* I got the IntelliJ information from its Help --> About
* I got the flutter/dart info from running `flutter --version` and `dart --version` respectively in Powershell
* IntelliJ was started _after_ I added `flutter` to the user Path. Obviously Powershell sees it, so no reason to believe it's a setup issue

#### Windows 
```
Microsoft Windows 10 Pro
Version 10.0.19041 Build 19041
```

#### IntelliJ IDEA 2021.1 Beta (Ultimate Edition)
```
Build #IU-211.6432.7, built on March 9, 2021
IntelliJ IDEA EAP User
Expiration date: April 9, 2021
Runtime version: 11.0.10+9-b1341.19 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1800M
Cores: 8
Non-Bundled Plugins: org.sonarlint.idea (4.14.2.28348), Dart (211.6432.7), io.flutter (54.1.5)
Kotlin: 211-1.4.21-release-IJ6432.2
```
#### Dart:
```
Dart SDK version: 2.12.1 (stable) (Wed Mar 10 10:18:47 2021 +0100) on "windows_x64"
```

#### Flutter:
```
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (5 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1
```

## Exception

null

```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Eos/AppData/Local/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6432.7.plugins/flutter-intellij/jxbrowser/jxbrowser-win64-7.12.2.jar
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.intellij.util.lang.UrlClassLoader.addURL(UrlClassLoader.java:166)
	at io.flutter.utils.FileUtils.loadClass(FileUtils.java:65)
	at io.flutter.jxbrowser.JxBrowserManager.loadClasses(JxBrowserManager.java:256)
	at io.flutter.jxbrowser.JxBrowserManager.setUp(JxBrowserManager.java:195)
	at io.flutter.ProjectOpenActivity.runActivity(ProjectOpenActivity.java:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:235)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:303)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:156)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:229)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:160)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by stevemessick** [comment]
@helin24 Perhaps we should catch errors like this and disable JxBrowser?

**Comment by helin24** [comment]
@clounie could you send your logs? Go to Help > Show log in explorer, and attach the file named 'idea'. It looks like the found path might be sometimes prepending a `/` but I'm not sure why.
