### ISSUE TITLE
Non-critical crash when running a Flutter app on a real device through IntelliJ Idea

### ISSUE THREAD

**Issue by Dzhuneyt** [flutter/flutter-intellij#5328]
## What happened

No idea. I was just developing my Flutter app and running it on a real Android device using the IDE.

## Version information

IntelliJ IDEA `2020.3.2` • Flutter plugin `io.flutter 54.1.3` • Dart plugin `203.7759`

Flutter 2.0.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (13 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

## Exception

null

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
	at io.flutter.perf.FlutterWidgetPerfManager.debugActive(FlutterWidgetPerfManager.java:201)
	at io.flutter.perf.FlutterWidgetPerfManager.lambda$new$0(FlutterWidgetPerfManager.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor987.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:652)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:401)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:383)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:189)
	at com.sun.proxy.$Proxy190.debugActive(Unknown Source)
	at io.flutter.view.FlutterViewMessages.sendDebugActive(FlutterViewMessages.java:49)
	at io.flutter.run.FlutterDebugProcess.onVmConnected(FlutterDebugProcess.java:77)
	at io.flutter.vmService.DartVmServiceDebugProcess.onConnectSucceeded(DartVmServiceDebugProcess.java:541)
	at io.flutter.vmService.DartVmServiceDebugProcess.lambda$scheduleConnect$1(DartVmServiceDebugProcess.java:245)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by stevemessick** [comment]
@jacob314

**Comment by pq** [comment]
Related to the legacy performance view; closing as stale.
