### ISSUE TITLE
InvocationTargetException in EmbeddedAndroidProject.init41()

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#5335]
## What happened

Got this exception while testing removal of Android framework detection. Was using local build of plugin for Android Studio 4.2. Don't believe I modified any code related to this problem.

## Version information

Android Studio `4.2 Beta 6` • Flutter plugin `io.flutter SNAPSHOT` • Dart plugin `202.8443`

Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (2 weeks ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

## Exception

null

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.init41(AndroidModuleLibraryManager.java:377)
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:222)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:99)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:213)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$6(DumbServiceImpl.java:463)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:808)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:328)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:808)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.init41(AndroidModuleLibraryManager.java:374)
	... 31 more
Caused by: java.lang.ClassCastException: class com.intellij.util.messages.impl.MessageBusImpl cannot be cast to class com.intellij.util.messages.impl.MessageBusEx (com.intellij.util.messages.impl.MessageBusImpl and com.intellij.util.messages.impl.MessageBusEx are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @150c158)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:242)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:157)
	at com.intellij.openapi.project.impl.ProjectLoadHelper.registerComponents(projectLoader.kt:26)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:175)
	... 36 more
```

**Comment by excode** [comment]
Same problem can't build file since  weeks. Any update regarding this issue. ?

**Comment by stevemessick** [comment]
See #5399 for update.
