### ISSUE TITLE
Stacktrace when adding icon to source code - can continue to work.

### ISSUE THREAD

**Issue by tiloc** [flutter/flutter-intellij#5337]
## What happened

Just regular editing of a code-file with reference to an Icon.

## Version information

IntelliJ IDEA `2020.3.3` • Flutter plugin `io.flutter 53.1.5` • Dart plugin `203.7759`

Flutter 2.1.0-12.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8264cb3e8a (11 days ago) • 2021-03-10 12:37:57 -0800
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)

## Exception

During querying provider Icon preview (class io.flutter.editor.FlutterIconLineMarkerProvider)

```
java.lang.ClassCastException: class com.jetbrains.lang.dart.psi.impl.DartIdImpl cannot be cast to class com.jetbrains.lang.dart.psi.DartReference (com.jetbrains.lang.dart.psi.impl.DartIdImpl and com.jetbrains.lang.dart.psi.DartReference are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @30e81b60)
	at io.flutter.editor.FlutterIconLineMarkerProvider.getLineMarkerInfo(FlutterIconLineMarkerProvider.java:70)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:158)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:83)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:78)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by stevemessick** [comment]
@tiloc Can you show us the statement that caused the exception? That would really help us fix this.

**Comment by tiloc** [comment]
final leading = (displayCategory == 'instructions')
        ? const Icon(Icons.info)
        : (displayCategory == 'security')
            ? const Icon(Icons.lock)
            : null;

**Comment by stevemessick** [comment]
That problem was fixed in Feb. If you update to the latest you should be fine. Please re-open if not.

**Comment by tiloc** [comment]
I am on IJ 2020.3.3 which is the latest. The latest Flutter plugin that is released for that version is 53.1.5. Why are the later 54.x ones only released for older versions of IJ?
In other words, I would have to downgrade the IDE in order to upgrade the plugin?

**Comment by stevemessick** [comment]
Apparently, one of the files did not get uploaded during the last release process. Try now, you should be able to upgrade.

**Comment by tiloc** [comment]
@stevemessick Thank you!!!

**Comment by stevemessick** [comment]
Sorry for the trouble, but glad you're up to date now.
