### ISSUE TITLE
Hot reload crashes in Flutter desktop 2.0.3

### ISSUE THREAD

**Issue by Oberdiah** [flutter/flutter-intellij#5355]
## Steps to Reproduce

1. flutter create --platforms=windows testproject
2. Open project in Android Studio
3. Run project in Android Studio
4. Make change to code
5. Hot reload

```======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building MyApp(dirty):
No constructor 'StatefulWidget.' with matching arguments declared in class 'StatefulWidget'.
Receiver: StatefulWidget
Tried calling: new StatefulWidget.()
Found: new StatefulWidget.({Key? key}) => StatefulWidget

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
When the exception was thrown, this was the stack: 
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:212:5)
#1      new MyHomePage (package:testproject/main.dart)
#2      MyApp.build (package:testproject/main.dart:25:13)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
...
====================================================================================================
```

## Version info

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.631], locale en-GB)
    • Flutter version 2.0.3 at C:\Universe\LargeStuff\flutter
    • Framework revision 4d7946a68d (7 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\richa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\richa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\richa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Users\richa\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.53.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.631]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!

**Comment by helin24** [comment]
I'm not able to reproduce with the given instructions. Does this happen for you with any change in the project? Does this also occur for you in IntelliJ?

**Comment by helin24** [comment]
Actually, I spoke too soon - I had the wrong version of Flutter before. I think you may be able to get around this for now by changing your flutter to the beta channel, but we'll check whether this has been fixed going forward.

**Comment by Oberdiah** [comment]
> Actually, I spoke too soon - I had the wrong version of Flutter before. I think you may be able to get around this for now by changing your flutter to the beta channel, but we'll check whether this has been fixed going forward.

I can confirm that upgrading to the beta channel fixed it. Thanks!

**Comment by LinarAI** [comment]
anyone can solve this??????? it is 2023.10 and windows cannot run hot reload!
