### ISSUE TITLE
message from 'Android Studio' to Flutter

### ISSUE THREAD

**Issue by benedicte69** [flutter/flutter-intellij#5387]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Nothing special happened, except that generally, Android Studio invite me to report this sort of message to Google, but this time it was clearly mentioned to report it to Flutter. So I just 'obey'

## Version information

Android Studio `4.1.3` • Flutter plugin `io.flutter 55.0.1` • Dart plugin `201.9335`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.IllegalArgumentException
	at io.flutter.inspector.TreeScrollAnimator.clampInterval(TreeScrollAnimator.java:350)
	at io.flutter.inspector.TreeScrollAnimator.animateTo(TreeScrollAnimator.java:432)
	at io.flutter.view.InspectorPanel.animateTo(InspectorPanel.java:1028)
	at io.flutter.view.InspectorPanel.setSelectedNode(InspectorPanel.java:1063)
	at io.flutter.view.InspectorPanel.refreshSelection(InspectorPanel.java:687)
	at io.flutter.view.InspectorPanel.applyNewSelection(InspectorPanel.java:983)
	at io.flutter.view.InspectorPanel.lambda$updateSelectionFromService$8(InspectorPanel.java:898)
	at io.flutter.inspector.InspectorService$ObjectGroup.lambda$null$79(InspectorService.java:1428)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pq** [comment]
Related to the legacy inspector; closing as stale.
