### ISSUE TITLE
Exception: Trying to reset custom component in a presentation

### ISSUE THREAD

**Issue by ksilz** [flutter/flutter-intellij#5400]
## Steps to Reproduce

Sorry for not being much help here - this just popped up in my IntelliJ event log somewhere along the way.
- I dowgraded Flutter to version 1.22.6 again while in IntelliJ.
- I started the application once more on an Android emulator.
- It may have happened then. 

## Version information

IntelliJ IDEA `2021.1` • Flutter plugin `io.flutter 55.0.5` • Dart plugin `211.6693.108`

Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (3 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

## Exception

Trying to reset custom component in a presentation

```
java.lang.Throwable
	at com.intellij.openapi.actionSystem.Presentation.putClientProperty(Presentation.java:403)
	at com.intellij.openapi.actionSystem.Presentation.copyFrom(Presentation.java:376)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$reflectSubsequentChangesInOriginalPresentation$9(ActionUpdater.java:140)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:308)
	at com.intellij.openapi.actionSystem.Presentation.fireBooleanPropertyChange(Presentation.java:335)
	at com.intellij.openapi.actionSystem.Presentation.setVisible(Presentation.java:302)
	at io.flutter.actions.DeviceSelectorAction.updateVisibility(DeviceSelectorAction.java:125)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$2(DeviceSelectorAction.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:415)
	at io.flutter.FlutterUtils.invokeAndWait(FlutterUtils.java:96)
	at io.flutter.actions.DeviceSelectorAction.update(DeviceSelectorAction.java:117)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$0(DeviceSelectorAction.java:84)
	at io.flutter.run.daemon.DeviceService.lambda$fireChangeEvent$4(DeviceService.java:159)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by helin24** [comment]
Thanks for the report. @stevemessick possibly from https://github.com/flutter/flutter-intellij/pull/5333?

**Comment by stevemessick** [comment]
Hmmm. #5333 was intended to prevent this log message but this case isn't handled.

See also: https://youtrack.jetbrains.com/issue/IDEA-263745

**Comment by stevemessick** [comment]
I cannot reproduce this problem. I tried starting three emulators, switching between them, and running the app on each. I also tried the Refresh option to re-build the device list. Closing and re-opening the project with all three emulators running also worked as expected.

We'll need more detailed repro steps if we're going to identify the root cause.

**Comment by ksilz** [comment]
Sorry, can't help you there. I saw this error in my log. That's pretty much all I can tell you.

**Comment by ksilz** [comment]
Sorry, didn't intend to re-open the issue. Closing it again.
