### ISSUE TITLE
Cannot run example app on Mac

### ISSUE THREAD

**Issue by pawellabaj** [flutter/flutter-intellij#5452]
## Steps to Reproduce

I am trying to execute example app in IntelliJ IDEA with Flutter plugin on Android Emulator. I get Following error:
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x54c67b91) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x54c67b91

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Exception: Gradle task assembleDebug failed with exit code 1
```

When I run this `assembleDebug` with IntelliJ to see what is the problem, it looks ok:
```
Executing task 'assembleDebug'...

> Task :app:compileFlutterBuildDebug UP-TO-DATE
> Task :app:packLibsflutterBuildDebug UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:cleanMergeDebugAssets
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:copyFlutterAssetsDebug
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugKotlin UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:mergeDebugJavaResource UP-TO-DATE
> Task :app:checkDebugDuplicateClasses UP-TO-DATE
> Task :app:dexBuilderDebug UP-TO-DATE
> Task :app:desugarDebugFileDependencies UP-TO-DATE
> Task :app:mergeExtDexDebug UP-TO-DATE
> Task :app:mergeDexDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :app:mergeDebugNativeLibs UP-TO-DATE
> Task :app:stripDebugDebugSymbols UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
32 actionable tasks: 4 executed, 28 up-to-date
Task execution finished 'assembleDebug'.
```

If I run the app from a terminal `flutter run -d emulator-5554` I get following error:
```
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Exception in thread "main" java.io.FileNotFoundException: /wrapper/dists/gradle-6.7-all/cuy9mc7upwgwgeb72wkcrupxe/gradle-6.7-all.zip.lck (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)      
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:347)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:261)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
        at org.gradle.wrapper.Install.createDist(Install.java:48)       
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        948ms
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception in thread "main" java.io.FileNotFoundException: /wrapper/dists/gradle-6.7-all/cuy9mc7upwgwgeb72wkcrupxe/gradle-6.7-all.zip.lck (No such file or directory)
        at java.base/java.io.RandomAccessFile.open0(Native Method)      
        at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:347)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:261)
        at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
        at org.gradle.wrapper.Install.createDist(Install.java:48)       
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        921ms
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDebug failed with exit code 1
```

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-PL)
    • Flutter version 2.0.5 at /Users/pawel_labaj/Library/flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/pawel_labaj/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/pawel_labaj/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 15.0.1+9-18)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1.1, Build version 12A7605b
    • CocoaPods version 1.10.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64  • Mac OS X 10.15.7 19H524 darwin-x64
```

**Comment by pawellabaj** [comment]
I've restarted a computer and the results are different now.

Application runs on emulator when started from a command line `flutter run -d emulator-5554`:
```
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        80.8s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
```

I still cannot run the application from IntelliJ. I get such error (different then previously):
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x193b0a12) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x193b0a12

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by stevemessick** [comment]
It looks like you are getting a version of Java that doesn't work with Flutter when running from IntelliJ. Check your path and class path in the terminal and IntelliJ to make sure they are the same.

**Comment by pawellabaj** [comment]
I think I've set up JDK 15 everywhere

```
java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```
```
echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home
```
```
echo $PATH   
/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home/bin:/Users/pawel_labaj/.gem/bin:/Users/pawel_labaj/Library/flutter/.pub-cache/bin:/Users/pawel_labaj/Library/flutter/bin:/Users/pawel_labaj/Library/Android/sdk/cmdline-tools/latest/bin:/Users/pawel_labaj/Library/Android/sdk/platform-tools:/Users/pawel_labaj/.gem/ruby/2.7.0/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/opt/apache-maven-3.6.3/bin
```
![image](https://user-images.githubusercontent.com/6212520/116586944-4661f200-a91a-11eb-9be2-873d12805311.png)

**Comment by stevemessick** [comment]
I know it works with version 11. I do not know about 15, but the error you're getting (`module jdk.compiler does not export com.sun.tools.javac.code`) suggests you have an incompatible version.

**Comment by pawellabaj** [comment]
I've found the cause of the problem.

Gradle build run by Flutter plugin uses IntelliJ's internal JDK and not project's JDK.

Workaround for this is to set up **org.gradle.java.home** in `gradle.properties`

I've set up 
```
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-15.0.1.jdk/Contents/Home
```
and it started to work

@stevemessick , do you know if choosing JDK is included in the Flutter plugin? Maybe this behaviour could be changed?

**Comment by stevemessick** [comment]
I'm glad you solved the problem @pawellabaj. I looked through the "Getting Started" section of flutter.dev for several platforms. No where could I find mention of which version of Java is required. I believe it is only required when building for Android, as the Android build uses Gradle. We might be able to specify the PATH when launching the Flutter app.

Related: #5292

**Comment by stevemessick** [comment]
Since this is a local configuration problem, I'm closing this issue.
