### ISSUE TITLE
Flutter editor exception

### ISSUE THREAD

**Issue by gmpassos** [flutter/flutter-intellij#5460]
## What happened

I have just opened IntelliJ. Actually I was opening a Kotlin project,
and I have added the `implementation "org.jetbrains.kotlin:kotlin-script-runtime:1.4.20"`
to the project as suggested by IntelliJ.

## Version information

IntelliJ IDEA `2021.1.1` • Flutter plugin `io.flutter 56.0.5` • Dart plugin `211.7233`

Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (9 weeks ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

## Exception

During querying provider Run line marker (class com.intellij.execution.lineMarker.RunLineMarkerProvider)

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'listener' of io/flutter/editor/ActiveEditorsOutlineService.addListener must not be null
	at io.flutter.editor.ActiveEditorsOutlineService.$$$reportNull$$$0(ActiveEditorsOutlineService.java)
	at io.flutter.editor.ActiveEditorsOutlineService.addListener(ActiveEditorsOutlineService.java)
	at io.flutter.run.common.CommonTestConfigUtils.getTestsFromOutline(CommonTestConfigUtils.java:99)
	at io.flutter.run.common.CommonTestConfigUtils.refreshOutline(CommonTestConfigUtils.java:44)
	at io.flutter.run.common.TestLineMarkerContributor.getInfo(TestLineMarkerContributor.java:75)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:57)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:157)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:82)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:77)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by bernaferrari** [comment]
Same here, but without Kotlin. Just navigating a standard flutter project.
