### ISSUE TITLE
java.util.concurrent.TimeoutException when starting DevTools when running an app

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#5560]
We're seeing several hundred exceptions reported to crash reporting related to timeouts while starting DevTools as part of running a flutter app. I suspect that we should switch to just using the DevTools instance that `flutter run` can now start.

Here's a sample exception:

```
57.0.5; IntelliJ IDEA/2021.1.2

java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.flutter.run.SdkFields.createFlutterSdkRunCommand(SdkFields.java:211)
	at io.flutter.run.SdkRunConfig.getCommand(SdkRunConfig.java:239)
	at io.flutter.run.SdkRunConfig.lambda$getState$1(SdkRunConfig.java:141)
	at io.flutter.run.LaunchState.laun...
```

Does `flutter run` now start a copy of DevTools? Is the url reported to us (the IDE)? And, if yes to the first two, what SDK version should we check for before relying on the sdk vended copy of devtools?

cc @kenzieschmoll @stevemessick @jonahwilliams

**Comment by devoncarew** [comment]
This is another common exception:

```
java.util.concurrent.ExecutionException: java.lang.Exception: DevTools instance not available after first run.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at io.flutter.run.SdkFields.createFlutterSdkRunCommand(SdkFields.java:211)
	at io.flutter.run.SdkRunConfig.getCommand(SdkRunConfig.java:239)
	at io.flutter.run.LaunchState$Runner.doExecute(LaunchState.java:368)
	at c...
```

It's not the same as the first one in this bug, but would also be resolved by moving away from launching devtools synchronously as part of running an app.

**Comment by helin24** [comment]
Fixed by https://github.com/flutter/flutter-intellij/pull/5576
