### ISSUE TITLE
Dart analysis issue: RangeError (index): Invalid value: Not in inclusive range 0..12: 13

### ISSUE THREAD

**Issue by rxlabz** [flutter/flutter-intellij#5568]
I'm not sure if/how it's related to the RangeError, but with the stable Flutter SDK (2.2.1 / Dart 2.13.1)  the Dart Analysis seems to crash when I open a file with "generated parts"  ( I use freezed and json_serializable ). The symptoms are a broken syntax coloration, I can't jump to source...

Everything seems to works when : 
- I switch to the Flutter dev channel (2.3.0-16.0.pre /  Dart 2.14.0 (build 2.14.0-136.0.dev))
- I disable the flutter plugin, set the Dart plugin SDk to the "standalone Dart" path (.../dart/libexec -> Dart 2.13.3 ) and open a "pure Dart" package with generated files
- I open the package in VSCode

## Dart analysis issue

RangeError (index): Invalid value: Not in inclusive range 0..12: 13

## Version information

- Dart SDK 2.13.1
- Dart IntelliJ 211.7233
- IntelliJ IDEA 2021.1.2
- Mac OS X 10.15.7

## Details

RangeError (index): Invalid value: Not in inclusive range 0..12: 13

```
#0      List.[] (dart:core-patch/array.dart:268:52)
#1      BestPracticesVerifier._targetKindsFor (package:analyzer/src/error/best_practices_verifier.dart:1601:38)
#2      BestPracticesVerifier.visitAnnotation (package:analyzer/src/error/best_practices_verifier.dart:253:17)
#3      AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:302:50)
#4      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#5      AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:145:17)
#6      MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6946:11)
#7      RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1071:10)
#8      BestPracticesVerifier.visitMethodDeclaration (package:analyzer/src/error/best_practices_verifier.dart:588:13)
#9      MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:6942:50)
#10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#11     MixinDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7199:13)
#12     RecursiveAstVisitor.visitMixinDeclaration (package:analyzer/dart/ast/visitor.dart:1083:10)
#13     BestPracticesVerifier.visitMixinDeclaration (package:analyzer/src/error/best_practices_verifier.dart:614:13)
#14     MixinDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7190:50)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7517:20)
#16     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2112:21)
#17     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:735:10)
#18     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2105:50)
#19     LibraryAnalyzer._computeHints (package:analyzer/src/dart/analysis/library_analyzer.dart:276:10)
#20     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:158:9)
#21     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
#22     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:157:13)
#23     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:104:12)
#24     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1315:63)
#25     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#26     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1286:20)
#27     AnalysisDriver._computeIndex (package:analyzer/src/dart/analysis/driver.dart:1381:26)
#28     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1001:39)
#29     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2006:24)
<asynchronous suspension>

#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:482:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1241:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:1164:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#4      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:402:11)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

## Debug log

```
1623397428932 <= {"id":"22"}
1623397428933 <= {"id":"23"}
1623397428935 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3169,"uri":"package:uuid/uuid.dart","items":[{"label":"ValidationMode","declaringLibraryUri":"package:uu...
1623397428935 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3170,"uri":"package:test_api/fake.dart","items":[{"label":"Fake","declaringLibraryUri":"package:test_api...
1623397428938 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3171,"uri":"package:test_api/test_api.dart","items":[{"label":"expectAsyncUntil6","declaringLibraryUri":...
1623397428939 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3172,"uri":"package:test_api/backend.dart","items":[{"label":"Runtime","declaringLibraryUri":"package:te...
1623397428942 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3173,"uri":"package:test_core/test_core.dart","items":[{"label":"expectAsyncUntil6","declaringLibraryUri...
1623397428945 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3174,"uri":"package:mime/mime.dart","items":[{"label":"defaultMagicNumbersMaxLength","declaringLibraryUr...
1623397428945 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3178,"uri":"package:quiver/core.dart","items":[{"label":"hashObjects","declaringLibraryUri":"package:qui...
1623397428946 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3179,"uri":"package:crypto/crypto.dart","items":[{"label":"sha512","declaringLibraryUri":"package:crypto...
1623397428952 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3180,"uri":"package:charcode/html_entity.dart","items":[{"label":"$sup","declaringLibraryUri":"package:c...
1623397428956 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3181,"uri":"package:charcode/ascii.dart","items":[{"label":"$b","declaringLibraryUri":"package:charcode/...
1623397428961 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3182,"uri":"package:charcode/charcode.dart","items":[{"label":"$sup","declaringLibraryUri":"package:char...
1623397428963 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3183,"uri":"package:test_api/scaffolding.dart","items":[{"label":"markTestSkipped","declaringLibraryUri"...
1623397428964 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3184,"uri":"package:test_api/backend.dart","items":[{"label":"Runtime","declaringLibraryUri":"package:te...
1623397428967 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3185,"uri":"package:test_api/test_api.dart","items":[{"label":"expectAsyncUntil6","declaringLibraryUri":...
1623397428968 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3186,"uri":"package:test_api/hooks.dart","items":[{"label":"TestFailure","declaringLibraryUri":"package:...
1623397428970 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3187,"uri":"package:test_api/expect.dart","items":[{"label":"expectAsyncUntil6","declaringLibraryUri":"p...
1623397428971 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3188,"uri":"package:test_core/scaffolding.dart","items":[{"label":"markTestSkipped","declaringLibraryUri...
1623397428975 <= {"event":"completion.availableSuggestions","params":{"changedLibraries":[{"id":3189,"uri":"package:test_core/test_core.dart","items":[{"label":"expectAsyncUntil6","declaringLibraryUri...
1623397429176 <= {"event":"analysis.highlights","params":{"file":"/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.freezed.dart","regions":[{"type":"DIRECTIV...
1623397429197 <= {"event":"analysis.navigation","params":{"file":"/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.freezed.dart","regions":[{"offset":533,"le...
1623397429205 <= {"event":"analysis.outline","params":{"file":"/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.freezed.dart","kind":"PART","outline":{"eleme...
1623397429215 <= {"event":"analysis.overrides","params":{"file":"/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.freezed.dart","overrides":[{"offset":2868,"...
1623397429223 <= {"event":"flutter.outline","params":{"file":"/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.freezed.dart","outline":{"kind":"DART_ELEMENT"...
1623397429229 <= {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
1623397429674 => {"id":"24","method":"edit.getAssists","params":{"file":"/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.freezed.dart","offset":0,"length":0...
1623397429680 <= {"id":"24","result":{"assists":[]}}
1623397430353 => {"id":"25","method":"analysis.setPriorityFiles","params":{"files":["/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.dart"]},"clientRequestT...
1623397430353 => {"id":"26","method":"analysis.setSubscriptions","params":{"subscriptions":{"OVERRIDES":["/Users/rxlabz/projects/YTBX020/dev/libs/yx_content_model/lib/src/activities/v2/item_data_v2.da...
```

**Comment by rxlabz** [comment]
Closing as the problem seems to be solved with the 2.2.2 stable release ( Dart 1.13.3 )
