### ISSUE TITLE
Flutter Plugin dies when `flutter upgrade` is run

### ISSUE THREAD

**Issue by spydx** [flutter/flutter-intellij#5579]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

---

## What happened

Open a Flutter project in IntelliJ, 
then open a terminal in IntelliJ.

Update the flutter framework through 
`flutter upgrade`
this crashes the plugin.

```sh
> flutter upgrade
Upgrading Flutter to 2.2.2 from 2.2.1 in /Users/username/flutter...
Downloading Dart SDK from Flutter engine 91c9fc8fe011352879e3bb6660966eafc0847233...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  2  200M    2 5854k    0     0  5104k      0  0:00:40  0:00:01  0:00:39 5099k
  7  200M    7 14.1M    0     0  6741k      0  0:00:30  0:00:02  0:00:28 6738k
 10  200M   10 20.8M    0     0  6771k      0  0:00:30  0:00:03  0:00:27 6769k
 15  200M   15 30.0M    0     0  7415k      0  0:00:27  0:00:04  0:00:23 7413k
 18  200M   18 37.7M    0     0  7518k      0  0:00:27  0:00:05  0:00:22 7864k
 22  200M   22 45.5M    0     0  7591k      0  0:00:26  0:00:06  0:00:20 8163k
 27  200M   27 54.2M    0     0  7779k      0  0:00:26  0:00:07  0:00:19 8224k
 31  200M   31 63.1M    0     0  7934k      0  0:00:25  0:00:08  0:00:17 8665k
 35  200M   35 71.1M    0     0  7967k      0  0:00:25  0:00:09  0:00:16 8425k
 39  200M   39 79.9M    0     0  8068k      0  0:00:25  0:00:10  0:00:15 8634k
 42  200M   42 84.6M    0     0  7773k      0  0:00:26  0:00:11  0:00:15 7996k
 46  200M   46 92.7M    0     0  7822k      0  0:00:26  0:00:12  0:00:14 7884k
 50  200M   50  101M    0     0  7917k      0  0:00:25  0:00:13  0:00:12 7891k
 55  200M   55  110M    0     0  7981k      0  0:00:25  0:00:14  0:00:11 8006k
 59  200M   59  118M    0     0  8013k      0  0:00:25  0:00:15  0:00:10 7900k
 63  200M   63  126M    0     0  8032k      0  0:00:25  0:00:16  0:00:09 8608k
 66  200M   66  133M    0     0  7957k      0  0:00:25  0:00:17  0:00:08 8284k
 70  200M   70  141M    0     0  7964k      0  0:00:25  0:00:18  0:00:07 8086k
 74  200M   74  149M    0     0  7971k      0  0:00:25  0:00:19  0:00:06 7942k
 78  200M   78  157M    0     0  8015k      0  0:00:25  0:00:20  0:00:05 8022k
 82  200M   82  165M    0     0  8010k      0  0:00:25  0:00:21  0:00:04 7939k
 86  200M   86  173M    0     0  8037k      0  0:00:25  0:00:22  0:00:03 8313k
 89  200M   89  179M    0     0  7948k      0  0:00:25  0:00:23  0:00:02 7891k
 93  200M   93  187M    0     0  7945k      0  0:00:25  0:00:24  0:00:01 7846k
 97  200M   97  195M    0     0  7948k      0  0:00:25  0:00:25 --:--:-- 7675k
100  200M  100  200M    0     0  7968k      0  0:00:25  0:00:25 --:--:-- 7778k
Building flutter tool...

Upgrading engine...
Downloading android-arm-profile/darwin-x64 tools...              1,390ms
Downloading android-arm-release/darwin-x64 tools...              1,296ms
Downloading android-arm64-profile/darwin-x64 tools...            1,282ms
Downloading android-arm64-release/darwin-x64 tools...              759ms
Downloading android-x64-profile/darwin-x64 tools...              1,458ms
Downloading android-x64-release/darwin-x64 tools...              1,161ms
Downloading android-x86 tools...                                    3.2s
Downloading android-x64 tools...                                 2,687ms
Downloading android-arm tools...                                 1,288ms
Downloading android-arm-profile tools...                           671ms
Downloading android-arm-release tools...                           774ms
Downloading android-arm64 tools...                               2,158ms
Downloading android-arm64-profile tools...                       1,011ms
Downloading android-arm64-release tools...                         759ms
Downloading android-x64-profile tools...                           880ms
Downloading android-x64-release tools...                           691ms
Downloading android-x86-jit-release tools...                     1,349ms
Downloading ios tools...                                            5.9s
Downloading ios-profile tools...                                    4.4s
Downloading ios-release tools...                                   29.0s
Downloading Web SDK...                                              3.8s

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (4 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2 RC)
[✓] VS Code (version 1.57.0)
[✓] Connected device (1 available)

• No issues found!
```

`flutter upgrade` finnishes and 
## Version information

IntelliJ IDEA `2021.1.2 RC` • Flutter plugin `io.flutter 57.0.5` • Dart plugin `211.7233`

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (4 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

## Exception

Trying to reset custom component in a presentation

```
java.lang.Throwable
	at com.intellij.openapi.actionSystem.Presentation.putClientProperty(Presentation.java:425)
	at com.intellij.openapi.actionSystem.Presentation.copyFrom(Presentation.java:397)
	at com.intellij.openapi.actionSystem.Presentation.copyFrom(Presentation.java:372)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$reflectSubsequentChangesInOriginalPresentation$9(ActionUpdater.java:140)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:308)
	at com.intellij.openapi.actionSystem.Presentation.fireBooleanPropertyChange(Presentation.java:348)
	at com.intellij.openapi.actionSystem.Presentation.setVisible(Presentation.java:315)
	at io.flutter.actions.DeviceSelectorAction.updateVisibility(DeviceSelectorAction.java:132)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$3(DeviceSelectorAction.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:415)
	at io.flutter.FlutterUtils.invokeAndWait(FlutterUtils.java:98)
	at io.flutter.actions.DeviceSelectorAction.update(DeviceSelectorAction.java:124)
	at io.flutter.actions.DeviceSelectorAction.lambda$queueUpdate$2(DeviceSelectorAction.java:119)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:287)
	at io.flutter.actions.DeviceSelectorAction.queueUpdate(DeviceSelectorAction.java:118)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$0(DeviceSelectorAction.java:85)
	at io.flutter.run.daemon.DeviceService.lambda$fireChangeEvent$4(DeviceService.java:159)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
Thanks for the detailed repro steps! This is just a (rather annoying) LOG message, and does not affect the plugin behavior.

Fixed in #5577
