### ISSUE TITLE
Stack trace truncated too soon

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter-intellij#5583]
## Steps to Reproduce

1. Make a flutter app that throws an exception. Any exception is good, such as `(null as bool?)!.toString();`.
2. Look at the logs. They are truncated, even though the "Include all stacktrace" option is enabled.

Example output log:
```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building StreamBuilder<ToiletsState>(dirty, state: _StreamBuilderBaseState<ToiletsState, AsyncSnapshot<ToiletsState>>#67f51):
type 'Null' is not a subtype of type 'int' of 'function result'

The relevant error-causing widget was: 
  StoreConnector<AppState, UserState> file:///D:/dev/app/v1/lib/pages/my_page.dart:233:23
When the exception was thrown, this was the stack: 
#0      MyData.overallRatingSum (package:myapp/models/my_page.dart)
#1      MyDataSum.calcAggregatedScoreInformation.<anonymous closure> (package:myapp/pages/my_page.dart:62:23)
#2      List.forEach (dart:core-patch/growable_array.dart:403:8)
#3      v.calcAggregatedScoreInformation (package:myapp/pages/my_page.dart:60:13)
#4      _MyPageState._createDataForUser (package:myapp/pages/my_page.dart:205:41)
...
====================================================================================================
```

## Version info

Flutter plugin version: 57.0.2

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.2 at D:\dev\Flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\dev\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = D:\dev\Android\Sdk
    • ANDROID_SDK_ROOT = D:\dev\Android\Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Chrome (web)                     • chrome        • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)                       • edge          • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!
```

**Comment by stevemessick** [comment]
@matanshukry Could you show us what the stack trace looks like when run from the command line?

**Comment by matanshukry** [comment]
I have a new computer completely now and it looks a bit different so I'm going to post it again completely, although the same issue still exists:

<details>
  <summary>Android Studio / Edge</summary>

```
======== Exception caught by gesture ===============================================================
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
packages/bug/main.dart 52:22                                                                                                   [_incrementCounter]
packages/flutter/src/material/ink_well.dart 989:21                                                                             [_handleTap]
packages/flutter/src/gestures/recognizer.dart 182:24                                                                           invokeCallback
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#a0888
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(1868.0, 914.0)
  finalLocalPosition: Offset(20.0, 17.0)
  button: 1
  sent tap down
====================================================================================================
```

</details>

<details>
  <summary>Terminal / Chrome</summary>

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown while handling a gesture:
Unexpected null value.

When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 518:63  nullCheck
packages/bug/main.dart 52:22                                                                                                   [_incrementCounter]
packages/flutter/src/material/ink_well.dart 989:21                                                                             [_handleTap]
packages/flutter/src/gestures/recognizer.dart 182:24                                                                           invokeCallback
packages/flutter/src/gestures/tap.dart 607:48                                                                                  handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                                                                   [_checkUp]
packages/flutter/src/gestures/tap.dart 267:7                                                                                   acceptGesture
packages/flutter/src/gestures/arena.dart 157:12                                                                                sweep
packages/flutter/src/gestures/binding.dart 443:20                                                                              handleEvent
packages/flutter/src/gestures/binding.dart 419:14                                                                              dispatchEvent
packages/flutter/src/rendering/binding.dart 287:11                                                                             dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                                                               [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                                                               handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                                                               [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                                                              [_handlePointerDataPacket]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 978:13                invoke1
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 177:5                 invokeOnPointerDataPacket
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 128:39                    [_onPointerData]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 553:18                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 506:21                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 214:16                    <fn>

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#5cb7a
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

**Comment by matanshukry** [comment]
@stevemessick please reopen tihs.

**Comment by jacob314** [comment]
If you try with tip of Trunk Flutter you should not see this issue.

**Comment by matanshukry** [comment]
@jacob314 yup, confirmed.

Do you know when the next release is going to be?
I couldn't find any information on when a release is happening.

**Comment by jacob314** [comment]
It is hard to predict when exactly the next release will be. You can try on the beta channel to see whether to expect a feature in the next stable release.
https://flutter.dev/docs/development/tools/sdk/releases
