### ISSUE TITLE
IllegalStateException: @NotNull method com/jetbrains/lang/dart/analyzer/DartAnalysisServerService.getInstance

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#5593]
## What happened

I opened an existing project (the flutter_tools project). I may have been updating the Flutter SDK in the background.

## Version information

IntelliJ IDEA `2021.1.2` • Flutter plugin `io.flutter 57.0.6-dev.5`

No Flutter sdk configured.

## Exception

null

```
java.lang.IllegalStateException: @NotNull method com/jetbrains/lang/dart/analyzer/DartAnalysisServerService.getInstance must not return null
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.$$$reportNull$$$0(DartAnalysisServerService.java)
	at com.jetbrains.lang.dart.analyzer.DartAnalysisServerService.getInstance(DartAnalysisServerService.java:725)
	at io.flutter.preview.OutlineOffsetConverter.getConvertedFileOffset(OutlineOffsetConverter.java:23)
	at io.flutter.preview.OutlineOffsetConverter.getConvertedOutlineOffset(OutlineOffsetConverter.java:28)
	at io.flutter.preview.PreviewView.addOutlinesCoveredByRange(PreviewView.java:505)
	at io.flutter.preview.PreviewView.applyEditorSelectionToTree(PreviewView.java:578)
	at io.flutter.preview.PreviewView$2.lambda$caretPositionChanged$0(PreviewView.java:122)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by devoncarew** [comment]
I'm on:

```
IntelliJ IDEA 2021.1.2 (Community Edition)
Build #IC-211.7442.40, built on May 31, 2021
```
