### ISSUE TITLE
Plugin exception

### ISSUE THREAD

**Issue by roscale** [flutter/flutter-intellij#5615]
## What happened

I compiled for the first time the demo app with flutter stable. I went to the terminal in the IDE to change the channel to dev. I ran flutter upgrade. After a few seconds this exception was thrown and the IDE told me to file this bug report.

## Version information (what the IDE gave me)

IntelliJ IDEA `2021.1.2` • Flutter plugin `io.flutter 57.0.5` • Dart plugin `211.7665`

No Flutter sdk configured.

## Version information (flutter doctor -v)

[✓] Flutter (Channel dev, 2.3.0-24.0.pre, on Arch Linux 5.12.12-xanmod1-1, locale en_US.UTF-8)
    • Flutter version 2.3.0-24.0.pre at /home/roscale/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (3 weeks ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/roscale/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at:
      /home/roscale/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.0
    • cmake version 3.20.5
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.2)
    • Android Studio at /home/roscale/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /home/roscale/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.7442.40
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7665

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Arch Linux 5.12.12-xanmod1-1

! Doctor found issues in 1 category.

## Exception

Trying to reset custom component in a presentation

```
java.lang.Throwable
	at com.intellij.openapi.actionSystem.Presentation.putClientProperty(Presentation.java:425)
	at com.intellij.openapi.actionSystem.Presentation.copyFrom(Presentation.java:397)
	at com.intellij.openapi.actionSystem.Presentation.copyFrom(Presentation.java:372)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$reflectSubsequentChangesInOriginalPresentation$9(ActionUpdater.java:140)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:308)
	at com.intellij.openapi.actionSystem.Presentation.fireBooleanPropertyChange(Presentation.java:348)
	at com.intellij.openapi.actionSystem.Presentation.setVisible(Presentation.java:315)
	at io.flutter.actions.DeviceSelectorAction.updateVisibility(DeviceSelectorAction.java:132)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$3(DeviceSelectorAction.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:415)
	at io.flutter.FlutterUtils.invokeAndWait(FlutterUtils.java:98)
	at io.flutter.actions.DeviceSelectorAction.update(DeviceSelectorAction.java:124)
	at io.flutter.actions.DeviceSelectorAction.lambda$queueUpdate$2(DeviceSelectorAction.java:119)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:287)
	at io.flutter.actions.DeviceSelectorAction.queueUpdate(DeviceSelectorAction.java:118)
	at io.flutter.actions.DeviceSelectorAction.lambda$update$0(DeviceSelectorAction.java:85)
	at io.flutter.run.daemon.DeviceService.lambda$fireChangeEvent$4(DeviceService.java:159)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
This is fixed in the latest release, published a few minutes ago.
