### ISSUE TITLE
Exceptions reported by IntelliJ IDEA after clicking `Open for Editing Android Studio`

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/flutter-intellij#5629]
## What happened

After clicking `Open for Editing Android Studio`, IntelliJ reported the following 4 exceptions.
I was testing my contribution done in #5606 and #5605 by setting Dev Channel.
The file does open as expected in Android Studio at the exact cursor.
Thought reporting these exceptions.

## Version information

IntelliJ IDEA `2021.1.3` • Flutter plugin `io.flutter 59.0.3-dev.2` • Dart plugin `211.7665`

<details>
<summary><code>$ flutter doctor -v</code></summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
    • Flutter version 2.2.3 at /home/hrk/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (11 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /mnt/common-data/softwares/android/sdk/linux
    • Platform android-S, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /mnt/common-data/softwares/android/sdk/linux
    • Java binary at: /snap/android-studio/105/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.2)
    • Android Studio at /snap/android-studio/105/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /snap/intellij-idea-community/310
    • Flutter plugin installed
    • Dart plugin version 211.7665

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

## Exception 1 - 
<details>
<summary><code>java.lang.Throwable: 2021-07-12 15:24:24,803 [   1338]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=com.android.tools.idea.AndroidInitialConfigurator)</code></summary>

```
java.lang.Throwable: 2021-07-12 15:24:24,803 [   1338]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=com.android.tools.idea.AndroidInitialConfigurator) 

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at io.flutter.actions.OpenInAndroidStudioAction$1.onTextAvailable(OpenInAndroidStudioAction.java:235)
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy52.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:102)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

## Exception 2 - 
<details>
<summary><code>java.lang.Throwable: 2021-07-12 15:24:26,070 [   2605]   WARN - nSystem.impl.ActionManagerImpl - keymap "ReSharper" not found [Plugin: com.android.tools.ndk]</code></summary>

```
java.lang.Throwable: 2021-07-12 15:24:26,070 [   2605]   WARN - nSystem.impl.ActionManagerImpl - keymap "ReSharper" not found [Plugin: com.android.tools.ndk] 

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at io.flutter.actions.OpenInAndroidStudioAction$1.onTextAvailable(OpenInAndroidStudioAction.java:235)
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy52.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:102)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

## Exception 3 - 
<details>
<summary><code>java.lang.Throwable: 2021-07-12 15:24:27,461 [   3996]   WARN - tartup.impl.StartupManagerImpl - Activities registered via registerPostStartupActivity must be dumb-aware: com.android.tools.idea.stats.AndroidStudioUsageTracker$ProjectLifecycleTracker$projectComponentsInitialized$1@69ca9480</code></summary>

```
java.lang.Throwable: 2021-07-12 15:24:27,461 [   3996]   WARN - tartup.impl.StartupManagerImpl - Activities registered via registerPostStartupActivity must be dumb-aware: com.android.tools.idea.stats.AndroidStudioUsageTracker$ProjectLifecycleTracker$projectComponentsInitialized$1@69ca9480 

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at io.flutter.actions.OpenInAndroidStudioAction$1.onTextAvailable(OpenInAndroidStudioAction.java:235)
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy52.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:102)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

## Exception 4 - 
<details>
<summary><code>java.lang.Throwable: 2021-07-12 15:24:34,927 [  11462]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=com.android.tools.idea.apk.ApkWritingAccessProvider)</code></summary>

```
java.lang.Throwable: 2021-07-12 15:24:34,927 [  11462]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=com.android.tools.idea.apk.ApkWritingAccessProvider) 

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
	at io.flutter.actions.OpenInAndroidStudioAction$1.onTextAvailable(OpenInAndroidStudioAction.java:235)
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy52.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:102)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

**Comment by helin24** [comment]
@hrishikesh-kadam These issues are reported by Android Studio as it starts up and are unrelated to the Flutter plugin; the plugin is just passing along the messages. 

Where were these messages reported for you? We see them when we start IntelliJ in a debugger and then click 'Open for editing.." there; they are reported in the console of the debug tool window.

**Comment by hrishikesh-kadam** [comment]
I first noticed it after adding dev channel to test `59.0.3-dev.2`.
I could see it in the bottom right corner as below - 

![Screenshot from 2021-07-20 01-46-57](https://user-images.githubusercontent.com/8739924/126228931-6f8329d1-f58b-4a6a-a2d0-0c8ca83be54c.png)

So after clicking "See details and submit report" I saw this window - 

![Screenshot from 2021-07-20 02-54-44](https://user-images.githubusercontent.com/8739924/126229554-9259c528-8830-40ef-8dd6-b321d762bc0f.png)

From which I created this single issue from those 4 errors.

Also, I can see these errors in the console of the debug window.

All these errors are pointing at [OpenInAndroidStudioAction.java:235](https://github.com/flutter/flutter-intellij/blob/890c07deec9f86420a93200a02626a8a057d0aaa/src/io/flutter/actions/OpenInAndroidStudioAction.java#L235).

**Comment by jacob314** [comment]
The fact that we are reporting those errors using LOG.error seems like a mistake. We should instead surface the error via
`FlutterMessages.showError`
or similar. This stack trace isn't really useful. The real message is the error message reported by android studio when it attempted to launch and perhaps failed? The other option is that while these messages are sent to stderr they are ignorable. For your case, did Android Studio still startup successfully. You could use LOG.warn or LOG.info to log these messages but not distract the user with them.

**Comment by hrishikesh-kadam** [comment]
@jacob314 As mentioned earlier, Android Studio does start correctly at the exact line and column.
I thought of just reporting the errors.

**Comment by stevemessick** [comment]
@hrishikesh-kadam Thanks for taking the time to report these errors. However, these are not caused by the Flutter plugin. The plugin is just passing along information reported by Android Studio when it starts up in the debugger. These messages are also reported by the production version but you only see them if you look in the log file.
