### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Wrong offset when modifying source externally

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter-intellij#5634]
## What happened

I was running a script that was modifying Flutter source code files. Perhaps importantly, the script was modifying samples (and removing dart code blocks) from the doc comments.

## Version information

IntelliJ IDEA `2021.1.3` • Flutter plugin `io.flutter 58.0.3` • Dart plugin `211.7665`

Flutter 2.4.0-5.0.pre.20 • channel master • git@github.com:gspencergoog/flutter.git
Framework • revision 1bf84b7cba (30 hours ago) • 2021-07-13 11:46:04 -0400
Engine • revision 0bf8bfdf17
Tools • Dart 2.14.0 (build 2.14.0-301.0.dev)

## Exception

null

```
java.lang.IndexOutOfBoundsException: Wrong offset: 224956. Should be in range: [0, 214857]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:165)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1008)
	at io.flutter.samples.DartDocumentUtils.getDartdocFor(DartDocumentUtils.java:31)
	at io.flutter.samples.FlutterSampleNotificationProvider.getSamplesFromDoc(FlutterSampleNotificationProvider.java:111)
	at io.flutter.samples.FlutterSampleNotificationProvider.lambda$createNotificationPanel$0(FlutterSampleNotificationProvider.java:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:830)
	at io.flutter.samples.FlutterSampleNotificationProvider.createNotificationPanel(FlutterSampleNotificationProvider.java:82)
	at io.flutter.samples.FlutterSampleNotificationProvider.createNotificationPanel(FlutterSampleNotificationProvider.java:34)
	at com.intellij.ui.EditorNotificationsImpl.calcNotificationUpdates(EditorNotificationsImpl.java:165)
	at com.intellij.ui.EditorNotificationsImpl.lambda$updateEditors$3(EditorNotificationsImpl.java:143)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by helin24** [comment]
@gspencergoog what sample were you working with?

**Comment by gspencergoog** [comment]
Pretty much all of them. I was working on a script that would extract the code from the samples and place it into external files, replacing the code with a pointer that looked like "/// [See code in examples/api/lib/widgets/navigator/transition_delegate.0.dart]", pointing to the place on disk where it was saved.

**Comment by stevemessick** [comment]
@gspencergoog These are the ones in flutter/flutter/examples? Or in flutter/samples?

**Comment by gspencergoog** [comment]
Neither. These are the samples currently embedded in the API doc comments for all of the widgets.

For example, I'm removing the [sample code here](https://cs.opensource.google/flutter/flutter/+/master:packages/flutter/lib/src/widgets/actions.dart;l=251;drc=3dea9f0251d7dcef7991f32a40b949c3a47911b6) from the doc comments and moving it into a separate file.

**Comment by stevemessick** [comment]
Thanks, that makes a lot more sense.

**Comment by stevemessick** [comment]
I'm having trouble reproducing this problem. My hypothesis is that the IDE's virtual file system got out of sync with the actual file content. But editing e.g. `widgets/actions.dart` to remove all the dartpad code then refreshing the IDE editor does not cause the issue to occur. It appears that changing focus away from the IDE causes the VFS to refresh. Were you running the script from the terminal emulator embedded in IntelliJ? Or maybe running the script from another machine?

**Comment by gspencergoog** [comment]
I was running the script from a "Dart command line" configuration.
