### ISSUE TITLE
The C:\ Drive Gets full suddenly

### ISSUE THREAD

**Issue by NourhanEl-khodary** [flutter/flutter-intellij#5647]
## What happened

While running any applipation the gradle building does not continue and the C:\ disk suddenly gets full.

## Version information

IntelliJ IDEA `2020.2.3` • Flutter plugin `io.flutter 58.0.1` • Dart plugin `202.8531` on Windows 10

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=test_app, containerState=ACTIVE, componentStore=D:\test_app) is being disposed so the child: null 501587121: running=false; canceled=false; task=null will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:69)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:70)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:95)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:43)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:35)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:31)
	at io.flutter.jxbrowser.JxBrowserManager.downloadJxBrowser(JxBrowserManager.java:278)
	at io.flutter.jxbrowser.JxBrowserManager.setUp(JxBrowserManager.java:237)
	at io.flutter.ProjectOpenActivity.runActivity(ProjectOpenActivity.java:62)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:300)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:226)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:298)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jacob314** [comment]
How much free space did you have before running the application?
