### ISSUE TITLE
ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction on start

### ISSUE THREAD

**Issue by koral--** [flutter/flutter-intellij#5653]
## Steps to Reproduce

Open Flutter project.

## Version info

Android Studio Bumblebee | 2021.1.1 Canary 3 • Flutter plugin io.flutter 58.0.3 • Dart plugin 211.7727

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

## Exception

```
com.intellij.diagnostic.PluginException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~/Library/Application Support/Google/AndroidStudioPreview2021.1/plugins/flutter-intellij, version=58.0.3, package=null), packagePrefix=null, instanceId=51, state=active)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:252)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:222)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:553)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:541)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:393)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:331)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.collectAllActions(WelcomeScreenActionsUtil.java:36)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.collectAllActions(WelcomeScreenActionsUtil.java:38)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.collectAllActions(WelcomeScreenActionsUtil.java:38)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.splitAndWrapActions(WelcomeScreenActionsUtil.java:167)
	at com.intellij.openapi.wm.impl.welcomeScreen.ProjectsTabFactory$1.createActionsToolbar(ProjectsTabFactory.java:180)
	at com.intellij.openapi.wm.impl.welcomeScreen.ProjectsTabFactory$1.buildComponent(ProjectsTabFactory.java:82)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$DefaultWelcomeScreenTab.getAssociatedComponent(TabbedWelcomeScreen.java:188)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$2.create(TabbedWelcomeScreen.java:132)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen$2.create(TabbedWelcomeScreen.java:124)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:83)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:111)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:96)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.lambda$new$0(TabbedWelcomeScreen.java:44)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(JList.java:1804)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1818)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:497)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2205)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.<init>(TabbedWelcomeScreen.java:75)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.<init>(FlatWelcomeFrame.java:91)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrameProvider.createFrame(FlatWelcomeFrameProvider.java:14)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.lambda$customizeFlatWelcomeFrame$2(FirstRunWizardFrameProvider.java:65)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:54)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.customizeFlatWelcomeFrame(FirstRunWizardFrameProvider.java:59)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.createFrame(FirstRunWizardFrameProvider.java:46)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$prepareToShow$1(WelcomeFrame.java:172)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.java:56)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.java:54)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$prepareToShow$2(WelcomeFrame.java:172)
	at com.intellij.idea.IdeStarter$showWizardAndWelcomeFrame$1.run(IdeStarter.kt:173)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~/Library/Application Support/Google/AndroidStudioPreview2021.1/plugins/flutter-intellij, version=58.0.3, package=null), packagePrefix=null, instanceId=51, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:235)
	... 70 more
```

**Comment by jacob314** [comment]
I'm guessing this is another Android Studio Bumblebee | 2021.1.1 Canary 3  isn't yet supported issue.
