### ISSUE TITLE
I Don't know what error is this, But this is an Error. I'm using Android Studio in Ubuntu 21.04 Hisrute Hippo. Please fix this issue ASAP.

### ISSUE THREAD

**Issue by BaraniARR** [flutter/flutter-intellij#5662]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `4.2.2` • Flutter plugin `io.flutter 58.0.1` • Dart plugin `202.8531`

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

## Exception

null

```
java.lang.IllegalArgumentException: Wrong end: 918; document length=810; start=914
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:62)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:38)
	at com.intellij.openapi.editor.impl.ErrorStripeMarkerImpl.<init>(ErrorStripeMarkerImpl.java:16)
	at com.intellij.openapi.editor.impl.ErrorStripeMarkersModel.createErrorStripeMarker(ErrorStripeMarkersModel.java:120)
	at com.intellij.openapi.editor.impl.ErrorStripeMarkersModel.attributesChanged(ErrorStripeMarkersModel.java:93)
	at com.intellij.openapi.editor.impl.ErrorStripeMarkersModel$1.attributesChanged(ErrorStripeMarkersModel.java:64)
	at com.intellij.openapi.editor.impl.MarkupModelImpl.fireAttributesChanged(MarkupModelImpl.java:270)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.fireChanged(RangeHighlighterImpl.java:352)
	at com.intellij.openapi.editor.impl.RangeHighlighterImpl.setErrorStripeMarkColor(RangeHighlighterImpl.java:230)
	at io.flutter.perf.PerfGutterIconRenderer.updateUI(EditorPerfDecorations.java:436)
	at io.flutter.perf.EditorPerfDecorations.updateIconUIAnimations(EditorPerfDecorations.java:191)
	at io.flutter.perf.EditorPerfDecorations.setHoverState(EditorPerfDecorations.java:255)
	at io.flutter.perf.EditorPerfDecorations.mouseEntered(EditorPerfDecorations.java:239)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseEnteredCommand(EditorImpl.java:3889)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseEntered(EditorImpl.java:3778)
	at java.desktop/java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:308)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6663)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
	at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:808)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
The original title included this info:
Android Studio in Ubuntu 21.04 Hisrute Hippo

**Comment by pq** [comment]
Related to the legacy performance view; closing as stale.
