### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by egaga** [flutter/flutter-intellij#5703]
## What happened

Was just updating markdown file when I noticed this. I did have open debugging connection to ios device.

## Version information

IntelliJ IDEA `2021.1.3` • Flutter plugin `io.flutter 58.0.3` • Dart plugin `211.7727`

Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

## Exception

Check after add Diff

Entity source filter: null

Version: v16.1
Saving store content at: /Users/egaga/Library/Logs/JetBrains/IntelliJIdea2021.1/workspaceModel/storeDump-20210804-124521

```
java.lang.NullPointerException
	at com.intellij.workspaceModel.storage.impl.references.OneToOneChild$NotNull.getValue(OneToOne.kt:45)
	at com.intellij.workspaceModel.storage.bridgeEntities.LibraryPropertiesEntity.getLibrary(bridgeModelEntities.kt)
	at com.intellij.workspaceModel.storage.bridgeEntities.LibraryPropertiesEntityData.assertConsistency(bridgeModelEntities.kt:603)
	at com.intellij.workspaceModel.storage.impl.EntitiesBarrel.assertConsistency(EntitiesBarrel.kt:130)
	at com.intellij.workspaceModel.storage.impl.AbstractEntityStorage.assertConsistency$intellij_platform_workspaceModel_storage(WorkspaceEntityStorageImpl.kt:848)
	at com.intellij.workspaceModel.storage.impl.AbstractEntityStorage.assertConsistencyInStrictMode$intellij_platform_workspaceModel_storage(WorkspaceEntityStorageImpl.kt:974)
	at com.intellij.workspaceModel.storage.impl.AddDiffOperation.addDiff(AddDiffOperation.kt:87)
	at com.intellij.workspaceModel.storage.impl.WorkspaceEntityStorageBuilderImpl.addDiff(WorkspaceEntityStorageImpl.kt:640)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl$commit$1.invoke(LibraryModifiableModelBridgeImpl.kt:98)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl$commit$1.invoke(LibraryModifiableModelBridgeImpl.kt:29)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.updateProjectModel(WorkspaceModelImpl.kt:86)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl.commit(LibraryModifiableModelBridgeImpl.kt:97)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at io.flutter.sdk.AbstractLibraryManager.lambda$updateLibraryContent$2(AbstractLibraryManager.java:100)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:258)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:244)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.java:503)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:244)
	at io.flutter.sdk.AbstractLibraryManager.lambda$updateLibraryContent$3(AbstractLibraryManager.java:99)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at io.flutter.sdk.AbstractLibraryManager.updateLibraryContent(AbstractLibraryManager.java:84)
	at io.flutter.sdk.AbstractLibraryManager.updateLibraryContent(AbstractLibraryManager.java:57)
	at io.flutter.sdk.FlutterPluginsLibraryManager.updateFlutterPluginsImpl(FlutterPluginsLibraryManager.java:119)
	at io.flutter.sdk.FlutterPluginsLibraryManager.updateFlutterPlugins(FlutterPluginsLibraryManager.java:106)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$9(DumbServiceImpl.java:532)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
This is caused by the experimental option that indexes Java and Kotlin in the Android module. You can tun that off to stop the error from happening. We recommend opening the Android module in Android Studio as a top-level project, just as you would open an iOS project in Xcode.

Does this error happen every time or was this a single failure in an otherwise usable project? Have you made any changes in the `android` (or `.android`) directory?

I am a little surprised this would even be triggered by changes to a markdown file. We should look into that.

**Comment by egaga** [comment]
Thank you for answering.

I think it may have happened before, but I didn't bother to make an error report (it could have been some other error.)

Not sure if it relates to editing a markdown file, I just was doing that when _I noticed_ it, sorry being misleading.

I think my only non-external changes are (by glimpsing Intellij local history) :

- build.grade:
`minSdkVersion 21`
   
- AndroidManifest.xml
```
<intent>
        <action android:name="android.media.action.IMAGE_CAPTURE" />
</intent>
```

Otherwise the changes should be automatic.

I hopefully remember to report here next time I encounter it.

**Comment by stevemessick** [comment]
Thanks for the update.
