### ISSUE TITLE
Idea froze while creating new project

### ISSUE THREAD

**Issue by mbreissi** [flutter/flutter-intellij#5707]
# What happened

Creating a new flutter project.  Idea hung while creating the project.  I killed it 
using task manager.  It had created the project files/structure so I started Idea and attempted to open the
created project.  Idea crashed again while opening but restarted itself and successfully opened the project.
 
## Version information

IntelliJ IDEA `2021.2` • Flutter plugin `io.flutter 58.0.4` • Dart plugin `212.4746.57` • Windows 11 Build 22000

Error getting Flutter sdk information.

## Exception

Cannot save entities to Dart_SDK.xml because it's already used for other entities;
Current entity source: FileInDirectory(directory=file://C:/Users/breis/source/flutter/layout_tutorial/.idea/libraries, fileNameId=10, projectLocation=DirectoryBased(projectDir=file://C:/Users/breis/source/flutter/layout_tutorial, ideaFolder=file://C:/Users/breis/source/flutter/layout_tutorial/.idea))
Old file name: null
Existing serializers: [JpsLibraryEntitiesSerializer(file://C:/Users/breis/source/flutter/layout_tutorial/.idea/libraries/Dart_SDK.xml)]
Their entity sources: [FileInDirectory(directory=file://C:/Users/breis/source/flutter/layout_tutorial/.idea/libraries, fileNameId=7, projectLocation=DirectoryBased(projectDir=file://C:/Users/breis/source/flutter/layout_tutorial, ideaFolder=file://C:/Users/breis/source/flutter/layout_tutorial/.idea))]
Entities with these sources in the storage: {}

Entity source filter: null

Version: v22
Saving store content at: C:\Users\breis\AppData\Local\JetBrains\IdeaIC2021.2\log\workspaceModel\storeDump-20210809-065322

```
java.lang.IllegalStateException
	at com.intellij.workspaceModel.storage.impl.ErrorReportingKt.reportErrorAndAttachStorage(ErrorReporting.kt:19)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectSerializersImpl.saveEntities(JpsProjectSerializersImpl.kt:630)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.saveChangedProjectEntities(JpsProjectModelSynchronizer.kt:281)
	at com.intellij.configurationStore.ProjectStoreBridge.saveModules(ProjectStoreBridge.kt:34)
	at com.intellij.configurationStore.ProjectWithModulesStoreImpl.saveModules(ProjectStoreImpl.kt:166)
	at com.intellij.configurationStore.ProjectStoreImpl$doSave$2$1.invokeSuspend(ProjectStoreImpl.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.configurationStore.StoreUtil$Companion.saveSettings(storeUtil.kt:49)
	at com.intellij.configurationStore.StoreUtil.saveSettings(storeUtil.kt)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:74)
	at io.flutter.utils.FlutterModuleUtils.setFlutterModuleAndReload(FlutterModuleUtils.java:363)
	at io.flutter.project.FlutterProjectOpenProcessor.convertToFlutterProject(FlutterProjectOpenProcessor.java:92)
	at io.flutter.project.FlutterProjectOpenProcessor.doOpenProject(FlutterProjectOpenProcessor.java:71)
	at com.intellij.ide.impl.ProjectUtil.lambda$chooseProcessorAndOpenAsync$12(ProjectUtil.java:365)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
I'm afraid the diagnostic information you've provided does not help determine the root problem. It appears to be generated by IntelliJ restarting itself. I've never seen that happen, so I don't know what might have caused it. The initial problem (hanging) seems to have happened before the Flutter tool had completely generated all the files in your new project. If the project had been fully generated you would not have gone down the control path that caused the stack trace.

Are you able to create new Flutter projects using IntelliJ?
