### ISSUE TITLE
Generated bug report

### ISSUE THREAD

**Issue by pulstar** [flutter/flutter-intellij#5831]
## What happened

Nothing special... I just came back from Windows hibernation and the error appeared in the log.

## Version information

Android Studio `Arctic Fox | 2020.3.1 Patch 3` • Flutter plugin `io.flutter 61.2.2` • Dart plugin `203.8430`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:142)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:130)
	at io.flutter.perf.FlutterWidgetPerf.dispose(FlutterWidgetPerf.java:513)
	at io.flutter.perf.FlutterWidgetPerfManager.updateCurrentAppChanged(FlutterWidgetPerfManager.java:276)
	at io.flutter.utils.StreamSubscription.notify(StreamSubscription.java:43)
	at io.flutter.utils.EventStream.lambda$setValue$0(EventStream.java:78)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:330)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## Version info

[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [version 10.0.19042.1288], locale pt-BR)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\pulst\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\pulst\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • Vivo XI (mobile)  • PRUCHYWGG6HYSK4H • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [version 10.0.19042.1288]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 94.0.4606.81
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 94.0.992.31

! Doctor found no issues.

**Comment by jinjilynn** [comment]
`import 'package:flutter_bloc/flutter_bloc.dart';`

**Comment by jinjilynn** [comment]
`import 'package:flutter_bloc/flutter_bloc.dart';
    class BottomNav extends StatelessWidget {
      BottomNav({Key? key}) : super(key: key);
      Map<String, String> localMap = {
        "Home": S.current.Home,
        "CM": "CM",
        "PM": "PM",
        "Messages": S.current.Messages
      };
      @override
      Widget build(BuildContext context) {
        return ConvexAppBar.badge(
          const {3: '99+'},
          backgroundColor: context.read<CommonRespository>().basicColor[600],
          badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
          style: TabStyle.react,
          items: bottomBar.values
              .map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
              .toList(),
          initialActiveIndex: 0,
          onTap: (index) {
            context.router.pushNamed('/CM');
          },
        );
      }
    }
`

**Comment by jinjilynn** [comment]
`    class BottomNav extends StatelessWidget {
      BottomNav({Key? key}) : super(key: key);
      Map<String, String> localMap = {
        "Home": S.current.Home,
        "CM": "CM",
        "PM": "PM",
        "Messages": S.current.Messages
      };
      @override
      Widget build(BuildContext context) {
        return ConvexAppBar.badge(
          const {3: '99+'},
          backgroundColor: context.read<CommonRespository>().basicColor[600],
          badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
          style: TabStyle.react,
          items: bottomBar.values
              .map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
              .toList(),
          initialActiveIndex: 0,
          onTap: (index) {
            context.router.pushNamed('/CM');
          },
        );
      }
    }`

**Comment by jinjilynn** [comment]
`import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:offline_solution/global_respository/common.dart';
`

**Comment by jinjilynn** [comment]
```dart

import 'package:auto_route/auto_route.dart';
import 'package:convex_bottom_bar/convex_bottom_bar.dart';
import 'package:flutter/material.dart';
import 'package:offline_solution/config/bottom_bar.dart';
import 'package:offline_solution/generated/l10n.dart';
import 'package:offline_solution/global_respository/common.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:offline_solution/routes/bloc/bloc.dart';

    class BottomNav extends StatelessWidget {
      BottomNav({Key? key}) : super(key: key);
      Map<String, String> localMap = {
        "Home": S.current.Home,
        "CM": "CM",
        "PM": "PM",
        "Messages": S.current.Messages
      };
      @override
      Widget build(BuildContext context) {
        return ConvexAppBar.badge(
          const {3: '99+'},
          backgroundColor: context.read<CommonRespository>().basicColor[600],
          badgeMargin: const EdgeInsets.only(bottom: 30, left: 30),
          style: TabStyle.react,
          items: bottomBar.values
              .map((e) => TabItem(title: localMap[e['path']], icon: e['icon']))
              .toList(),
          initialActiveIndex: 0,
          onTap: (index) {
            context.router.pushNamed('/CM');
          },
        );
      }
    }

```
