### ISSUE TITLE
Cannot save entities to Dart_SDK.xml because it's already used for other entities

### ISSUE THREAD

**Issue by BorzdeG** [flutter/flutter-intellij#5847]
## Version information

IntelliJ IDEA `2021.2.3` • Flutter plugin `io.flutter 61.2.4` • Dart plugin `212.5632`

Flutter 2.7.0-3.1.pre • channel beta • git@github.com:flutter/flutter.git
Framework • revision fc7015e35a (4 days ago) • 2021-10-27 15:18:41 -0700
Engine • revision a75e3b80f9
Tools • Dart 2.15.0 (build 2.15.0-178.1.beta)

## Exception

Cannot save entities to Dart_SDK.xml because it's already used for other entities;
Current entity source: FileInDirectory(directory=file:///$PROJECT_DIR/.idea/libraries, fileNameId=5, projectLocation=DirectoryBased(projectDir=file:///$PROJECT_DIR, ideaFolder=file:///$PROJECT_DIR/.idea))
Old file name: null
Existing serializers: [JpsLibraryEntitiesSerializer(file:///$PROJECT_DIR/.idea/libraries/Dart_SDK.xml)]
Their entity sources: [FileInDirectory(directory=file:///$PROJECT_DIR/.idea/libraries, fileNameId=1, projectLocation=DirectoryBased(projectDir=file:///$PROJECT_DIR, ideaFolder=file:///$PROJECT_DIR/.idea))]
Entities with these sources in the storage: {}

Entity source filter: null

Version: v22
Saving store content at: /Users/borz/Library/Logs/JetBrains/IntelliJIdea2021.2/workspaceModel/storeDump-20211031-131120

```
java.lang.IllegalStateException
	at com.intellij.workspaceModel.storage.impl.ErrorReportingKt.reportErrorAndAttachStorage(ErrorReporting.kt:19)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectSerializersImpl.saveEntities(JpsProjectSerializersImpl.kt:630)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.saveChangedProjectEntities(JpsProjectModelSynchronizer.kt:281)
	at com.intellij.configurationStore.ProjectStoreBridge.saveModules(ProjectStoreBridge.kt:34)
	at com.intellij.configurationStore.ProjectWithModulesStoreImpl.saveModules(ProjectStoreImpl.kt:166)
	at com.intellij.configurationStore.ProjectStoreImpl$doSave$2$1.invokeSuspend(ProjectStoreImpl.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.configurationStore.StoreUtil$Companion.saveSettings(storeUtil.kt:49)
	at com.intellij.configurationStore.StoreUtil.saveSettings(storeUtil.kt)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:74)
	at io.flutter.utils.FlutterModuleUtils.setFlutterModuleAndReload(FlutterModuleUtils.java:363)
	at io.flutter.project.FlutterProjectOpenProcessor.convertToFlutterProject(FlutterProjectOpenProcessor.java:92)
	at io.flutter.project.FlutterProjectOpenProcessor.doOpenProject(FlutterProjectOpenProcessor.java:71)
	at com.intellij.ide.impl.ProjectUtil.lambda$chooseProcessorAndOpenAsync$12(ProjectUtil.java:365)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
I cannot reproduce this problem. Please provide more detail on the sequence of events that lead to this exception. If possible, also attach a project that reproduces the issue.
