### ISSUE TITLE
Plugin crash after closing IntelliJ settings / "plugins" page

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter-intellij#5860]
---

## What happened

See title

## Version information

IntelliJ IDEA `2021.2.3` • Flutter plugin `io.flutter 62.0.3` • Dart plugin `212.5632`

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

## Exception

null

```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'long com.intellij.util.net.NetUtils.copyStreamContent(com.intellij.openapi.progress.ProgressIndicator, java.io.InputStream, java.io.OutputStream, long)'
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.intellij.util.download.impl.FileDownloaderImpl.download(FileDownloaderImpl.java:250)
	at io.flutter.jxbrowser.JxBrowserManager$1.run(JxBrowserManager.java:269)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'long com.intellij.util.net.NetUtils.copyStreamContent(com.intellij.openapi.progress.ProgressIndicator, java.io.InputStream, java.io.OutputStream, long)'
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:435)
	at com.intellij.util.download.impl.FileDownloaderImpl$2.process(FileDownloaderImpl.java:341)
	at com.intellij.util.download.impl.FileDownloaderImpl$2.process(FileDownloaderImpl.java:332)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at com.intellij.util.download.impl.FileDownloaderImpl.downloadFile(FileDownloaderImpl.java:332)
	at com.intellij.util.download.impl.FileDownloaderImpl.lambda$download$1(FileDownloaderImpl.java:229)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	... 7 more
```

**Comment by stevemessick** [comment]
I cannot reproduce this problem. Do you have multiple versions of IntelliJ installed? The missing method was introduced quite recently, and I think is only available in 2021.3 or later, but your header indicates you are using 2021.2.
