### ISSUE TITLE
Exception when running newly created default flutter app

### ISSUE THREAD

**Issue by enzopapiro** [flutter/flutter-intellij#5865]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## What happened
Developing on a Mac mini (intel) / macOS Big Sur.

Created default flutter app in Android Studio, Ran it using a simulator and got the exception in "IDE Fatal Errors" dialog  (iOS or Android yields same result).

Was looking to get details of the app inside the Flutter Inspector, this presently doesn't work I guess it is related to the exception below.

## Version information

Android Studio `Arctic Fox | 2020.3.1 Patch 3` • Flutter plugin `io.flutter 62.0.1` • Dart plugin `203.8452`

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (5 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

## Exception

null

```
java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/s5/ckvb659x26vd4gs1f_7nr51h0000gn/T/JxBrowser/7.19/libawt_toolkit.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.teamdev.jxbrowser.internal.JniLibrary.loadLibrary(JniLibrary.java:53)
	at com.teamdev.jxbrowser.internal.JniLibrary.lambda$new$0(JniLibrary.java:47)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.teamdev.jxbrowser.internal.JniLibrary.<init>(JniLibrary.java:45)
	at com.teamdev.jxbrowser.internal.AwtHelperLibrary.<init>(AwtHelperLibrary.java:46)
	at com.teamdev.jxbrowser.internal.AwtHelperLibrary.instance(AwtHelperLibrary.java:36)
	at com.teamdev.jxbrowser.view.swing.internal.IoSurfaceRenderWidget.<init>(IoSurfaceRenderWidget.java:40)
	at com.teamdev.jxbrowser.view.swing.BrowserView.createBrowserWidget(BrowserView.java:170)
	at com.teamdev.jxbrowser.view.swing.BrowserView.<init>(BrowserView.java:103)
	at com.teamdev.jxbrowser.view.swing.BrowserView.newInstance(BrowserView.java:76)
	at io.flutter.jxbrowser.EmbeddedBrowser.lambda$openPanel$1(EmbeddedBrowser.java:134)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:330)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by enzopapiro** [comment]
No longer experiencing issue after IDE restart.
