### ISSUE TITLE
I get an Ansroid Stuiod error when open Flutter project.

### ISSUE THREAD

**Issue by liujiakuoyx** [flutter/flutter-intellij#5888]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

I get an Ansroid Stuiod error when open Flutter project.

## Version information

Android Studio `Arctic Fox | 2020.3.1 Patch 3` • Flutter plugin `io.flutter 63.0.1` • Dart plugin `203.8452`

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (6 months ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

## Exception

null

```
java.lang.RuntimeException: java.io.EOFException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:143)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java:518)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:1325)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.readContent(PersistentFSImpl.java:243)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:551)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:126)
	at io.flutter.FlutterUtils.readPubspecFileToMap(FlutterUtils.java:452)
	at io.flutter.FlutterUtils.getFlutterPubspecInfo(FlutterUtils.java:392)
	at io.flutter.pub.PubRoot.validateUpdateCachedPubspecInfo(PubRoot.java:238)
	at io.flutter.pub.PubRoot.declaresFlutter(PubRoot.java:229)
	at io.flutter.utils.FlutterModuleUtils.declaresFlutter(FlutterModuleUtils.java:291)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:92)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:329)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:303)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$3(StartupManagerImpl.java:239)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:399)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:391)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:330)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:828)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.EOFException
	at com.intellij.util.io.storage.RefCountingStorage$CustomInflaterInputStream.fill(RefCountingStorage.java:84)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.intellij.openapi.util.io.StreamUtil.copy(StreamUtil.java:27)
	at com.intellij.util.io.storage.RefCountingStorage.internalReadStream(RefCountingStorage.java:69)
	at com.intellij.util.io.storage.RefCountingStorage.readStream(RefCountingStorage.java:53)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.doReadContentById(FSRecords.java:1343)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.readContent(FSRecords.java:1319)
	... 44 more
```

**Comment by stevemessick** [comment]
It looks like your `pubspec.yaml` file is bad. Try running `flutter pub get` from a terminal. You may need to delete the `pubspec.yaml` file first. Let us know if that helps.

**Comment by liujiakuoyx** [comment]
Thanks~,I didn't do anything, just restart ide. This error report was never received again.
