### ISSUE TITLE
Exception while coding/debugging

### ISSUE THREAD

**Issue by tiloc** [flutter/flutter-intellij#5898]
## What happened

This exception occurs in random intervals while coding/debugging with Flutter in IntelliJ. Impact unknown, I can continue to work.

## Version information

IntelliJ IDEA `2021.3.1` • Flutter plugin `io.flutter 63.2.4` • Dart plugin `213.5744.122`

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (2 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: No library matching [package:flutter/src/widgets/widget_inspector.dart] found.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.flutter.inspector.EvalOnDartLibrary$4.received(EvalOnDartLibrary.java:295)
	at org.dartlang.vm.service.VmService.forwardResponse(VmService.java:950)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:619)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
Caused by: java.lang.RuntimeException: No library matching [package:flutter/src/widgets/widget_inspector.dart] found.
	... 6 more
```

**Comment by stevemessick** [comment]
Does restarting the Dart analysis server have any effect?

If not, can you enable verbose logging and attach the tail-end of the log file after this happens again?
