### ISSUE TITLE
Initial app run consistently loads old version of app

### ISSUE THREAD

**Issue by ScottPierce** [flutter/flutter-intellij#590]
Every time I run my flutter application from IntelliJ, it loads an old, out of date version of my application from days ago.

It ends up producing weird issues. If I launch the debug version of the application, with a break point set, my application seems to be crashing and never getting to a point where I can refresh it. I have to launch into debug mode, refresh my application, and then set a break point before I can properly debug.

## Steps to Reproduce
1. Click the IntelliJ run button to run the flutter configuration
2. Watch an old version of the application (from days ago) get loaded into the android emulator.
3. Press hot reload, or app restart button, and now the app has all the changes from the past few days.

## Version info
```
flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Volumes/MacintoshHD/Users/spierce7/frameworks/flutter
    • Framework revision d05c7f62f2 (2 weeks ago), 2016-12-21 06:19:42
    • Engine revision 2f32e8054d
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • ANDROID_HOME = /Volumes/MacintoshHD/Users/spierce7/Android/sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[-] iOS toolchain - develop for iOS devices
    x XCode not installed; this is necessary for iOS development.
      Download at https://developer.apple.com/xcode/download/.
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3.2)
    • Dart plugin version 163.11306
    • Flutter plugin version 0.1.7

[✓] Connected devices
    • Google Nexus 5X, 7 0 0, API 24, 1080x1920 • 192.168.56.101:5555 • android-x86 • Android 7.0 (API 24)
```

**Comment by mit-mit** [comment]
Sorry to hear that @ScottPierce! I'm curious, If you `flutter run` the same app from the terminal does it have the same issue or not?

**Comment by devoncarew** [comment]
The current process for running the app is:
- create a snapshot of your code
- ship it over to the device
- start the app (from the snapshot)
- connect to the app via a debug connection
- ship all the Dart source over
- when we restart (a hot reload or a full restart) we use the source shipped over

It sounds like somehow we're failing to use the new snapshot when starting the app. Perhaps we're failing to write the new snapshot to the phone? An error like that should stop the launch process. Can you start up `adb logcat` from a command-line terminal and see if any errors show up for your next launch?

**Comment by ScottPierce** [comment]
Confirmed that `flutter run` from the IntelliJ command line has the same issue.

The first time I run the app from a fresh emulator, I get this "MTP Host has stopped" error dialog popping up. I assumed initially that it was a genymotion process, but maybe the MTP process is owned by flutter?

Here is the log:
```
01-04 12:00:08.995 D/WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
                                     
                                     --------- beginning of system
01-04 12:00:08.996 E/BatteryStatsService: no controller energy info supplied
01-04 12:00:14.761 D/InitAlarmsService: Clearing and rescheduling alarms.
01-04 12:00:22.936 W/WifiMode: WiredSSID, Invalid SupportedRates!!!
01-04 12:00:22.936 W/WifiMode: WiredSSID, Invalid SupportedRates!!!
01-04 12:00:22.937 W/WifiMode: WiredSSID, Invalid SupportedRates!!!
01-04 12:00:24.959 D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-04 12:00:24.961 D/AndroidRuntime: CheckJNI is OFF
01-04 12:00:24.976 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:24.978 D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
01-04 12:00:24.988 E/memtrack: Couldn't load memtrack module (No such file or directory)
01-04 12:00:24.989 E/android.os.Debug: failed to load memtrack module: -2
01-04 12:00:24.989 I/Radio-JNI: register_android_hardware_Radio DONE
01-04 12:00:24.993 D/AndroidRuntime: Calling main entry com.android.commands.am.Am
01-04 12:00:24.995 I/ActivityManager: Force stopping com.yourcompany.test appid=10100 user=0: from pid 1505
01-04 12:00:24.996 D/AndroidRuntime: Shutting down VM
01-04 12:00:24.997 D/CarrierSvcBindHelper: No carrier app for: 0
01-04 12:00:25.197 D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-04 12:00:25.198 D/AndroidRuntime: CheckJNI is OFF
01-04 12:00:25.214 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.216 D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
01-04 12:00:25.227 E/memtrack: Couldn't load memtrack module (No such file or directory)
01-04 12:00:25.227 E/android.os.Debug: failed to load memtrack module: -2
01-04 12:00:25.227 I/Radio-JNI: register_android_hardware_Radio DONE
01-04 12:00:25.231 D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
01-04 12:00:25.235 W/MessageQueue: Handler (android.os.Handler) {113e4e7} sending message to a Handler on a dead thread
                                   java.lang.IllegalStateException: Handler (android.os.Handler) {113e4e7} sending message to a Handler on a dead thread
                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                       at android.os.Handler.enqueueMessage(Handler.java:643)
                                       at android.os.Handler.sendMessageAtTime(Handler.java:612)
                                       at android.os.Handler.sendMessageDelayed(Handler.java:582)
                                       at android.os.Handler.post(Handler.java:338)
                                       at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
                                       at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
                                       at android.os.Binder.execTransact(Binder.java:565)
01-04 12:00:25.235 I/art: System.exit called, status: 0
01-04 12:00:25.235 I/AndroidRuntime: VM exiting with result code 0.
01-04 12:00:25.290 I/ActivityManager: Force stopping com.yourcompany.test appid=10100 user=-1: deletePackageX
01-04 12:00:25.321 I/art: Starting a blocking GC Explicit
01-04 12:00:25.337 I/art: Explicit concurrent mark sweep GC freed 20319(1032KB) AllocSpace objects, 5(192KB) LOS objects, 33% free, 9MB/13MB, paused 349us total 15.899ms
01-04 12:00:25.345 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.348 I/ActivityManager: Start proc 1535:com.android.defcontainer/u0a7 for service com.android.defcontainer/.DefaultContainerService
01-04 12:00:25.349 I/ActivityManager: Force stopping com.yourcompany.test appid=10100 user=0: pkg removed
01-04 12:00:25.359 I/LatinIME:LogUtils: Dictionary info: dictionary = main:en ; version = 54 ; date = 1414726273
01-04 12:00:25.359 I/InputReader: Reconfiguring input devices.  changes=0x00000010
01-04 12:00:25.363 D/CarrierSvcBindHelper: No carrier app for: 0
01-04 12:00:25.368 I/art: Debugger is no longer active
01-04 12:00:25.368 I/art: Starting a blocking GC Instrumentation
01-04 12:00:25.373 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.381 I/ActivityManager: Start proc 1551:com.android.gallery3d/u0a45 for broadcast com.android.gallery3d/.app.PackagesMonitor
                                      
                                      [ 01-04 12:00:25.390   146:  146 I/         ]
                                      free_cache(9685011) avail 13148147712
01-04 12:00:25.395 W/LocationProviderProxy-network: Odd, no component found for service com.android.location.service.v3.NetworkLocationProvider
01-04 12:00:25.395 W/GeocoderProxy: Odd, no component found for service com.android.location.service.GeocodeProvider
01-04 12:00:25.395 W/GeofenceProxy: Odd, no component found for service com.android.location.service.GeofenceProvider
01-04 12:00:25.395 W/ActivityRecognitionProxy: Odd, no component found for service com.android.location.service.ActivityRecognitionProvider
01-04 12:00:25.447 W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1385 android.content.ContextWrapper.startService:613 android.content.ContextWrapper.startService:613 com.android.keychain.KeyChainBroadcastReceiver.onReceive:12 android.app.ActivityThread.handleReceiver:3011 
01-04 12:00:25.454 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.459 I/ActivityManager: Start proc 1575:com.android.musicfx/u0a16 for broadcast com.android.musicfx/.Compatibility$Receiver
01-04 12:00:25.488 W/System: ClassLoader referenced unknown path: /system/priv-app/MusicFX/lib/x86
01-04 12:00:25.497 D/VoicemailCleanupService: Cleaning up data for package: com.yourcompany.test
01-04 12:00:25.512 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.515 I/ActivityManager: Start proc 1592:com.android.documentsui/u0a9 for broadcast com.android.documentsui/.PackageReceiver
01-04 12:00:25.540 W/System: ClassLoader referenced unknown path: /system/priv-app/DocumentsUI/lib/x86
01-04 12:00:25.583 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.592 I/ActivityManager: Start proc 1607:com.android.externalstorage/u0a13 for content provider com.android.externalstorage/.ExternalStorageProvider
01-04 12:00:25.597 I/ActivityManager: Killing 976:com.android.cellbroadcastreceiver/u0a4 (adj 906): empty #17
01-04 12:00:25.607 I/ActivityManager: Killing 1321:com.android.dialer/u0a8 (adj 906): empty #17
01-04 12:00:25.619 W/System: ClassLoader referenced unknown path: /system/priv-app/ExternalStorageProvider/lib/x86
01-04 12:00:25.629 D/ExternalStorage: After updating volumes, found 2 active roots
01-04 12:00:25.650 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:25.657 I/ActivityManager: Start proc 1624:com.android.mtp/u0a10 for content provider com.android.mtp/.MtpDocumentsProvider
01-04 12:00:25.659 I/ActivityManager: Killing 1403:com.android.managedprovisioning/u0a15 (adj 906): empty #17
01-04 12:00:25.691 D/VoldConnector: SND -> {7 appfuse mount 10010 1624 MtpDocumentsProvider}
01-04 12:00:25.692 E/vold: Failed to mount /mnt/appfuse/10010_MtpDocumentsProvider: Invalid argument
01-04 12:00:25.696 D/VoldConnector: RCV <- {400 7 Command failed}
01-04 12:00:25.696 D/AndroidRuntime: Shutting down VM
                                     
                                     
                                     --------- beginning of crash
01-04 12:00:25.697 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.android.mtp, PID: 1624
                                     java.lang.RuntimeException: Unable to get provider com.android.mtp.MtpDocumentsProvider: java.lang.IllegalStateException: command '7 appfuse mount 10010 1624 MtpDocumentsProvider' failed with '400 7 Command failed'
                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5814)
                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
                                         at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                      Caused by: java.lang.IllegalStateException: command '7 appfuse mount 10010 1624 MtpDocumentsProvider' failed with '400 7 Command failed'
                                         at android.os.Parcel.readException(Parcel.java:1691)
                                         at android.os.Parcel.readException(Parcel.java:1636)
                                         at android.os.storage.IMountService$Stub$Proxy.mountAppFuse(IMountService.java:1368)
                                         at android.os.storage.StorageManager.mountAppFuse(StorageManager.java:1239)
                                         at com.android.mtp.AppFuse.mount(AppFuse.java:69)
                                         at com.android.mtp.MtpDocumentsProvider.onCreate(MtpDocumentsProvider.java:136)
                                         at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
                                         at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
                                         at android.provider.DocumentsProvider.attachInfo(DocumentsProvider.java:177)
                                         at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
                                         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403) 
                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342) 
                                         at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                         at android.os.Looper.loop(Looper.java:154) 
                                         at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
01-04 12:00:25.737 I/OpenGLRenderer: Initialized EGL, version 1.4
01-04 12:00:25.738 D/OpenGLRenderer: Swap behavior 1
                                     
                                     [ 01-04 12:00:25.738   623: 1642 D/         ]
                                     HostConnection::get() New Host Connection established 0xd0226fa0, tid 1642
01-04 12:00:26.321 I/PackageManager.DexOptimizer: Running dexopt (dex2oat) on: /data/app/vmdl1971261529.tmp/base.apk pkg=com.yourcompany.test isa=x86 vmSafeMode=false debuggable=true target-filter=interpret-only oatDir = /data/app/vmdl1971261529.tmp/oat sharedLibraries=null
01-04 12:00:26.331 W/dex2oat: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:26.331 I/dex2oat: /system/bin/dex2oat --compiler-filter=interpret-only --debuggable
01-04 12:00:26.331 E/cutils-trace: Error opening trace file: Permission denied (13)
01-04 12:00:26.382 I/dex2oat: dex2oat took 51.156ms (threads: 4) arena alloc=5KB (5248B) java alloc=313KB (320536B) native alloc=1360KB (1393600B) free=2MB (2800704B)
01-04 12:00:26.402 V/BackupManagerService: restoreAtInstall pkg=com.yourcompany.test token=1 restoreSet=0
01-04 12:00:26.402 V/BackupManagerService: Finishing install immediately
01-04 12:00:26.402 I/art: Starting a blocking GC Explicit
01-04 12:00:26.419 I/art: Explicit concurrent mark sweep GC freed 42754(2MB) AllocSpace objects, 22(696KB) LOS objects, 33% free, 9MB/14MB, paused 382us total 16.289ms
                          
                          [ 01-04 12:00:26.419   146:  146 E/         ]
                          Couldn't opendir /data/app/vmdl1971261529.tmp: No such file or directory
01-04 12:00:26.424 I/InputReader: Reconfiguring input devices.  changes=0x00000010
01-04 12:00:26.442 D/CarrierSvcBindHelper: No carrier app for: 0
01-04 12:00:26.443 D/CarrierConfigLoader: mHandler: 9 phoneId: 0
01-04 12:00:26.448 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:26.455 I/ActivityManager: Start proc 1658:com.svox.pico/u0a54 for broadcast com.svox.pico/.VoiceDataInstallerReceiver
01-04 12:00:26.459 W/VoiceInteractionManagerService: no available voice recognition services found for user 0
01-04 12:00:26.459 W/LocationProviderProxy-network: Odd, no component found for service com.android.location.service.v3.NetworkLocationProvider
01-04 12:00:26.459 W/GeocoderProxy: Odd, no component found for service com.android.location.service.GeocodeProvider
01-04 12:00:26.459 W/GeofenceProxy: Odd, no component found for service com.android.location.service.GeofenceProvider
01-04 12:00:26.459 W/ActivityRecognitionProxy: Odd, no component found for service com.android.location.service.ActivityRecognitionProvider
01-04 12:00:26.667 D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
01-04 12:00:26.669 D/AndroidRuntime: CheckJNI is OFF
01-04 12:00:26.683 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:26.686 D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
01-04 12:00:26.696 E/memtrack: Couldn't load memtrack module (No such file or directory)
01-04 12:00:26.696 E/android.os.Debug: failed to load memtrack module: -2
01-04 12:00:26.697 I/Radio-JNI: register_android_hardware_Radio DONE
01-04 12:00:26.700 D/AndroidRuntime: Calling main entry com.android.commands.am.Am
01-04 12:00:26.702 I/ActivityManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.yourcompany.test/org.domokit.sky.shell.SkyActivity (has extras)} from uid 0 on display 0
01-04 12:00:26.721 D/AndroidRuntime: Shutting down VM
01-04 12:00:26.731 I/art: Late-enabling -Xcheck:jni
01-04 12:00:26.731 W/art: Unexpected CPU variant for X86 using defaults: x86
01-04 12:00:26.732 I/ActivityManager: Start proc 1682:com.yourcompany.test/u0a101 for activity com.yourcompany.test/org.domokit.sky.shell.SkyActivity
01-04 12:00:26.803 I/cr.library_loader: Time to load native libraries: 6 ms (timestamps 4310-4316)
01-04 12:00:26.803 I/cr.library_loader: Expected native library version number "", actual native library version number ""
01-04 12:00:26.877 E/ApkAssets: Error while loading asset assets/icudtl.dat: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
01-04 12:00:26.907 D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
01-04 12:00:26.908 E/libEGL: load_driver(/system/lib/egl/libGLES_emulation.so): dlopen failed: library "/system/lib/egl/libGLES_emulation.so" not found
01-04 12:00:26.954 D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
01-04 12:00:26.958 D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
01-04 12:00:26.966 D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so
                             
                             [ 01-04 12:00:26.985  1682: 1682 D/         ]
                             HostConnection::get() New Host Connection established 0xe366bab0, tid 1682
                             
                             
                             [ 01-04 12:00:27.001  1682: 1701 D/         ]
                             HostConnection::get() New Host Connection established 0xe6113540, tid 1701
01-04 12:00:27.105 I/OpenGLRenderer: Initialized EGL, version 1.4
01-04 12:00:27.105 D/OpenGLRenderer: Swap behavior 1
                                     
                                     [ 01-04 12:00:27.109  1682: 1708 D/         ]
                                     HostConnection::get() New Host Connection established 0xe366c1d0, tid 1708
01-04 12:00:27.159 I/flutter: Diagnostic server listening on http://127.0.0.1:45814
01-04 12:00:27.173 I/flutter: Observatory listening on http://127.0.0.1:42332/
                              
                              [ 01-04 12:00:27.184  1682: 1699 D/         ]
                              HostConnection::get() New Host Connection established 0xdffb3d70, tid 1699
01-04 12:00:27.355 I/ActivityManager: Displayed com.yourcompany.test/org.domokit.sky.shell.SkyActivity: +634ms
01-04 12:00:27.570 I/WindowManager: Destroying surface Surface(name=Starting com.yourcompany.test) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704 
01-04 12:00:27.771 I/WindowManager: Destroying surface Surface(name=com.android.launcher3/com.android.launcher3.Launcher) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.AppWindowToken.notifyAppStopped:389 com.android.server.wm.WindowManagerService.notifyAppStopped:4456 com.android.server.am.ActivityStack.activityStoppedLocked:1252 com.android.server.am.ActivityManagerService.activityStopped:6873 
01-04 12:00:30.402 I/ActivityManager: Killing 1240:com.android.messaging/u0a59 (adj 906): empty #17
01-04 12:00:34.027 E/BatteryStatsService: power: Missing API
01-04 12:00:34.027 D/WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
01-04 12:00:34.031 E/BluetoothAdapter: Bluetooth binder is null
01-04 12:00:34.031 E/BatteryStatsService: no controller energy info supplied
01-04 12:00:34.035 E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
01-04 12:00:35.660 W/ActivityManager: Unable to launch app com.android.mtp/10010 for provider com.android.mtp.documents: launching app became null
01-04 12:00:35.660 W/ActivityManager: Unable to launch app com.android.mtp/10010 for provider com.android.mtp.documents: launching app became null
01-04 12:00:35.660 E/ActivityThread: Failed to find provider info for com.android.mtp.documents
01-04 12:00:35.660 W/ActivityManager: Unable to launch app com.android.mtp/10010 for provider com.android.mtp.documents: launching app became null
01-04 12:00:35.660 W/RootsCache: Failed to load some roots from com.android.mtp.documents: android.os.RemoteException: Failed to acquire provider for com.android.mtp.documents
01-04 12:00:35.660 E/ActivityThread: Failed to find provider info for com.android.mtp.documents
01-04 12:00:35.660 E/ActivityThread: Failed to find provider info for com.android.mtp.documents
01-04 12:00:35.660 W/RootsCache: Failed to load some roots from com.android.mtp.documents: android.os.RemoteException: Failed to acquire provider for com.android.mtp.documents
01-04 12:00:35.660 I/ActivityManager: Killing 1624:com.android.mtp/u0a10 (adj 902): timeout publishing content providers
01-04 12:00:35.660 W/RootsCache: Failed to load some roots from com.android.mtp.documents: android.os.RemoteException: Failed to acquire provider for com.android.mtp.documents
01-04 12:00:35.661 W/ActivityManager: Ignoring remove of inactive process: ProcessRecord{2415873 0:com.android.mtp/u0a10}
01-04 12:00:35.919 I/WindowManager: Destroying surface Surface(name=Application Error: com.android.mtp) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8079 android.os.Handler.dispatchMessage:102 
01-04 12:00:35.920 W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
01-04 12:00:36.305 I/ActivityManager: Killing 1420:com.android.onetimeinitializer/u0a17 (adj 906): empty #17
```

**Comment by mit-mit** [comment]
@pq @devoncarew any news on this one?

**Comment by mit-mit** [comment]
@ScottPierce are you still having issues with this?

**Comment by ScottPierce** [comment]
@mit-mit I haven't been playing with flutter for a week or so, so I don't know.

**Comment by devoncarew** [comment]
@ScottPierce, I'm unable to repro this. I see some errors in your log that _look_ like issues with the file system (`appfuse mount`, `FileNotFound`, and `dlopen failed`). I don't know if these are non-issues or are related to why we can't write a new snapshot to the device.

I'm closing this issue, but we'll keep an eye out to see if we get any similar reports coming in.

**Comment by toregua** [comment]
I have exaclty the same behavior. I always need to do an MAJ + R to have the latest source files after a normal "flutter run". I am using VS Code with DART plugin.

My flutter doctor is : 

`[√] Flutter (on Microsoft Windows [version 6.1.7601], locale fr-FR, channel alpha)
    • Flutter at C:\flutter
    • Framework revision fd7853faad (7 days ago), 2017-12-05 16:12:55 -0800
    • Engine revision b57fca02b5
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d4cfecb1065d322d3670df7e9ec9a0cc2d4b90f0

[√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at C:\Users\Toregua\AppData\Local\Android\sdk
    • Android NDK location not configured (this optional configuration is useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 2.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Connected devices
    • ONEPLUS A5000 • 6d010b4a • android-arm • Android 7.1.1 (API 25)

`

**Comment by amitrai988** [comment]
Facing the same issue, old app gets reloading continuously, Even I am making changes in the js files it's not reflecting in android app.

**Comment by iBob101** [comment]
Same issue here

**Comment by RedTech64** [comment]
I'm having the same problem.
