### ISSUE TITLE
endless sync files loop, after code change and save action

### ISSUE THREAD

**Issue by fmt-Println-MKO** [flutter/flutter-intellij#5901]
## What happened

when chaning code, a flutter project, or just dart code, runs into endless sync files loop. 
dart code just crashes. and a flutter project you will see have the files will be reloaded and reloaded again and again 
working with dart / flutter in this way is not possible at all. 

## Version information

IntelliJ IDEA `2021.3.1` • Flutter plugin `io.flutter 63.2.4` • Dart plugin `213.5744.122`

No Flutter sdk configured.

## Exception

null

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.codeStyle.ProjectCodeStyleSettingsManager because container is already disposed (container=Project(name=wstflutter, containerState=DISPOSE_COMPLETED, componentStore=/Users/matthiaskoch/Development/fmt-println-mko/wstflutter) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:617)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:569)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getInstance(CodeStyleSettingsManager.java:102)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getSettings(CodeStyleSettingsManager.java:206)
	at io.flutter.editor.FlutterSaveActionsManager.getRightMargin(FlutterSaveActionsManager.java:210)
	at io.flutter.editor.FlutterSaveActionsManager.performFormat(FlutterSaveActionsManager.java:160)
	at io.flutter.editor.FlutterSaveActionsManager$2.lambda$run$0(FlutterSaveActionsManager.java:151)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
It looks like you do not have a Flutter SDK configured in the Flutter plugin. Does this problem continue to happen after setting the SDK? You can do that by opening Preferences or Settings, selecting Flutter under Languages & Frameworks, and navigating the combo box (Flutter SDK path) to point to your Flutter SDK.

**Comment by fmt-Println-MKO** [comment]
the sdk is configured, this was just an example project where I wanted to get the stacktrace for the exception. 

it happened to me also when I create a new project from the IDE. go to the dart file. change one line and save.
now the editor/ide is in an endless loop. don't know what exactly but seems for reloaded the file / changes, or what ever. but syntax coloring don't work, autocomplete don't work. cpu is on high load. etc

**Comment by stevemessick** [comment]
Could you share that new project with us? Everything works as expected when I create a project so I'd like to see what's different about the one you created.

**Comment by fmt-Println-MKO** [comment]
here is a new project, 
it is just created from scratch, 
I can see the behavior if I just comment and uncomment the line with the primary color. 

[bug_test_untitled.zip](https://github.com/flutter/flutter-intellij/files/7877159/bug_test_untitled.zip)

**Comment by stevemessick** [comment]
Thanks for sharing the project. Unfortunately, I still can't reproduce the problem. It looks like you have enabled the option to automatically format your code when saved. Disabling that might make things better. I suspect there is some configuration issue, though. Your best course of action might be to delete and re-install IntelliJ.

I noticed in the stack trace that IntelliJ was complaining about a project that had already been disposed. The project was named "wstflutter". Can you tell me the history of it?

**Comment by fmt-Println-MKO** [comment]
yes disableing the auto format on save, solved the problem thank you.
But usually it shouldn't be a problem, right?
reinstalling also didn't help. 

they are all just test projects. the project is not disposed. I don't know why the plugin/intellij "thinks" this. 
Maybe because the stack trace was only available once I closed the project window. Before there was no information etc. just the endless realoding of the code. Closing the project window was the only way to stop it.

**Comment by stevemessick** [comment]
Could you add the output of running `flutter doctor -v`?

IntelliJ uses the term "disposed" to mean the internal state of a project model after the project window has been closed. The project may still exist outside IntelliJ.

I wasn't able to reproduce the problem. Can you give more detailed instructions?
