### ISSUE TITLE
Plugin crash report

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter-intellij#5921]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Starting Android studio.

## Version information

Android Studio `Bumblebee | 2021.1.1` • Flutter plugin `io.flutter 63.2.2` • Dart plugin `211.7798`

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (6 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

## Exception

Check after add Diff

Entity source filter: null

Version: v16.1
Saving store content at: /Users/foxtom/Library/Logs/Google/AndroidStudio2021.1/workspaceModel/storeDump-20220128-151837

```
java.lang.NullPointerException
	at com.intellij.workspaceModel.storage.impl.references.OneToOneChild$NotNull.getValue(OneToOne.kt:45)
	at com.intellij.workspaceModel.storage.bridgeEntities.LibraryPropertiesEntity.getLibrary(bridgeModelEntities.kt)
	at com.intellij.workspaceModel.storage.bridgeEntities.LibraryPropertiesEntityData.assertConsistency(bridgeModelEntities.kt:603)
	at com.intellij.workspaceModel.storage.impl.EntitiesBarrel.assertConsistency(EntitiesBarrel.kt:130)
	at com.intellij.workspaceModel.storage.impl.AbstractEntityStorage.assertConsistency$intellij_platform_workspaceModel_storage(WorkspaceEntityStorageImpl.kt:848)
	at com.intellij.workspaceModel.storage.impl.AbstractEntityStorage.assertConsistencyInStrictMode$intellij_platform_workspaceModel_storage(WorkspaceEntityStorageImpl.kt:974)
	at com.intellij.workspaceModel.storage.impl.AddDiffOperation.addDiff(AddDiffOperation.kt:87)
	at com.intellij.workspaceModel.storage.impl.WorkspaceEntityStorageBuilderImpl.addDiff(WorkspaceEntityStorageImpl.kt:640)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl$commit$1.invoke(LibraryModifiableModelBridgeImpl.kt:98)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl$commit$1.invoke(LibraryModifiableModelBridgeImpl.kt:29)
	at com.intellij.workspaceModel.ide.impl.WorkspaceModelImpl.updateProjectModel(WorkspaceModelImpl.kt:86)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.library.LibraryModifiableModelBridgeImpl.commit(LibraryModifiableModelBridgeImpl.kt:97)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:965)
	at io.flutter.sdk.AbstractLibraryManager.lambda$updateLibraryContent$2(AbstractLibraryManager.java:100)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:258)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:244)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.java:503)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:244)
	at io.flutter.sdk.AbstractLibraryManager.lambda$updateLibraryContent$3(AbstractLibraryManager.java:99)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:965)
	at io.flutter.sdk.AbstractLibraryManager.updateLibraryContent(AbstractLibraryManager.java:84)
	at io.flutter.sdk.AbstractLibraryManager.updateLibraryContent(AbstractLibraryManager.java:57)
	at io.flutter.sdk.FlutterPluginsLibraryManager.updateFlutterPluginsImpl(FlutterPluginsLibraryManager.java:119)
	at io.flutter.sdk.FlutterPluginsLibraryManager.updateFlutterPlugins(FlutterPluginsLibraryManager.java:106)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$9(DumbServiceImpl.java:532)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
I'm not sure what your description means. Can you be more specific?

**Comment by Tom3652** [comment]
I have no idea about what this is, i have simply open Android studio and they asked me to fill a bug report 😅 
It doesn't prevent me from using the IDE !

**Comment by efortuna** [comment]
This seems to happen when you open Android Studio and there's an issue with the flutter installation. Even if you fix the issue with the Flutter installation, Android Studio seems to get in this perpetual loop

**Comment by stevemessick** [comment]
Hi @efortuna !

@Tom3652 Are you up for trying an experiment? I have a theory that, based on the previous comment and looking at some of my own log files, there is a bad file in the Dart pub cache. Can you upgrade Flutter to 2.10 and see if the problem goes away? It might not; what I'm hoping will happen is that the bad file will be replaced with a good one during `pub get` but that might not happen. Another option would be to delete the cache entirely, but that seems heavy-handed.

**Comment by Tom3652** [comment]
Yes sure, i have already upgrade to Flutter 2.10 and so far no issue :) 
I have done a `pub cache repair` as well.

**Comment by stevemessick** [comment]
Thanks! Sounds like your problem is solved. I'm closing this, but I added another issue to help others solve the problem.
