### ISSUE TITLE
FileSystemException: Creation failed, path = '~' (OS Error: Read-only file system, errno = 30) when selecting 'Open Flutter DevTools'

### ISSUE THREAD

**Issue by indyant** [flutter/flutter-intellij#5925]
## What happened

<img width="685" alt="2022-01-30_23-43-01" src="https://user-images.githubusercontent.com/59300194/151704507-0bed47b6-0024-404a-88a2-5c42471005c2.png">

When I tried to 'Open Flutter DevTools' in Tool > Flutter > Open Flutter DevTools, the exception in "Exception" section  were reported and the message windows showed the Unhandled exception like following. 

```
Unhandled exception:
FileSystemException: Creation failed, path = '~' (OS Error: Read-only file system, errno = 30)
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:128:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#3      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#6      new Config._common (package:flutter_tools/src/base/config.dart:76:17)
#7      new Config (package:flutter_tools/src/base/config.dart:37:19)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:169:21)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:453:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     config (package:flutter_tools/src/globals_null_migrated.dart:56:30)
#14     getBuildDirectory (package:flutter_tools/src/build_info.dart:766:48)
#15     defaultDepfilePath (package:flutter_tools/src/bundle.dart:16:55)
#16     new BuildBundleCommand (package:flutter_tools/src/commands/build_bundle.dart:28:21)
#17     new BuildCommand (package:flutter_tools/src/commands/build.dart:36:20)
#18     generateCommands (package:flutter_tools/executable.dart:150:3)
#19     main.<anonymous closure> (package:flutter_tools/executable.dart:96:11)
#20     run.<anonymous closure> (package:flutter_tools/runner.dart:48:13)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#22     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

And one more funny thing I want to mention is whenever I execute flutter command like ```flutter doctor``` or ```flutter run```, "~" (tilde) directory is created in the current directory, and it contains ```.config``` folder in it.

<img width="812" alt="2022-01-31_00-00-06" src="https://user-images.githubusercontent.com/59300194/151705140-bfd27c67-2d28-4272-9269-9482099bd6b3.png">

## Version information

IntelliJ IDEA `2021.2.4` • Flutter plugin `io.flutter 63.3.3` • Dart plugin `212.5632`

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (6 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

## Exception

null

```
java.lang.Exception: pub activate of DevTools failed
	at io.flutter.run.daemon.DevToolsService.logExceptionAndComplete(DevToolsService.java:259)
	at io.flutter.run.daemon.DevToolsService.lambda$setUpWithPub$4(DevToolsService.java:175)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at io.flutter.run.daemon.DevToolsService.setUpWithPub(DevToolsService.java:170)
	at io.flutter.run.daemon.DevToolsService.lambda$startServer$2(DevToolsService.java:113)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Steps to Reproduce

Just select 'Open Flutter DevTools' in Tool > Flutter > Open Flutter DevTools.

## Version info

↳ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.2 21D49 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/user_name/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user_name/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Users/user_name/Applications/JetBrains Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/user_name/Applications/JetBrains Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8092744/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Users/user_name/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 63.3.3
    • Dart plugin version 212.5632

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
    • IntelliJ at /Users/user_name/Applications/JetBrains Toolbox/apps/IDEA-U/ch-0/212.5712.43/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 97.0.4692.99
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!

**Comment by indyant** [comment]
I found the cause of the problem.
My zsh environment extension defined alias for '~'. I unalias the '~', and all problems are gone.
