### ISSUE TITLE
scratch when running a command

### ISSUE THREAD

**Issue by MAlazhariy** [flutter/flutter-intellij#6032]
## What happened

(please describe what you were doing when this exception occurred)

I wrote this command below :)
                          const int printableCharsStartIndex = 32;
                          const int charLength = 1114111 - printableCharsStartIndex;
                          final List<int> charCodes = List.generate(charLength, (index) => index+printableCharsStartIndex);
                          final String chars = String.fromCharCodes(charCodes);
                          print(chars.split(''));
                          FlutterClipboard.copy(chars.split('').toString()).then((value) {
                            print('DONE !');
                          });

## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 1` • Flutter plugin `io.flutter 64.1.2` • Dart plugin `211.7798`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:246)
	at com.sun.proxy.$Proxy34.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:220)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:63)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:100)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:64)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:52)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:156)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:206)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:190)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:137)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:68)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:158)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by stevemessick** [comment]
I wasn't able to exactly reproduce the problem, but I did cause Android Studio to become unresponsive. I think trying to print  a million-character string broke it. I did not get an exception but I had to force-quit Android Studio.

**Comment by stevemessick** [comment]
I see this in your original report:
> Caused by: java.lang.OutOfMemoryError: Java heap space

I probably have my IDE configured with enough memory to handle the string, and it was probably trying to print the string but I got tired of waiting for it to finish.

**Comment by stevemessick** [comment]
@jacob314 I'm tempted to close this issue. Is this use-case something we want to encourage? The user is using a Flutter app to print a million characters to the console in the IDE.

**Comment by abdulrojakdev** [comment]
> @jacob314 I'm tempted to close this issue. Is this use-case something we want to encourage? The user is using a Flutter app to print a million characters to the console in the IDE.

![0410BDCD-DFE8-4A35-B5FB-54DB58FDFC7D](https://user-images.githubusercontent.com/83383753/184297458-35db1272-8590-4499-b1d3-9e5448b84c6b.jpeg)
