### ISSUE TITLE
IDE error when I open an existing flutter project in IntelliJ

### ISSUE THREAD

**Issue by onumengine** [flutter/flutter-intellij#6038]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

I just opened an existing Flutter project in IntelliJ and I got this error. It popped up at the bottom right

## Version information

IntelliJ IDEA `2021.3.2` • Flutter plugin `io.flutter 65.2.4` • Dart plugin `213.7227`

Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (9 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

## Exception

Cannot save entities to Dart_SDK.xml because it's already used for other entities;
Current entity source: FileInDirectory(directory=file:///Users/onum/WORK/FlutterProjects/merchant_admoni/.idea/libraries, fileNameId=4, projectLocation=DirectoryBased(projectDir=file:///Users/onum/WORK/FlutterProjects/merchant_admoni, ideaFolder=file:///Users/onum/WORK/FlutterProjects/merchant_admoni/.idea))
Old file name: null
Existing serializers: [JpsLibraryEntitiesSerializer(file:///Users/onum/WORK/FlutterProjects/merchant_admoni/.idea/libraries/Dart_SDK.xml)]
Their entity sources: [FileInDirectory(directory=file:///Users/onum/WORK/FlutterProjects/merchant_admoni/.idea/libraries, fileNameId=1, projectLocation=DirectoryBased(projectDir=file:///Users/onum/WORK/FlutterProjects/merchant_admoni, ideaFolder=file:///Users/onum/WORK/FlutterProjects/merchant_admoni/.idea))]
Entities with these sources in the storage: {}

Version: v30
Saving store content at: /Users/onum/Library/Logs/JetBrains/IdeaIC2021.3/workspaceModel/storeDump-20220311-090523

```
java.lang.IllegalStateException
	at com.intellij.workspaceModel.storage.impl.ErrorReportingKt.reportErrorAndAttachStorage(ErrorReporting.kt:28)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectSerializersImpl.saveEntities(JpsProjectSerializersImpl.kt:632)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectModelSynchronizer.saveChangedProjectEntities(JpsProjectModelSynchronizer.kt:281)
	at com.intellij.configurationStore.ProjectStoreBridge.saveModules(ProjectStoreBridge.kt:34)
	at com.intellij.configurationStore.ProjectWithModulesStoreImpl.saveModules(ProjectStoreImpl.kt:165)
	at com.intellij.configurationStore.ProjectStoreImpl$doSave$2$1.invokeSuspend(ProjectStoreImpl.kt:114)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.configurationStore.StoreUtil$Companion.saveSettings(storeUtil.kt:49)
	at com.intellij.configurationStore.StoreUtil.saveSettings(storeUtil.kt)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:74)
	at io.flutter.utils.FlutterModuleUtils.setFlutterModuleAndReload(FlutterModuleUtils.java:394)
	at io.flutter.project.FlutterProjectOpenProcessor.convertToFlutterProject(FlutterProjectOpenProcessor.java:92)
	at io.flutter.project.FlutterProjectOpenProcessor.doOpenProject(FlutterProjectOpenProcessor.java:71)
	at com.intellij.ide.impl.ProjectUtil.lambda$chooseProcessorAndOpenAsync$12(ProjectUtil.java:393)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
Let's check some settings to see why this error could occur. I want to know how the Dart SDK and Flutter SDK are configured, and the modules in your project.

Dart SDK, in Preferences:
<img width="1007" alt="Screen Shot 2022-03-15 at 2 06 31 PM" src="https://user-images.githubusercontent.com/8518285/158473215-56e3139f-42d9-4d09-ac88-1466107dad18.png">

Flutter SDK, in Preferences:
<img width="1002" alt="Screen Shot 2022-03-15 at 2 06 58 PM" src="https://user-images.githubusercontent.com/8518285/158473268-e8da8f8a-e2b9-4e75-858a-1cd85eac3d7b.png">

Project Structure, from the File menu:
<img width="625" alt="Screen Shot 2022-03-15 at 2 08 01 PM" src="https://user-images.githubusercontent.com/8518285/158473385-538b3440-2d46-4d9d-916d-ebd8e3f0a800.png">

If you can attach similar screen shots we might have a clue. Thanks!

**Comment by stevemessick** [comment]
And one more question: Does this happen every time you open the project?
