### ISSUE TITLE
IDE NullPointerException in FlutterWidgetPerf.dispose

### ISSUE THREAD

**Issue by filiph** [flutter/flutter-intellij#6042]
## What happened

I terminated a Profile run of a macOS Flutter app with the red "Stop" button. IDE works okay, I just got the big red notification and clicked "Report to Google".

## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 2` • Flutter plugin `io.flutter 65.2.2` • Dart plugin `211.7808`

Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (13 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

## Exception

null

```
java.lang.NullPointerException
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:153)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:141)
	at io.flutter.perf.FlutterWidgetPerf.dispose(FlutterWidgetPerf.java:518)
	at io.flutter.perf.FlutterWidgetPerfManager.updateCurrentAppChanged(FlutterWidgetPerfManager.java:276)
	at io.flutter.utils.StreamSubscription.notify(StreamSubscription.java:43)
	at io.flutter.utils.EventStream.lambda$setValue$0(EventStream.java:78)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
We have seen a few dispose problems and recently added some additional logging. Could you attach your log file? Or you can just grep for the line containing "NPE during dispose of" and paste that here. Thanks!

**Comment by filiph** [comment]
Hi Steve, sorry, how do I get logs from Android Studio? My quick search yielded only getting logs of Android apps, not logs of the IDE itself. And I haven't found anything in this repo's README nor CONTRIBUTING.md.

**Comment by stevemessick** [comment]
No problem, here you go:

<img width="374" alt="Screen Shot 2022-03-15 at 3 58 21 PM" src="https://user-images.githubusercontent.com/8518285/158485994-33b01030-4f28-4f28-817a-6c525389d078.png">

**Comment by filiph** [comment]
Thank you!

I looked into the log but couldn't find the "NPE during dispose of" string. Here's the part with the error:

```text
2022-03-15 22:01:51,160 [393602206]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 22 to update, calculated in 99ms 
2022-03-15 22:01:51,161 [393602207]   INFO - g.FileBasedIndexProjectHandler - Using 4 threads for indexing 
2022-03-15 22:01:51,190 [393602236]   INFO - .diagnostic.PerformanceWatcher - Reindexing refreshed files took 29ms; general responsiveness: ok; EDT responsiveness: ok 
2022-03-15 22:01:51,190 [393602236]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 0 to update, calculated in 0ms 
2022-03-15 22:02:07,073 [393618119]   INFO - .FlutterAppDaemonEventListener - app shutdown took longer than 100ms 
2022-03-15 22:02:07,135 [393618181]   INFO - .flutter.run.daemon.FlutterApp - StopApp flutter_game_sample (PROFILE) 
2022-03-15 22:02:07,426 [393618472]  ERROR - tellij.openapi.util.ObjectTree - null 
java.lang.NullPointerException
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:153)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:141)
	at io.flutter.perf.FlutterWidgetPerf.dispose(FlutterWidgetPerf.java:518)
	at io.flutter.perf.FlutterWidgetPerfManager.updateCurrentAppChanged(FlutterWidgetPerfManager.java:276)
	at io.flutter.utils.StreamSubscription.notify(StreamSubscription.java:43)
	at io.flutter.utils.EventStream.lambda$setValue$0(EventStream.java:78)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2022-03-15 22:02:07,427 [393618473]  ERROR - tellij.openapi.util.ObjectTree - Android Studio Bumblebee | 2021.1.1 Patch 2  Build #AI-211.7628.21.2111.8193401 
2022-03-15 22:02:07,427 [393618473]  ERROR - tellij.openapi.util.ObjectTree - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2022-03-15 22:02:07,427 [393618473]  ERROR - tellij.openapi.util.ObjectTree - OS: Mac OS X 
2022-03-15 22:02:07,427 [393618473]  ERROR - tellij.openapi.util.ObjectTree - Plugin to blame: Flutter version: 65.2.2 
2022-03-15 22:02:07,427 [393618473]  ERROR - tellij.openapi.util.ObjectTree - Last Action: Stop 
2022-03-15 22:06:08,958 [393860004]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 8 to update, calculated in 30ms 
2022-03-15 22:06:08,961 [393860007]   INFO - g.FileBasedIndexProjectHandler - Using 4 threads for indexing 
2022-03-15 22:06:08,973 [393860019]   INFO - .diagnostic.PerformanceWatcher - Reindexing refreshed files took 13ms; general responsiveness: ok; EDT responsiveness: ok 
2022-03-15 22:06:09,002 [393860048]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 0 to update, calculated in 0ms 
2022-03-15 22:06:11,399 [393862445]   INFO -                         STDERR - character class has ']' without escape 
```

[idea.log](https://github.com/flutter/flutter-intellij/files/8257972/idea.log)

**Comment by stevemessick** [comment]
Thanks, Filip!

**Comment by stevemessick** [comment]
Yeah, it turns out that the IntelliJ `dispose()` code as a `catch Throwable` clause that intercepts all errors and logs them. Our additional logging isn't running due to that.

**Comment by stevemessick** [comment]
This is reproducible and can be debugged, but I haven't got a solution yet.

1. Use Android Studio Dolphin to create a sample project configured for MacOS. Shut it down.
2. Start Android Studio with the new project open.
3. Select Mac OS in the device selector.
4. Run the app in Profile mode.
5. Use the Stop button to terminate it.
6. See error notification.

To debug, launch IntelliJ with the Flutter plugin project open. Then create a Remote JVM Debug run config. Copy the command-line options from the run config and paste them into your equivalent of /Applications/Android Studio 2021.3/Contents/bin/studio.vmoptions. Then do steps 2-4 above. Switch back to IntelliJ and click the Debug button. Add a breakpoint at line 518 of FlutterWidgetPerf. Switch back to Android Studio to do step 5 from above. You should be switched back to the IntelliJ debugger.
