### ISSUE TITLE
Opening any `.dart` file causes `Access is allowed from event dispatch thread only` exception

### ISSUE THREAD

**Issue by citizenharris** [flutter/flutter-intellij#6116]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Opening any `.dart` file causes this exception

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /usr/local/Caskroom/flutter/2.8.1/flutter
    • Upstream repository ssh://git@github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Users/citizenharris/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 66.0.4
    • Dart plugin version 221.5480

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Users/citizenharris/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/citizenharris/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPad Pro (9.7-inch) (mobile) • A30AE985-E4FA-4CE1-A2CD-F1FAE2944B15 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 100.0.4896.88

! Doctor found issues in 2 categories.
```

IntelliJ IDEA `2022.1` • Flutter plugin `io.flutter 66.0.4` • Dart plugin `221.5480`

Flutter 2.8.1 • channel stable • ssh://git@github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

## Exception

Access is allowed from event dispatch thread only

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[JobScheduler FJ pool 2/7,4,main] 1928988980
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1514700987
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1103)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1086)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3339)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:944)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:940)
	at com.intellij.openapi.editor.impl.SettingsImpl.fireEditorRefresh(SettingsImpl.java:724)
	at com.intellij.openapi.editor.impl.SettingsImpl.setIndentGuidesShown(SettingsImpl.java:187)
	at io.flutter.editor.WidgetIndentsHighlightingPassFactory.createHighlightingPass(WidgetIndentsHighlightingPassFactory.java:181)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:171)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:75)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$14(DaemonCodeAnalyzerImpl.java:960)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$15(DaemonCodeAnalyzerImpl.java:951)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$16(DaemonCodeAnalyzerImpl.java:943)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by stevemessick** [comment]
This appears to be a timing issue. Sometimes it happens, sometimes it does not. It is the result of noticing that custom indent guides should not be shown, and changing the default settings to accommodate that.

You can work around the problem by enabling the Flutter preference "Show UI guides for build methods".

**Comment by citizenharris** [comment]
> This appears to be a timing issue. Sometimes it happens, sometimes it does not. It is the result of noticing that custom indent guides should not be shown, and changing the default settings to accommodate that.
> 
> You can work around the problem by enabling the Flutter preference "Show UI guides for build methods".

This fixed it, thanks!

**Comment by stevemessick** [comment]
Thanks for the update! However, while that prevents the error, someone may really not want the indent guides, so I think we should try to fix the underlying problem.
