### ISSUE TITLE
FlutterCoverage Could not find project root

### ISSUE THREAD

**Issue by SLIU149-ford** [flutter/flutter-intellij#6125]
## What happened

M1 chipset happened

## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 3` • Flutter plugin `io.flutter 66.0.1` • Dart plugin `211.7817`

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (10 months ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

## Exception

null

```
java.lang.RuntimeException: Could not find project root
	at io.flutter.run.coverage.FlutterCoverageEnabledConfiguration.createCoverageFile(FlutterCoverageEnabledConfiguration.java:41)
	at io.flutter.run.coverage.FlutterCoverageEnabledConfiguration.<init>(FlutterCoverageEnabledConfiguration.java:30)
	at io.flutter.run.coverage.FlutterCoverageEngine.createCoverageEnabledConfiguration(FlutterCoverageEngine.java:57)
	at com.intellij.execution.configurations.coverage.CoverageEnabledConfiguration.getOrCreate(CoverageEnabledConfiguration.java:155)
	at io.flutter.run.coverage.FlutterCoverageProgramRunner.processCoverage(FlutterCoverageProgramRunner.java:86)
	at io.flutter.run.coverage.FlutterCoverageProgramRunner$1.lambda$processTerminated$0(FlutterCoverageProgramRunner.java:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
What is the directory structure of your project?

**Comment by SLIU149-ford** [comment]
> What is the directory structure of your project?

is Android subproject

I thy

> What is the directory structure of your project?

I tried to use the Flutter project as a basic project, and the problem was solved. The previous project was an Android project that depended on the Flutter project.
