### ISSUE TITLE
blank screen / popups

### ISSUE THREAD

**Issue by uditrugman** [flutter/flutter-intellij#6135]
periodically, intellij will start showing blank popups or even the whole windows as blank.

i found the below error in idea.log. not sure if it's related:

`
2022-04-24 09:37:58,397 [4720610]   WARN - #c.i.o.a.Presentation - Shall not be called on a template presentation
java.lang.Throwable: Shall not be called on a template presentation
        at com.intellij.openapi.actionSystem.Presentation.assertNotTemplatePresentation(Presentation.java:418)
        at com.intellij.openapi.actionSystem.Presentation.setEnabled(Presentation.java:391)
        at io.flutter.actions.FlutterAppAction$1.stateChanged(FlutterAppAction.java:28)
        at jdk.internal.reflect.GeneratedMethodAccessor887.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
        at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
        at com.sun.proxy.$Proxy242.stateChanged(Unknown Source)
        at io.flutter.run.daemon.FlutterApp.changeState(FlutterApp.java:580)
        at io.flutter.run.daemon.FlutterApp.performRestartApp(FlutterApp.java:386)
        at io.flutter.run.FlutterReloadManager.restartApp(FlutterReloadManager.java:338)
        at io.flutter.run.FlutterReloadManager.saveAllAndRestart(FlutterReloadManager.java:359)
        at io.flutter.actions.RestartFlutterApp.actionPerformed(RestartFlutterApp.java:46)
        at io.flutter.actions.FlutterRetargetAppAction.actionPerformed(FlutterRetargetAppAction.java:47)
        at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

## Steps to Reproduce

i can't pinpoint the exact cause. it just happens after some time.

## Version info

below is the output of `flutter doctor -v`

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-arm, locale en-IL)
    • Flutter version 2.10.4 at /Users/udi/work/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/udi/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/udi/Library/Android/sdk
    • Java binary at: /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8309675/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/211.7628.21.2111.8193401/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Users/udi/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 66.0.4
    • Dart plugin version 221.5480

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.0)
    • VS Code at /Users/udi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.127
(code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

some lines from `Intellij->Tools->Flutter->Flutter Doctor `  
`
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Users/udi/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 66.0.4
    • Dart plugin version 221.5480

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.5080.210/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Users/udi/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/213.7172.25/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

`

**Comment by stevemessick** [comment]
Thanks for pointing out that warning. We weren't aware of it, and need to tweak our code to eliminate it. It was added in 2022.1, but I don't think it affects the UI.

What specifically is blank?

**Comment by uditrugman** [comment]
actually every popup window. not only those that are dart/flutter related. but, it starts happening at some point. in most cases, I have to restart the IDE.  
I suspect it's related to the latest build. updated the plugin and IDE in the last few days and it started happening.

**Comment by stevemessick** [comment]
Ah, that sounds like a problem with IntelliJ, not the Flutter plugin. It may be related to using the M1 chip (not that I'm an expert on that). You'll get better support if you report it to JetBrains at [youtrack.jetbrains.com](https://youtrack.jetbrains.com). As an experiment to help them find the problem, you might try disabling all optional plugins and seeing if the problem still happens (and report that with your new issue).

**Comment by stevemessick** [comment]
@alexander-doroshko have you gotten reports of this problem?
