### ISSUE TITLE
Error while opening Flutter Inspector

### ISSUE THREAD

**Issue by rishabh-hk** [flutter/flutter-intellij#6149]
## What happened

Build Flutter Project and Try to open Flutter Inspector

## Version information

IntelliJ IDEA `2021.3.3` • Flutter plugin `io.flutter 67.0.3` • Dart plugin `213.7371`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "dart" (in directory "C:\src\flutter\bin\cache\dart-sdk"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:364)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:94)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:41)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:23)
	at io.flutter.utils.MostlySilentColoredProcessHandler.<init>(MostlySilentColoredProcessHandler.java:49)
	at io.flutter.utils.MostlySilentColoredProcessHandler.<init>(MostlySilentColoredProcessHandler.java:44)
	at io.flutter.run.daemon.DevToolsService.setUpWithDart(DevToolsService.java:141)
	at io.flutter.run.daemon.DevToolsService.lambda$startServer$2(DevToolsService.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Cannot run program "dart" (in directory "C:\src\flutter\bin\cache\dart-sdk"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:447)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:354)
	... 18 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 21 more
```

**Comment by Paolo-N** [comment]
Same error for me, it should be look for dart.exe in "\flutter\bin\cache\dart-sdk\bin" instead of "\flutter\bin\cache\dart-sdk", and currently I can't open devtools from Android Studio

**Comment by RossHS** [comment]
The problem for me was solved when I manually rolled back to the previous version of the plugin. Just install 66.0.1 version
https://plugins.jetbrains.com/plugin/9212-flutter/versions/stable

**Comment by stevemessick** [comment]
Sorry about the problem. Is anyone using Flutter SDK stable and seeing this problem? I think it only occurs if you are using Flutter 2.15 or later. Stable is 2.10.5, currently, and beta is 2.13.

Adding the output of `flutter doctor -v` would be helpful.

**Comment by rishabh-hk** [comment]
Problem Solved by updating plugin. Version is 67.1.3. Thanks @helin24
