### ISSUE TITLE
org.jdom.JDOMException: Unexpected End-of-input in prolog

### ISSUE THREAD

**Issue by zhaojin1229** [flutter/flutter-intellij#6199]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2022.1` • Flutter plugin `io.flutter 67.1.4` • Dart plugin `221.5588`

Error getting Flutter sdk information.

## Exception

null

```
org.jdom.JDOMException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:240)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:269)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoaderKt.loadStorageFile(JpsProjectEntitiesLoader.kt:167)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponents(JpsProjectSerializersImpl.kt:861)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.access$loadComponents(JpsProjectSerializersImpl.kt:838)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:848)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:838)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponent(JpsProjectSerializersImpl.kt:847)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.readModuleOptions(ModuleImlFileEntitiesSerializer.kt:184)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadModuleEntity(ModuleImlFileEntitiesSerializer.kt:106)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadEntities(ModuleImlFileEntitiesSerializer.kt:72)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule$intellij_platform_workspaceModel_jps(JpsProjectEntitiesLoader.kt:60)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule(JpsProjectEntitiesLoader.kt:48)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleManagerComponentBridge.loadModuleToBuilder(ModuleManagerComponentBridge.kt:307)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.loadModule(ModifiableModuleModelBridgeImpl.kt:153)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModule(FlutterModuleBuilder.java:211)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:153)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:249)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:398)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:390)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwWfe(StreamReaderImpl.java:1777)
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwUnexpectedEOI(StreamReaderImpl.java:1796)
	at com.fasterxml.aalto.stax.StreamReaderImpl.handlePrologEoi(StreamReaderImpl.java:1756)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:810)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:102)
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:233)
	... 55 more
```

**Comment by zhaojin1229** [comment]
Thanks for the reply, it turns out that the `<project-name>_android.iml` file is an empty file in my project, after rebuilding, the error is not showing any more

**Comment by stevemessick** [comment]
OK, it sounds like a possible network glitch during project creation.
