### ISSUE TITLE
Cannot get flutter working from path or from IntelliJ IDEA

### ISSUE THREAD

**Issue by kigsan** [flutter/flutter-intellij#6206]
## What happened

I get this error when I create a new Flutter project. I have followed all the steps at https://docs.flutter.dev/get-started/install/windows (Windows 10).

## Version information

IntelliJ IDEA `2022.1.1` • Flutter plugin `io.flutter 67.1.4` • Dart plugin `221.5591.58`

No Flutter sdk configured.

## Exception

null

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfig(FlutterSdk.java:631)
	at io.flutter.ProjectOpenActivity.lambda$runActivity$1(ProjectOpenActivity.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by stevemessick** [comment]
Glad you got it working.
