### ISSUE TITLE
org.jdom.JDOMException: Unexpected End-of-input in prolog

### ISSUE THREAD

**Issue by bholendraofficial** [flutter/flutter-intellij#6216]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

Android Studio `Chipmunk | 2021.2.1 Patch 1` • Flutter plugin `io.flutter 68.1.2` • Dart plugin `212.5744`

Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (2 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

## Exception

null

```
org.jdom.JDOMException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:239)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:267)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoaderKt.loadStorageFile(JpsProjectEntitiesLoader.kt:162)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponents(JpsProjectSerializersImpl.kt:810)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.access$loadComponents(JpsProjectSerializersImpl.kt:791)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:797)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:791)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponent(JpsProjectSerializersImpl.kt:796)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.readModuleOptions(ModuleImlFileEntitiesSerializer.kt:184)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadModuleEntity(ModuleImlFileEntitiesSerializer.kt:106)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadEntities(ModuleImlFileEntitiesSerializer.kt:72)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule$intellij_platform_workspaceModel_jps(JpsProjectEntitiesLoader.kt:57)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule(JpsProjectEntitiesLoader.kt:45)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleManagerComponentBridge.loadModuleToBuilder(ModuleManagerComponentBridge.kt:301)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.loadModule(ModifiableModuleModelBridgeImpl.kt:155)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModule(FlutterModuleBuilder.java:211)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:153)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:268)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.kt:247)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivity(StartupManagerImpl.kt:59)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:222)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:401)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:393)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwWfe(StreamReaderImpl.java:1777)
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwUnexpectedEOI(StreamReaderImpl.java:1796)
	at com.fasterxml.aalto.stax.StreamReaderImpl.handlePrologEoi(StreamReaderImpl.java:1756)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:810)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:102)
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:232)
	... 53 more
```

**Comment by stevemessick** [comment]
Could you show us the contents of the file named `<project-name>_android.iml`? It is probably in the `android` directory. It looks like it has a format problem, or may be empty.

**Comment by SiRumCz** [comment]
Hi @stevemessick, I happened to have this same issue and I checked my `_android.iml` and it is indeed empty, what can I do in this case to fix this problem?
