### ISSUE TITLE
Unexpected IDE error when running flutter assembleProfile build

### ISSUE THREAD

**Issue by RonBis** [flutter/flutter-intellij#6236]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2022.1.1` • Flutter plugin `io.flutter 68.1.4` • Dart plugin `221.5591.58`

Error getting Flutter sdk information.

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: WidgetInspectorService class not found
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: WidgetInspectorService class not found
	at io.flutter.inspector.InspectorService.lambda$create$3(InspectorService.java:235)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	... 6 more
```

**Comment by stevemessick** [comment]
Nope, this code hasn't changed recently. Is this reproducible? If so, try reinstalling the Flutter SDK.

**Comment by RonBis** [comment]
This is the output for Flutter Doctor : 

D:\Code\SDK\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.25136.1000], locale en-IN)
    • Flutter version 3.0.2 at D:\Code\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:/Users/ronil/AppData/Local/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:/Users/ronil/AppData/Local/Android/Sdk
    • Java binary at: C:\Users\ronil\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Users\ronil\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Users\ronil\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\221.5591.52
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5591.58

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\ronil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[!] Connected device
    ! No devices available

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by stevemessick** [comment]
Thanks for the update.

Is this reproducible? If so, try reinstalling the Flutter SDK.
