### ISSUE TITLE
Please allow us not to use the Flutter inspector that was built with Flutter.

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter-intellij#6243]
## What happened
I was developing a flutter application.

## Version information

IntelliJ IDEA `2022.1.3` • Flutter plugin `io.flutter 68.1.4` • Dart plugin `221.5921.27`

Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (6 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2

## Exception

null

```
java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/7s/wssfgn5d001__19kbh2r_ym40000gn/T/JxBrowser/7.22/libawt_toolkit.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.teamdev.jxbrowser.internal.JniLibrary.loadLibrary(JniLibrary.java:53)
	at com.teamdev.jxbrowser.internal.JniLibrary.lambda$new$0(JniLibrary.java:47)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.teamdev.jxbrowser.internal.JniLibrary.<init>(JniLibrary.java:45)
	at com.teamdev.jxbrowser.internal.AwtHelperLibrary.<init>(AwtHelperLibrary.java:46)
	at com.teamdev.jxbrowser.internal.AwtHelperLibrary.instance(AwtHelperLibrary.java:36)
	at com.teamdev.jxbrowser.view.swing.internal.IoSurfaceRenderWidget.<init>(IoSurfaceRenderWidget.java:46)
	at com.teamdev.jxbrowser.view.swing.BrowserView.createBrowserWidget(BrowserView.java:190)
	at com.teamdev.jxbrowser.view.swing.BrowserView.<init>(BrowserView.java:107)
	at com.teamdev.jxbrowser.view.swing.BrowserView.newInstance(BrowserView.java:80)
	at io.flutter.jxbrowser.EmbeddedBrowser.lambda$openPanel$1(EmbeddedBrowser.java:141)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by stevemessick** [comment]
Open the Flutter options page and uncheck the check box "Enable embedding DevTools in the Flutter inspector window".

@helin24 can you take a look at the exception here? I think we may have seen this before.

**Comment by helin24** [comment]
Yes this has come up a few other times (e.g. https://github.com/flutter/flutter-intellij/issues/6233) but I think we need logs to debug further. Vladyslav from JxBrowser offered to help us with this, and he may have other suggestions.

**Comment by stevemessick** [comment]
@long1eu we've seen this issue before but need some additional logs to debug. If you're able to send these to us it may help.

Instructions:

Go to Preferences > Languages & Frameworks > Flutter > check Enable verbose logging (under General)
Reproduce the problem
Go to Help > Show log in finder and send me idea.log and jxbrowser.log
