### ISSUE TITLE
IllegalStateException: Not a JSON Array: null

### ISSUE THREAD

**Issue by asashour** [flutter/flutter-intellij#6254]
## Steps to Reproduce

I was opening the `analysis_server` project, which is part of Dart SDK, using IntelliJ, with Flutter plugin enabled (but no Flutter SDK defined), since it is a Dart project.

## Version information

IntelliJ IDEA `2022.1.3` • Flutter plugin `io.flutter 69.0.4` • Dart plugin `221.5921.27`

`Dart SDK version: 2.18.0-edge.1c461e06c1d53cf60e4458bb89b2a1543266bd95 (be) (Thu Jun 30 00:21:36 2022 +0000) on "windows_x64"`

No Flutter sdk configured.

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Not a JSON Array: null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalStateException: Not a JSON Array: null
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)
	at org.dartlang.vm.service.element.Library.getClasses(Library.java:35)
	at io.flutter.inspector.InspectorService.lambda$create$3(InspectorService.java:224)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	... 6 more
```

**Comment by stevemessick** [comment]
This is `dart-lang/sdk/pkg/analysis_server`, right? I cannot reproduce the problem. 

Do you have any other Dart- or Flutter-related plugins installed?

Is the problem repeatable? How do you open the project (File menu, welcome screen, re-open previously open project on startup)?
