### ISSUE TITLE
IDE exception 

### ISSUE THREAD

**Issue by tjsummour17** [flutter/flutter-intellij#6292]
## What happened

I got this exception with my IDE

## Version information

IntelliJ IDEA `2022.2.1` • Flutter plugin `io.flutter 70.0.5` • Dart plugin `222.3739.24`

Flutter 3.3.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffccd96b62 (9 days ago) • 2022-08-29 17:28:57 -0700
Engine • revision 5e9e0e0aa8
Tools • Dart 2.18.0 • DevTools 2.15.0

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: RPCError calling getIsolate:org.dartlang.vm.service.element.RPCError@192da6ab
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.flutter.inspector.EvalOnDartLibrary$4.onError(EvalOnDartLibrary.java:300)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
Caused by: java.lang.RuntimeException: RPCError calling getIsolate:org.dartlang.vm.service.element.RPCError@192da6ab
	... 5 more
```

**Comment by stevemessick** [comment]
Can you tell us more about what happened prior to this exception? For example, were you trying to start a debug session? Or opening the Inspector or Perf tool window? Had you recently stopped a Flutter app? The log file might have some useful info, if you can share it. `Help > Show Log in Finder`
