### ISSUE TITLE
InvocationTargetException in non-Flutter project

### ISSUE THREAD

**Issue by markathomas** [flutter/flutter-intellij#6306]
Please fill this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2022.2.2` • Flutter plugin `io.flutter 70.0.5` • Dart plugin `222.4167.21`

No Flutter SDK configured.

## Exception

null

```
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor181.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:248)
	at jdk.proxy2/jdk.proxy2.$Proxy35.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:222)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:96)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:60)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:155)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:205)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:189)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:136)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:75)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:156)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.StringIndexOutOfBoundsException: index 0, length 0
	at java.base/java.lang.String.checkIndex(String.java:4563)
	at java.base/java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:351)
	at java.base/java.lang.StringBuilder.charAt(StringBuilder.java:91)
	at io.flutter.utils.StdoutJsonParser.appendOutput(StdoutJsonParser.java:57)
	at io.flutter.run.daemon.DaemonConsoleView.print(DaemonConsoleView.java:82)
	at com.intellij.execution.impl.ConsoleViewRunningState.print(ConsoleViewRunningState.java:78)
	at com.intellij.execution.impl.ConsoleViewRunningState$1.lambda$onTextAvailable$0(ConsoleViewRunningState.java:33)
	at com.intellij.execution.impl.ProcessStreamsSynchronizer.doWhenStreamsSynchronized(ProcessStreamsSynchronizer.java:79)
	at com.intellij.execution.impl.ConsoleViewRunningState$1.onTextAvailable(ConsoleViewRunningState.java:33)
	... 28 more
```

**Comment by stevemessick** [comment]
Fixed in #6313
