### ISSUE TITLE
Android Studio Dolphin fails to export Flutter project to zip file on Mac (Error: java.is.IOException: Is a directory) 

### ISSUE THREAD

**Issue by keybow007** [flutter/flutter-intellij#6345]
I upgraded my Android Studio version from "Chipmunk" to "Dolphin" and exported my Flutter project as a zip file.

But it failed with an "Error: java.is.IOException: Is a directory" error.

The zip file was exported, but the contents were missing (no "android" or "lib" folders. (See attached image and video).

When I was using "Chipmunk", I could do it without any problem.

---
Android Studio Dolphin | 2021.3.1
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Intel Core i7

![AS_Dolphin_Export_zip_failed](https://user-images.githubusercontent.com/12907755/194473755-afd8f426-1355-4b7b-bc3b-f0a125e3b09b.png)

https://user-images.githubusercontent.com/12907755/194473768-e2ca8c16-b685-4b4d-b7a5-0c7184a44f09.mp4

**Comment by stevemessick** [comment]
The Flutter plugin does not implement any features for exporting projects, so I don't think we'll be able to solve your problem.

I have a couple suggestions to help work around the problem.

First, if you use the Finder to zip up the project, does that work? I'm guessing it does, but it probably create a larger zip file since it would include the `build` directory.

Try opening a command-line terminal with the working directory being the root of your project. Then run this command:
`find . -name .DS_Store -delete -print`
I've had so many problem from those hidden files that this is the first thing I try when something weird happens. It doesn't always help, but it doesn't hurt to try.

Let us know if that helps.

**Comment by keybow007** [comment]
Thanks for your reply.

Unfortunately, deleting the build folder with "flutter clean" and running the command you gave me did not work.
As for zipping directly from the Finder, I can do that with no problem.

**Comment by stevemessick** [comment]
Thanks for the update. I cannot reproduce this problem. I have a bunch of follow-up questions.

Can you make a sample project that reproduces the problem and attach it to this issue?

There may be something in the log file. Can you attempt the export then attach the log file here? You can find the log via `Help > Show Log in Finder`.

Have you added any new directories to the `android` folder?

Does the beta (electric eel) also have this problem? Have you tried exporting with Chipmunk lately? I'm wondering if maybe you recently added something to `android` that confuses the exporter.

**Comment by keybow007** [comment]
Thanks for your feedback.

> Can you make a sample project that reproduces the problem and attach it to this issue?

https://github.com/keybow007/sample2

> Can you attempt the export then attach the log file here?

`2022-10-19 05:58:56,200 [166085312]   INFO - .idea.actions.ExportProjectZip - error making zip 
java.io.IOException: Is a directory
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at com.intellij.openapi.util.io.StreamUtil.copy(StreamUtil.java:33)
	at com.intellij.util.io.Compressor$Zip.writeFileEntry(Compressor.java:130)
	at com.intellij.util.io.Compressor$1.visitFile(Compressor.java:268)
	at com.intellij.util.io.Compressor$1.visitFile(Compressor.java:247)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2800)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2872)
	at com.intellij.util.io.Compressor.addRecursively(Compressor.java:247)
	at com.intellij.util.io.Compressor.addDirectory(Compressor.java:226)
	at com.intellij.util.io.Compressor.addDirectory(Compressor.java:222)
	at com.android.tools.idea.actions.ExportProjectZip.save(ExportProjectZip.java:167)
	at com.android.tools.idea.actions.ExportProjectZip$1.run(ExportProjectZip.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:436)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:120)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:496)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

> Have you added any new directories to the android folder?

No.

> Have you tried exporting with Chipmunk lately?

Not done for this project, but done for other projects.

**Comment by stevemessick** [comment]
Thanks for the update. Unfortunately, I cannot reproduce the problem using your sample project. If you download it and install it, then open it and try to export it, does it fail for you? Also, I've had problems (in a different context) with symbolic links. Do you have any symlinks in your project?

The stack trace was helpful. I took a look at the IntelliJ code that is doing the compression. It was heavily refactored in 2021, which is the version in Dolphin. Chipmunk used an older version. It is possible they introduced a bug. If so, I won't be able to help fix your problem. You can report an issue at [youtrack.jetbrains.com](youtrack.jetbrains.com).

**Comment by keybow007** [comment]
Thanks for the update. Surprisingly, even though I uploaded the project to Github that had the error, I cloned the project from Github and there was no error. As you said, it may be a bug in IntelliJ, so I'll try to throw an issue at youtrack.jetbrains.com.

**Comment by keybow007** [comment]
This issue is not resolved in Android Studio Electric Eel | 2022.1.1.

![スクリーンショット 2023-01-24 14 41 18](https://user-images.githubusercontent.com/12907755/214220269-5a583125-284c-46ef-a356-aa18099ba3c6.png)

**Comment by keybow007** [comment]
log

```
2023-01-24 14:46:30,050 [ 652564]   INFO - #c.a.t.i.a.ExportProjectZip - error making zip
java.io.IOException: Is a directory
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at com.intellij.openapi.util.io.StreamUtil.copy(StreamUtil.java:33)
	at com.intellij.util.io.Compressor$Zip.writeFileEntry(Compressor.java:130)
	at com.intellij.util.io.Compressor$1.visitFile(Compressor.java:268)
	at com.intellij.util.io.Compressor$1.visitFile(Compressor.java:247)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2800)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2872)
	at com.intellij.util.io.Compressor.addRecursively(Compressor.java:247)
	at com.intellij.util.io.Compressor.addDirectory(Compressor.java:226)
	at com.intellij.util.io.Compressor.addDirectory(Compressor.java:222)
	at com.android.tools.idea.actions.ExportProjectZip.save(ExportProjectZip.java:167)
	at com.android.tools.idea.actions.ExportProjectZip$1.run(ExportProjectZip.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by stevemessick** [comment]
There is no Flutter plugin code in that stack trace. That makes it an IntelliJ problem. Sorry I can't help more.

**Comment by alexander-doroshko** [comment]
I believe `com.android.tools.idea.actions.ExportProjectZip` action is maintained by the Android Studio developers. Though the status of this issue in their tracker is unlucky: https://issuetracker.google.com/issues/251686876

**Comment by victoremanuelgo** [comment]
same problem here, also macos

**Comment by ManPanchani** [comment]
same problem here, also macos, please solution send me
