### ISSUE TITLE
While opening MasterStudy LMS Mobile App - Flutter v.3 iOS & Android 

### ISSUE THREAD

**Issue by bajpangosh** [flutter/flutter-intellij#6357]
## Version information

Android Studio `Bumblebee | 2021.1.1 Patch 2` • Flutter plugin `io.flutter 70.2.1` • Dart plugin `211.7817`

Flutter 3.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 676cefaaff (4 months ago) • 2022-06-22 11:34:49 -0700
Engine • revision ffe7b86a1e
Tools • Dart 2.17.5 • DevTools 2.12.2

## Exception

null

```
org.jdom.JDOMException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:293)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:324)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoaderKt.loadStorageFile(JpsProjectEntitiesLoader.kt:174)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponents(JpsProjectSerializersImpl.kt:781)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.access$loadComponents(JpsProjectSerializersImpl.kt:762)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:768)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:762)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponent(JpsProjectSerializersImpl.kt:767)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.readModuleOptions(ModuleImlFileEntitiesSerializer.kt:173)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadModuleEntity(ModuleImlFileEntitiesSerializer.kt:103)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadEntities(ModuleImlFileEntitiesSerializer.kt:69)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule$intellij_platform_workspaceModel_ide(JpsProjectEntitiesLoader.kt:63)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule(JpsProjectEntitiesLoader.kt:51)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.loadModule(ModifiableModuleModelBridgeImpl.kt:163)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModuleFromFile(FlutterModuleBuilder.java:216)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModule(FlutterModuleBuilder.java:199)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:153)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.java:335)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:309)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$3(StartupManagerImpl.java:245)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:403)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:325)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:94)
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:286)
	... 52 more
```

**Comment by stevemessick** [comment]
It looks like your Android module file is empty or does not exist. The first thing to try is re-creating the Flutter framework files. Make a backup copy of your project first. Then use a terminal to run `flutter create .` in the root directory of your project. If that fixes it, please let us know.

If that doesn't fix the problem, then can you look for a file that ends with `android.iml`? It might be in the root directory, or it could be in a directory named `android` or `.android`. There might not be any prefix before `android.iml`.

Another way to fix the problem would be to re-create the project. Make a new Flutter project then copy your app content into the new project. There are some old Flutter projects that do not have the IML file I mentioned.
