### ISSUE TITLE
Android Studio breakpoint debugging is not available

### ISSUE THREAD

**Issue by hzhyan** [flutter/flutter-intellij#6366]
My project is mixed development.With the Flutter plugin enabled, Android Studio's native debugging breakpoints are not available.
And With the Flutter plugin disable, Android Studio's native debugging breakpoint is regular work.

It is not required, but I am sure there is a relationship between debug not taking effect and the Flutter plugin.

Android Studio Version: 2021.3.1 Patch 1
Flutter Plugin Version: 70.2.3

Android Stuido idea.log

2022-10-24 17:02:06,972 [1245626]  ERROR - lij.debugger.impl.InvokeThread - null 
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at io.flutter.utils.AddToAppUtils$3$1.processAttached(AddToAppUtils.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy229.processAttached(Unknown Source)
	at com.intellij.debugger.engine.DebugProcessEvents.vmAttached(DebugProcessEvents.java:400)
	at com.intellij.debugger.engine.DebugProcessEvents.commitVM(DebugProcessEvents.java:81)
	at com.intellij.debugger.engine.DebugProcessImpl$12$1.action(DebugProcessImpl.java:2280)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:43)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:155)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:30)
	at com.intellij.debugger.impl.InvokeThread.lambda$run$0(InvokeThread.java:138)
	at com.intellij.openapi.project.DumbService.runWithAlternativeResolveEnabled(DumbService.java:383)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:125)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.lambda$run$0(InvokeThread.java:49)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-24 17:02:06,972 [1245626]  ERROR - lij.debugger.impl.InvokeThread - Android Studio Dolphin | 2021.3.1 Patch 1  Build #AI-213.7172.25.2113.9123335 
2022-10-24 17:02:06,972 [1245626]  ERROR - lij.debugger.impl.InvokeThread - JDK: 11.0.13; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2022-10-24 17:02:06,972 [1245626]  ERROR - lij.debugger.impl.InvokeThread - OS: Mac OS X 
2022-10-24 17:02:06,972 [1245626]  ERROR - lij.debugger.impl.InvokeThread - Plugin to blame: Flutter version: 70.2.3 
2022-10-24 17:02:06,972 [1245626]  ERROR - lij.debugger.impl.InvokeThread - Last Action: AndroidConnectDebuggerAction 
2022-10-24 17:02:10,463 [1249117]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving 
2022-10-24 17:02:10,464 [1249118]   INFO - re.component.SaveActionManager - Locating psi files for 0 documents: [] 
2022-10-24 17:02:10,464 [1249118]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving

**Comment by stevemessick** [comment]
If you change back to Android Studio Chipmunk, does debugging work?

**Comment by hzhyan** [comment]
> If you change back to Android Studio Chipmunk, does debugging work?

Downgrade is troublesome.I found trigger Gradle Sync could solve the problem,but it would take a long time, just like the cache is not available, i need download all dependence.

**Comment by stevemessick** [comment]
Debugging Flutter + Java/Kotlin *does* require a full Gradle sync. You need all the dependencies, and everything must be fully compiled.

**Comment by hzhyan** [comment]
> 

Of course. I suspect the Flutter Plugin may have corrupted some state recorded internally by the compiler to cause this problem. 
Do you have any ideas about how to solve this problem through the log provided above? Do you plan a version later?
