### ISSUE TITLE
Git command is called from the event dispatch thread

### ISSUE THREAD

**Issue by juliabeliaeva** [flutter/flutter-intellij#6368]
`FlutterCreateAdditionalSettingsFields` calls `PlatformsForm.initChannel`: https://github.com/flutter/flutter-intellij/blob/418068ba3a7063adf699443085939ea337c50a93/flutter-idea/src/io/flutter/module/settings/FlutterCreateAdditionalSettingsFields.java#L140 which leads to `LightGitUtilKt.getLocation` being called from the EDT, which is not advisable since it synchronously executes a git command. It's better to move such calls to background. See the exception from the platform:
```
java.lang.Throwable: Synchronous execution on EDT: /usr/bin/git rev-parse --abbrev-ref HEAD, see com.intellij.execution.process.OSProcessHandler#checkEdtAndReadAction() Javadoc for resolutions
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.execution.process.OSProcessHandler.checkEdtAndReadAction(OSProcessHandler.java:171)
	at com.intellij.execution.process.OSProcessHandler.waitFor(OSProcessHandler.java:109)
	at git4idea.commands.GitTextHandler.waitForProcess(GitTextHandler.java:123)
	at git4idea.commands.GitHandler.runInCurrentThread(GitHandler.java:402)
	at git4idea.commands.GitImplBase.doRun(GitImplBase.java:201)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:172)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:63)
	at git4idea.light.LightGitUtilKt.getLocation(LightGitUtil.kt:22)
	at io.flutter.sdk.FlutterSdk.queryFlutterChannel(FlutterSdk.java:545)
	at io.flutter.module.settings.PlatformsForm.initChannel(PlatformsForm.kt:31)
	at io.flutter.module.settings.FlutterCreateAdditionalSettingsFields.addSettingsFields(FlutterCreateAdditionalSettingsFields.java:140)
	at io.flutter.module.FlutterModuleBuilder.modifySettingsStep(FlutterModuleBuilder.java:313)
	at com.intellij.ide.projectWizard.ProjectSettingsStep.setupPanels(ProjectSettingsStep.java:104)
	at com.intellij.ide.projectWizard.ProjectSettingsStep.updateStep(ProjectSettingsStep.java:126)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.updateStep(AbstractProjectWizard.java:154)
	at com.intellij.ide.wizard.AbstractWizard.updateStep(AbstractWizard.java:411)
	at com.intellij.ide.wizard.AbstractWizard.doNextAction(AbstractWizard.java:435)
	at com.intellij.ide.util.newProjectWizard.AbstractProjectWizard.doNextAction(AbstractProjectWizard.java:258)
	at com.intellij.ide.wizard.AbstractWizard.proceedToNextStep(AbstractWizard.java:247)
	at com.intellij.ide.wizard.AbstractWizard$5.actionPerformed(AbstractWizard.java:199)
...
```

Product: IntelliJ IDEA 222.4345.14
Plugin: Flutter 70.2.5

**Comment by stevemessick** [comment]
This is correct, but we don't plan to change it. The specific git command is very quick and causes an almost-imperceptible pause the first time the new project wizard displays its second page. Subsequent displays use the cached value. If the Flutter SDK is changed by selecting a non-default value on the first page of the wizard, or by changing it in the plugin settings page, the value will be cached.

**Comment by stevemessick** [comment]
I replied too quickly. We already have a PR that removes the necessity of using git. I've filed an issue to remind myself to clean up the code.
