### ISSUE TITLE
Code coverage is not working in monorepo projects

### ISSUE THREAD

**Issue by imudita** [flutter/flutter-intellij#6375]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
- select xxx_test.dart file
- right click on the file to show popup menu
- click "run 'xxx_test.dart' with coverage" menu item
- when test is completed, the test is OK, however when processing the coverage, the error would be reported

The project file structures are:
root folder
- project_a
> - lib
> > - xxx.dart
> - test
> > - xxx_test.dart
- module_a
> - lib
> - test
- module_b
- etc

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19044.2130], locale en-AU)
    • Flutter version 2.5.0 at D:\tools\flt\flutter250
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (1 year, 2 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\MUDITA\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = d:\alias\google-chrome-unsafe.bat

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Android Studio (version 2021.2)
    • Android Studio at D:\tools\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\MUDITA\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 107.0.5304.62
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 105.0.1343.50

**Comment by imudita** [comment]
## Exception

null

```
java.lang.RuntimeException: Could not find project root
	at io.flutter.run.coverage.FlutterCoverageEnabledConfiguration.createCoverageFile(FlutterCoverageEnabledConfiguration.java:41)
	at io.flutter.run.coverage.FlutterCoverageEnabledConfiguration.<init>(FlutterCoverageEnabledConfiguration.java:30)
	at io.flutter.run.coverage.FlutterCoverageEngine.createCoverageEnabledConfiguration(FlutterCoverageEngine.java:57)
	at com.intellij.execution.configurations.coverage.CoverageEnabledConfiguration.getOrCreate(CoverageEnabledConfiguration.java:155)
	at io.flutter.run.coverage.FlutterCoverageProgramRunner.processCoverage(FlutterCoverageProgramRunner.java:86)
	at io.flutter.run.coverage.FlutterCoverageProgramRunner$1.lambda$processTerminated$0(FlutterCoverageProgramRunner.java:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stevemessick** [comment]
This looks like a monorepo project. The stack trace suggests the coverage code needs to be updated to work in a monorepo project. For now, you can probably work around this by opening each sub-project as a top-level project. Let us know if that works and I'll update this to reflect the monorepo dependency.

**Comment by dk-imudita** [comment]
Yes, it works fine, if we open each sub-project as a top-level project.

Thanks ..

**Comment by stevemessick** [comment]
Monorepo Flutter projects are tricky in Android Studio. The instructions for building them are here:
https://groups.google.com/g/flutter-announce/c/on6eKqmhD3A

Did you build your project according to those instructions?

**Comment by stevemessick** [comment]
@imudita @dk-imudita: I just created a PR to allow test coverage to work in monorepo projects. You'll need to re-create your monorepo project according to the instructions I linked previously. You should also remove any run configs that have been run with coverage -- even if it didn't work, they may still be invalid. But there is no hurry, since I don't know when the next point release will be published.

**Comment by dk-imudita** [comment]
I am not so sure, this is existing project that already there for more than 2 years. I will try to create new monorepo Flutter project as per your instructions later.

Thank you for the link.
