### ISSUE TITLE
Flutter plugin error

### ISSUE THREAD

**Issue by Panaith** [flutter/flutter-intellij#6413]
---

## What happened

Restarted Intellij right after Dart plugin update version

## Version information

IntelliJ IDEA `2022.3` • Flutter plugin `io.flutter 71.0.6`

No Flutter sdk configured.

## Exception

null

```
com.intellij.diagnostic.PluginException: Cannot create class io.flutter.editor.FlutterIconLineMarkerProvider (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2022.3\plugins\flutter-intellij, version=71.0.6, package=null, isBundled=false), packagePrefix=null, instanceId=364, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:995)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1012)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:44)
	at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
	at com.intellij.application.options.editor.GutterIconsSearchableOptionContributor.processOptions(GutterIconsSearchableOptionContributor.java:19)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$0(SearchableOptionsRegistrarImpl.java:125)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:35)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:46)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:125)
	at com.intellij.openapi.options.newEditor.SettingsFilter.lambda$new$1(SettingsFilter.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.diagnostic.PluginException: Cannot load class io.flutter.editor.FlutterIconLineMarkerProvider$IconInfoVisitor (
  error: com/jetbrains/lang/dart/psi/DartRecursiveVisitor,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2022.3\plugins\flutter-intellij, version=71.0.6, package=null, isBundled=false), packagePrefix=null, instanceId=364, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:426)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:240)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:212)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:956)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: com/jetbrains/lang/dart/psi/DartRecursiveVisitor
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:264)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:113)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:243)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:176)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:418)
	... 26 more
Caused by: java.lang.ClassNotFoundException: com.jetbrains.lang.dart.psi.DartRecursiveVisitor PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2022.3\plugins\flutter-intellij, version=71.0.6, package=null, isBundled=false), packagePrefix=null, instanceId=364, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 34 more
```

**Comment by stevemessick** [comment]
It looks like IntelliJ had a problem upgrading the Dart plugin. Try removing it and re-installing. If you are still having problems then you might be able to get help from JetBrains. Just to be clear, I checked and the missing class is still in the Dart plugin. I had no problems upgrading, although I did upgrade the plugin before upgrading IntelliJ. Let us know if that works.

**Comment by mdddj** [comment]
> 
Reinstallation works for me

**Comment by Panaith** [comment]
Yes, re-installing the plugin does the trick. Thank you very much

**Comment by stevemessick** [comment]
Great, thanks for the update.

**Comment by Nikzed** [comment]
hi, still isn't working even after reinstallation :(
