### ISSUE TITLE
NoSuchMethodError: AndroidSdkUtils.setupAndroidPlatformIfNecessary(Module, boolean)

### ISSUE THREAD

**Issue by josephwambura** [flutter/flutter-intellij#6459]
## What happened

Just restarted the IDE, to clear the cache

## Version information

Android Studio `Flamingo | 2022.2.1 Canary 9` • Flutter plugin `io.flutter 71.0.5` • Dart plugin `222.4345.14`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.NoSuchMethodError: 'void org.jetbrains.android.sdk.AndroidSdkUtils.setupAndroidPlatformIfNecessary(com.intellij.openapi.module.Module, boolean)'
	at io.flutter.android.AndroidModuleLibraryManager.addAndroidLibraryDependencies(AndroidModuleLibraryManager.java:129)
	at io.flutter.android.AndroidModuleLibraryManager.addAndroidLibraryDependencies(AndroidModuleLibraryManager.java:119)
	at io.flutter.android.AndroidModuleLibraryManager.lambda$scheduleAddAndroidLibraryDeps$0(AndroidModuleLibraryManager.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by stevemessick** [comment]
This works in canary 8 but is broken in canary 9. The method does exist in IntelliJ 2022.3.

I asked the Android Studio team to consider restoring the missing method. I'd link to that issue here but I can't find it in the public issue tracker yet.

**Comment by josephwambura** [comment]
> This works in canary 8 but is broken in canary 9. The method does exist in IntelliJ 2022.3.
> 
> I asked the Android Studio team to consider restoring the missing method. I'd link to that issue here but I can't find it in the public issue tracker yet.

okay

**Comment by stevemessick** [comment]
I'm not seeing this problem in canary 11, so I'll close it.
