### ISSUE TITLE
Unable to simplify default flutter test configuration

### ISSUE THREAD

**Issue by JaredEzz** [flutter/flutter-intellij#6529]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

It's unfortunate that the default configuration in IntelliJ for running a flutter test is to run it as `...\flutter\bin\flutter.bat --no-color test --machine --start-paused [args] test\some_test.dart`. Because I'm running tests for Flutter Web and have html imported in various places, I have to add the `--platform chrome` arg which does not work with this default config. Running just plain `flutter test --platform chrome test\some_test.dart` works great though from the command line. Would love it if there were options to simplify the default configuration - is that possible?

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\jared\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (7 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\jared\.jdks\corretto-11.0.14\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.7571.203

[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.7571.182
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4345.14

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by stevemessick** [comment]
Are you saying that it does not work if you replace `[args]` in your first command line with `--platform chrome`?

The other args (`--machine --start-paused`) are required for sync'ing the Flutter process and the IDE.

**Comment by JaredEzz** [comment]
It does not work. running `flutter test --platform chrome` from the terminal results in all tests passing. 
![image](https://user-images.githubusercontent.com/13698465/213511329-f2852e47-895f-406f-83b6-c8a3948db0e8.png)

However, using "Run All Tests" where I've added `--platform chrome` in additional args causes flutter to rash and the tests don't all pass. This time I get a crash report. I'll paste details below.

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color test --machine --platform chrome test

## exception

UnsupportedError: Unsupported operation: Illegal character in path: C:

```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1841:11)
#1      _Uri._toWindowsFilePath (dart:core/uri.dart:2879:7)
#2      _Uri.toFilePath (dart:core/uri.dart:2854:38)
#3      JsonReporter._frameInfo.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:314:19)
#4      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:246:15)
#5      JsonReporter._frameInfo (package:test_core/src/runner/reporter/json.dart:312:35)
#6      JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:145:12)
#7      _rootRunUnary (dart:async/zone.dart:1407:13)
#8      _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#13     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#14     _rootRunUnary (dart:async/zone.dart:1399:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1300:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1209:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#19     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:25)
#20     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
#21     LiveSuiteController.reportLiveTest (package:test_core/src/runner/live_suite_controller.dart:133:30)
#22     Engine._runLiveTest (package:test_core/src/runner/engine.dart:364:21)
<asynchronous suspension>
#23     Engine._runGroup (package:test_core/src/runner/engine.dart:325:13)
<asynchronous suspension>
#24     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:268:13)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.22622.575], locale en-US)
    • Flutter version 3.3.8 on channel stable at C:\Users\jared\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (2 months ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\jared\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Users\jared\.jdks\corretto-11.0.14\bin\java.exe
    • Java version OpenJDK Runtime Environment Corretto-11.0.14.9.1 (build 11.0.14+9-LTS)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\222.4345.14
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.7571.203

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at C:\Users\jared\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\223.7571.182
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4345.14

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.575]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.75
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

**Comment by JaredEzz** [comment]
> Are you saying that it does not work if you replace `[args]` in your first command line with `--platform chrome`?
> 
> The other args (`--machine --start-paused`) are required for sync'ing the Flutter process and the IDE.

In this, it seems the --machine arg and the --platform arg are intended to be mutually exclusive. Can I create a configuration that removes the machine arg? https://github.com/flutter/flutter/issues/98110#issuecomment-1033792130

**Comment by stevemessick** [comment]
The IntelliJ plugin requires the `--machine` arg. Since this problem is reproducible on the command line I'm transferring it to the flutter repo.
