### ISSUE TITLE
`LateInitializationError` on hot reloading 

### ISSUE THREAD

**Issue by CicadaCinema** [flutter/flutter-intellij#6537]
## Steps to Reproduce

1) Run `flutter create myapp`.
2) Paste the following code into `main.dart`:
```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(const ExampleApp());
}
class Data {
  late double _i;

  void initI(double i) => _i = i;

  void printI() => print(_i);
}

class DataDisplay extends StatefulWidget {
  final Data data;

  const DataDisplay({
    Key? key,
    required this.data,
  }) : super(key: key);

  @override
  State<DataDisplay> createState() => _DataDisplayState();
}

class _DataDisplayState extends State<DataDisplay> {
  late final Timer _timer;

  @override
  initState() {
    super.initState();

    widget.data.initI(5);

    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      widget.data.printI();
      print('a');
    });
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}


class ExampleApp extends StatelessWidget {
  const ExampleApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: DataDisplay(
          data: Data(),
        ),
      ),
    );
  }
}

```

3) Open the project using Android Studio.
4) Select the "Windows (desktop)" device, and run the app. Observe that no error is thrown and output is printed to the terminal every second.
5) Click "hot restart", observe a `LateInitializationError`:
```
Performing hot restart...
Syncing files to device Windows...
Restarted application in 345ms.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_i@18264790' has not been initialized.
#0      Data._i (package:myapp/main.dart)
#1      Data.printI (package:myapp/main.dart:14:26)
#2      _DataDisplayState.initState.<anonymous closure> (package:myapp/main.dart:39:19)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

Note that when using the terminal (`flutter run -d Windows` to run the app and `R` to perform a hot restart) no error is thrown.

## Version info

```
C:\Users\Atom>flutter doctor -v
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2364], locale en-GB)
    • Flutter version 3.3.10 on channel stable at C:\Software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Atom\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at:
      C:\Users\Atom\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31605.320
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Users\Atom\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8609683
    • Flutter plugin version 70.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Users\Atom\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\213.7172.25.2113.9123335
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code, 64-bit edition (version 1.74.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.46

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by stevemessick** [comment]
Thanks for the repro code!

I know it looks like an IDE problem but I don't think it is. The IDE effectively does `flutter run` but adds additional arguments, putting the `flutter` tool into a different mode. You'd probably see the same problem if you included all the additional arguments when you run it from the command line. If you want to know what the additional args are you can find them in the log file. Search for "start-paused". Here's an example from my log file:
```dart
flutter/bin/flutter [--no-color, run, --machine, --track-widget-creation, --device-id=emulator-5554, --start-paused, --dart-define=flutter.inspector.structuredErrors=true, lib/main.dart]
```
Transferring to `flutter/flutter`.
