### ISSUE TITLE
Starting up Android Studio have an error: java.lang.NoSuchMethodError.

### ISSUE THREAD

**Issue by imchrm** [flutter/flutter-intellij#6634]
## System
  _Kernel: 5.15.0-60-generic x86_64 bits: 64 compiler: gcc v: 11.3.0_
  _Desktop: Cinnamon 5.6.7 tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0_
  _Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy_

## **Steps to Reproduce**
Each time when I start Android Studio, open a new one or a recent project.
However, I can compile and build a project and run it on a device or emulator. At first glance, all functions work.

## Version information

Android Studio `Flamingo | 2022.2.1 Beta 3` • Flutter plugin `io.flutter 72.1.3` • Dart plugin `222.4533`

[✓] Flutter (Channel stable, 3.7.3, on Linux Mint 21.1 5.15.0-60-generic, locale en_US.UTF-8)
    • Flutter version 3.7.3 on channel stable at /home/dm/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (13 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /opt/android-sdk/
    • Platform android-33-ext4, build-tools 33.0.1
    • ANDROID_HOME = /opt/android-sdk/
    • ANDROID_SDK_ROOT = /opt/android-sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.4.1+0-17.0.4.1b469.62-9127311)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 17.0.4.1+0-17.0.4.1b469.62-9127311)

[!] Android Studio (version 2022.2)
    • Android Studio at /home/dm/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9601061
    • Flutter plugin version 72.1.3
    • Dart plugin version 222.4533
    ✗ **_Unable to find bundled Java version._**
    • Try updating or re-installing Android Studio.

[✓] Android Studio
    • Android Studio at /opt/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /opt/android-studio/
    • Java version OpenJDK Runtime Environment (build 17.0.4.1+0-17.0.4.1b469.62-9127311)

[✓] Connected device (2 available)
    • M2101K6G (mobile) • 814a2be5 • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux    • linux-x64     • Linux Mint 21.1 5.15.0-60-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

## Exception

null

```
java.lang.NoSuchMethodError: 'void org.jetbrains.android.sdk.AndroidSdkUtils.setupAndroidPlatformIfNecessary(com.intellij.openapi.module.Module, boolean)'
	at io.flutter.android.AndroidModuleLibraryManager.addAndroidLibraryDependencies(AndroidModuleLibraryManager.java:129)
	at io.flutter.android.AndroidModuleLibraryManager.addAndroidLibraryDependencies(AndroidModuleLibraryManager.java:119)
	at io.flutter.android.AndroidModuleLibraryManager.lambda$scheduleAddAndroidLibraryDeps$0(AndroidModuleLibraryManager.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by stevemessick** [comment]
In the source code I have (EAP, not beta) the class and method are both defined. I'm not sure how you'd get a `NoSuchMethodError` if the class exists. Perhaps there is another class named `org.jetbrains.android.sdk.AndroidSdkUtils` on your class path? That could happen (I think) if you have other plugins installed in addition to Dart and Flutter. Or if you have defined the Java class path using environment variables and it has a reference to another class of that name. You should check your environment variables, and remember that the ones used by the IDE are different from those in a terminal emulator.

The quickest way to fix it is probably to remove and re-install.
https://www.jetbrains.com/help/idea/uninstall.html
You might want to try a stand-alone installation.
https://www.jetbrains.com/help/idea/installation-guide.html#standalone

Let us know if that helps.
