### ISSUE TITLE
java.util.concurrent.CompletionException: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@6b933f3d

### ISSUE THREAD

**Issue by SIHU08** [flutter/flutter-intellij#6687]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2022.3.3` • Flutter plugin `io.flutter 72.1.4` • Dart plugin `223.8888`

Error getting Flutter sdk information.

## Exception

null

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@6b933f3d
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.flutter.inspector.EvalOnDartLibrary.lambda$addRequest$0(EvalOnDartLibrary.java:98)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: RPCError calling getObject: org.dartlang.vm.service.element.RPCError@6b933f3d
	at io.flutter.inspector.EvalOnDartLibrary$3.onError(EvalOnDartLibrary.java:227)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by stevemessick** [comment]
Please attach your log file. You can find it using the `Help` menu. Caution, it may contain confidential information, so please remove that.
