### ISSUE TITLE
Opening an existing Flutter project after upgrading Flutter to version 3.7.11 crashes IDE

### ISSUE THREAD

**Issue by roslamir** [flutter/flutter-intellij#6715]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Opening an existing Flutter project after upgrading Flutter to version 3.7.11.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by roslamir** [comment]
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.19044.2846], locale en-MY)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by roslamir** [comment]
Exception
Worker exited due to exception

java.lang.AssertionError: Cannot create com.intellij.execution.ui.RunContentManager because container is already disposed (container=ClientId(value=Host))
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.execution.ui.RunContentManager because container is already disposed (container=ClientId(value=Host))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:640)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:752)
	at com.intellij.openapi.client.ClientSessionImpl.doGetService(ClientSessionImpl.kt:93)
	at com.intellij.openapi.client.ClientAwareComponentManager.postGetService(ClientAwareComponentManager.kt:39)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:699)
	at com.intellij.openapi.components.ServiceManager.getServiceIfCreated(ServiceManager.java:36)
	at io.flutter.run.FlutterAppManager.getRunContentManager(FlutterAppManager.java:128)
	at io.flutter.run.FlutterAppManager.getActiveApp(FlutterAppManager.java:66)
	at io.flutter.run.FlutterAppManager.updateActiveApp(FlutterAppManager.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 8 more
