### ISSUE TITLE
Android App could not debug build with Flutter，debugger show connected. But break point couldn't go into effected

### ISSUE THREAD

**Issue by DuanTzXavier** [flutter/flutter-intellij#6726]
## Steps to Reproduce

when I connect debugger to android device, I always get success callback in console print :

Connected to the target VM, address: 'localhost:XXXX', transport: 'socket'

But the break point couldn't go into effected (the red icon didn't show the checked icon).

And here is my error log:

```

2023-04-24 20:43:55,355 [3005028]  ERROR - lij.debugger.impl.InvokeThread - Last Action: AndroidConnectDebuggerAction 
2023-04-24 20:43:56,929 [3006602]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=soulapp-android, containerState=COMPONENT_CREATED, componentStore=/Users/bask/WorkSpace/copy/soulapp-android)GradleLocalSettings took 12 ms 
2023-04-24 20:43:58,382 [3008055]   INFO - il.indexing.FileBasedIndexImpl - Health check heartbeat 
2023-04-24 20:45:10,384 [3080057]   INFO - .http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://clients2.google.com:443: No route to host (Host unreachable) 
2023-04-24 20:45:10,385 [3080058]   INFO - .http.impl.execchain.RetryExec - Retrying request to {s}->https://clients2.google.com:443 
2023-04-24 20:46:05,800 [3135473]  ERROR - lij.debugger.impl.InvokeThread - null 
java.lang.AssertionError
	at io.flutter.utils.AddToAppUtils$3$1.processAttached(AddToAppUtils.java:161)
	at jdk.internal.reflect.GeneratedMethodAccessor1018.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy253.processAttached(Unknown Source)
	at com.intellij.debugger.engine.DebugProcessEvents.vmAttached(DebugProcessEvents.java:400)
	at com.intellij.debugger.engine.DebugProcessEvents.commitVM(DebugProcessEvents.java:81)
	at com.intellij.debugger.engine.DebugProcessImpl$12$1.action(DebugProcessImpl.java:2280)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:43)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:155)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:30)
	at com.intellij.debugger.impl.InvokeThread.lambda$run$0(InvokeThread.java:138)
	at com.intellij.openapi.project.DumbService.runWithAlternativeResolveEnabled(DumbService.java:383)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:125)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.lambda$run$0(InvokeThread.java:49)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

## Version info

```
[!] Flutter (Channel unknown, 3.7.6, on macOS 13.1 22C65 darwin-arm64, locale
    zh-Hans-CN)
    ! Flutter version 3.7.6 on channel unknown at /Users/bask/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an
      official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions
      at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Framework revision 12cb4eb7a0 (8 weeks ago), 2023-03-01 10:29:26 -0800
    • Engine revision ada363ee93
    • Dart version 2.19.3
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bask/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/bask/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • ANA AN00 (mobile) • NAB0220314015389 • android-arm64  • Android 12 (API
      31)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 13.1 22C65
      darwin-arm64
    • Chrome (web)      • chrome        
   • web-javascript • Google Chrome
      112.0.5615.137

```
the attach file is full logs [idea.log](https://github.com/flutter/flutter-intellij/files/11319947/idea.log)

report from :
https://youtrack.jetbrains.com/issue/IDEA-318839/Android-App-could-not-debug-build-with-Flutterdebugger-show-connected.-But-break-point-couldnt-go-into-effected

**Comment by DuanTzXavier** [comment]
I'm using Android Studio and also  working in a multi repo project that include many native module and one flutter module.

I read the plugin code last day. Maybe the code could be optimize by not using assert to throw exception in origin process:

```
        @Override
        public void processAttached(@NotNull DebugProcess process) {
          if (project.getUserData(ATTACH_IS_ACTIVE) != null) {
            return;
          }
          // Launch flutter attach if a run config can be found.
          if (findRunConfig(project) == null) {
            // Either there is no Flutter run config or there are more than one.
            if (RunManagerEx.getInstanceEx(project).getSelectedConfiguration() instanceof SdkRunConfig) {
              // The selected run config at this point is not Flutter, so we can't start the process automatically.
              return;
            }
          }
          FlutterSdk sdk = FlutterSdk.getFlutterSdk(project);
          if (sdk == null) {
            return;
          }
          // If needed, DataContext could be saved by FlutterReloadManager.beforeActionPerformed() in project user data.
          DataContext context = DataContext.EMPTY_CONTEXT;
          List<Module> modules = FlutterModuleUtils.findModulesWithFlutterContents(project);
          assert modules.size() == 1; // TODO(messick) Need to change this if multiple :flutter sub-projects supported.
          PubRoot pubRoot = PubRoot.forDirectory(Objects.requireNonNull(modules.get(0).getModuleFile()).getParent());
          Application app = ApplicationManager.getApplication();
          project.putUserData(ATTACH_IS_ACTIVE, ThreeState.fromBoolean(true));
          // Note: Using block comments to preserve formatting.
          app.invokeLater( /* After the Android launch completes, */
            () -> app.executeOnPooledThread( /* but not on the EDT, */
              () -> app.runReadAction( /* with read access, */
                () -> new AttachDebuggerAction().startCommand(project, sdk, pubRoot, context)))); /* attach. */
        }
      };
```

It's very dangerous for product project.

Maybe there are some rarely occur error that  function `public static List<Module> findModulesWithFlutterContents(@NotNull Project project)`  can't located the Flutter Content case this bug.

Anyway, you shouldn't `assert ` something, because this cause other plugin couldn't make there process by throw exception.

**Comment by stevemessick** [comment]
@DuanTzXavier The reason for the assert is that the code after it won't work in a monorepo project. At the time add-to-app was being created the plugin expected there to be a single Flutter module. We started relaxing that requirement about a year ago, and are still finding places that need to be updated. This is one.

**Comment by DuanTzXavier** [comment]
> @DuanTzXavier The reason for the assert is that the code after it won't work in a monorepo project. At the time add-to-app was being created the plugin expected there to be a single Flutter module. We started relaxing that requirement about a year ago, and are still finding places that need to be updated. This is one.

` it won't work in a monorepo project` . I just want to use Android  Studio java / kotlin code debug. But this Error **assert** cause all debug crash.

Only one feature not support will cause whole system crash ....
