### ISSUE TITLE
java.lang.RuntimeException: Exception while applying information to Editor: file://E:/workspace/dart/bin/dart.dart(com.jetbrains.lang.dart.DartFileType@50a7e45a) 

### ISSUE THREAD

**Issue by danielesk** [flutter/flutter-intellij#6735]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Build: AI-222.4459.24.2221.9862592, 202303311419,

AI-222.4459.24.2221.9862592, JRE 17.0.6+0-b2043.56-9586694x64 JetBrains s.r.o., OS Windows 11(amd64) v10.0 , screens 3240.0x2160.0, 1920.0x1080.0

AS: Flamingo | 2022.2.1
Kotlin plugin: 222-1.8.0-release-AS3739.54
Android Gradle Plugin: (plugin information not found)
Gradle: (gradle version information not found)
Gradle JDK: JetBrains Runtime version 17.0.6
NDK: from local.properties: (not specified), latest from SDK: (not found)
CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)
Source: send_feedback_icon

IMPORTANT: Please read https://developer.android.com/studio/report-bugs.html carefully and supply all required information.
```


java.lang.RuntimeException: Exception while applying information to Editor: file://E:/workspace/dart/bin/dart.dart(com.jetbrains.lang.dart.DartFileType@50a7e45a)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$9(PassExecutorService.java:488)
        at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
        at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
        at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
        at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
        at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
        at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
        at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.diagnostic.PluginException: Positive width should be defined for an inline element by <image>
        at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
        at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
        at com.intellij.openapi.editor.impl.InlineInlayImpl.doUpdate(InlineInlayImpl.java:73)
        at com.intellij.openapi.editor.impl.InlayImpl.<init>(InlayImpl.java:35)
        at com.intellij.openapi.editor.impl.InlineInlayImpl.<init>(InlineInlayImpl.java:26)
        at com.intellij.openapi.editor.impl.InlayModelImpl.addInlineElement(InlayModelImpl.java:149)
        at com.intellij.openapi.editor.impl.InlayModelImpl.addInlineElement(InlayModelImpl.java:136)
        at com.intellij.codeInsight.hints.InlayHintsPass$Companion.addInlineHints(InlayHintsPass.kt:129)
        at com.intellij.codeInsight.hints.InlayHintsPass$Companion.access$addInlineHints(InlayHintsPass.kt:73)
        at com.intellij.codeInsight.hints.InlayHintsPass$Companion$applyCollected$1.run(InlayHintsPass.kt:105)
        at com.intellij.openapi.editor.impl.InlayModelImpl.execute(InlayModelImpl.java:510)
        at com.intellij.codeInsight.hints.InlayHintsPass$Companion.applyCollected$intellij_platform_lang_impl(InlayHintsPass.kt:99)
        at com.intellij.codeInsight.hints.InlayHintsPass$Companion.applyCollected$intellij_platform_lang_impl$default(InlayHintsPass.kt:78)
        at com.intellij.codeInsight.hints.InlayHintsPass.doApplyInformationToEditor(InlayHintsPass.kt:66)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:114)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$9(PassExecutorService.java:468)
        ... 31 more

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

The Flutter version is the latest stable version at the current time

**Comment by stevemessick** [comment]
I don't see anything in the stack trace that relates to the Flutter plugin, other than a file name.

Do you have any plugins other than Flutter and Dart installed manually?

**Comment by danielesk** [comment]
yes

**Comment by stevemessick** [comment]
This error message suggests there is a problem with a plugin:
`PluginException: Positive width should be defined for an inline element by <image>`

But, it isn't Flutter, so I'm closing this.
