### ISSUE TITLE
AssertionError: Cannot create com.intellij.execution.ui.RunContentManager because container is already disposed (container=ClientId(value=Host))

### ISSUE THREAD

**Issue by pavel-shatskikh** [flutter/flutter-intellij#6752]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

Nothing special. I was working with a ktor project when this error happened.

## Version info

IntelliJ IDEA `2023.1.1` • Flutter plugin `io.flutter 73.1.1` • Dart plugin `231.9065`

No Flutter sdk configured.

java.lang.AssertionError: Cannot create com.intellij.execution.ui.RunContentManager because container is already disposed (container=ClientId(value=Host))
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.execution.ui.RunContentManager because container is already disposed (container=ClientId(value=Host))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:640)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:752)
	at com.intellij.openapi.client.ClientSessionImpl.doGetService(ClientSessionImpl.kt:93)
	at com.intellij.openapi.client.ClientAwareComponentManager.postGetService(ClientAwareComponentManager.kt:39)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:699)
	at com.intellij.openapi.components.ServiceManager.getServiceIfCreated(ServiceManager.java:36)
	at io.flutter.run.FlutterAppManager.getRunContentManager(FlutterAppManager.java:128)
	at io.flutter.run.FlutterAppManager.getActiveApp(FlutterAppManager.java:66)
	at io.flutter.run.FlutterAppManager.updateActiveApp(FlutterAppManager.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 8 more

**Comment by stevemessick** [comment]
Did you have a Flutter project open at the same time as your Ktor project? Or had you recently closed a Flutter project?

I'm not sure this is related, but I recently discovered that updating the Dart plugin can cause odd errors until IntelliJ is restarted. Have you restarted the IDE since updating Dart to 231.9065?

**Comment by helin24** [comment]
This issue is pretty old; reopen if it occurs on a new version of the plugin.
