### ISSUE TITLE
Something crashed when open Android Studio IDLE

### ISSUE THREAD

**Issue by maucoder-ingeint** [flutter/flutter-intellij#6758]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

Something crashed when open Android Studio IDLE, still working

I opened android Studio, doesn't do something else

## Version information

Android Studio `Flamingo | 2022.2.1 Patch 1` • Flutter plugin `io.flutter 73.0.2` • Dart plugin `222.4560`

Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (4 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

## Exception

null

```
org.jdom.JDOMException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:236)
	at com.intellij.openapi.util.JDOMUtil.load(JDOMUtil.java:258)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoaderKt.loadStorageFile(JpsProjectEntitiesLoader.kt:167)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponents(JpsProjectSerializersImpl.kt:858)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.access$loadComponents(JpsProjectSerializersImpl.kt:835)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:845)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader$loadComponent$content$1.apply(JpsProjectSerializersImpl.kt:835)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.CachingJpsFileContentReader.loadComponent(JpsProjectSerializersImpl.kt:844)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.readModuleOptions(ModuleImlFileEntitiesSerializer.kt:185)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadModuleEntity(ModuleImlFileEntitiesSerializer.kt:107)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.ModuleImlFileEntitiesSerializer.loadEntities(ModuleImlFileEntitiesSerializer.kt:73)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule$intellij_platform_workspaceModel_jps(JpsProjectEntitiesLoader.kt:60)
	at com.intellij.workspaceModel.ide.impl.jps.serialization.JpsProjectEntitiesLoader.loadModule(JpsProjectEntitiesLoader.kt:48)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModuleManagerComponentBridge.loadModuleToBuilder(ModuleManagerComponentBridge.kt:304)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.module.ModifiableModuleModelBridgeImpl.loadModule(ModifiableModuleModelBridgeImpl.kt:161)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModuleFromFile(FlutterModuleBuilder.java:216)
	at io.flutter.module.FlutterModuleBuilder.addAndroidModule(FlutterModuleBuilder.java:199)
	at io.flutter.FlutterInitializer.runActivity(FlutterInitializer.java:153)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:260)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:387)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.fasterxml.aalto.WFCException: Unexpected End-of-input in prolog
 at [row,col {unknown-source}]: [1,1]
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwWfe(StreamReaderImpl.java:1777)
	at com.fasterxml.aalto.stax.StreamReaderImpl.throwUnexpectedEOI(StreamReaderImpl.java:1796)
	at com.fasterxml.aalto.stax.StreamReaderImpl.handlePrologEoi(StreamReaderImpl.java:1756)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:810)
	at com.intellij.openapi.util.SafeStAXStreamBuilder.build(SafeStAXStreamBuilder.java:102)
	at com.intellij.openapi.util.JDOMUtil.loadUsingStaX(JDOMUtil.java:229)
	... 57 more
```

**Comment by stevemessick** [comment]
It looks like you have a bad Android module file. You can fix it from the command line. You'll need to find the file and remove it first. It is probably in your `android` directory with a name like `<project-name>_android.iml`. (You should have a `<project-name>.iml` in your top-level project directory, but don't remove that one.) However, if your project is very old, it may be in the top-level project directory.
- Shut down Android Studio
- Remove the file you found
- In a terminal, with the current working directory at `<project-name>` do: `flutter create .` (note the dot at the end)

Let us know if that helps.

**Comment by maucoder-ingeint** [comment]
I did it, The file name from my project is <project-name>_android.iml, I run the command, the error doesn't happens again

**Comment by stevemessick** [comment]
Just to be clear, your problem is solved now?

**Comment by maucoder-ingeint** [comment]
Yes, thanks, It works
