### ISSUE TITLE
crash on debugging

### ISSUE THREAD

**Issue by arashbi** [flutter/flutter-intellij#6792]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

I was debugging a purchase flow when the purchase bottom nav was open, 
and I reached to intellij to remove "skip break point".
That was initial fail. It keeps happening regularly now while debugging. 
All of a sudden the link to app breaks while debugging with
```
Lost connection to device.
adb: device '94EAX0DTAC' not found
Failed to send request: {"jsonrpc":"2.0","id":"641","method":"resume","params":{"isolateId":"isolates/185431659047431"}}
```
One thing that might be relevant is that I am running `MacOs 13.5 Beta (22G5038d)`
## Version information

IntelliJ IDEA `2023.1.1` • Flutter plugin `io.flutter 73.0.4` • Dart plugin `231.8770.15`

Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (5 weeks ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

## Exception

null

```
java.lang.Throwable: org.dartlang.vm.service.element.RPCError@4b7268f0
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:210)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:120)
	at io.flutter.vmService.VmServiceWrapper$9.onError(VmServiceWrapper.java:611)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by stevemessick** [comment]
There may be more info in the log file. You can find it with the menu `Help > Show Log in Finder`. Please attach it, after removing sensitive info.

Have you tried restarting your Mac?
