### ISSUE TITLE
Opening the IDE just throw this exception and not applying dart & flutter to the code. 

### ISSUE THREAD

**Issue by alaajaddou** [flutter/flutter-intellij#6803]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Opening the IDE just throw this exception and not applying dart & flutter to the code. 

## Version information

IntelliJ IDEA `2023.1.2` • Flutter plugin `io.flutter 74.0.4` • Dart plugin `231.9065`

Error getting Flutter sdk information.

## Exception
```
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader com.intellij.util.lang.PathClassLoader @75412c2f)
	at com.google.gson.JsonObject.getAsJsonPrimitive(JsonObject.java:197)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfig(FlutterSdk.java:639)
	at io.flutter.ProjectOpenActivity.lambda$runActivity$1(ProjectOpenActivity.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by stevemessick** [comment]
Fixed in #6820
