### ISSUE TITLE
FAIL ON STARTUP ON MAC FLUTTER

### ISSUE THREAD

**Issue by hhkk** [flutter/flutter-intellij#6813]
What happened
nothing but start up the project.

Version information
IntelliJ IDEA 2023.1.3 • Flutter plugin io.flutter 74.0.4 • Dart plugin 231.9161.14

Flutter 3.12.0-14.0.pre.30 • channel master • https://github.com/flutter/flutter.git Framework • revision ddb16b7d92 (3 days ago) • 2023-07-03 14:27:33 -0400 Engine • revision 987b621eac Tools • Dart 3.1.0 (build 3.1.0-262.0.dev) • DevTools 2.25.0

Exception
null

java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader com.intellij.util.lang.PathClassLoader @f5f2bb7)
	at com.google.gson.JsonObject.getAsJsonPrimitive(JsonObject.java:197)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfig(FlutterSdk.java:639)
	at io.flutter.ProjectOpenActivity.lambda$runActivity$1(ProjectOpenActivity.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by stevemessick** [comment]
Dup of #6803
