### ISSUE TITLE
Android Studio Giraffe notified me about a crash, asked me to submit manually

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter-intellij#6855]
## What happened

I started the Android Studio with a Flutter project being automatically loaded as the last project. Shortly after the IDE started and somewhat "settled down" I saw a notification at bottom right corner that a crash occurred. When I clicked "Submit and Clear" on that notification the IDE opened a Markdown file which stated at the first line:

> Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

I'm copying the markdown content:

## Version information

Android Studio `Giraffe | 2022.3.1` • Flutter plugin `io.flutter 74.0.3` • Dart plugin `223.8950`

Flutter 3.13.0-0.2.pre • channel beta • https://github.com/flutter/flutter
Framework • revision ac71592bc6 (13 days ago) • 2023-07-18 14:53:57 -0600
Engine • revision e14db68a86
Tools • Dart 3.1.0 (build 3.1.0-262.2.beta) • DevTools 2.25.0

## Exception

null

```
java.lang.AssertionError
	at io.flutter.android.AndroidModuleLibraryManager$EmbeddedAndroidProject.init42(AndroidModuleLibraryManager.java:346)
	at io.flutter.android.AndroidModuleLibraryManager.doGradleSync(AndroidModuleLibraryManager.java:226)
	at io.flutter.android.AndroidModuleLibraryManager.update(AndroidModuleLibraryManager.java:103)
	at io.flutter.android.AndroidModuleLibraryManager.updateAndroidLibraries(AndroidModuleLibraryManager.java:217)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$smartInvokeLater$9(DumbServiceImpl.java:528)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by MrCsabaToth** [comment]
This crash happened two more times, looks like once a day: July 29, 30, 31.

**Comment by MrCsabaToth** [comment]
```
$ uname -a
Linux asus 6.4.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.4-1 (2023-07-23) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Devuan
Description:	Devuan GNU/Linux 6 (excalibur/ceres)
Release:	6
Codename:	excalibur ceres
```

**Comment by MrCsabaToth** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.13.0-0.2.pre, on Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.80.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by MrCsabaToth** [comment]
```
[✓] Flutter (Channel beta, 3.13.0-0.2.pre, on Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64, locale en_US.UTF-8)
    • Flutter version 3.13.0-0.2.pre on channel beta at /home/csaba/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision ac71592bc6 (13 days ago), 2023-07-18 14:53:57 -0600
    • Engine revision e14db68a86
    • Dart version 3.1.0 (build 3.1.0-262.2.beta)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/csaba/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/csaba/android-studio-preview/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.27.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/csaba/android-studio-preview
    • Flutter plugin version 74.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[!] Android Studio (version unknown)
    • Android Studio at /home/csaba/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.80.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
Note that there's no error about the latest Android Studio (was Flamingo and now Giraffe), not sure what about the unknown version entry, the Studio functions nominally. Of course there's a ton of carnage going on lately with AGP 8.0+ upgrade, Flutter embedding API, etc., needing to carry some plugins on my back to be able to keep my app up-to-date.

**Comment by MrCsabaToth** [comment]
[idea.log](https://github.com/flutter/flutter-intellij/files/12221054/idea.log)

**Comment by stevemessick** [comment]
This problem no longer occurs with version 75 of the plugin. Unfortunately, the feature that caused this problem, indexing Java and Kotlin to make it easier to work on Android code, is no longer available. We recommend opening the Android module as a separate project in Android Studio. That's similar to opening the iOS module in Xcode (or AppCode).
https://groups.google.com/g/flutter-announce/c/VXYo8havbnQ

**Comment by MrCsabaToth** [comment]
Ok, so it's not like I have an outdated plugin or something, but with the next update this will be resolved?

**Comment by stevemessick** [comment]
Yes, version 75 is available now.

**Comment by MrCsabaToth** [comment]
I see, I got it, it's the general Flutter plugin for Android Studio. I didn't get a crash now. When I build an APK or AAB I open a separate instance with the Android project only. Otherwise I always has the instance open with the whole Flutter project.
