### ISSUE TITLE
Android Studio Flamingo and Giraffe notified me about a crash, asked me to submit manually

### ISSUE THREAD

**Issue by MrCsabaToth** [flutter/flutter-intellij#6856]
## What happened

I started the Android Studio with a Flutter project being automatically loaded as the last project. I cannot remember if this came shortly after startup, or I had also another instance opened with the Android port of said Flutter project and I was doing something with that, but at some point I saw a notification at bottom right corner that a crash occurred. When I clicked "Submit and Clear" on that notification the IDE opened a Markdown file which stated at the first line:

> Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

I'm copying the markdown content:

## Version information

Android Studio `Flamingo | 2022.2.1 Patch 2` • Flutter plugin `io.flutter 74.0.2` • Dart plugin `222.4582`

Flutter 3.12.0 • channel beta • https://github.com/flutter/flutter
Framework • revision 8fcb74dbc1 (3 weeks ago) • 2023-06-08 13:37:31 -0600
Engine • revision b84ad1ad30
Tools • Dart 3.1.0 (build 3.1.0-163.1.beta) • DevTools 2.24.0

## Exception

Unexpected error while updating representations

```
java.util.concurrent.CancellationException: {com.android.tools.idea.concurrency.AndroidCoroutinesAware$Companion$CONTEXT$1.CONTEXT=[SupervisorJobImpl{Active}@6345bfb, com.android.tools.idea.concurrency.CoroutinesUtilsKt$special$$inlined$CoroutineExceptionHandler$1@19094d91, com.intellij.util.concurrency.AppScheduledExecutorService$BackendThreadPoolExecutor@38db96e6[Running, pool size = 8, active threads = 0, queued tasks = 0, completed tasks = 8928]]} has been disposed.
	at com.android.tools.idea.concurrency.CoroutinesUtilsKt$cancelJobOnDispose$1.dispose(CoroutinesUtils.kt:172)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:129)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:207)
	at com.intellij.openapi.fileEditor.TextEditorWithPreview.dispose(TextEditorWithPreview.java:113)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:129)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:219)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:207)
	at com.intellij.openapi.fileEditor.FileEditorProvider.disposeEditor(FileEditorProvider.java:54)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.disposeComposite(FileEditorManagerImpl.java:1664)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.lambda$closeFile$3(EditorWindow.java:213)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1702)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:194)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeAllFiles(EditorsSplitters.java:293)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeAllFiles$32(FileEditorManagerImpl.java:2001)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1702)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeAllFiles$33(FileEditorManagerImpl.java:2001)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeAllFiles(FileEditorManagerImpl.java:1999)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$2.projectClosing(FileEditorManagerImpl.java:199)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.executeOrAddToQueue(MessageBusImpl.kt:470)
	at com.intellij.util.messages.impl.ToDirectChildrenMessagePublisher.publish$intellij_platform_core(CompositeMessageBus.kt:292)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:425)
	at jdk.proxy2/jdk.proxy2.$Proxy101.projectClosing(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectClosing(ProjectManagerImpl.java:419)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$5(ProjectManagerImpl.java:376)
	at com.intellij.openapi.util.ShutDownTracker.executeWithStopperThread(ShutDownTracker.java:114)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:359)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:411)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$closeAndDisposeKeepingFrame$1.get(ProjectManagerExImpl.kt:438)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$closeAndDisposeKeepingFrame$1.get(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.runWithFrameReuseEnabled(WindowManagerImpl.kt:386)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.closeAndDisposeKeepingFrame(ProjectManagerExImpl.kt:438)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$closeAndDisposeKeepingFrame(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$checkExistingProjectOnOpen$1.invoke(ProjectManagerExImpl.kt:420)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$checkExistingProjectOnOpen$1.run(ProjectManagerExImpl.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:492)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.checkExistingProjectOnOpen(ProjectManagerExImpl.kt:384)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.openProjectAsync(ProjectManagerExImpl.kt:108)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.openProject(ProjectManagerExImpl.kt:76)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion.doOpenProject(PlatformProjectOpenProcessor.kt:121)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.kt:226)
	at io.flutter.editor.FlutterStudioProjectOpenProcessor.doOpenProject(FlutterStudioProjectOpenProcessor.java:40)
	at com.intellij.ide.impl.ProjectUtil.lambda$chooseProcessorAndOpen$9(ProjectUtil.java:361)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:492)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:525)
	at com.intellij.ide.impl.ProjectUtil.chooseProcessorAndOpen(ProjectUtil.java:360)
	at com.intellij.ide.impl.ProjectUtil.tryOpenOrImport(ProjectUtil.java:172)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:138)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:134)
	at com.android.tools.idea.actions.AndroidOpenFileAction.openOrImportProject(AndroidOpenFileAction.java:179)
	at com.android.tools.idea.actions.AndroidOpenFileAction.doOpenFile(AndroidOpenFileAction.java:149)
	at com.android.tools.idea.actions.AndroidOpenFileAction.lambda$actionPerformed$0(AndroidOpenFileAction.java:111)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:137)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:102)
	at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:80)
	at com.android.tools.idea.actions.AndroidOpenFileAction.actionPerformed(AndroidOpenFileAction.java:101)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$4(ActionMenuItem.java:293)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:286)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:546)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:578)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6421)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:759)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by MrCsabaToth** [comment]
The crash happened with Flamingo on the June 30th, while the exact same with Giraffe on July 30th.

**Comment by MrCsabaToth** [comment]
```
$ uname -a
Linux asus 6.4.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.4.4-1 (2023-07-23) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Devuan
Description:	Devuan GNU/Linux 6 (excalibur/ceres)
Release:	6
Codename:	excalibur ceres
```

**Comment by MrCsabaToth** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.13.0-0.2.pre, on Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.3)
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.80.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

**Comment by MrCsabaToth** [comment]
```
[✓] Flutter (Channel beta, 3.13.0-0.2.pre, on Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64, locale en_US.UTF-8)
    • Flutter version 3.13.0-0.2.pre on channel beta at /home/csaba/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision ac71592bc6 (13 days ago), 2023-07-18 14:53:57 -0600
    • Engine revision e14db68a86
    • Dart version 3.1.0 (build 3.1.0-262.2.beta)
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/csaba/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/csaba/android-studio-preview/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.27.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /home/csaba/android-studio-preview
    • Flutter plugin version 74.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[!] Android Studio (version unknown)
    • Android Studio at /home/csaba/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.80.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.68.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Devuan GNU/Linux 6 (excalibur/ceres) 6.4.0-1-amd64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
Note that there's no error about the latest Android Studio (was Flamingo and now Giraffe), not sure what about the unknown version entry, the Studio functions nominally. Of course there's a ton of carnage going on lately with AGP 8.0+ upgrade, Flutter embedding API, etc., needing to carry some plugins on my back to be able to keep my app up-to-date.

**Comment by MrCsabaToth** [comment]
[idea.log](https://github.com/flutter/flutter-intellij/files/12221092/idea.log)

**Comment by stevemessick** [comment]
Thanks for the detailed report. I didn't see anything in the log related to this stack trace, but it is possible this is related to your other issue, #6855.

Apparently, while opening a project during IDE initialization, the IntelliJ framework detected another project that was supposedly closing. While finishing the close operation, it discovered that the project had already been disposed, which caused the error. There is no indication what kind of project that was, so it might have been the Android module.

Just to clarify, you did at one point have the Android module of a Flutter project open as its own project in Android Studio, correct?

Interesting idea, that this might be related to IDE upgrades. I don't know how to test that.

**Comment by MrCsabaToth** [comment]
Yes, for build I open the Android project portion (android subfolder) open in a separate Studio instance. Besides that I always have the Flutter (the whole) project open. Often times I also have to fiddle with Flutter plugins, which have their Flutter project and even an embedded example Flutter project within them, and sometimes I open the Android project of the plugin example. There were times I had two plugins open like that. I try to not have too many Studio instances open so I close them as soon as I can.

**Comment by MrCsabaToth** [comment]
In general I didn't really notice any data loss or functionality besides the crash notification popping up. I certainly put Studio to test.

**Comment by helin24** [comment]
It looks like this may have been fixed in a later version, so closing.
