### ISSUE TITLE
I was attempting to start an Android simulator.

### ISSUE THREAD

**Issue by ToddBrawn** [flutter/flutter-intellij#6897]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I selected a simulated Android device and selected debug run for my application. 

java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabs(JBTabsImpl.java:2015)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabCount(JBTabsImpl.java:2651)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.getTabCount(EditorTabbedContainer.kt:184)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.getTabCount(EditorWindow.kt:107)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.findCompositeAndIndex$intellij_platform_ide_impl(EditorWindow.kt:783)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.getComposite(EditorWindow.kt:779)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getComposite(FileEditorManagerImpl.kt:1527)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedEditorWithProvider(FileEditorManagerImpl.kt:1492)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.getSelectedEditor(FileEditorManagerEx.kt:104)
	at io.flutter.actions.OpenInAndroidStudioAction.getCurrentEditor(OpenInAndroidStudioAction.java:107)
	at io.flutter.actions.OpenInAndroidStudioAction.lambda$actionPerformed$0(OpenInAndroidStudioAction.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

## Version info

[✓] Flutter (Channel master, 3.14.0-8.0.pre.13, on macOS 13.5.1 22G90 darwin-x64, locale en-US)
    • Flutter version 3.14.0-8.0.pre.13 on channel master at /Users/username/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1bdef6fea7 (3 weeks ago), 2023-08-18 17:09:19 -0400
    • Engine revision 654d3a2c84
    • Dart version 3.2.0 (build 3.2.0-85.0.dev)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 75.1.3
    • Dart plugin version 231.9161.14

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • macOS 13.5.1 22G90 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jacob314** [comment]
Should be a quick fix to ensure we are running code on the EDT thread where it should run rather than a background thread.
