### ISSUE TITLE
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader com.intellij.util.lang.PathClassLoader

### ISSUE THREAD

**Issue by rdamus** [flutter/flutter-intellij#6906]
## What happened

While starting IntelliJ with the Flutter plugin, the app reports an error but still functions so this report is an FYI

## Steps to Reproduce

1. Start Intellij, observe error dialog

## Version info

IntelliJ IDEA 2023.2.2 • Flutter plugin io.flutter 74.0.5 • Dart plugin 232.8660.129

Flutter 3.13.0-3.0.pre.89 • channel master • https://github.com/flutter/flutter.git Framework • revision 4f437d4765 (9 weeks ago) • 2023-07-15 18:27:42 -0400 Engine • revision 683087731f Tools • Dart 3.1.0 (build 3.1.0-315.0.dev) • DevTools 2.25.0

## Exception
null
```

java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader com.intellij.util.lang.PathClassLoader @ba4d54)
	at com.google.gson.JsonObject.getAsJsonPrimitive(JsonObject.java:197)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfig(FlutterSdk.java:639)
	at io.flutter.ProjectOpenActivity.lambda$runActivity$1(ProjectOpenActivity.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by helin24** [comment]
Since this is pretty old I'm closing for now. Reopen if it occurs on more recent version.
