### ISSUE TITLE
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@38c404d8

### ISSUE THREAD

**Issue by tasselx** [flutter/flutter-intellij#7046]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2023.2.4` • Flutter plugin `io.flutter 76.1.4` • Dart plugin `232.10072.19`

Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (1 year, 4 months ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@38c404d8
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by simonecaf** [comment]
Got this as well and lost the connection with the simulator. Any resolution?

**Comment by helin24** [comment]
@CoderDake do you know where this `ToolEvent` error comes from?
