### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException

### ISSUE THREAD

**Issue by wdonne** [flutter/flutter-intellij#7076]
What happened
(please describe what you were doing when this exception occurred)

Version information
IntelliJ IDEA 2023.2.5 • Flutter plugin io.flutter 76.3.4 • Dart plugin 232.10072.19

No Flutter sdk configured.

Exception
null

com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.execution.ui.RunContentManager because container is already disposed (container=ClientId(value=Host))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:599)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:714)
	at com.intellij.openapi.client.ClientSessionImpl.doGetService(ClientSessionImpl.kt:102)
	at com.intellij.openapi.client.ClientAwareComponentManager.postGetService(ClientAwareComponentManager.kt:41)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:661)
	at com.intellij.openapi.components.ServiceManager.getServiceIfCreated(ServiceManager.java:40)
	at io.flutter.run.FlutterAppManager.getRunContentManager(FlutterAppManager.java:128)
	at io.flutter.run.FlutterAppManager.getActiveApp(FlutterAppManager.java:66)
	at io.flutter.run.FlutterAppManager.updateActiveApp(FlutterAppManager.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by helin24** [comment]
Duplicate of https://github.com/flutter/flutter-intellij/issues/6752
