### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by sunrustpower** [flutter/flutter-intellij#7084]
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@3187c1d
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)

**Comment by jwren** [comment]
Duplicate of https://github.com/flutter/flutter-intellij/issues/7133
