### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheGhostRoot** [flutter/flutter-intellij#7107]
## What happened

I went to Tools -> Flutter -> Open for editing in Android Studio

## Version information

IntelliJ IDEA `2023.1.4` • Flutter plugin `io.flutter 76.3.3` • Dart plugin `231.9161.14`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:68)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabs(JBTabsImpl.java:2015)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabCount(JBTabsImpl.java:2651)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.getTabCount(EditorTabbedContainer.kt:184)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.getTabCount(EditorWindow.kt:107)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.findCompositeAndIndex$intellij_platform_ide_impl(EditorWindow.kt:783)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.getComposite(EditorWindow.kt:779)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getComposite(FileEditorManagerImpl.kt:1527)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedEditorWithProvider(FileEditorManagerImpl.kt:1492)
	at com.intellij.openapi.fileEditor.ex.FileEditorManagerEx.getSelectedEditor(FileEditorManagerEx.kt:104)
	at io.flutter.actions.OpenInAndroidStudioAction.getCurrentEditor(OpenInAndroidStudioAction.java:105)
	at io.flutter.actions.OpenInAndroidStudioAction.lambda$actionPerformed$0(OpenInAndroidStudioAction.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jwren** [comment]
Closing as obsolete.  This action was removed due to AS platform changes.
