### ISSUE TITLE
IDE Crash during flutter build

### ISSUE THREAD

**Issue by shaizar** [flutter/flutter-intellij#7133]
## What happened

IDE crash while running a debug session.

## Version information

IntelliJ IDEA `2023.3` • Flutter plugin `io.flutter 77.0.1` • Dart plugin `233.11799.172`

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (12 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@5aefd187
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by shaizar** [comment]
App still runs on device and debug messages are showing in console.

**Comment by krishnamadugu** [comment]
please run flutter doctor to make sure if flutter is properly installed on your system

**Comment by jwren** [comment]
Yes, do update your flutter and dart versions, and see if this issue is resolved.

**Comment by acheronian** [comment]
Same issue, intellij throws the following exception:

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@7ee6bfe
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

Stopping at breakpoint, console prints:
```
Cannot invoke "com.google.gson.JsonElement.isJsonPrimitive()" because "elem" is null
```

Flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 3.0.5, on Microsoft Windows [Version 10.0.19045.4046], locale de-AT)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)                  
    X Android license status unknown.                                                         
      Run `flutter doctor --android-licenses` to accept the SDK licenses.                     
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web                                                              
[X] Visual Studio - develop for Windows                                                       
    X Visual Studio not installed; this is necessary for Windows development.                 
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[!] Android Studio (version 2022.3)
    X Unable to find bundled Java version.
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 4 categories.
