### ISSUE TITLE
Exception Flutter 77.0.1

### ISSUE THREAD

**Issue by Earevalo** [flutter/flutter-intellij#7178]
com.intellij.diagnostic.PluginException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~\AppData\Roaming\Google\AndroidStudioPreview2023.3\plugins\flutter-intellij, version=77.0.1, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1434)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.instantiate(ActionManagerImpl.kt:1404)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1737)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.kt:323)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:314)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:375)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.collectAllActions(WelcomeScreenActionsUtil.java:38)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.collectAllActions(WelcomeScreenActionsUtil.java:40)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenActionsUtil.splitAndWrapActions(WelcomeScreenActionsUtil.java:203)
	at com.intellij.openapi.wm.impl.welcomeScreen.ProjectsTab.createActionsToolbar(ProjectsTabFactory.kt:217)
	at com.intellij.openapi.wm.impl.welcomeScreen.ProjectsTab.createRecentProjectsPanel(ProjectsTabFactory.kt:187)
	at com.intellij.openapi.wm.impl.welcomeScreen.ProjectsTab.<init>(ProjectsTabFactory.kt:68)
	at com.intellij.openapi.wm.impl.welcomeScreen.ProjectsTabFactory.createWelcomeTab(ProjectsTabFactory.kt:60)
	at com.intellij.openapi.wm.WelcomeTabFactory.createWelcomeTabs(WelcomeTabFactory.java:31)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.loadTabs(TabbedWelcomeScreen.java:130)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.<init>(TabbedWelcomeScreen.java:88)
	at com.intellij.openapi.wm.impl.welcomeScreen.TabbedWelcomeScreen.<init>(TabbedWelcomeScreen.java:39)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.<init>(FlatWelcomeFrame.kt:77)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.<init>(FlatWelcomeFrame.kt)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrameProvider.createFrame(FlatWelcomeFrameProvider.java:14)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.lambda$customizeFlatWelcomeFrame$2(FirstRunWizardFrameProvider.java:65)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:59)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:58)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.customizeFlatWelcomeFrame(FirstRunWizardFrameProvider.java:59)
	at com.android.tools.idea.welcome.wizard.FirstRunWizardFrameProvider.createFrame(FirstRunWizardFrameProvider.java:46)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$Companion$prepareToShow$1$frame$1.invoke(WelcomeFrame.kt:158)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$Companion$prepareToShow$1$frame$1.invoke(WelcomeFrame.kt:158)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$Companion$prepareToShow$1.invoke(WelcomeFrame.kt:158)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$Companion$prepareToShow$1.invoke(WelcomeFrame.kt:153)
	at com.intellij.idea.IdeStarter$showWelcomeFrame$2.invokeSuspend(IdeStarter.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:43)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~\AppData\Roaming\Google\AndroidStudioPreview2023.3\plugins\flutter-intellij, version=77.0.1, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:2255)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1426)
	... 74 more

**Comment by hunt-angel** [comment]
I also have the same problem
android studio version：2023.3.1.5

**Comment by jwren** [comment]
Duplicate of https://github.com/flutter/flutter-intellij/issues/6880
