### ISSUE TITLE
Error while using debugger in windows

### ISSUE THREAD

**Issue by sauer-kindra** [flutter/flutter-intellij#7182]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

I was debugging a Flutter windows application, as the breakpoint 
is reached I get this message from the IDE telling that an error ocurred.

## Version information

IntelliJ IDEA `2023.3.2` • Flutter plugin `io.flutter 77.0.1` • Dart plugin `233.13135.65`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.Throwable: Error listening to ToolEvent stream: org.dartlang.vm.service.element.RPCError@35e04bef
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at io.flutter.vmService.VmServiceWrapper$2.onError(VmServiceWrapper.java:185)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by helin24** [comment]
I think this may be an issue from an old version of the Flutter SDK. Please reopen if this still occurs on a more recent plugin with a recent Flutter SDK.
