### ISSUE TITLE
IDE/System hanging on hot-reload while in debug model

### ISSUE THREAD

**Issue by kevindmoore** [flutter/flutter-intellij#7186]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I was debugging my Flutter app on an Android API 33 emulator. Hitting hot-reload hangs the system. I can stop the app and restart but that is not ideal.
Flutter developement in Intellij is totally messed up. So many problems. I have to quit Intellij to get things to work and even that doesn't work, I have to do a force quit.

## Version information

IntelliJ IDEA `2023.3.2` • Flutter plugin `io.flutter 77.0.1` • Dart plugin `233.13135.65`

Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (7 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

## Exception

null

```
java.lang.Throwable: {"jsonrpc":"2.0","id":"2627","method":"lookupPackageUris","params":{"isolateId":"isolates/3738022630842243","uris":["file:///Users/kevin/Projects/FlutterApps/ata/lib/ui/login/login_main.dart"]}}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:382)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:120)
	at io.flutter.vmService.VmServiceWrapper$10.onError(VmServiceWrapper.java:624)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by helin24** [comment]
Sorry about the long delay getting back to these issues. This one requires more information to isolate issues as it sounds like there are multiple problems related to debugging, so I'm going to close since things have likely changed since this was filed. If there is a reproducing project / system setup with a recent version of the plugin, please reopen with tips for reproduction.
