### ISSUE TITLE
Report bug creates multiple instances of bug markdown files

### ISSUE THREAD

**Issue by kevindmoore** [flutter/flutter-intellij#7187]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I saw an error flashing in the bottom right of Intellij. Clicked and said report and clear. After several minutes, bug-report_30-57.md were created

## Version info

IntelliJ IDEA `2023.3.2` • Flutter plugin `io.flutter 77.0.1` • Dart plugin `233.13135.65`

Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (7 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

## Exception

null

```
java.lang.Throwable: {"jsonrpc":"2.0","id":"39621","method":"lookupPackageUris","params":{"isolateId":"isolates/6495024778465051","uris":["file:///Users/kevin/Projects/FlutterApps/supa_manager/lib/src/auth/login_state.dart"]}}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:382)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:120)
	at io.flutter.vmService.VmServiceWrapper$10.onError(VmServiceWrapper.java:624)
	at org.dartlang.vm.service.VmServiceBase.processResponse(VmServiceBase.java:633)
	at org.dartlang.vm.service.VmServiceBase.processMessage(VmServiceBase.java:422)
	at org.dartlang.vm.service.VmServiceBase$1.onMessage(VmServiceBase.java:86)
	at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:65)
```

**Comment by jwren** [comment]
Thanks for the report. Marking as obsolete.  Do create a new issue with repro steps if you experience this again.
