### ISSUE TITLE
IntelliJ crash

### ISSUE THREAD

**Issue by kiwicmc** [flutter/flutter-intellij#7231]
## What happened

Project appeared to have hung. Closed windows and reopened (did not Force Quit). Was running against physical iPhone and iPhone Simulator

## Version information

IntelliJ IDEA `2023.2.5` • Flutter plugin `io.flutter 77.1.3` • Dart plugin `232.10286`

Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (5 weeks ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

## Exception

*** exception class was changed or removed

```
During querying provider Icon preview (class io.flutter.editor.FlutterIconLineMarkerProvider)
  
  java.lang.ClassCastException: class com.jetbrains.lang.dart.psi.impl.DartVarAccessDeclarationImpl cannot be cast to class com.jetbrains.lang.dart.psi.DartVarInit (com.jetbrains.lang.dart.psi.impl.DartVarAccessDeclarationImpl and com.jetbrains.lang.dart.psi.DartVarInit are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3e0069e0)
at io.flutter.editor.FlutterIconLineMarkerProvider$IconInfoVisitor.visitVarAccessDeclaration(FlutterIconLineMarkerProvider.java:497)
at com.jetbrains.lang.dart.psi.impl.DartVarAccessDeclarationImpl.accept(DartVarAccessDeclarationImpl.java:21)
at com.jetbrains.lang.dart.psi.impl.DartVarAccessDeclarationImpl.accept(DartVarAccessDeclarationImpl.java:26)
at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
at com.jetbrains.lang.dart.psi.DartRecursiveVisitor.visitElement(DartRecursiveVisitor.java:10)
at com.jetbrains.lang.dart.psi.DartVisitor.visitPsiCompositeElement(DartVisitor.java:763)
at com.jetbrains.lang.dart.psi.DartVisitor.visitVarDeclarationList(DartVisitor.java:699)
at com.jetbrains.lang.dart.psi.impl.DartVarDeclarationListImpl.accept(DartVarDeclarationListImpl.java:21)
at com.jetbrains.lang.dart.psi.impl.DartVarDeclarationListImpl.accept(DartVarDeclarationListImpl.java:26)
at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
at com.jetbrains.lang.dart.psi.DartRecursiveVisitor.visitElement(DartRecursiveVisitor.java:10)
at com.jetbrains.lang.dart.psi.DartVisitor.visitPsiCompositeElement(DartVisitor.java:763)
at com.jetbrains.lang.dart.psi.DartVisitor.visitExecutionScope(DartVisitor.java:739)
at com.jetbrains.lang.dart.psi.DartVisitor.visitClassMembers(DartVisitor.java:95)
at com.jetbrains.lang.dart.psi.impl.DartClassMembersImpl.accept(DartClassMembersImpl.java:21)
at com.jetbrains.lang.dart.psi.impl.DartClassMembersImpl.accept(DartClassMembersImpl.java:26)
at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
at com.jetbrains.lang.dart.psi.DartRecursiveVisitor.visitElement(DartRecursiveVisitor.java:10)
at com.jetbrains.lang.dart.psi.DartVisitor.visitPsiCompositeElement(DartVisitor.java:763)
at com.jetbrains.lang.dart.psi.DartVisitor.visitClassBody(DartVisitor.java:87)
at com.jetbrains.lang.dart.psi.impl.DartClassBodyImpl.accept(DartClassBodyImpl.java:21)
at com.jetbrains.lang.dart.psi.impl.DartClassBodyImpl.accept(DartClassBodyImpl.java:26)
at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:59)
at com.jetbrains.lang.dart.psi.DartRecursiveVisitor.visitElement(DartRecursiveVisitor.java:10)
at com.jetbrains.lang.dart.psi.DartVisitor.visitPsiCompositeElement(DartVisitor.java:763)
at com.jetbrains.lang.dart.psi.DartVisitor.visitClass(DartVisitor.java:731)
at com.jetbrains.lang.dart.psi.DartVisitor.visitClassDefinition(DartVisitor.java:91)
at com.jetbrains.lang.dart.psi.impl.DartClassDefinitionImpl.accept(DartClassDefinitionImpl.java:21)
at com.jetbrains.lang.dart.psi.impl.DartClassDefinitionImpl.accept(DartClassDefinitionImpl.java:26)
at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:183)
at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:747)
at com.jetbrains.lang.dart.psi.DartRecursiveVisitor.visitElement(DartRecursiveVisitor.java:10)
at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:51)
at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:59)
at io.flutter.editor.FlutterIconLineMarkerProvider.findDefinition(FlutterIconLineMarkerProvider.java:331)
at io.flutter.editor.FlutterIconLineMarkerProvider.getIconFromPackage(FlutterIconLineMarkerProvider.java:286)
at io.flutter.editor.FlutterIconLineMarkerProvider.getLineMarkerInfo(FlutterIconLineMarkerProvider.java:152)
at io.flutter.editor.FlutterIconLineMarkerProvider.getLineMarkerInfo(FlutterIconLineMarkerProvider.java:84)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:183)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectMarkers$2(LineMarkersPass.java:107)
at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:95)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectMarkers(LineMarkersPass.java:103)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:76)
at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

chris@Mando.local:/Users/chris/IdeaProjects/MICDUP/micdup_app> flutter doctor -v
[✓] Flutter (Channel stable, 3.16.8, on macOS 13.6 22G120 darwin-arm64, locale en-NZ)
    • Flutter version 3.16.8 on channel stable at /Users/chris/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (5 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/chris/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 77.1.3
    • Dart plugin version 232.10286

[✓] Connected device (6 available)
    • SM A105G (mobile)          • RF8M61TGCRL                          • android-arm    • Android 11 (API 30)
    • iPhone 13 Mini (mobile)    • 00008110-00063CC22E61401E            • ios            • iOS 17.3.1 21D61
    • iPhone XS (mobile)         • 00008020-000105463E44002E            • ios            • iOS 17.1.2 21B101
    • iPhone 15 Pro Max (mobile) • 90C1AC7E-B5B5-4AE2-8CAF-5370C60C6100 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 121.0.6167.184

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
chris@Mando.local:/Users/chris/IdeaProjects/MICDUP/micdup_app>

**Comment by helin24** [comment]
I expect we'll need a project that reproduces this to try to debug. Let me know if this is still happening.
