### ISSUE TITLE
IntelliJ errors while switching from a java project to another one

### ISSUE THREAD

**Issue by elsoft74** [flutter/flutter-intellij#7293]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Just switched from a java project to another one

## Version information

IntelliJ IDEA `2023.3.5` • Flutter plugin `io.flutter 78.3.1` • Dart plugin `233.14888`

No Flutter sdk configured.

## Exception

Worker exited due to exception

```
java.lang.AssertionError: Project-level session is not set. ClientId(value=Host)
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:83)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:275)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Project-level session is not set. ClientId(value=Host)
	at com.intellij.openapi.client.ClientSessionsUtil.getCurrentSession(clientSessionsUtil.kt:84)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.getToolWindow(BackendServerToolWindowManager.kt:109)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerByToolWindowId(RunContentManagerImpl.kt:353)
	at com.intellij.execution.ui.RunContentManagerImpl.getSelectedContent(RunContentManagerImpl.kt:230)
	at io.flutter.run.FlutterAppManager.getActiveApp(FlutterAppManager.java:70)
	at io.flutter.run.FlutterAppManager.updateActiveApp(FlutterAppManager.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	... 8 more
```

**Comment by helin24** [comment]
I'm going to close this because it's probably outdated (`FlutterAppManager` no longer exists)
