### ISSUE TITLE
Flutter plugin don't works with Android Studio Koala 3 

### ISSUE THREAD

**Issue by eugen-yakovets** [flutter/flutter-intellij#7314]
```
Caused by: java.lang.ClassNotFoundException: io.flutter.android.AndroidModuleLibraryType PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~/.local/share/Google/AndroidStudioPreview2024.1/flutter-intellij, version=78.5.1, package=null, isBundled=false), packagePrefix=null, state=active)
    at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1466)
    at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:895)
    at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:20)
    at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:51)
    ... 242 more
2024-04-02 12:29:36,436 [   4805] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Android Studio Koala | 2024.1.1 Canary 3  Build #AI-241.14494.158.2411.11648550
2024-04-02 12:29:36,437 [   4806] SEVERE - #c.i.o.e.i.ExtensionPointImpl - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-04-02 12:29:36,437 [   4806] SEVERE - #c.i.o.e.i.ExtensionPointImpl - OS: Linux
2024-04-02 12:29:36,437 [   4806] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Plugin to blame: Flutter version: 78.5.1
```

```
Caused by: java.lang.ClassNotFoundException: io.flutter.actions.FlutterNewProjectAction PluginClassLoader(plugin=PluginDescriptor(name=Flutter, id=io.flutter, descriptorPath=plugin.xml, path=~/.local/share/Google/AndroidStudioPreview2024.1/flutter-intellij, version=78.5.1, package=null, isBundled=false), packagePrefix=null, state=active)
    at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1466)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:943)
    ... 81 more
2024-04-02 12:29:48,146 [  16515] SEVERE - #c.i.o.a.i.ActionManagerImpl - Android Studio Koala | 2024.1.1 Canary 3  Build #AI-241.14494.158.2411.11648550
2024-04-02 12:29:48,146 [  16515] SEVERE - #c.i.o.a.i.ActionManagerImpl - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-04-02 12:29:48,146 [  16515] SEVERE - #c.i.o.a.i.ActionManagerImpl - OS: Linux
2024-04-02 12:29:48,146 [  16515] SEVERE - #c.i.o.a.i.ActionManagerImpl - Plugin to blame: Flutter version: 78.5.1
```

**Comment by jwren** [comment]
Thank you for the issue. The current build 2024.1 build is only meant as an early release of Community and Ultimate.

**Comment by eugen-yakovets** [comment]
but itt is displayed as Android Studio compatible on plugin page:
![image](https://github.com/flutter/flutter-intellij/assets/1287790/143dbd4b-e9e3-4ef3-beeb-5513b43bf3bb)

**Comment by jwren** [comment]
Yes, I noticed that!  I haven't created an issue for this yet.  Other issues are currently higher priority.

**Comment by RileyManda** [comment]
You can just create a new flutter app using the following command in your terminal:

`flutter create -t app myapp`

Then open your app using android studio.

**Comment by jwren** [comment]
Leaving closed, AS Koala Canary 6 is working with the latest v80 push of the Flutter IJ plugin.
