### ISSUE TITLE
windows version , flutter, android studio not recognized 

### ISSUE THREAD

**Issue by SalmaEthera2028** [flutter/flutter-intellij#7400]
when i run or let the microsoft defender automatically trust the project 

C:\Users\SALMA\Downloads\trektofinal\untitled>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try again after     
      restarting the terminal and/or IDE.
[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "systeminfo" in the search path.
        Command: systeminfo 
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Android Studio (version 2023.3)
    X Unable to find bundled Java version.
[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = 'C:\Program Files\Android\Android Studio & C:\flutter/bin/internal/exit_with_errorlevel.bat.plugins' (OS Error: The filename, directory name, or volume label syntax is incorrect. 
      , errno = 123)
[√] VS Code (version 1.89.0)
[√] Connected device (2 available)
[√] HTTP Host Availability

! Doctor found issues in 4 categories.
here is the result of flutter doctor -v 
C:\Users\SALMA\Downloads\trektofinal\untitled>flutter doctor -v
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Cannot find the executable for `where`. This can happen if the System32 folder (e.g. C:\Windows\System32 ) is removed from the PATH environment variable. Ensure that this is present and then try again after     
      restarting the terminal and/or IDE.
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:488:7)
      #2      OperatingSystemUtils.which (package:flutter_tools/src/base/os.dart:92:31)
      #3      FlutterValidator._validateSdkBinary (package:flutter_tools/src/doctor.dart:617:52)
      #4      FlutterValidator._validateRequiredBinaries (package:flutter_tools/src/doctor.dart:604:47)
      #5      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:7)
      #6      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:250:72)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #8      _rootRun (dart:async/zone.dart:1398:13)
      #9      _CustomZone.run (dart:async/zone.dart:1300:19)
      #10     _runZoned (dart:async/zone.dart:1803:10)
      #11     runZonedGuarded (dart:async/zone.dart:1791:12)
      #12     runZoned (dart:async/zone.dart:1743:12)
      #13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:242:9)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:375:72)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
      <asynchronous suspension>
      #18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
      <asynchronous suspension>
      #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #20     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
      <asynchronous suspension>
      #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #26     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>

[☠] Windows Version (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X ProcessException: Failed to find "systeminfo" in the search path.
        Command: systeminfo 
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:87:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:674:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:568:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:673:12)
      #4      WindowsVersionValidator.validate (package:flutter_tools/src/windows/windows_version_validator.dart:33:31)
      #5      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:250:72)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1398:13)
      #8      _CustomZone.run (dart:async/zone.dart:1300:19)
      #9      _runZoned (dart:async/zone.dart:1803:10)
      #10     runZonedGuarded (dart:async/zone.dart:1791:12)
      #11     runZoned (dart:async/zone.dart:1743:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:242:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:375:72)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
      <asynchronous suspension>
      #17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
      <asynchronous suspension>
      #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #19     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
      <asynchronous suspension>
      #21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #25     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>

[!] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[☠] Android Studio (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Exists failed, path = 'C:\Program Files\Android\Android Studio & C:\flutter/bin/internal/exit_with_errorlevel.bat.plugins' (OS Error: The filename, directory name, or volume label syntax is incorrect. 
      , errno = 123)
    • #0      _Directory.existsSync (dart:io/directory_impl.dart:92:7)
      #1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
      #2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:498:22)
      #3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:600:14)
      #4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:497:12)
      #5      AndroidStudio.pluginsPath (package:flutter_tools/src/android/android_studio.dart:184:52)
      #6      AndroidStudioValidator.validate (package:flutter_tools/src/android/android_studio_validator.dart:56:17)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:250:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1398:13)
      #10     _CustomZone.run (dart:async/zone.dart:1300:19)
      #11     _runZoned (dart:async/zone.dart:1803:10)
      #12     runZonedGuarded (dart:async/zone.dart:1791:12)
      #13     runZoned (dart:async/zone.dart:1743:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:242:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:375:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1426:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>

extra info :
![image](https://github.com/flutter/flutter-intellij/assets/105130433/e92ca0ce-4699-4d43-9f60-eb0433f4d3bb)
flutter plugin : 79.0.2
flutter sdk version : 3.7.3
dart : 2.19.2
dart plugin: 233.15123

please help im trying to work on my graduation project that is due in a month and i need this to work to integrate with firebase which is another hassel i dont know how to do yet

**Comment by SalmaEthera2028** [comment]
my solution was run this command in terminal lutter config --android-studio-dir="C:\Program Files\Android\Android Studio then restart android studio
