### ISSUE TITLE
flutter vs tflite issue -how to solve this?

### ISSUE THREAD

**Issue by DMDiep** [flutter/flutter-intellij#7540]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

---

## What happened

PS C:\Users\Eigenaar\AndroidStudioProjects\attempt11> flutter run
Resolving dependencies... 
Downloading packages...
  collection 1.18.0 (1.19.0 available)
  http_parser 4.0.2 (4.1.0 available)
  image_picker_for_web 2.2.0 (3.0.4 available)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  material_color_utilities 0.8.0 (0.12.0 available)
  meta 1.12.0 (1.15.0 available)
  test_api 0.7.0 (0.7.2 available)
  vm_service 14.2.1 (14.2.4 available)
Got dependencies!
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
C:\Users\Eigenaar\AppData\Local\Pub\Cache\hosted\pub.dev\tflite-1.1.2\android\src\main\java\sq\flutter\tflite\TflitePlugin.java:32: error: package org.tensorflow.lite.gpu does not exist
import org.tensorflow.lite.gpu.GpuDelegate;
                              ^
C:\Users\Eigenaar\AppData\Local\Pub\Cache\hosted\pub.dev\tflite-1.1.2\android\src\main\java\sq\flutter\tflite\TflitePlugin.java:232: error: cannot find symbol
      GpuDelegate delegate = new GpuDelegate();
      ^
  symbol:   class GpuDelegate
  location: class TflitePlugin
C:\Users\Eigenaar\AppData\Local\Pub\Cache\hosted\pub.dev\tflite-1.1.2\android\src\main\java\sq\flutter\tflite\TflitePlugin.java:232: error: cannot find symbol
      GpuDelegate delegate = new GpuDelegate();
                                 ^
  symbol:   class GpuDelegate
  location: class TflitePlugin
Note: C:\Users\Eigenaar\AppData\Local\Pub\Cache\hosted\pub.dev\tflite-1.1.2\android\src\main\java\sq\flutter\tflite\TflitePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Eigenaar\AppData\Local\Pub\Cache\hosted\pub.dev\tflite-1.1.2\android\src\main\java\sq\flutter\tflite\TflitePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tflite:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Running Gradle task 'assembleDebug'...                             10.4s
Error: Gradle task assembleDebug failed with exit code 1
PS C:\Users\Eigenaar\AndroidStudioProjects\attempt11>

## Version information

Android Studio `Jellyfish | 2023.3.1 Patch 1` • Flutter plugin `io.flutter 80.0.1` • Dart plugin `233.15271`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.diagnostic.PluginException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplatePresentation()" because "this.myAction" is null [Plugin: io.flutter]
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1.invokeSuspend(EditorNotificationsImpl.kt:251)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplatePresentation()" because "this.myAction" is null
	at io.flutter.editor.NativeEditorNotificationProvider$NativeEditorActionsPanel.<init>(NativeEditorNotificationProvider.java:123)
	at io.flutter.editor.NativeEditorNotificationProvider.createPanelForAction(NativeEditorNotificationProvider.java:63)
	at io.flutter.editor.NativeEditorNotificationProvider.createPanelForFile(NativeEditorNotificationProvider.java:56)
	at io.flutter.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:49)
	at io.flutter.editor.NativeEditorNotificationProvider.createNotificationPanel(NativeEditorNotificationProvider.java:25)
	at com.intellij.ui.EditorNotifications$Provider.lambda$collectNotificationData$0(EditorNotifications.java:73)
	at com.intellij.ui.EditorNotificationsImpl$updateEditors$job$1$2.invokeSuspend(EditorNotificationsImpl.kt:243)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by helin24** [comment]
Is this still a problem? It seems like a problem with a particular package.
