### ISSUE TITLE
Exception on Flutter Test run configuration

### ISSUE THREAD

**Issue by julio-bulgarelli** [flutter/flutter-intellij#7611]
Please file this bug report at https://github.com/flutter/flutter-intellij/issues/new.

---

## What happened

Went to execute a Flutter Test run configuration

## Version information

IntelliJ IDEA `2024.2.0.1` • Flutter plugin `io.flutter 81.1.3` • Dart plugin `242.20629`

Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (2 weeks ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2

## Exception

null

```
java.lang.Throwable: [FlutterTestRunner]: Parent node id should be defined: TestStartedEvent{name='', running=true}.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.findValidParentNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:197)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.createNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:150)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.doStartNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:142)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.onTestStarted(GeneralIdBasedToSMTRunnerEventsConvertor.java:110)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.fireOnTestStarted(OutputToGeneralTestEventsConverter.java:142)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$MyServiceMessageVisitor.visitTestStarted(OutputToGeneralTestEventsConverter.java:427)
	at jetbrains.buildServer.messages.serviceMessages.TestStarted.visit(TestStarted.java:62)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessage(OutputToGeneralTestEventsConverter.java:135)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessages(OutputToGeneralTestEventsConverter.java:129)
	at io.flutter.test.DartTestEventsConverterZ.doProcessServiceMessages(DartTestEventsConverterZ.java:157)
	at io.flutter.test.DartTestEventsConverterZ.handleStart(DartTestEventsConverterZ.java:408)
	at io.flutter.test.DartTestEventsConverterZ.process(DartTestEventsConverterZ.java:185)
	at io.flutter.test.DartTestEventsConverterZ.processEventText(DartTestEventsConverterZ.java:145)
	at io.flutter.test.DartTestEventsConverterZ.processServiceMessages(DartTestEventsConverterZ.java:121)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailableInternal(OutputEventSplitter.kt:81)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailable(OutputEventSplitter.kt:76)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal(OutputEventSplitterBase.kt:162)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal$default(OutputEventSplitterBase.kt:148)
	at com.intellij.smRunner.OutputEventSplitterBase.processInternal(OutputEventSplitterBase.kt:96)
	at com.intellij.smRunner.OutputEventSplitterBase.process(OutputEventSplitterBase.kt:77)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:61)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:96)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:217)
	at com.intellij.execution.process.ProcessHandler$2.onTextAvailable(ProcessHandler.java:292)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:223)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:107)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:133)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:151)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by pq** [comment]
Thanks for the report. Closing this one as a duplicate of #8003, where we're tracking a fix.
