### ISSUE TITLE
[FlutterTestRunner]: Missing nodeId: TestStartedEvent{name='', running=true}

### ISSUE THREAD

**Issue by thermoworker** [flutter/flutter-intellij#7614]
## What happened

I wrote a simple unit test for a dart class used in a flutter project. I tried to run the test using the IntelliJ IDEA IDE. The IDE reported a 2 errors and suggested that I create this bug report [1 of 2].

## Version information

IntelliJ IDEA `2024.2.0.1` • Flutter plugin `io.flutter 81.1.3` • Dart plugin `242.20629`

Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (5 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

## Exception

null

```
java.lang.Throwable: [FlutterTestRunner]: Missing nodeId: TestStartedEvent{name='', running=true}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.validateAndGetNodeId(GeneralIdBasedToSMTRunnerEventsConvertor.java:410)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.findNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:416)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.doStartNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:125)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.onTestStarted(GeneralIdBasedToSMTRunnerEventsConvertor.java:110)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.fireOnTestStarted(OutputToGeneralTestEventsConverter.java:142)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$MyServiceMessageVisitor.visitTestStarted(OutputToGeneralTestEventsConverter.java:427)
	at jetbrains.buildServer.messages.serviceMessages.TestStarted.visit(TestStarted.java:62)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessage(OutputToGeneralTestEventsConverter.java:135)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessages(OutputToGeneralTestEventsConverter.java:129)
	at io.flutter.test.DartTestEventsConverterZ.doProcessServiceMessages(DartTestEventsConverterZ.java:157)
	at io.flutter.test.DartTestEventsConverterZ.handleStart(DartTestEventsConverterZ.java:408)
	at io.flutter.test.DartTestEventsConverterZ.process(DartTestEventsConverterZ.java:185)
	at io.flutter.test.DartTestEventsConverterZ.processEventText(DartTestEventsConverterZ.java:145)
	at io.flutter.test.DartTestEventsConverterZ.processServiceMessages(DartTestEventsConverterZ.java:121)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailableInternal(OutputEventSplitter.kt:81)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailable(OutputEventSplitter.kt:76)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal(OutputEventSplitterBase.kt:162)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal$default(OutputEventSplitterBase.kt:148)
	at com.intellij.smRunner.OutputEventSplitterBase.processInternal(OutputEventSplitterBase.kt:96)
	at com.intellij.smRunner.OutputEventSplitterBase.process(OutputEventSplitterBase.kt:77)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:61)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:96)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:217)
	at com.intellij.execution.process.ProcessHandler$2.onTextAvailable(ProcessHandler.java:292)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:223)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:107)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:133)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:151)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

## Version info

Please note that my flutter project is using `fvm`, so I will attach the output of both `fvm flutter doctor -v` [fvm.flutter.doctor.txt](https://github.com/user-attachments/files/16678226/fvm.flutter.doctor.txt) and  `flutter doctor -v` [flutter.doctor.txt](https://github.com/user-attachments/files/16678227/flutter.doctor.txt) as files to this ticket.

**Comment by diogomreiras** [comment]
I have the same issue


## Version information

IntelliJ IDEA `2024.2.3` • Flutter plugin `io.flutter 82.0.3` • Dart plugin `242.22855.32`

Error getting Flutter sdk information.


<details>
<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-DE)
    • Flutter version 3.24.3 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\diogo\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\diogo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.31729.503
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.4
    • Flutter plugin version 79.0.1
    • Dart plugin version 232.10335.13

[√] IntelliJ IDEA Community Edition (version 2024.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.2.3
    • Flutter plugin version 82.0.3
    • Dart plugin version 242.22855.32

[√] VS Code (version 1.94.2)
    • VS Code at C:\Users\diogo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4317]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.89
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 128.0.2739.67

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>



## Exception

<details>
<summary>The call stack of error 1</summary>

```
java.lang.Throwable: [FlutterTestRunner]: Missing nodeId: TestStartedEvent{name='', running=true}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.validateAndGetNodeId(GeneralIdBasedToSMTRunnerEventsConvertor.java:410)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.findNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:416)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.doStartNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:125)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.onTestStarted(GeneralIdBasedToSMTRunnerEventsConvertor.java:110)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.fireOnTestStarted(OutputToGeneralTestEventsConverter.java:142)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$MyServiceMessageVisitor.visitTestStarted(OutputToGeneralTestEventsConverter.java:427)
	at jetbrains.buildServer.messages.serviceMessages.TestStarted.visit(TestStarted.java:62)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessage(OutputToGeneralTestEventsConverter.java:135)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessages(OutputToGeneralTestEventsConverter.java:129)
	at io.flutter.test.DartTestEventsConverterZ.doProcessServiceMessages(DartTestEventsConverterZ.java:157)
	at io.flutter.test.DartTestEventsConverterZ.handleStart(DartTestEventsConverterZ.java:408)
	at io.flutter.test.DartTestEventsConverterZ.process(DartTestEventsConverterZ.java:185)
	at io.flutter.test.DartTestEventsConverterZ.processEventText(DartTestEventsConverterZ.java:145)
	at io.flutter.test.DartTestEventsConverterZ.processServiceMessages(DartTestEventsConverterZ.java:121)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailableInternal(OutputEventSplitter.kt:81)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailable(OutputEventSplitter.kt:76)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal(OutputEventSplitterBase.kt:162)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal$default(OutputEventSplitterBase.kt:148)
	at com.intellij.smRunner.OutputEventSplitterBase.processInternal(OutputEventSplitterBase.kt:96)
	at com.intellij.smRunner.OutputEventSplitterBase.process(OutputEventSplitterBase.kt:77)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:61)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:96)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:217)
	at com.intellij.execution.process.ProcessHandler$2.onTextAvailable(ProcessHandler.java:292)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:223)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:107)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:133)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:151)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>


<details>
<summary>The call stack of error 2</summary>

```
java.lang.Throwable: [FlutterTestRunner]: Parent node id should be defined: TestStartedEvent{name='', running=true}.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.findValidParentNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:197)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.createNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:150)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.doStartNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:142)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.onTestStarted(GeneralIdBasedToSMTRunnerEventsConvertor.java:110)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.fireOnTestStarted(OutputToGeneralTestEventsConverter.java:142)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$MyServiceMessageVisitor.visitTestStarted(OutputToGeneralTestEventsConverter.java:427)
	at jetbrains.buildServer.messages.serviceMessages.TestStarted.visit(TestStarted.java:62)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessage(OutputToGeneralTestEventsConverter.java:135)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessages(OutputToGeneralTestEventsConverter.java:129)
	at io.flutter.test.DartTestEventsConverterZ.doProcessServiceMessages(DartTestEventsConverterZ.java:157)
	at io.flutter.test.DartTestEventsConverterZ.handleStart(DartTestEventsConverterZ.java:408)
	at io.flutter.test.DartTestEventsConverterZ.process(DartTestEventsConverterZ.java:185)
	at io.flutter.test.DartTestEventsConverterZ.processEventText(DartTestEventsConverterZ.java:145)
	at io.flutter.test.DartTestEventsConverterZ.processServiceMessages(DartTestEventsConverterZ.java:121)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailableInternal(OutputEventSplitter.kt:81)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailable(OutputEventSplitter.kt:76)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal(OutputEventSplitterBase.kt:162)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal$default(OutputEventSplitterBase.kt:148)
	at com.intellij.smRunner.OutputEventSplitterBase.processInternal(OutputEventSplitterBase.kt:96)
	at com.intellij.smRunner.OutputEventSplitterBase.process(OutputEventSplitterBase.kt:77)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:61)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:96)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:217)
	at com.intellij.execution.process.ProcessHandler$2.onTextAvailable(ProcessHandler.java:292)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:223)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:77)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:107)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:133)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:151)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

**Comment by thermoworker** [comment]
I've updated my tools but this still seems to be a problem with these versions:

## Version information

IntelliJ IDEA `2024.3.1` • Flutter plugin `io.flutter 83.0.4` • Dart plugin `243.23177`

Flutter 3.24.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision dec2ee5c1f (4 weeks ago) • 2024-11-13 11:13:06 -0800
Engine • revision a18df97ca5
Tools • Dart 3.5.4 • DevTools 2.37.3

**Comment by srix55** [comment]
Yep... getting the same. Here's my intelliJ & flutter details.

```sh
Flutter 3.29.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c236373904 (3 weeks ago) • 2025-03-13 16:17:06 -0400
Engine • revision 18b71d647a
Tools • Dart 3.7.2 • DevTools 2.42.3

IntelliJ IDEA 2024.3.5 (Community Edition)
Build #IC-243.26053.27, built on March 16, 2025
Runtime version: 21.0.6+8-b631.39 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.13.9-200.fc41.x86_64
Fedora Linux 41 (Workstation Edition); glibc: 2.4
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  ide.experimental.ui=true
  llm.show.ai.promotion.window.on.start=false
Non-Bundled Plugins:
  com.codeium.intellij (1.43.7)
  Dart (243.26053.17)
  org.jetbrains.android (243.26053.27)
  io.flutter (83.0.4)
Kotlin: 243.26053.27-IJ
Current Desktop: GNOME

java.lang.Throwable: [FlutterTestRunner]: Missing nodeId: TestStartedEvent{name='', running=true}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.validateAndGetNodeId(GeneralIdBasedToSMTRunnerEventsConvertor.java:410)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.findNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:416)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.doStartNode(GeneralIdBasedToSMTRunnerEventsConvertor.java:125)
	at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.onTestStarted(GeneralIdBasedToSMTRunnerEventsConvertor.java:110)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.fireOnTestStarted(OutputToGeneralTestEventsConverter.java:142)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$MyServiceMessageVisitor.visitTestStarted(OutputToGeneralTestEventsConverter.java:427)
	at jetbrains.buildServer.messages.serviceMessages.TestStarted.visit(TestStarted.java:62)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessage(OutputToGeneralTestEventsConverter.java:135)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processServiceMessages(OutputToGeneralTestEventsConverter.java:129)
	at io.flutter.test.DartTestEventsConverterZ.doProcessServiceMessages(DartTestEventsConverterZ.java:156)
	at io.flutter.test.DartTestEventsConverterZ.handleStart(DartTestEventsConverterZ.java:407)
	at io.flutter.test.DartTestEventsConverterZ.process(DartTestEventsConverterZ.java:184)
	at io.flutter.test.DartTestEventsConverterZ.processEventText(DartTestEventsConverterZ.java:144)
	at io.flutter.test.DartTestEventsConverterZ.processServiceMessages(DartTestEventsConverterZ.java:120)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailableInternal(OutputEventSplitter.kt:81)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.onTextAvailable(OutputEventSplitter.kt:76)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal(OutputEventSplitterBase.kt:162)
	at com.intellij.smRunner.OutputEventSplitterBase.flushInternal$default(OutputEventSplitterBase.kt:148)
	at com.intellij.smRunner.OutputEventSplitterBase.processInternal(OutputEventSplitterBase.kt:96)
	at com.intellij.smRunner.OutputEventSplitterBase.process(OutputEventSplitterBase.kt:77)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:61)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:96)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:217)
	at com.intellij.execution.process.ProcessHandler$2.onTextAvailable(ProcessHandler.java:292)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:223)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:68)
	at io.flutter.utils.MostlySilentColoredProcessHandler.coloredTextAvailable(MostlySilentColoredProcessHandler.java:75)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:107)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:57)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:133)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:220)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:204)
	at com.intellij.util.io.BaseOutputReader.readAvailableBlocking(BaseOutputReader.java:151)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:72)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:153)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:103)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:103)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:109)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:103)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by pq** [comment]
Thanks for the report. Closing this one as a duplicate of #8003, where we're tracking a fix.
