### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by AvailableNameWill** [flutter/flutter-intellij#7656]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

I opened the IDE and the error appeared in the bottom right corner of the screen. Apparently It doesn't affect anything.

## Version info

IntelliJ IDEA `2023.1.2` • Flutter plugin `io.flutter 74.0.4` • Dart plugin `231.9065`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonPrimitive (com.google.gson.JsonNull and com.google.gson.JsonPrimitive are in unnamed module of loader com.intellij.util.lang.PathClassLoader @21a06946)
	at com.google.gson.JsonObject.getAsJsonPrimitive(JsonObject.java:197)
	at io.flutter.sdk.FlutterSdk.queryFlutterConfig(FlutterSdk.java:639)
	at io.flutter.ProjectOpenActivity.lambda$runActivity$1(ProjectOpenActivity.java:93)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jwren** [comment]
We no longer support this version of the IDEA platform, see https://github.com/flutter/flutter-intellij/blob/master/product-matrix.json
