### ISSUE TITLE
com.intellij.diagnostic.PluginException

### ISSUE THREAD

**Issue by prashant-angelbroking** [flutter/flutter-intellij#7662]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2024.2.1` • Flutter plugin `io.flutter 81.1.3` • Dart plugin `242.21829.3`

No Flutter sdk configured.

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.inspector.JumpToSourceAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by pq** [comment]
We've removed `io.flutter.inspector.JumpToSourceAction`, so this won't happen anymore. Sorry for the slow follow-up!
