### ISSUE TITLE
IntelliJ plugin issue report

### ISSUE THREAD

**Issue by MirnaEmbaby** [flutter/flutter-intellij#7790]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
[bug-report_3.md](https://github.com/user-attachments/files/17786662/bug-report_3.md)

**Comment by Johannes-Schiel** [comment]
I have the same Bug in my IntelliJ setup

```
java.lang.Throwable: [FlutterTestRunner]: Parent node id should be defined: TestStartedEvent{name='', running=true}.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)

```

```
java.lang.Throwable: [FlutterTestRunner]: Missing nodeId: TestStartedEvent{name='', running=true}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:376)
	at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:362)

```

**Comment by pq** [comment]
Thanks for the report. Closing this one as a duplicate of #8003, where we're tracking a fix.
