### ISSUE TITLE
DTD theme changed event exception

### ISSUE THREAD

**Issue by jwren** [flutter/flutter-intellij#7794]
Flutter plugin version `82.0.3`, IntelliJ IDEA 2024.2 (Ultimate Edition)

Unable to send theme changed event

java.util.concurrent.ExecutionException: java.lang.Exception: Timed out waiting for DTD websocket to start
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.flutter.FlutterInitializer.lambda$sendThemeChangedEvent$6(FlutterInitializer.java:335)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.Exception: Timed out waiting for DTD websocket to start
	at io.flutter.dart.DtdUtils.readyDtdService(DtdUtils.java:35)
	... 7 more

**Comment by AlexV525** [comment]
Run into this in a relatively high frequency with my production projects:

[idea-dump.log](https://github.com/user-attachments/files/21764030/idea-dump.log)

[flutter-dump.log](https://github.com/user-attachments/files/21764053/flutter-dump.log)

**Comment by helin24** [comment]
Thanks for the logs - it looks like DTD is succeeding eventually but not in the timeout we have set up.

It's odd in the first place that is sent so soon after project startup. Potentially we could add a check somewhere on whether theme info has changed before requesting DTD action.
