### ISSUE TITLE
when running with an out-of-date Dart plugin, we should disable some init code

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#802]
GS-P3 has used Webstorm for Dart a while ago but switched to VS Code, so their dart plugin and Webstorm versions were probably old.

They then installed the Flutter plugin, upon loading they got:

## Version information

Flutter plugin `0.1.11.1`

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 0136b965e8 (10 hours ago) • 2017-03-07 22:51:05
Engine • revision f9c1f5fa53
Tools • Dart 1.23.0-dev.2.0

## Exception

com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess.<init>(Lcom/intellij/xdebugger/XDebugSession;Ljava/lang/String;ILcom/intellij/execution/ExecutionResult;Lcom/jetbrains/lang/dart/util/DartUrlResolver;Ljava/lang/String;ZILcom/intellij/openapi/vfs/VirtualFile;)V

```
java.lang.NoSuchMethodError: com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcess.<init>(Lcom/intellij/xdebugger/XDebugSession;Ljava/lang/String;ILcom/intellij/execution/ExecutionResult;Lcom/jetbrains/lang/dart/util/DartUrlResolver;Ljava/lang/String;ZILcom/intellij/openapi/vfs/VirtualFile;)V
	at com.jetbrains.lang.dart.ide.runner.server.vmService.DartVmServiceDebugProcessZ.<init>(DartVmServiceDebugProcessZ.java:95)
	at io.flutter.run.FlutterDebugProcess.<init>(FlutterDebugProcess.java:45)
	at io.flutter.run.FlutterRunner$2.start(FlutterRunner.java:216)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.a(XDebuggerManagerImpl.java:219)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:181)
	at io.flutter.run.FlutterRunner.doExecuteDartDebug(FlutterRunner.java:203)
	at io.flutter.run.FlutterRunner.doExecute(FlutterRunner.java:156)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:380)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:417)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:292)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:417)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:61)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:117)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:67)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:509)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:829)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by devoncarew** [comment]
@lukechurch, do you know if this exception was after the user tried to run an app, or just on loading?

We have a warning on open if the Dart plugin is too old, but it sounds like we'll also need to make sure some initializer code is not run.

**Comment by devoncarew** [comment]
(I suspect that the flutter daemon is starting up and hitting missing Dart plugin functionality)

**Comment by lukechurch** [comment]
@devoncarew I'll look back in the video and find out, I'm pretty sure it was just loading?

**Comment by devoncarew** [comment]
KK, that would be consistent w/ the stack trace, so probably no need to look back through the video.

**Comment by pq** [comment]
@devoncarew : this is pretty old.  Any objection to closing in favor of a fresh issue (if needed) related to the current bits?
