### ISSUE TITLE
use after dispose exception

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#842]
To repro:

- open an project
- close the project
- create (or open) a new project

you'll see an exception, likely from accessing the old (disposed) project

```
Caused by: java.lang.AssertionError: Already disposed: Project (Disposed) flutter_gallery
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:259)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:58)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:47)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:42)
	at com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable.getInstance(ProjectLibraryTable.java:57)
	at com.jetbrains.lang.dart.sdk.DartSdk.lambda$getDartSdk$0(DartSdk.java:56)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.jetbrains.lang.dart.sdk.DartSdk.getDartSdk(DartSdk.java:72)
	at io.flutter.dart.DartPlugin.getDartSdk(DartPlugin.java:47)
	at io.flutter.sdk.FlutterSdk.getFlutterSdk(FlutterSdk.java:61)
	at io.flutter.sdk.FlutterSdkManager.isFlutterSdkSetAndNeeded(FlutterSdkManager.java:97)
	at io.flutter.sdk.FlutterSdkManager.checkForFlutterSdkChange(FlutterSdkManager.java:72)
	at io.flutter.sdk.FlutterSdkManager$1.projectOpened(FlutterSdkManager.java:51)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:686)
```

**Comment by alexander-doroshko** [comment]
Got this report from a user, probably the same cause:
```
 Product:IDEA Community 163.15188 OS:Mac OS X 
java.lang.AssertionError: Already disposed: Project (Disposed) squanchy-flutter
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
    at com.jetbrains.lang.dart.DartProjectComponent.getProjectRootsModificationTracker(DartProjectComponent.java:71)
    at com.jetbrains.lang.dart.sdk.DartSdk.lambda$getDartSdk$0(DartSdk.java:64)
    at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
    at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
    at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
    at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
    at com.jetbrains.lang.dart.sdk.DartSdk.getDartSdk(DartSdk.java:74)
    at io.flutter.sdk.FlutterSdk.getFlutterSdk(FlutterSdk.java:67)
    at io.flutter.actions.DeviceSelectorAction.lambda$updateVisibility$1(DeviceSelectorAction.java:113)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:650)
    at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:667)
    at io.flutter.actions.DeviceSelectorAction.updateVisibility(DeviceSelectorAction.java:112)
    at io.flutter.actions.DeviceSelectorAction.access$000(DeviceSelectorAction.java:35)
    at io.flutter.actions.DeviceSelectorAction$1.flutterSdkRemoved(DeviceSelectorAction.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
    at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
    at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
    at com.sun.proxy.$Proxy91.flutterSdkRemoved(Unknown Source)
    at io.flutter.sdk.FlutterSdkManager.checkForFlutterSdkRemoval(FlutterSdkManager.java:69)
    at io.flutter.sdk.FlutterSdkManager.access$200(FlutterSdkManager.java:22)
    at io.flutter.sdk.FlutterSdkManager$1.projectClosed(FlutterSdkManager.java:54)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectClosed(ProjectManagerImpl.java:672)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$11(ProjectManagerImpl.java:571)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:568)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:592)
    at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:89)
    at com.intellij.ide.actions.CloseProjectAction.actionPerformed(CloseProjectAction.java:35)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$2(ActionMenuItem.java:315)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:91)
    at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
    at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
    at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
    at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) 
```

**Comment by devoncarew** [comment]
Looks like it! Thanks for the report. A new version should be out shortly.
