### ISSUE TITLE
stack trace opening second project

### ISSUE THREAD

**Issue by skybrian** [flutter/flutter-intellij#848]
With the latest RC for 12.0, I'm getting a stack trace opening a second project:

IDEA 2016.3.1
Dart plugin 163.13137
Running on Linux.

```
Caused by: java.lang.AssertionError: Already disposed: Project (Disposed) flutter-misc
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:172)
	at com.jetbrains.lang.dart.DartProjectComponent.getProjectRootsModificationTracker(DartProjectComponent.java:71)
	at com.jetbrains.lang.dart.sdk.DartSdk.lambda$getDartSdk$0(DartSdk.java:64)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:65)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.jetbrains.lang.dart.sdk.DartSdk.getDartSdk(DartSdk.java:74)
	at io.flutter.dart.DartPlugin.getDartSdk(DartPlugin.java:47)
	at io.flutter.sdk.FlutterSdk.getFlutterSdk(FlutterSdk.java:61)
	at io.flutter.sdk.FlutterSdkManager.isFlutterSdkSetAndNeeded(FlutterSdkManager.java:97)
	at io.flutter.sdk.FlutterSdkManager.checkForFlutterSdkChange(FlutterSdkManager.java:68)
	at io.flutter.sdk.FlutterSdkManager$1.projectOpened(FlutterSdkManager.java:51)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.h(ProjectManagerImpl.java:657)
```

**Comment by devoncarew** [comment]
`FlutterSdkManager.java:68` doesn't line up with a source line for me. I think we built an out of date plugin or you are running one. Can you check?

**Comment by pq** [comment]
I'm seeing this too. Looking....

**Comment by pq** [comment]
Hmmm, yeah.  It looks like only one `FlutterSdkManager` instance is ever getting created and it's caching the first `project` instance in it.

**Comment by skybrian** [comment]
That seems rather weird because FlutterSdkManager.getInstance() takes a Project and passes it to the ServiceManager. I'd expect getInstance() to return a different FlutterSdkManager for each Project?

**Comment by pq** [comment]
Agreed.  That said, I've got a dirty fix for this actually...  Stand by!

**Comment by pq** [comment]
I think I may have misspoke.  That said, it does look like there's a timing issue that means some accesses can occur post project dispose.  This fix is quick (and easy) and probably not terrible: https://github.com/flutter/flutter-intellij/pull/849 (if a little defensive)
