### ISSUE TITLE
unable to open /flutter/examples without issues in 2017.1

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#860]
Repro steps:

1. Install RC plugin
1. File>Create project, set paths, and ensure everything is open
1. File>Close all open projects
1. Click open, pick <flutter sdk dir>/examples/hello_world/

=> Project load fails:

![screen shot 2017-03-30 at 12 55 54](https://cloud.githubusercontent.com/assets/13644170/24501058/3ccb3b3a-1548-11e7-94e8-f2fdfa5521c5.png)

**Comment by mit-mit** [comment]
Reproed on both macOS and Windows.

**Comment by mit-mit** [comment]
This is probably the same root issue as #859?

**Comment by alexander-doroshko** [comment]
Most likely the cause is different. I guess there's some critical error in logs (Help | Show Log).

**Comment by mit-mit** [comment]
Log file contents:

```
2017-03-30 16:11:36,788 [1781431]   INFO - ellij.project.impl.ProjectImpl - 158 project components initialized in 55 ms 
2017-03-30 16:11:36,791 [1781434]   INFO - le.impl.ModuleManagerComponent - 1 module(s) loaded in 3 ms 
2017-03-30 16:11:36,856 [1781499]   INFO - CompilerBackwardReferenceIndex - /Users/mit/Library/Caches/IdeaIC2017.1/compile-server/hello_world_77f0c04d/backward-refs/version (No such file or directory) 
java.io.FileNotFoundException: /Users/mit/Library/Caches/IdeaIC2017.1/compile-server/hello_world_77f0c04d/backward-refs/version (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.jetbrains.jps.backwardRefs.CompilerBackwardReferenceIndex.versionDiffers(CompilerBackwardReferenceIndex.java:162)
	at com.intellij.compiler.backwardRefs.CompilerReferenceReader.exists(CompilerReferenceReader.java:114)
	at com.intellij.compiler.backwardRefs.CompilerReferenceServiceImpl.lambda$projectOpened$2(CompilerReferenceServiceImpl.java:140)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-30 16:11:36,920 [1781563]   WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix ToolWindow (ID:  Flutter) or icon jar:file:/Users/mit/Library/Application%20Support/IdeaIC2017.1/flutter-intellij.jar!/icons/flutter.png 
2017-03-30 16:11:36,924 [1781567]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 0ms; general responsiveness: ok; EDT responsiveness: ok 
2017-03-30 16:11:36,925 [1781568]   INFO - riptDefsFromTemplatesProviders - [kts] loading script definitions [kotlin.script.templates.standard.ScriptTemplateWithArgs] using cp:  
2017-03-30 16:11:36,944 [1781587]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 20ms; general responsiveness: ok; EDT responsiveness: ok 
2017-03-30 16:11:36,949 [1781592]   INFO - tartup.impl.StartupManagerImpl - /Users/mit/dev/github/flutter/examples/hello_world/.idea case-sensitivity: expected=false actual=false 
2017-03-30 16:11:36,977 [1781620]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 246 ms 
2017-03-30 16:11:37,000 [1781643]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2017-03-30 16:11:37,008 [1781651]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 0ms; general responsiveness: ok; EDT responsiveness: ok 
2017-03-30 16:11:37,009 [1781652]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 0ms; general responsiveness: ok; EDT responsiveness: ok 

```

**Comment by alexander-doroshko** [comment]
This piece of log show no problems. Pay attention to the recommendations wrt tool window icon size. :)

I could misunderstand the bug report. Is the IDE in an unactionable state? Can you open tool windows, files, preferences, etc.? Or what do you mean by 'project load fails'?

**Comment by mit-mit** [comment]
Sorry for being imprecise. Project load doesn't actually fail, it just looks like it (no project view, no file opens, run config has red cross). If you open main.dart you get:

![screen shot 2017-03-30 at 16 21 01](https://cloud.githubusercontent.com/assets/13644170/24508799/e3923880-1564-11e7-8ccd-0d26b19ad0ad.png)

**Comment by alexander-doroshko** [comment]
If the project has ever been opened before - next time you open it all files and tool windows are restored in the state you left them previous time. However, if you deleted .idea/workspace.xml file then knowledge about tool windows / open files / etc. is lost.

**Comment by devoncarew** [comment]
Some of the issues here may have been the intelliJ metadata needing to be updated, and that the workspace files may have been deleted. I am able to open the flutter repo, using these steps:

```shell
git clone https://github.com/flutter/flutter.git
(cd flutter; bin/flutter update-packages)
idea flutter
```

**Comment by mit-mit** [comment]
This still does not work for me with these steps:

```
cd tmp
git clone https://github.com/flutter/flutter.git
```

* Start IJ
* File > Open, select `tmp/flutter/examples/hello_world/`
* Open `lib/main.dart`

![image](https://cloud.githubusercontent.com/assets/13644170/24660959/410955d0-1951-11e7-902f-5fa44d5c661b.png)

Above steps using IJ on Windows, thus no open from terminal. File > Create a Flutter projects works as expected.

**Comment by devoncarew** [comment]
Your initial issue was that the project load fails; it looks like that's not an issue now.

I do see what the same behavior as your latest repro steps. When I set an sdk and run the 'get dependencies' from the editor header, things work as expected.

An enhancement here would be to offer to set the Flutter sdk in the editor header. Perhaps better tracked under https://github.com/flutter/flutter-intellij/issues/535?

**Comment by mit-mit** [comment]
No, this is the same issue I saw before, see https://github.com/flutter/flutter-intellij/issues/860#issuecomment-290425712

**Comment by mit-mit** [comment]
I don't think this is the same as #535. That is a small enhancement to make the 'File > Open, select example' step easier to perform. This tracks a more concrete issue that we fail to properly load and configure a Flutter project with working analysis from our own examples.

Didn't we add support a few months ago to auto-get dependencies if needed?

Do we also not see the 'No Flutter SDK issue' if you try on Windows?

**Comment by devoncarew** [comment]
> Didn't we add support a few months ago to auto-get dependencies if needed?

I don't think so - just displaying the editor header when you need to run flutter packages get.

> Do we also not see the 'No Flutter SDK issue' if you try on Windows?

I don't have a windows machine available at the moment - I'm testing on macos.

**Comment by mit-mit** [comment]
Clarifying title to better match https://github.com/flutter/flutter-intellij/issues/860#issuecomment-290425712

**Comment by mit-mit** [comment]
This also repros for me on Linux with 2017.1.

I can File > Create projects and things work as expected. But both /examples/hello_world/ and a new project created with `flutter create` lead to the not Dart + Flutter SDK banners when `lib/main.dart` is opened.

**Comment by devoncarew** [comment]
note to self: we can add the SDK info into the metadata in the repo

**Comment by pq** [comment]
@mit-mit can repro on the mac.

**Comment by pq** [comment]
For at least @pq and @mit-mit, it looks like the SDK setting is not reliably sticking?

**Comment by mit-mit** [comment]
Still repros in 2017.1 on Windows. Clicking the 'Enable Dart' support in the banner resolves it, but not pretty...

**Comment by pq** [comment]
What example did you try?  @skybrian fixed the metadata in gallery as of https://github.com/flutter/flutter/pull/9452, so I'd expect that to work.  If it does, we should probably update them all similarly.

**Comment by mit-mit** [comment]
I see no difference between opening flutter_gallery and hello_world

**Comment by devoncarew** [comment]
@mit-mit, did the newly cloned repo have a dart sdk? If you don't run that initial `bin/flutter` script, there will be no dart sdk.

**Comment by skybrian** [comment]
I think Devon's guess is quite likely. We could fix this by running bin/flutter just before opening any Flutter project, to "warm it up" (make sure the Dart SDK exists).

Or perhaps do this whenever the Dart SDK is missing in a Flutter SDK?

**Comment by pq** [comment]
@skybrian: would you mind testing the theory?

**Comment by mit-mit** [comment]
Yup, I think that is it. Won't be able to re-test until tomorrow though....

**Comment by skybrian** [comment]
If I clone the flutter repo, don't run bin/flutter, and open the project, here's what happens:

 - In Project Structure, there is a problem report: "Library Dart SDK has broken classes paths:" (sic)

If I open lib/main.dart, there are three warnings:

  - Dart SDKis not configured
  - No Flutter SDK configured
  - 'Packages get' has not been run

I'll see what I can do.

**Comment by mit-mit** [comment]
I can confirm that opening /examples/flutter_gallery/ works after running the get-packages step.

But looks like we still need to fix each of the other sample apps in /examples/

**Comment by pq** [comment]
Great!

@skybrian @devoncarew : any reason not to update all the examples this way?

**Comment by devoncarew** [comment]
We'll need to maintain the sdk metadata for each sample. If we do this, we should put in a test so that the build fails if and when the metadata gets out of date.

**Comment by skybrian** [comment]
Sure, updating the samples seems fine.

**Comment by devoncarew** [comment]
We have a solution on track for this, but it's probably a bigger change than we want to go into the tail end of M13. Let's publish M13, evaluate the solution, and see if we want it in M14 or a 13.1.

**Comment by pq** [comment]
@devoncarew, @skybrian : what's the current thinking on this one?

**Comment by skybrian** [comment]
I'll verify it works.

**Comment by skybrian** [comment]
Opening Flutter Gallery works. The other examples have apparently not been updated. I'll send a patch.

**Comment by skybrian** [comment]
Also, it can be slow depending on the network connection. #992

**Comment by skybrian** [comment]
Other flutter examples patched as of: https://github.com/flutter/flutter/pull/9847

**Comment by pq** [comment]
Sounds like this should be fixed.

@mit-mit  can you verify on your end?

**Comment by mit-mit** [comment]
All /examples/ open great now! Thanks!

Closing.
