### ISSUE TITLE
IntelliJ crashed after upgrading to 2017.1

### ISSUE THREAD

**Issue by eseidel** [flutter/flutter-intellij#874]
I was replacing 2016.3, which I think had just-before upgraded itself from 2016.1 (as well as plugins).

When I started I got this:

```
Internal error. Please report to http://jb.gg/ide/critical-startup-errors

java.lang.AssertionError: Problems found loading plugins:<p/>Plugin "Flutter" was not loaded: required plugin "Dart" not installed.<p/><br><a href="disable">Disable Flutter</a><p/><a href="enable">Enable Dart</a><p/><a href="edit">Open plugin manager</a>
    at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:71)
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
    at com.intellij.ide.plugins.PluginManagerCore.prepareLoadingPluginsErrorMessage(PluginManagerCore.java:563)
    at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:1204)
    at com.intellij.ide.plugins.PluginManagerCore.initPlugins(PluginManagerCore.java:1364)
    at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:118)
    at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:112)
    at com.intellij.idea.IdeaApplication.getStarter(IdeaApplication.java:184)
    at com.intellij.idea.IdeaApplication.<init>(IdeaApplication.java:103)
    at com.intellij.idea.MainImpl$1.lambda$start$1(MainImpl.java:45)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Throwable
    ... 23 more
```

**Comment by eseidel** [comment]
I can't actually start intellij now. :/  So presumably I have to remove my plugins from disk manually.

**Comment by eseidel** [comment]
The URL they state is for filing a support ticket, which probably isn't what I want, hence filing here.  Happy to move to youtrack from my work account if needed.

**Comment by eseidel** [comment]
[IdeaIC2016.3.zip](https://github.com/flutter/flutter-intellij/files/891811/IdeaIC2016.3.zip)
[IdeaIC2017.1.zip](https://github.com/flutter/flutter-intellij/files/891812/IdeaIC2017.1.zip)

**Comment by eseidel** [comment]
Once I removed those directories I was able to start 2017.1 (and let it upgrade my installed plugins, etc.)

**Comment by devoncarew** [comment]
I'll dig through those logs, but this: `'<a href="enable">Enable Dart</a>'`, makes me think that somehow your Dart plugin became disabled, so it was not available for the Flutter plugin. It's not clear how IntelliJ could get into that state, but it definitely should have handled it better in terms of still being able to start up.

**Comment by eseidelGoogle** [comment]
I launched 2016.1 (maybe 2?) and it gave me an upgrade dialog which I clicked, brought me to 2016.3 which launched and gave me a download dialog which I clicked, quit IntelliJ and installed the newly downloaded 2017.1.  I launched the new 2017.1, told it to upgrade from my previous settings, and then it died here, and would die this way every time I launched until I removed the 2017.1 folder.  Happy to move to youtrack if told where.  @alexander-doroshko

**Comment by alexander-doroshko** [comment]
Failing to start is not good, whatever the combination of installed/enabled plugins is. YouTrack link is https://youtrack.jetbrains.com, specify IntelliJ IDEA project for the issue.

**Comment by eseidelGoogle** [comment]
Filed as https://youtrack.jetbrains.com/issue/IDEA-170965

**Comment by devoncarew** [comment]
closing; moved to https://youtrack.jetbrains.com/issue/IDEA-170965
