### ISSUE TITLE
flutter create fails with pub get -4 error

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#974]
I have been seeing this sporadically (on MacOS, flutter is up-to-date on master:

```
$ flutter create test82
Creating project test82...
Wrote 64 files.

Running 'flutter packages get' in test82...
1
pub get failed (-4)
$
```

To test things a bit, I just tried this 25 times in a row, and I got the failure three times.

**Comment by devoncarew** [comment]
Is this a pub error? Does this mean that the pub hosted service is overloaded or failing?

**Comment by devoncarew** [comment]
Where is that `1` coming from above?

**Comment by mit-mit** [comment]
cc @kevmoo

**Comment by mit-mit** [comment]
Managed to get a repro with `-v`:

```
mit-macbookpro2:tmp mit$ flutter create -v test99
[  +19 ms] [/Users/mit/dev/github/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] [/Users/mit/dev/github/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[        ] [/Users/mit/dev/github/flutter/] git log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] ff8609f27396c91f9ead5a560a19ec3d34d5f7b8
[        ] [/Users/mit/dev/github/flutter/] git log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 16 hours ago
[ +113 ms] Creating project test99...
[  +15 ms]   test99/.gitignore
[   +8 ms]   test99/.idea/libraries/Dart_SDK.xml
[   +7 ms]   test99/.idea/libraries/Flutter_for_Android.xml
[        ]   test99/.idea/modules.xml
[        ]   test99/.idea/runConfigurations/main_dart.xml
[        ]   test99/.idea/workspace.xml
[   +3 ms]   test99/android.iml
[   +1 ms]   test99/android/.gitignore
[   +1 ms]   test99/android/app/build.gradle
[   +1 ms]   test99/android/app/src/main/AndroidManifest.xml
[   +1 ms]   test99/android/app/src/main/java/com/yourcompany/test99/MainActivity.java
[   +1 ms]   test99/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
[        ]   test99/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
[        ]   test99/android/build.gradle
[        ]   test99/android/gradle.properties
[        ]   test99/android/settings.gradle
[   +1 ms]   test99/ios/.gitignore
[        ]   test99/ios/Flutter/AppFrameworkInfo.plist
[        ]   test99/ios/Flutter/Debug.xcconfig
[        ]   test99/ios/Flutter/Release.xcconfig
[        ]   test99/ios/Podfile
[        ]   test99/ios/Podfile.lock
[        ]   test99/ios/Pods/Manifest.lock
[        ]   test99/ios/Pods/Pods.xcodeproj/project.pbxproj
[   +1 ms]   test99/ios/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods-Runner.xcscheme
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-acknowledgements.markdown
[   +1 ms]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-acknowledgements.plist
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-resources.sh
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig
[        ]   test99/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig
[        ]   test99/ios/Runner/AppDelegate.h
[        ]   test99/ios/Runner/AppDelegate.m
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
[        ]   test99/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
[        ]   test99/ios/Runner/Base.lproj/LaunchScreen.storyboard
[        ]   test99/ios/Runner/Base.lproj/Main.storyboard
[        ]   test99/ios/Runner/Info.plist
[        ]   test99/ios/Runner/main.m
[        ]   test99/ios/Runner.xcodeproj/project.pbxproj
[  +12 ms]   test99/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
[        ]   test99/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
[   +1 ms]   test99/ios/Runner.xcworkspace/contents.xcworkspacedata
[        ]   test99/lib/main.dart
[   +2 ms]   test99/test99.iml
[        ]   test99/pubspec.yaml
[   +1 ms]   test99/README.md
[        ] Wrote 64 files.
[   +4 ms] Running 'flutter packages get' in test99...
[   +2 ms] [/Users/mit/tmp/test99/] /Users/mit/dev/github/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning get --no-precompile
[  +18 ms] 1
pub get failed (-4)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      pubGet (package:flutter_tools/src/dart/pub.dart:62)
<asynchronous suspension>
#2      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:147)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:205)
<asynchronous suspension>
#4      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:262)
<asynchronous suspension>
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#8      Future.Future.sync (dart:async/future.dart:208)
#9      CommandRunner.run (package:args/command_runner.dart:109)
#10     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#11     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#12     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#13     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#14     _rootRun (dart:async/zone.dart:1120)
#15     _CustomZone.run (dart:async/zone.dart:1001)
#16     runZoned (dart:async/zone.dart:1465)
#17     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#18     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#20     main (file:///Users/mit/dev/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#21     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


[  +95 ms] ensureAnalyticsSent: 86ms
[   +4 ms] exiting with code -4
mit-macbookpro2:tmp mit$
```

**Comment by mit-mit** [comment]
@kevmoo looks like this is the pub command failing. Do we have server-side logs that can help us understand what is going on?

**Comment by mit-mit** [comment]
This issue was moved to flutter/flutter#9727
